/******************************************************************************
 * Copyright 2022 Kristiyan Manev, Joseph Powell (University of Manchester)
 *
 * Licensed under the Apache License, Version 2.0(the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

#ifndef XILINXULTRASCALEPLUSDEVICES_H
#define XILINXULTRASCALEPLUSDEVICES_H

#include<cstring>//strcpy

enum XUSP_DEVICE_ENUM    ///< Enumeration of recognized Xilinx UltraScale+ devices and boards.
{
    XUSP_DEVICE_NULL = 0,
    //XUSP Artix
    XUSP_DEVICE_XCAU10P,
    XUSP_DEVICE_XCAU15P,
    XUSP_DEVICE_XCAU20P,
    XUSP_DEVICE_XCAU25P,
    //XUSP Kintex
    XUSP_DEVICE_XCKU3P,
    XUSP_DEVICE_XCKU5P,
    XUSP_DEVICE_XCKU9P,
    XUSP_DEVICE_XCKU11P,
    XUSP_DEVICE_XCKU13P,
    XUSP_DEVICE_XCKU15P,
    XUSP_DEVICE_XCKU19P,
    //XUSP Virtex
    XUSP_DEVICE_XCVU3P,
    XUSP_DEVICE_XCVU5P,
    XUSP_DEVICE_XCVU7P,
    XUSP_DEVICE_XCVU9P,
    XUSP_DEVICE_XCVU11P,
    XUSP_DEVICE_XCVU13P,
    XUSP_DEVICE_XCVU19P,
    XUSP_DEVICE_XCVU23P,
    XUSP_DEVICE_XCVU27P,
    XUSP_DEVICE_XCVU29P,
    XUSP_DEVICE_XCVU31P,
    XUSP_DEVICE_XCVU33P,
    XUSP_DEVICE_XCVU35P,
    XUSP_DEVICE_XCVU37P,
    XUSP_DEVICE_XCVU45P,
    XUSP_DEVICE_XCVU47P,
    XUSP_DEVICE_XCVU57P,
    //XUSP RFSoC
    XUSP_DEVICE_XCZU21DR,
    XUSP_DEVICE_XCZU25DR,
    XUSP_DEVICE_XCZU27DR,
    XUSP_DEVICE_XCZU28DR,
    XUSP_DEVICE_XCZU29DR,
    XUSP_DEVICE_XCZU39DR,
    XUSP_DEVICE_XCZU42DR,
    XUSP_DEVICE_XCZU43DR,
    XUSP_DEVICE_XCZU46DR,
    XUSP_DEVICE_XCZU47DR,
    XUSP_DEVICE_XCZU48DR,
    XUSP_DEVICE_XCZU49DR,
    XUSP_DEVICE_XCZU65DR,
    XUSP_DEVICE_XCZU67DR,
    //XUSP MPSoC
    XUSP_DEVICE_XCZU1,
    XUSP_DEVICE_XCZU2,
    XUSP_DEVICE_XCZU3,
    XUSP_DEVICE_XCZU4,
    XUSP_DEVICE_XCZU5,
    XUSP_DEVICE_XCZU6,
    XUSP_DEVICE_XCZU7,
    XUSP_DEVICE_XCZU9,
    XUSP_DEVICE_XCZU11,
    XUSP_DEVICE_XCZU15,
    XUSP_DEVICE_XCZU17,
    XUSP_DEVICE_XCZU19,
    //XUSP Alveo
    XUSP_DEVICE_XCU200,
    XUSP_DEVICE_XCU250,
    XUSP_DEVICE_XCU26,
    XUSP_DEVICE_XCUX35,
    XUSP_DEVICE_XCU50,
    XUSP_DEVICE_XCU55N,
    XUSP_DEVICE_XCU55C,
    XUSP_DEVICE_XCU280,
    XUSP_DEVICE_XCU30,
    XUSP_DEVICE_XCU25,
    //XUSP Boards
    XUSP_DEVICE_ZCU102,
    XUSP_DEVICE_ZCU104,
    XUSP_DEVICE_ZCU106,
    XUSP_DEVICE_AXU15EG,
    XUSP_DEVICE_AXU2CG,
    XUSP_DEVICE_AXU3EG,
    XUSP_DEVICE_AXU4EV,
    XUSP_DEVICE_AXU5EV,
    XUSP_DEVICE_AXU9EG,
    XUSP_DEVICE_ULTRAZED_EV,
    XUSP_DEVICE_CHAMP_XD1S,
    XUSP_DEVICE_ZU_3EG,
    XUSP_DEVICE_ZU_5EV,
    XUSP_DEVICE_HTG_Z999_06,
    XUSP_DEVICE_HTG_Z999_09,
    XUSP_DEVICE_HTG_Z999_15,
    XUSP_DEVICE_HTG_930_9_3,
    XUSP_DEVICE_HTG_930_9,
    XUSP_DEVICE_HTG_930_13_3,
    XUSP_DEVICE_HTG_930_13,
    XUSP_DEVICE_HTG_937_37P,
    XUSP_DEVICE_HTG_937_47P,
    XUSP_DEVICE_HTG_Z922_11,
    XUSP_DEVICE_HTG_Z922_19_DG,
    XUSP_DEVICE_HTG_Z922_19,
    XUSP_DEVICE_CZU3EG,
    XUSP_DEVICE_CZU4EV,
    XUSP_DEVICE_TE0802,
    XUSP_DEVICE_TE0803_04_3BE11,
    XUSP_DEVICE_TE0807_03_7DE21,
    XUSP_DEVICE_TE0808_05_9BE21,
    XUSP_DEVICE_TE0808_05_9GI21,
    XUSP_DEVICE_TE0808_05_BBE21,
    XUSP_DEVICE_TE0812,
    XUSP_DEVICE_TEB0911,
    XUSP_DEVICE_TEB0912,
    XUSP_DEVICE_TYSOM_3_ZU7EV,
    XUSP_DEVICE_XPEDITE2600,
    XUSP_DEVICE_AMC574,
    XUSP_DEVICE_ZCU208,
    XUSP_DEVICE_ZCU216,
    XUSP_DEVICE_ZCU670,
    XUSP_DEVICE_ULTRA96,
    XUSP_DEVICE_K26C,
    XUSP_DEVICE_K26I,
    XUSP_DEVICE_KV260,
    XUSP_DEVICE_AMC584,
    XUSP_DEVICE_HTG_960,
    XUSP_DEVICE_VCU1525,
    XUSP_DEVICE_VCU118,
    XUSP_DEVICE_VCU128,
    XUSP_DEVICE_VCU129,
    XUSP_DEVICE_HTG_940_9_3,
    XUSP_DEVICE_HTG_940_9,
    XUSP_DEVICE_HTG_940_13_3,
    XUSP_DEVICE_HTG_940_13,
    XUSP_DEVICE_HTG_9200_5P,
    XUSP_DEVICE_HTG_9200_9P,
    XUSP_DEVICE_HTG_9200_13P,
    XUSP_DEVICE_HTG_VUP_PCIE_HH_9P,
    XUSP_DEVICE_HTG_VUP_PCIE_HH_13P,
    XUSP_DEVICE_HTG_ZRF_FMC_28,
    XUSP_DEVICE_HTG_ZRF_FMC_48,
    XUSP_DEVICE_HTG_ZRF16_29,
    XUSP_DEVICE_HTG_ZRF16_49,
    XUSP_DEVICE_HTG_ZRF_HH_28,
    XUSP_DEVICE_HTG_ZRF_HH_48,
    XUSP_DEVICE_HTG_ZUSP_PCIE_11_3,
    XUSP_DEVICE_HTG_ZUSP_PCIE_19_2,
    XUSP_DEVICE_HTG_ZRF8_R2_28,
    XUSP_DEVICE_HTG_ZRF8_R2_48_I,
    XUSP_DEVICE_HTG_ZRF8_R2_48,
    XUSP_DEVICE_ZUBOARD_1CG,
    XUSP_DEVICE_KCU116,
    XUSP_DEVICE_VERMEO_T1_MP,
    XUSP_DEVICE_VERMEO_T1_RF,
    XUSP_DEVICE_ZCU1275,
    XUSP_DEVICE_ZCU1285,
    XUSP_DEVICE_ZCU111,
    XUSP_DEVICE_GENESYS_5EV,
	XUSP_DEVICE_GENESYS_3EG,
    
    
    XUSP_DEVICE_MAX
};

#define TODO 0
//Functions how to build devices
#define XUSP_PARTNAME(value) {initializedResourceStringPartName = partName = value;}
#define XUSP_SLRFROMROW(slrID,value) {SLRinfo[slrID].fromRow = value;}
#define XUSP_SLRTOROW(slrID,value) {SLRinfo[slrID].toRow = value;}
#define XUSP_ROWNUM(value) {numberOfRows = value;}
#define XUSP_SLRNUM(value) {numberOfSLRs = value;}
#define XUSP_IDCODE(slrID,value) {SLRinfo[slrID].IDCODE = value;}
#define XUSP_STRING(rowID,value) {strcpy(resourceString[rowID],value);}
#define XUSP_STRING_CAT(x,y)  {XUSP_STRING(y, x##STRING##y);}
#define XUSP_STRING_CAT_2(x)  {XUSP_STRING_CAT(x,0);  XUSP_STRING_CAT(x,1);}
#define XUSP_STRING_CAT_3(x)  {XUSP_STRING_CAT_2(x);  XUSP_STRING_CAT(x,2);}
#define XUSP_STRING_CAT_4(x)  {XUSP_STRING_CAT_3(x);  XUSP_STRING_CAT(x,3);}
#define XUSP_STRING_CAT_5(x)  {XUSP_STRING_CAT_4(x);  XUSP_STRING_CAT(x,4);}
#define XUSP_STRING_CAT_6(x)  {XUSP_STRING_CAT_5(x);  XUSP_STRING_CAT(x,5);}
#define XUSP_STRING_CAT_7(x)  {XUSP_STRING_CAT_6(x);  XUSP_STRING_CAT(x,6);}
#define XUSP_STRING_CAT_8(x)  {XUSP_STRING_CAT_7(x);  XUSP_STRING_CAT(x,7);}
#define XUSP_STRING_CAT_9(x)  {XUSP_STRING_CAT_8(x);  XUSP_STRING_CAT(x,8);}
#define XUSP_STRING_CAT_10(x) {XUSP_STRING_CAT_9(x);  XUSP_STRING_CAT(x,9);}
#define XUSP_STRING_CAT_11(x) {XUSP_STRING_CAT_10(x); XUSP_STRING_CAT(x,10);}
#define XUSP_STRING_CAT_12(x) {XUSP_STRING_CAT_11(x); XUSP_STRING_CAT(x,11);}
#define XUSP_STRING_CAT_13(x) {XUSP_STRING_CAT_12(x); XUSP_STRING_CAT(x,12);}
#define XUSP_STRING_CAT_14(x) {XUSP_STRING_CAT_13(x); XUSP_STRING_CAT(x,13);}
#define XUSP_STRING_CAT_15(x) {XUSP_STRING_CAT_14(x); XUSP_STRING_CAT(x,14);}
#define XUSP_STRING_CAT_16(x) {XUSP_STRING_CAT_15(x); XUSP_STRING_CAT(x,15);}
#define XUSP_STRING_CAT_17(x) {XUSP_STRING_CAT_16(x); XUSP_STRING_CAT(x,16);}
#define XUSP_STRING_CAT_18(x) {XUSP_STRING_CAT_17(x); XUSP_STRING_CAT(x,17);}
#define XUSP_STRING_CAT_19(x) {XUSP_STRING_CAT_18(x); XUSP_STRING_CAT(x,18);}
#define XUSP_STRING_CAT_20(x) {XUSP_STRING_CAT_19(x); XUSP_STRING_CAT(x,19);}

#define XUSP_SETUP_SLR_EXPANDED(slrID,idcodeVal,fromRowVal,toRowVal) {XUSP_IDCODE(slrID,idcodeVal);XUSP_SLRFROMROW(slrID,fromRowVal);XUSP_SLRTOROW(slrID,toRowVal);}
#define XUSP_SETUP_SLR0(prefix) {XUSP_SETUP_SLR_EXPANDED(0, prefix##IDCODE, prefix##SLR0_START, prefix##SLR0_END);}
#define XUSP_SETUP_SLR(slrID, prefix) {XUSP_SETUP_SLR_EXPANDED(slrID, prefix##IDCODE##slrID, prefix##SLR##slrID##_START, prefix##SLR##slrID##_END);}
#define XUSP_SETUP_SLRs_2(prefix) {XUSP_SETUP_SLR0(prefix); XUSP_SETUP_SLR(1,prefix);}
#define XUSP_SETUP_SLRs_3(prefix) {XUSP_SETUP_SLRs_2(prefix); XUSP_SETUP_SLR(2,prefix);}
#define XUSP_SETUP_SLRs_4(prefix) {XUSP_SETUP_SLRs_3(prefix); XUSP_SETUP_SLR(3,prefix);}
#define XUSP_SETUP_DEVICE(prefix) {                                                               \
    XUSP_PARTNAME(prefix##NAME);                                                                  \
    XUSP_SLRNUM(prefix##SLRNUM);                                                                  \
    XUSP_ROWNUM(prefix##ROWNUM);                                                                  \
    XUSP_SLRFROMROW(0,0);                                                                         \
    XUSP_SLRTOROW(0,prefix##ROWNUM-1);                                                              \
    XUSP_IDCODE(0,prefix##IDCODE);                                                                \
}


//Xilinx UltraScale+ Artix
    #define XCAU10P_NAME "xcau10p"
    #define XCAU10P_SLRNUM 1
    #define XCAU10P_ROWNUM 3
    #define XCAU10P_IDCODE 0x4AC5093
    #define XCAU10P_STRING0 "abcdJPLJPLJPAJPLJELJPLJPLJPLJPLJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfijKQOKQCKQOKGOKQOKGOKQOKkl\x01"
    #define XCAU10P_STRING1 "abcdJPLJPLJPAJPLJELJPLJPLJPLJPLJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfmjKQOKQCKQOKGOKQOKGOKQOKkl\x01"
    #define XCAU10P_STRING2 "abcdJPLJPLJPAJPLJELJPLJPLJPLJPLJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfnjKQOKQCKQOKGOKQOKGOKQOKkl\x01"
    #define XCAU10P() {                                                                            \
        XUSP_SETUP_DEVICE(XCAU10P_);                                                               \
        XUSP_STRING_CAT_3(XCAU10P_);                                                               \
    }

    #define XCAU15P_NAME "xcau15p"
    #define XCAU15P_SLRNUM 1
    #define XCAU15P_ROWNUM 3
    #define XCAU15P_IDCODE 0x4AC4093
    #define XCAU15P_STRING0 XCAU10P_STRING0
    #define XCAU15P_STRING1 XCAU10P_STRING1
    #define XCAU15P_STRING2 XCAU10P_STRING2
    #define XCAU15P() {                                                                            \
        XUSP_SETUP_DEVICE(XCAU15P_);                                                               \
        XUSP_STRING_CAT_3(XCAU15P_);                                                               \
    }
	
	//SW-limitted version of AU25P, same FPGA as KU3P, KU5P
    #define XCAU20P_NAME "xcau20p"
    #define XCAU20P_SLRNUM 1
    #define XCAU20P_ROWNUM 4
    #define XCAU20P_IDCODE 0x4A65093
    #define XCAU20P_STRING0 "abcdJPLJPBJPLJELJPSJPLJELJPMJPAJPLJELJPSJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPAJPSJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJPBJPLJELJPSJPLJELJPSJPLJPAJPMJELJPSJPLJDJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPBJPLJfojKQOKQCKQOKGOKQOKGOKQOKkp\x01"
    #define XCAU20P_STRING1 "abcdJPLJPBJPLJELJPSJPLJELJPMJPAJPLJELJPSJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPAJPSJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJPBJPLJELJPSJPLJELJPSJPLJPAJPMJELJPSJPLJDJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPBJPLJfmjKQOKQCKQOKGOKQOKGOKQOKkp\x01"
    #define XCAU20P_STRING2 "abcdJPLJPBJPLJELJPSJPLJELJPMJPAJPLJELJPSJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPAJPSJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJPBJPLJELJPSJPLJELJPSJPLJPAJPMJELJPSJPLJDJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPBJPLJfnjKQOKQCKQOKGOKQOKGOKQOKkp\x01"
    #define XCAU20P_STRING3 "abcdJPLJPBJPLJELJPSJPLJELJPMJPAJPLJELJPSJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPAJPSJPLJfghJPLJPSJPBJPLJELJPLJELJPLJFLJPLJPBJPLJELJPSJPLJELJPSJPLJPAJPMJELJPSJPLJDJPLJELJPSJPLJPAJPLJFLJPLJELJPLJELJPLJPBJPLJfqjKQOKQCKQOKGOKQOKGOKQOKkp\x01"
    #define XCAU20P() {                                                                            \
        XUSP_SETUP_DEVICE(XCAU20P_);                                                               \
        XUSP_STRING_CAT_4(XCAU20P_);                                                               \
    }
	
	//Same FPGA as KU5P
    #define XCAU25P_NAME "xcau25p"
    #define XCAU25P_SLRNUM 1
    #define XCAU25P_ROWNUM 4
    #define XCAU25P_IDCODE 0x4A64093
    #define XCAU25P_STRING0 XCAU20P_STRING0
    #define XCAU25P_STRING1 XCAU20P_STRING1
    #define XCAU25P_STRING2 XCAU20P_STRING2
    #define XCAU25P_STRING3 XCAU20P_STRING3
    #define XCAU25P() {                                                                            \
        XUSP_SETUP_DEVICE(XCAU25P_);                                                               \
        XUSP_STRING_CAT_4(XCAU25P_);                                                               \
    }
    
//Xilinx UltraScale+ Kintex
    //XCKU3P is software-limited version of XCKU5P
    #define XCKU3P_NAME "xcku3p"
    #define XCKU3P_SLRNUM 1
    #define XCKU3P_ROWNUM 4
    #define XCKU3P_IDCODE 0x4A63093
	#define XCKU3P_STRING0 XCAU20P_STRING0
    #define XCKU3P_STRING1 XCAU20P_STRING1
    #define XCKU3P_STRING2 XCAU20P_STRING2
    #define XCKU3P_STRING3 XCAU20P_STRING3
    #define XCKU3P() {                                                                            \
        XUSP_SETUP_DEVICE(XCKU3P_);                                                               \
        XUSP_STRING_CAT_4(XCKU3P_);                                                               \
    }

    #define XCKU5P_NAME "xcku5p"
    #define XCKU5P_SLRNUM 1
    #define XCKU5P_ROWNUM 4
    #define XCKU5P_IDCODE 0x4A62093
    #define XCKU5P_STRING0 XCKU3P_STRING0
    #define XCKU5P_STRING1 XCKU3P_STRING1
    #define XCKU5P_STRING2 XCKU3P_STRING2
    #define XCKU5P_STRING3 XCKU3P_STRING3
    #define XCKU5P() {                                                                            \
        XUSP_SETUP_DEVICE(XCKU5P_);                                                               \
        XUSP_STRING_CAT_4(XCKU5P_);                                                               \
    }

    #define XCKU9P_NAME "xcku9p"
    #define XCKU9P_SLRNUM 1
    #define XCKU9P_ROWNUM 7
    #define XCKU9P_IDCODE 0x484A093
    #define XCKU9P_STRING0  "2076676176672676676176672676672676676176672676676176672676672676676176672rJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPLJFLJPLJPBJPLJELJPLJPAJPMJELJPLJPBJPLJELJPLJFLJPLJPBJPLJPAJPLJfgjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU9P_STRING1  "2076676176672676676176672676672676676176672676676176672676672676676176672rJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPLJFLJPLJPBJPLJELJPLJPAJPMJELJPLJPBJPLJELJPLJFLJPLJPBJPLJPAJPLJfmjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU9P_STRING2  "2076676176672676676176672676672676676176672676676176672676672676676176672rJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPLJFLJPLJPBJPLJELJPLJPAJPMJELJPLJPBJPLJELJPLJFLJPLJPBJPLJPAJPLJfnjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU9P_STRING3  "xyJPLJPAJPLJELJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJPBJPLJELJPLJFLJPLJPAJPLJELJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPLJFLJPLJPBJPLJELJPLJPAJPMJELJPLJPBJPLJELJPLJFLJPLJPBJPLJPAJPLJfgjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU9P_STRING4  "xyJPLJPAJPLJELJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJPBJPLJELJPLJFLJPLJPAJPLJELJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPLJFLJPLJPBJPLJELJPLJPAJPMJELJPLJPBJPLJELJPLJFLJPLJPBJPLJPAJPLJfgjKQOKGOKQOKGOKQOKQCKQOKz50l\x01"
    #define XCKU9P_STRING5 XCKU9P_STRING4
    #define XCKU9P_STRING6 XCKU9P_STRING4
    #define XCKU9P() {                                                                            \
        XUSP_SETUP_DEVICE(XCKU9P_);                                                               \
        XUSP_STRING_CAT_7(XCKU9P_);                                                               \
    }

    #define XCKU11P_NAME "xcku11p"
    #define XCKU11P_SLRNUM 1
    #define XCKU11P_ROWNUM 8
    #define XCKU11P_IDCODE 0x4A4E093
    #define XCKU11P_STRING0 "2076676676672676676176670407667617667667376672%JPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING1 "2076676676672676676176670407667617667667376672%JPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfmjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING2 "2076676676672676676176670407667617667667376672%JPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfnjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING3 "UyJPLJPSJPLJELJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING4 "UyJPLJPSJPLJELJPLJPBJPLJfohJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING5 "UyJPLJPSJPLJELJPLJPBJPLJfVhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING6 "UyJPLJPSJPLJELJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJELJPMJEabc^JPLJPBJPLJELJPLJEMJPLJELJPLJELJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU11P_STRING7 XCKU11P_STRING4
    #define XCKU11P() {                                                                           \
        XUSP_SETUP_DEVICE(XCKU11P_);                                                              \
        XUSP_STRING_CAT_8(XCKU11P_);                                                              \
    }

    #define XCKU13P_NAME "xcku13p"
    #define XCKU13P_SLRNUM 1
    #define XCKU13P_ROWNUM 7
    #define XCKU13P_IDCODE 0x4A52093
    #define XCKU13P_STRING0 "2076676176672676676176672676672676676176672676676176672676672676676176672rJPLJDJPLJELJPLJPBJPLJEMJPLJELJPLJELJPLJPAJPLJELJPLJFLJPLJELJPSJPLJPLJELJPLJPBJPLJELJPMJELJPSJPLJELJPLJPAJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfgjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU13P_STRING1 "2076676176672676676176672676672676676176672676676176672676672676676176672rJPLJDJPLJELJPLJPBJPLJEMJPLJELJPLJELJPLJPAJPLJELJPLJFLJPLJELJPSJPLJPLJELJPLJPBJPLJELJPMJELJPSJPLJELJPLJPAJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfmjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU13P_STRING2 "2076676176672676676176672676672676676176672676676176672676672676676176672rJPLJDJPLJELJPLJPBJPLJEMJPLJELJPLJELJPLJPAJPLJELJPLJFLJPLJELJPSJPLJPLJELJPLJPBJPLJELJPMJELJPSJPLJELJPLJPAJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfnjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU13P_STRING3 "xyJPLJPAJPLJELJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJPBJPLJELJPLJFLJPLJPAJPLJELJPLJDJPLJELJPLJPBJPLJEMJPLJELJPLJELJPLJPAJPLJELJPLJFLJPLJELJPSJPLJPLJELJPLJPBJPLJELJPMJELJPSJPLJELJPLJPAJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfgjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCKU13P_STRING4 "xyJPLJPAJPLJELJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJPBJPLJELJPLJFLJPLJPAJPLJELJPLJDJPLJELJPLJPBJPLJEMJPLJELJPLJELJPLJPAJPLJELJPLJFLJPLJELJPSJPLJPLJELJPLJPBJPLJELJPMJELJPSJPLJELJPLJPAJPLJELJPLJFLJPLJELJPLJELJPLJPBJPLJfgjKQOKGOKQOKGOKQOKQCKQOKz50l\x01"
    #define XCKU13P_STRING5 XCKU13P_STRING4
    #define XCKU13P_STRING6 XCKU13P_STRING4
    #define XCKU13P() {                                                                           \
        XUSP_SETUP_DEVICE(XCKU13P_);                                                              \
        XUSP_STRING_CAT_7(XCKU13P_);                                                              \
    }

    #define XCKU15P_NAME "xcku15p"
    #define XCKU15P_SLRNUM 1
    #define XCKU15P_ROWNUM 11
    #define XCKU15P_IDCODE 0x4A56093
    #define XCKU15P_STRING0 "2076676676672676676176670407667617667667376672%JPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING1 "2076676676672676676176670407667617667667376672%JPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfmjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING2 "2076676676672676676176670407667617667667376672%JPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfnjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING3 "UyJPLJPSJPLJELJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING4 "UyJPLJPSJPLJELJPLJPBJPLJfohJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING5 "UyJPLJPSJPLJELJPLJPBJPLJfVhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfVjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING6 "UyJPLJPSJPLJELJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING7 "UyJPLJPSJPLJELJPLJPBJPLJfohJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING8 "UyJPLJPSJPLJELJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfVjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING9 "UyJPLJPSJPLJELJPLJPBJPLJfVhJPLJPBJPSJPLJDJPLJFLJPLJPBJPLJELJPLJEMJPLJPAJPLJELJPLJEMJPabc^JPLJPBJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPSJPAJPLJFLJPLJPSJPLJPSJPSJPLJPBJPSJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCKU15P_STRING10 XCKU15P_STRING6
    #define XCKU15P() {                                                                           \
        XUSP_SETUP_DEVICE(XCKU15P_);                                                              \
        XUSP_STRING_CAT_11(XCKU15P_);                                                             \
    }

    #define XCKU19P_NAME "xcku19p"
    #define XCKU19P_SLRNUM 1
    #define XCKU19P_ROWNUM 9
    #define XCKU19P_IDCODE 0x4ACF093
    #define XCKU19P_STRING0 "abcdJPLJPAJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJDJPLJPSJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPLJDJPLJPLJPAJPLJfmjKQTKQCKQOKGOKQTKQOKRTKkp\x01"
    #define XCKU19P_STRING1 "abcdJPLJPAJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJDJPLJPSJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPLJDJPLJPLJPAJPLJfnjKQTKQCKQOKGOKQTKQOKRTKkp\x01"
    #define XCKU19P_STRING2 "abcdJPLJPAJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJDJPLJPSJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPLJDJPLJPLJPAJPLJfijKQTKQCKQOKGOKQTKQOKRTKkp\x01"
    #define XCKU19P_STRING3 "abcdJPLJPAJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJDJPLJPSJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPLJDJPLJPLJPAJPLJfgjKQTKQCKQOKGOKQTKQOKRTKkp\x01"
    #define XCKU19P_STRING4 XCKU19P_STRING2
    #define XCKU19P_STRING5 XCKU19P_STRING3
    #define XCKU19P_STRING6 XCKU19P_STRING2
    #define XCKU19P_STRING7 XCKU19P_STRING3
    #define XCKU19P_STRING8 "abcdJPLJPAJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJDJPLJPSJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPAJPLJPSJPSJPLJPSJPAJPLJPSJPSJPMJPSJPSJPLJPAJPSJPLJPSJPSJPLJPSJPBJPLJFLJPLJDJPLJPLJPAJPLJfqjKQTKQCKQOKGOKQTKQOKRTKkW\x01"
    #define XCKU19P() {                                                                           \
        XUSP_SETUP_DEVICE(XCKU19P_);                                                              \
        XUSP_STRING_CAT_9(XCKU19P_);                                                              \
    }

//Xilinx UltraScale+ Virtex
    #define XCVU3P_NAME "xcvu3p"
    #define XCVU3P_SLRNUM 1
    #define XCVU3P_ROWNUM 5
    #define XCVU3P_IDCODE 0x4B39093
    #define XCVU3P_STRING0 "UyJPLJELJPLJPLJPXJPAJPLJfqhJPLJPBJPLJELJPXJPLJELJPLJELJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJELJPMJPabc^JPLJPAJPLJELJPXJPLJDJPMJPLJPLJPLJPLJPLJPXJPLJELJPBJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJELJPMJPabc^JPLJPAJPLJELJPXJPLJDJPMJPLJPLJPLJPLJPLJPXJPLJELJPBJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfojKQOKQCKQYKQOKQOKGOKQOKkp\x01"
    #define XCVU3P_STRING1 "UyJPLJELJPLJPLJPLJPAJPLJfVhJPLJPBJPLJELJPLJPLJELJPLJELJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJELJPMJPabc^JPLJPAJPLJELJPLJPLJDJPMJPLJPLJPLJPLJPLJPLJPLJELJPBJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJELJPMJPabc^JPLJPAJPLJELJPLJPLJDJPMJPLJPLJPLJPLJPLJPLJPLJELJPBJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfmjKQOKQCKQOKQOKQOKGOKQOKkp\x01"
    #define XCVU3P_STRING2 "UyJPLJELJPLJPLJPLJPAJPLJfqhJPLJPBJPLJELJPLJPLJELJPLJELJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJELJPMJPabc^JPLJPAJPLJELJPLJPLJDJPMJPLJPLJPLJPLJPLJPLJPLJELJPBJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJELJPMJPabc^JPLJPAJPLJELJPLJPLJDJPMJPLJPLJPLJPLJPLJPLJPLJELJPBJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfnjKQOKQCKQOKQOKQOKGOKQOKkp\x01"
    #define XCVU3P_STRING3 "UyJPLJELJPLJPLJPLJPAJPLJfohJPLJPBJPLJELJPLJPLJELJPLJELJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJELJPMJPabc^JPLJPAJPLJELJPLJPLJDJPMJPLJPLJPLJPLJPLJPLJPLJELJPBJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJELJPMJPabc^JPLJPAJPLJELJPLJPLJDJPMJPLJPLJPLJPLJPLJPLJPLJELJPBJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfVjKQOKQCKQOKQOKQOKGOKQOKkp\x01"
    #define XCVU3P_STRING4 "UyJPLJELJPLJPLJPXJPAJPLJfqhJPLJPBJPLJELJPXJPLJELJPLJELJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJELJPMJPabc^JPLJPAJPLJELJPXJPLJDJPMJPLJPLJPLJPLJPLJPXJPLJELJPBJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJELJPMJPabc^JPLJPAJPLJELJPXJPLJDJPMJPLJPLJPLJPLJPLJPXJPLJELJPBJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfVjKQOKQCKQYKQOKQOKGOKQOKkp\x01"
    #define XCVU3P() {                                                                            \
        XUSP_SETUP_DEVICE(XCVU3P_);                                                               \
        XUSP_STRING_CAT_5(XCVU3P_);                                                               \
    }

    //XCVU5P is software-limited version of 2 XCVU3P dies
    #define XCVU5P_NAME "xcvu5p"
    #define XCVU5P_SLRNUM 2
    #define XCVU5P_ROWNUM 10
    #define XCVU5P_IDCODE 0x4B2B093
    #define XCVU5P_IDCODE1 0x4B22093
    #define XCVU5P_SLR0_START 0
    #define XCVU5P_STRING0 XCVU3P_STRING0
    #define XCVU5P_STRING1 XCVU3P_STRING1
    #define XCVU5P_STRING2 XCVU3P_STRING2
    #define XCVU5P_STRING3 XCVU3P_STRING3
    #define XCVU5P_STRING4 XCVU3P_STRING4
    #define XCVU5P_SLR0_END 4
    #define XCVU5P_SLR1_START 5
    #define XCVU5P_STRING5 XCVU3P_STRING0
    #define XCVU5P_STRING6 XCVU3P_STRING1
    #define XCVU5P_STRING7 XCVU3P_STRING2
    #define XCVU5P_STRING8 XCVU3P_STRING3
    #define XCVU5P_STRING9 XCVU3P_STRING4
    #define XCVU5P_SLR1_END 9
    #define XCVU5P() {                                                                            \
        XUSP_SETUP_DEVICE(XCVU5P_);                                                               \
        XUSP_SETUP_SLRs_2(XCVU5P_);                                                               \
        XUSP_STRING_CAT_10(XCVU5P_);                                                              \
    }

    //XCVU7P is 2 XCVU3P dies
    #define XCVU7P_NAME "xcvu7p"
    #define XCVU7P_SLRNUM 2
    #define XCVU7P_ROWNUM 10
    #define XCVU7P_IDCODE 0x4B29093
    #define XCVU7P_IDCODE1 XCVU5P_IDCODE1
    #define XCVU7P_SLR0_START 0
    #define XCVU7P_STRING0 XCVU5P_STRING0
    #define XCVU7P_STRING1 XCVU5P_STRING1
    #define XCVU7P_STRING2 XCVU5P_STRING2
    #define XCVU7P_STRING3 XCVU5P_STRING3
    #define XCVU7P_STRING4 XCVU5P_STRING4
    #define XCVU7P_SLR0_END 4
    #define XCVU7P_SLR1_START 5
    #define XCVU7P_STRING5 XCVU5P_STRING5
    #define XCVU7P_STRING6 XCVU5P_STRING6
    #define XCVU7P_STRING7 XCVU5P_STRING7
    #define XCVU7P_STRING8 XCVU5P_STRING8
    #define XCVU7P_STRING9 XCVU5P_STRING9
    #define XCVU7P_SLR1_END 9
    #define XCVU7P() {                                                                            \
        XUSP_SETUP_DEVICE(XCVU7P_);                                                               \
        XUSP_SETUP_SLRs_2(XCVU7P_);                                                               \
        XUSP_STRING_CAT_10(XCVU7P_);                                                              \
    }

    //XCVU9P is 3 XCVU3P dies
    #define XCVU9P_NAME "xcvu9p"
    #define XCVU9P_SLRNUM 3
    #define XCVU9P_ROWNUM 15
    #define XCVU9P_IDCODE 0x4B31093
    #define XCVU9P_IDCODE1 XCVU7P_IDCODE1
    #define XCVU9P_IDCODE2 0x4B24093
    #define XCVU9P_SLR1_START 0
    #define XCVU9P_STRING0 XCVU3P_STRING0
    #define XCVU9P_STRING1 XCVU3P_STRING1
    #define XCVU9P_STRING2 XCVU3P_STRING2
    #define XCVU9P_STRING3 XCVU3P_STRING3
    #define XCVU9P_STRING4 XCVU3P_STRING4
    #define XCVU9P_SLR1_END 4
    #define XCVU9P_SLR0_START 5
    #define XCVU9P_STRING5 XCVU3P_STRING0
    #define XCVU9P_STRING6 XCVU3P_STRING1
    #define XCVU9P_STRING7 XCVU3P_STRING2
    #define XCVU9P_STRING8 XCVU3P_STRING3
    #define XCVU9P_STRING9 XCVU3P_STRING4
    #define XCVU9P_SLR0_END 9
    #define XCVU9P_SLR2_START 10
    #define XCVU9P_STRING10 XCVU3P_STRING0
    #define XCVU9P_STRING11 XCVU3P_STRING1
    #define XCVU9P_STRING12 XCVU3P_STRING2
    #define XCVU9P_STRING13 XCVU3P_STRING3
    #define XCVU9P_STRING14 XCVU3P_STRING4
    #define XCVU9P_SLR2_END 14
    #define XCVU9P() {                                                                            \
        XUSP_SETUP_DEVICE(XCVU9P_);                                                               \
        XUSP_SETUP_SLRs_3(XCVU9P_);                                                               \
        XUSP_STRING_CAT_15(XCVU9P_);                                                              \
    }

    //3 identical dies (4 rows each)
    #define XCVU11P_NAME "xcvu11p"
    #define XCVU11P_SLRNUM 3
    #define XCVU11P_ROWNUM 12
    #define XCVU11P_IDCODE 0x4B49093
    #define XCVU11P_IDCODE1 0x4B42093
    #define XCVU11P_IDCODE2 0x4B44093
    #define XCVU11P_SLR0_START 0
    #define XCVU11P_STRING0 "UyJPLJELJPLJPLJPXJPAJPLJfqhJPLJPBJPLJELJPXJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPXJPLJDJPMJELJPLJPLJPLJPXJPLJELJPAJPLJFLJPBJPLJELJPXJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPXJPLJELJPAJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJEMJPabc^JPLJPAJPLJELJPXJPLJDJPMJELJPSJPLJPSJPLJPXJPLJELJPBJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfojKQOKQCKQYKQOKQOKGOKQOKkp\x01"
    #define XCVU11P_STRING1 "UyJPLJELJPLJPLJPLJPAJPLJfVhJPLJPBJPLJELJPLJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPLJPLJDJPMJELJPLJPLJPLJPLJPLJELJPAJPLJFLJPBJPLJELJPLJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPLJPLJELJPAJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJEMJPabc^JPLJPAJPLJELJPLJPLJDJPMJELJPSJPLJPSJPLJPLJPLJELJPBJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfmjKQOKQCKQOKQOKQOKGOKQOKkp\x01"
    #define XCVU11P_STRING2 "UyJPLJELJPLJPLJPLJPAJPLJfqhJPLJPBJPLJELJPLJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPLJPLJDJPMJELJPLJPLJPLJPLJPLJELJPAJPLJFLJPBJPLJELJPLJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPLJPLJELJPAJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJEMJPabc^JPLJPAJPLJELJPLJPLJDJPMJELJPSJPLJPSJPLJPLJPLJELJPBJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfnjKQOKQCKQOKQOKQOKGOKQOKkp\x01"
    #define XCVU11P_STRING3 "UyJPLJELJPLJPLJPXJPAJPLJfqhJPLJPBJPLJELJPXJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPXJPLJDJPMJELJPLJPLJPLJPXJPLJELJPAJPLJFLJPBJPLJELJPXJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPXJPLJELJPAJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJEMJPabc^JPLJPAJPLJELJPXJPLJDJPMJELJPSJPLJPSJPLJPXJPLJELJPBJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfVjKQOKQCKQYKQOKQOKGOKQOKkp\x01"
    #define XCVU11P_SLR0_END 3
    #define XCVU11P_SLR1_START 4
    #define XCVU11P_STRING4 XCVU11P_STRING0
    #define XCVU11P_STRING5 XCVU11P_STRING1
    #define XCVU11P_STRING6 XCVU11P_STRING2
    #define XCVU11P_STRING7 XCVU11P_STRING3
    #define XCVU11P_SLR1_END 7
    #define XCVU11P_SLR2_START 8
    #define XCVU11P_STRING8 XCVU11P_STRING0
    #define XCVU11P_STRING9 XCVU11P_STRING1
    #define XCVU11P_STRING10 XCVU11P_STRING2
    #define XCVU11P_STRING11 XCVU11P_STRING3
    #define XCVU11P_SLR2_END 11
    #define XCVU11P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU11P_);                                                              \
        XUSP_SETUP_SLRs_3(XCVU11P_);                                                              \
        XUSP_STRING_CAT_12(XCVU11P_);                                                             \
    }

    //4 identical dies (4 rows each) (same dies as XCVU11P)
    #define XCVU13P_NAME "xcvu13p"
    #define XCVU13P_SLRNUM 4
    #define XCVU13P_ROWNUM 16
    #define XCVU13P_IDCODE 0x4B51093
    #define XCVU13P_IDCODE1 XCVU11P_IDCODE1
    #define XCVU13P_IDCODE2 XCVU11P_IDCODE2
    #define XCVU13P_IDCODE3 0x4B46093
    #define XCVU13P_SLR1_START 0
    #define XCVU13P_STRING0 XCVU11P_STRING0
    #define XCVU13P_STRING1 XCVU11P_STRING1
    #define XCVU13P_STRING2 XCVU11P_STRING2
    #define XCVU13P_STRING3 XCVU11P_STRING3
    #define XCVU13P_SLR1_END 3
    #define XCVU13P_SLR0_START 4
    #define XCVU13P_STRING4 XCVU11P_STRING0
    #define XCVU13P_STRING5 XCVU11P_STRING1
    #define XCVU13P_STRING6 XCVU11P_STRING2
    #define XCVU13P_STRING7 XCVU11P_STRING3
    #define XCVU13P_SLR0_END 7
    #define XCVU13P_SLR2_START 8
    #define XCVU13P_STRING8 XCVU11P_STRING0
    #define XCVU13P_STRING9 XCVU11P_STRING1
    #define XCVU13P_STRING10 XCVU11P_STRING2
    #define XCVU13P_STRING11 XCVU11P_STRING3
    #define XCVU13P_SLR2_END 11
    #define XCVU13P_SLR3_START 12
    #define XCVU13P_STRING12 XCVU11P_STRING0
    #define XCVU13P_STRING13 XCVU11P_STRING1
    #define XCVU13P_STRING14 XCVU11P_STRING2
    #define XCVU13P_STRING15 XCVU11P_STRING3
    #define XCVU13P_SLR3_END 15
    #define XCVU13P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU13P_);                                                              \
        XUSP_SETUP_SLRs_4(XCVU13P_);                                                              \
        XUSP_STRING_CAT_16(XCVU13P_);                                                             \
    }

    //4 identical dies (5 rows each) also rows are the widest
    #define XCVU19P_NAME "xcvu19p"
    #define XCVU19P_SLRNUM 4
    #define XCVU19P_ROWNUM 20
    #define XCVU19P_IDCODE 0x4BA1093
    #define XCVU19P_IDCODE1 0x4BA2093
    #define XCVU19P_IDCODE2 0x4BA4093
    #define XCVU19P_IDCODE3 0x4BA6093
    #define XCVU19P_SLR1_START 0
    #define XCVU19P_STRING0 "abcdJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPBJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJDJPLJPLJFLJPLJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJPMJPabc^JPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPSJPLJPSJPSJPLJPSJPSJPLJPSJPAJPLJfijKQOKQCKQTKQOKQOKGOKQOKkp\x01"
    #define XCVU19P_STRING1 "abcdJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPBJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJDJPLJPLJFLJPLJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJPMJPabc^JPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPSJPLJPSJPSJPLJPSJPSJPLJPSJPAJPLJfmjKQOKQCKQTKQOKQOKGOKQOKkp\x01"
    #define XCVU19P_STRING2 "abcdJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPBJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJDJPLJPLJFLJPLJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJPMJPabc^JPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPSJPLJPSJPSJPLJPSJPSJPLJPSJPAJPLJfnjKQOKQCKQTKQOKQOKGOKQOKkp\x01"
    #define XCVU19P_STRING3 "abcdJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPLJPBJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJDJPLJPLJFLJPLJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJPMJPabc^JPLJPAJPSJPLJPNJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPNJPSJPLJPSJPSJPLJFLJPSJPLJPSJPSJPLJPSJPSJPLJPSJPAJPLJfijKQOKQCKQTKQOKQOKGOKQOKkp\x01"
    #define XCVU19P_STRING4 "abcdJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPLJPBJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJDJPLJPLJFLJPLJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJPMJPabc^JPLJPAJPSJPLJPZJPSJPLJPSJPSJPLJPSJPSJPMJPSJPSJPLJPSJPSJPLJPZJPSJPLJPSJPSJPLJFLJPSJPLJPSJPSJPLJPSJPSJPLJPSJPAJPLJfgjKQOKQCKQTKQOKQOKGOKQOKkp\x01"
    #define XCVU19P_SLR1_END 4
    #define XCVU19P_SLR0_START 5
    #define XCVU19P_STRING5 XCVU19P_STRING0
    #define XCVU19P_STRING6 XCVU19P_STRING1
    #define XCVU19P_STRING7 XCVU19P_STRING2
    #define XCVU19P_STRING8 XCVU19P_STRING3
    #define XCVU19P_STRING9 XCVU19P_STRING4
    #define XCVU19P_SLR0_END 9
    #define XCVU19P_SLR2_START 10
    #define XCVU19P_STRING10 XCVU19P_STRING0
    #define XCVU19P_STRING11 XCVU19P_STRING1
    #define XCVU19P_STRING12 XCVU19P_STRING2
    #define XCVU19P_STRING13 XCVU19P_STRING3
    #define XCVU19P_STRING14 XCVU19P_STRING4
    #define XCVU19P_SLR2_END 14
    #define XCVU19P_SLR3_START 15
    #define XCVU19P_STRING15 XCVU19P_STRING0
    #define XCVU19P_STRING16 XCVU19P_STRING1
    #define XCVU19P_STRING17 XCVU19P_STRING2
    #define XCVU19P_STRING18 XCVU19P_STRING3
    #define XCVU19P_STRING19 XCVU19P_STRING4
    #define XCVU19P_SLR3_END 19
    #define XCVU19P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU19P_);                                                              \
        XUSP_SETUP_SLRs_4(XCVU19P_);                                                              \
        XUSP_STRING_CAT_20(XCVU19P_);                                                             \
    }

    #define XCVU23P_NAME "xcvu23p"
    #define XCVU23P_SLRNUM 1
    #define XCVU23P_ROWNUM 11
    #define XCVU23P_IDCODE 0x4ACE093
    #define XCVU23P_STRING0 XCKU19P_STRING2
    #define XCVU23P_STRING1 XCKU19P_STRING0
    #define XCVU23P_STRING2 XCKU19P_STRING1
    #define XCVU23P_STRING3 XCVU23P_STRING0
    #define XCVU23P_STRING4 XCKU19P_STRING3
    #define XCVU23P_STRING5 XCVU23P_STRING0
    #define XCVU23P_STRING6 XCVU23P_STRING4
    #define XCVU23P_STRING7 XCVU23P_STRING0
    #define XCVU23P_STRING8 XCVU23P_STRING4
    #define XCVU23P_STRING9 XCKU19P_STRING8
    #define XCVU23P_STRING10 XCVU23P_STRING9
    #define XCVU23P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU23P_);                                                              \
        XUSP_STRING_CAT_11(XCVU23P_);                                                             \
    }

    //XCVU27P is a software-limited version of XCVU29P
    //4 dies from XCVU11P with different I/O: first third and fourth are the same, second is diff
    #define XCVU27P_NAME "xcvu27p"
    #define XCVU27P_SLRNUM 4
    #define XCVU27P_ROWNUM 16
    #define XCVU27P_IDCODE 0x4B43093
    #define XCVU27P_IDCODE1 0x4B82093
    #define XCVU27P_IDCODE2 0x4B84093
    #define XCVU27P_IDCODE3 0x4B86093
    #define XCVU27P_SLR1_START 0
    #define XCVU27P_STRING0 "_yJPLJELJPLJPLJPXJPAJPLJfqhJPLJPBJPLJELJPXJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPXJPLJDJPMJELJPLJPLJPLJPXJPLJELJPAJPLJFLJPBJPLJELJPXJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPXJPLJELJPAJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJEMJPabc^JPLJPAJPLJELJPXJPLJDJPMJELJPSJPLJPSJPLJPXJPLJELJPBJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfqjKQOKQCKQYKQOKQOKGOKQOKkW\x01"
    #define XCVU27P_STRING1 "_yJPLJELJPLJPLJPLJPAJPLJfVhJPLJPBJPLJELJPLJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPLJPLJDJPMJELJPLJPLJPLJPLJPLJELJPAJPLJFLJPBJPLJELJPLJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPLJPLJELJPAJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJEMJPabc^JPLJPAJPLJELJPLJPLJDJPMJELJPSJPLJPSJPLJPLJPLJELJPBJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfmjKQOKQCKQOKQOKQOKGOKQOKkW\x01"
    #define XCVU27P_STRING2 "_yJPLJELJPLJPLJPLJPAJPLJfqhJPLJPBJPLJELJPLJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPLJPLJDJPMJELJPLJPLJPLJPLJPLJELJPAJPLJFLJPBJPLJELJPLJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPLJPLJELJPAJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJEMJPabc^JPLJPAJPLJELJPLJPLJDJPMJELJPSJPLJPSJPLJPLJPLJELJPBJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfnjKQOKQCKQOKQOKQOKGOKQOKkW\x01"
    #define XCVU27P_STRING3 "_yJPLJELJPLJPLJPXJPAJPLJfqhJPLJPBJPLJELJPXJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPXJPLJDJPMJELJPLJPLJPLJPXJPLJELJPAJPLJFLJPBJPLJELJPXJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPXJPLJELJPAJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJEMJPabc^JPLJPAJPLJELJPXJPLJDJPMJELJPSJPLJPSJPLJPXJPLJELJPBJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfVjKQOKQCKQYKQOKQOKGOKQOKkW\x01"
    #define XCVU27P_SLR1_END 3
    #define XCVU27P_SLR0_START 4
    #define XCVU27P_STRING4 XCVU11P_STRING0
    #define XCVU27P_STRING5 XCVU11P_STRING1
    #define XCVU27P_STRING6 XCVU11P_STRING2
    #define XCVU27P_STRING7 XCVU11P_STRING3
    #define XCVU27P_SLR0_END 7
    #define XCVU27P_SLR2_START 8
    #define XCVU27P_STRING8 XCVU27P_STRING0
    #define XCVU27P_STRING9 XCVU27P_STRING1
    #define XCVU27P_STRING10 XCVU27P_STRING2
    #define XCVU27P_STRING11 XCVU27P_STRING3
    #define XCVU27P_SLR2_END 11
    #define XCVU27P_SLR3_START 12
    #define XCVU27P_STRING12 XCVU27P_STRING0
    #define XCVU27P_STRING13 XCVU27P_STRING1
    #define XCVU27P_STRING14 XCVU27P_STRING2
    #define XCVU27P_STRING15 XCVU27P_STRING3
    #define XCVU27P_SLR3_END 15
    #define XCVU27P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU27P_);                                                              \
        XUSP_SETUP_SLRs_4(XCVU27P_);                                                              \
        XUSP_STRING_CAT_16(XCVU27P_);                                                             \
    }

    #define XCVU29P_NAME "xcvu29p"
    #define XCVU29P_SLRNUM 4
    #define XCVU29P_ROWNUM 16
    #define XCVU29P_IDCODE 0x4B41093
    #define XCVU29P_IDCODE1 XCVU27P_IDCODE1
    #define XCVU29P_IDCODE2 XCVU27P_IDCODE2
    #define XCVU29P_IDCODE3 XCVU27P_IDCODE3
    #define XCVU29P_SLR1_START 0
    #define XCVU29P_STRING0 XCVU27P_STRING0
    #define XCVU29P_STRING1 XCVU27P_STRING1
    #define XCVU29P_STRING2 XCVU27P_STRING2
    #define XCVU29P_STRING3 XCVU27P_STRING3
    #define XCVU29P_SLR1_END 3
    #define XCVU29P_SLR0_START 4
    #define XCVU29P_STRING4 XCVU27P_STRING4
    #define XCVU29P_STRING5 XCVU27P_STRING5
    #define XCVU29P_STRING6 XCVU27P_STRING6
    #define XCVU29P_STRING7 XCVU27P_STRING7
    #define XCVU29P_SLR0_END 7
    #define XCVU29P_SLR2_START 8
    #define XCVU29P_STRING8 XCVU27P_STRING8
    #define XCVU29P_STRING9 XCVU27P_STRING9
    #define XCVU29P_STRING10 XCVU27P_STRING10
    #define XCVU29P_STRING11 XCVU27P_STRING11
    #define XCVU29P_SLR2_END 11
    #define XCVU29P_SLR3_START 12
    #define XCVU29P_STRING12 XCVU27P_STRING12
    #define XCVU29P_STRING13 XCVU27P_STRING13
    #define XCVU29P_STRING14 XCVU27P_STRING14
    #define XCVU29P_STRING15 XCVU27P_STRING15
    #define XCVU29P_SLR3_END 15
    #define XCVU29P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU29P_);                                                              \
        XUSP_SETUP_SLRs_4(XCVU29P_);                                                              \
        XUSP_STRING_CAT_16(XCVU29P_);                                                             \
    }

    #define XCVU31P_NAME "xcvu31p"
    #define XCVU31P_SLRNUM 1
    #define XCVU31P_ROWNUM 4
    #define XCVU31P_IDCODE 0x4B6B093
    #define XCVU31P_STRING0 "UyJPLJ!LJPLJPLJPLJPAJPLJfihJPLJPBJPLJ!LJPLJPLJPSJPSJPLJ!LJPLJ!LJPBJPLJ!LJPLJPLJDJPMJ!LJPLJPLJPLJPLJPLJ!LJPAJPLJ!LJPBJPLJ!LJPLJPLJPSJPSJPLJ!LJPMJPLJ!LJPSJPLJPSJPLJPLJ!LJPAJPLJPBJPLJ!LJPLJPLJ!LJPLJDJPLJPMJ!LJPLJPLJPAJPLJ!MJPab@^JPLJPAJPLJ!LJPLJPLJDJPMJ!LJPSJPLJPSJPLJPLJPLJ!LJPBJPLJ!LJPBJPLJ!LJPLJPLJDJPMJ!LJPSJPLJ!LJPLJPLJ!LJPSJPLJPSJPLJ!LJPBJPLJ!LJPLJPLJDJPMJ!LJPSJPLJ!LJPLJPLJ!LJPSJPLJPSJPLJ!LJPLJPLJPLJPLJPLJ!LJPBJPLJfijKQOKQCKQOKQOKQOK!OKQOKkp\x01"
    #define XCVU31P_STRING1 "UyJPLJELJPLJPLJPLJPAJPLJfqhJPLJPBJPLJELJPLJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPLJPLJDJPMJELJPLJPLJPLJPLJPLJELJPAJPLJFLJPBJPLJELJPLJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPLJPLJELJPAJPLJPBJPLJFLJPLJPLJELJPLJDJPLJPMJELJPLJPLJPAJPLJEMJPabc^JPLJPAJPLJELJPLJPLJDJPMJELJPSJPLJPSJPLJPLJPLJELJPBJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPLJPLJDJPMJELJPSJPLJELJPLJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPLJPLJELJPBJPLJfmjKQOKQCKQOKQOKQOKGOKQOKkp\x01"
    #define XCVU31P_STRING2 XCVU11P_STRING2
    #define XCVU31P_STRING3 "UyJPLJELJPLJPLJPXJPAJPLJfihJPLJPBJPLJELJPXJPLJPSJPSJPLJELJPLJFLJPBJPLJELJPXJPLJDJPMJELJPLJPLJPLJPXJPLJELJPAJPLJFLJPBJPLJELJPXJPLJPSJPSJPLJELJPMJPLJELJPSJPLJPSJPXJPLJELJPAJPLJPBJPLJFLJPXJPLJELJPLJDJPLJPMJELJPLJPXJPAJPLJEMJPabc^JPLJPAJPLJELJPXJPLJDJPMJELJPSJPLJPSJPLJPXJPLJELJPBJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPBJPLJELJPXJPLJDJPMJELJPSJPLJELJPXJPLJELJPSJPLJPSJPLJFLJPLJPLJPLJPXJPLJELJPBJPLJfijKQOKQCKQYKQOKQOKGOKQOKkp\x01"
    #define XCVU31P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU31P_);                                                              \
        XUSP_STRING_CAT_4(XCVU31P_);                                                              \
    }

    //XCVU33P same as XCVU31P but with more HBM
    #define XCVU33P_NAME "xcvu33p"
    #define XCVU33P_SLRNUM 1
    #define XCVU33P_ROWNUM 4
    #define XCVU33P_IDCODE 0x4B69093
    #define XCVU33P_STRING0 XCVU31P_STRING0
    #define XCVU33P_STRING1 XCVU31P_STRING1
    #define XCVU33P_STRING2 XCVU31P_STRING2
    #define XCVU33P_STRING3 XCVU31P_STRING3
    #define XCVU33P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU33P_);                                                              \
        XUSP_STRING_CAT_4(XCVU33P_);                                                              \
    }

    //2 dies: XCVU33P + 1 die from XCVU11P
    #define XCVU35P_NAME "xcvu35p"
    #define XCVU35P_SLRNUM 2
    #define XCVU35P_ROWNUM 8
    #define XCVU35P_IDCODE 0x4B71093
    #define XCVU35P_IDCODE1 0x4B42093
    #define XCVU35P_SLR0_START 0
    #define XCVU35P_STRING0 XCVU33P_STRING0
    #define XCVU35P_STRING1 XCVU33P_STRING1
    #define XCVU35P_STRING2 XCVU33P_STRING2
    #define XCVU35P_STRING3 XCVU33P_STRING3
    #define XCVU35P_SLR0_END 3
    #define XCVU35P_SLR1_START 4
    #define XCVU35P_STRING4 XCVU11P_STRING0
    #define XCVU35P_STRING5 XCVU11P_STRING1
    #define XCVU35P_STRING6 XCVU11P_STRING2
    #define XCVU35P_STRING7 XCVU11P_STRING3
    #define XCVU35P_SLR1_END 7
    #define XCVU35P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU35P_);                                                              \
        XUSP_SETUP_SLRs_2(XCVU35P_);                                                              \
        XUSP_STRING_CAT_8(XCVU35P_);                                                              \
    }

    //3 dies: XCVU33P + 2 dies from XCVU11P
    #define XCVU37P_NAME "xcvu37p"
    #define XCVU37P_SLRNUM 3
    #define XCVU37P_ROWNUM 12
    #define XCVU37P_IDCODE 0x4B79093
    #define XCVU37P_IDCODE1 XCVU35P_IDCODE1
    #define XCVU37P_IDCODE2 0x4B44093
    #define XCVU37P_SLR0_START 0
    #define XCVU37P_STRING0 XCVU33P_STRING0
    #define XCVU37P_STRING1 XCVU33P_STRING1
    #define XCVU37P_STRING2 XCVU33P_STRING2
    #define XCVU37P_STRING3 XCVU33P_STRING3
    #define XCVU37P_SLR0_END 3
    #define XCVU37P_SLR1_START 4
    #define XCVU37P_STRING4 XCVU11P_STRING0
    #define XCVU37P_STRING5 XCVU11P_STRING1
    #define XCVU37P_STRING6 XCVU11P_STRING2
    #define XCVU37P_STRING7 XCVU11P_STRING3
    #define XCVU37P_SLR1_END 7
    #define XCVU37P_SLR2_START 8
    #define XCVU37P_STRING8 XCVU11P_STRING0
    #define XCVU37P_STRING9 XCVU11P_STRING1
    #define XCVU37P_STRING10 XCVU11P_STRING2
    #define XCVU37P_STRING11 XCVU11P_STRING3
    #define XCVU37P_SLR2_END 11
    #define XCVU37P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU37P_);                                                              \
        XUSP_SETUP_SLRs_3(XCVU37P_);                                                              \
        XUSP_STRING_CAT_12(XCVU37P_);                                                             \
    }

    //XCVU45P same as XCVU35P but with more HBM
    #define XCVU45P_NAME "xcvu45p"
    #define XCVU45P_SLRNUM 2
    #define XCVU45P_ROWNUM 8
    #define XCVU45P_IDCODE 0x4B73093
    #define XCVU45P_IDCODE1 XCVU35P_IDCODE1
    #define XCVU45P_SLR0_START 0
    #define XCVU45P_STRING0 XCVU35P_STRING0
    #define XCVU45P_STRING1 XCVU35P_STRING1
    #define XCVU45P_STRING2 XCVU35P_STRING2
    #define XCVU45P_STRING3 XCVU35P_STRING3
    #define XCVU45P_SLR0_END 3
    #define XCVU45P_SLR1_START 4
    #define XCVU45P_STRING4 XCVU35P_STRING4
    #define XCVU45P_STRING5 XCVU35P_STRING5
    #define XCVU45P_STRING6 XCVU35P_STRING6
    #define XCVU45P_STRING7 XCVU35P_STRING7
    #define XCVU45P_SLR1_END 7
    #define XCVU45P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU45P_);                                                              \
        XUSP_SETUP_SLRs_2(XCVU45P_);                                                              \
        XUSP_STRING_CAT_8(XCVU45P_);                                                              \
    }

    //XCVU47P same as XCVU37P but with more HBM
    #define XCVU47P_NAME "xcvu47p"
    #define XCVU47P_SLRNUM 3
    #define XCVU47P_ROWNUM 12
    #define XCVU47P_IDCODE 0x4B7B093
    #define XCVU47P_IDCODE1 XCVU37P_IDCODE1
    #define XCVU47P_IDCODE2 XCVU37P_IDCODE2
    #define XCVU47P_SLR0_START 0
    #define XCVU47P_STRING0 XCVU37P_STRING0
    #define XCVU47P_STRING1 XCVU37P_STRING1
    #define XCVU47P_STRING2 XCVU37P_STRING2
    #define XCVU47P_STRING3 XCVU37P_STRING3
    #define XCVU47P_SLR0_END 3
    #define XCVU47P_SLR1_START 4
    #define XCVU47P_STRING4 XCVU37P_STRING4
    #define XCVU47P_STRING5 XCVU37P_STRING5
    #define XCVU47P_STRING6 XCVU37P_STRING6
    #define XCVU47P_STRING7 XCVU37P_STRING7
    #define XCVU47P_SLR1_END 7
    #define XCVU47P_SLR2_START 8
    #define XCVU47P_STRING8 XCVU37P_STRING8
    #define XCVU47P_STRING9 XCVU37P_STRING9
    #define XCVU47P_STRING10 XCVU37P_STRING10
    #define XCVU47P_STRING11 XCVU37P_STRING11
    #define XCVU47P_SLR2_END 11
    #define XCVU47P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU47P_);                                                              \
        XUSP_SETUP_SLRs_3(XCVU47P_);                                                              \
        XUSP_STRING_CAT_12(XCVU47P_);                                                             \
    }

    //3 dies: XCVU33P + 2 dies from XCVU27P
    #define XCVU57P_NAME "xcvu57p"
    #define XCVU57P_SLRNUM 3
    #define XCVU57P_ROWNUM 12
    #define XCVU57P_IDCODE 0x4B61093
    #define XCVU57P_IDCODE1 XCVU27P_IDCODE1
    #define XCVU57P_IDCODE2 XCVU27P_IDCODE2
    #define XCVU57P_SLR0_START 0
    #define XCVU57P_STRING0 XCVU33P_STRING0
    #define XCVU57P_STRING1 XCVU33P_STRING1
    #define XCVU57P_STRING2 XCVU33P_STRING2
    #define XCVU57P_STRING3 XCVU33P_STRING3
    #define XCVU57P_SLR0_END 3
    #define XCVU57P_SLR1_START 4
    #define XCVU57P_STRING4 XCVU27P_STRING0
    #define XCVU57P_STRING5 XCVU27P_STRING1
    #define XCVU57P_STRING6 XCVU27P_STRING2
    #define XCVU57P_STRING7 XCVU27P_STRING3
    #define XCVU57P_SLR1_END 7
    #define XCVU57P_SLR2_START 8
    #define XCVU57P_STRING8 XCVU27P_STRING0
    #define XCVU57P_STRING9 XCVU27P_STRING1
    #define XCVU57P_STRING10 XCVU27P_STRING2
    #define XCVU57P_STRING11 XCVU27P_STRING3
    #define XCVU57P_SLR2_END 11
    #define XCVU57P() {                                                                           \
        XUSP_SETUP_DEVICE(XCVU57P_);                                                              \
        XUSP_SETUP_SLRs_3(XCVU57P_);                                                              \
        XUSP_STRING_CAT_12(XCVU57P_);                                                             \
    }
    
//Xilinx UltraScale+ Zynq MPSoC
    #define XCZU1_NAME "xczu1"
    #define XCZU1_SLRNUM 1
    #define XCZU1_ROWNUM 3
    #define XCZU1_IDCODE 0x4826093
    #define XCZU1_STRING0 "#JPLJPBJPLJELJPSJPLJPSJPAJPLJfgjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCZU1_STRING1 "#JPLJPBJPLJELJPSJPLJPSJPAJPLJfmjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCZU1_STRING2 "#JPLJPBJPLJELJPSJPLJPSJPAJPLJfnjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCZU1() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU1_);                                                                \
        XUSP_STRING_CAT_3(XCZU1_);                                                                \
    }

    //XCZU2 is software-limited version of XCZU3
    #define XCZU2_NAME "xczu2"
    #define XCZU2_SLRNUM 1
    #define XCZU2_ROWNUM 3
    #define XCZU2_IDCODE 0x4A43093
    #define XCZU2_STRING0 "#JPLJPBJPLJELJPSJPLJPSJPAJPLJfghJPLJPBJPLJELJPSJPLJPSJPLJFLJPLJPBJPLJPAJPLJfgjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCZU2_STRING1 "#JPLJPBJPLJELJPSJPLJPSJPAJPLJfghJPLJPBJPLJELJPSJPLJPSJPLJFLJPLJPBJPLJPAJPLJfmjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCZU2_STRING2 "#JPLJPBJPLJELJPSJPLJPSJPAJPLJfghJPLJPBJPLJELJPSJPLJPSJPLJFLJPLJPBJPLJPAJPLJfnjKQOKGOKQOKGOKQOKQCKQOKtuvw\x01"
    #define XCZU2() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU2_);                                                                \
        XUSP_STRING_CAT_3(XCZU2_);                                                                \
    }

    #define XCZU3_NAME "xczu3"
    #define XCZU3_SLRNUM 1
    #define XCZU3_ROWNUM 3
    #define XCZU3_IDCODE 0x4A42093
    #define XCZU3_STRING0 XCZU2_STRING0
    #define XCZU3_STRING1 XCZU2_STRING1
    #define XCZU3_STRING2 XCZU2_STRING2
    #define XCZU3() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU3_);                                                                \
        XUSP_STRING_CAT_3(XCZU3_);                                                                \
    }

    //XCZU4 is software-limited version of XCZU5
    #define XCZU4_NAME "xczu4"
    #define XCZU4_SLRNUM 1
    #define XCZU4_ROWNUM 4
    #define XCZU4_IDCODE 0x4A47093
    #define XCZU4_STRING0 "#JPLJELJPLJELJPLJELJPLJfghJPLJELJPSJPLJELJPLJEMJPabc^JPLJELJPBJPLJELJPMJELJPLJELJPLJELJPLJFLJPLJDJPLJPAJPSJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU4_STRING1 XCZU4_STRING0
    #define XCZU4_STRING2 "#JPLJELJPLJELJPLJELJPLJfghJPLJELJPSJPLJELJPLJEMJPabc^JPLJELJPBJPLJELJPMJELJPLJELJPLJELJPLJFLJPLJDJPLJPAJPSJfmjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU4_STRING3 "#JPLJELJPLJELJPLJELJPLJfghJPLJELJPSJPLJELJPLJEMJPabc^JPLJELJPBJPLJELJPMJELJPLJELJPLJELJPLJFLJPLJDJPLJPAJPSJfnjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU4() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU4_);                                                                \
        XUSP_STRING_CAT_4(XCZU4_);                                                                \
    }

    #define XCZU5_NAME "xczu5"
    #define XCZU5_SLRNUM 1
    #define XCZU5_ROWNUM 4
    #define XCZU5_IDCODE 0x4A46093
    #define XCZU5_STRING0 XCZU4_STRING0
    #define XCZU5_STRING1 XCZU4_STRING1
    #define XCZU5_STRING2 XCZU4_STRING2
    #define XCZU5_STRING3 XCZU4_STRING3
    #define XCZU5() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU5_);                                                                \
        XUSP_STRING_CAT_4(XCZU5_);                                                                \
    }

    //XCZU6 is software-limited version of XCZU9 (which is XCKU9P with enabled PS)
    #define XCZU6_NAME "xczu6"
    #define XCZU6_SLRNUM 1
    #define XCZU6_ROWNUM 7
    #define XCZU6_IDCODE 0x484B093
    #define XCZU6_STRING0 XCKU9P_STRING0
    #define XCZU6_STRING1 XCKU9P_STRING1
    #define XCZU6_STRING2 XCKU9P_STRING2
    #define XCZU6_STRING3 XCKU9P_STRING3
    #define XCZU6_STRING4 XCKU9P_STRING4
    #define XCZU6_STRING5 XCKU9P_STRING5
    #define XCZU6_STRING6 XCKU9P_STRING6
    #define XCZU6() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU6_);                                                                \
        XUSP_STRING_CAT_7(XCZU6_);                                                                \
    }

    #define XCZU7_NAME "xczu7"
    #define XCZU7_SLRNUM 1
    #define XCZU7_ROWNUM 6
    #define XCZU7_IDCODE 0x4A5A093
    #define XCZU7_STRING0 "2050766766761766726766766766766766704076676676676676676676676676676676676672676676672$JPLJELJPBJPLJELJPMJELJPSJPLJDJPLJEMJPabc^JPLJPBJPLJELJPLJEMJPSJPLJELJPLJPLJELJPLJPLJFLJPSJPLJELJPLJPAJPSJfojKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU7_STRING1 XCZU7_STRING0
    #define XCZU7_STRING2 "2050766766761766726766766766766766704076676676676676676676676676676676676672676676672$JPLJELJPBJPLJELJPMJELJPSJPLJDJPLJEMJPabc^JPLJPBJPLJELJPLJEMJPSJPLJELJPLJPLJELJPLJPLJFLJPSJPLJELJPLJPAJPSJfmjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU7_STRING3 "2050766766761766726766766766766766704076676676676676676676676676676676676672676676672$JPLJELJPBJPLJELJPMJELJPSJPLJDJPLJEMJPabc^JPLJPBJPLJELJPLJEMJPSJPLJELJPLJPLJELJPLJPLJFLJPSJPLJELJPLJPAJPSJfnjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU7_STRING4 "abcdJPLJPLJPAJPLJELJPLJPLJPLJPLJPLJfghJPLJPLJPLJPLJPSJPLJPLJPSJPLJPLJPLJPLJFLJPSJPLJELJPLJELJPBJPLJELJPMJELJPSJPLJDJPLJEMJPabc^JPLJPBJPLJELJPLJEMJPSJPLJELJPLJPLJELJPLJPLJFLJPSJPLJELJPLJPAJPSJfgjKQTKQCKQOKGOKQTKQOKQTKkl\x01"
    #define XCZU7_STRING5 XCZU7_STRING4
    #define XCZU7() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU7_);                                                                \
        XUSP_STRING_CAT_6(XCZU7_);                                                                \
    }

    //XCZU9 is XCKU9P but with PS enabled
    #define XCZU9_NAME "xczu9"
    #define XCZU9_SLRNUM XCKU9P_SLRNUM
    #define XCZU9_ROWNUM XCKU9P_ROWNUM
    #define XCZU9_IDCODE XCKU9P_IDCODE
    #define XCZU9_STRING0 XCKU9P_STRING0
    #define XCZU9_STRING1 XCKU9P_STRING1
    #define XCZU9_STRING2 XCKU9P_STRING2
    #define XCZU9_STRING3 XCKU9P_STRING3
    #define XCZU9_STRING4 XCKU9P_STRING4
    #define XCZU9_STRING5 XCKU9P_STRING5
    #define XCZU9_STRING6 XCKU9P_STRING6
    #define XCZU9() {                                                                             \
        XUSP_SETUP_DEVICE(XCZU9_);                                                                \
        XUSP_STRING_CAT_7(XCZU9_);                                                                \
    }

    //XCZU11 is XCKU11P but with PS enabled
    #define XCZU11_NAME "xczu11"
    #define XCZU11_SLRNUM XCKU11P_SLRNUM
    #define XCZU11_ROWNUM XCKU11P_ROWNUM
    #define XCZU11_IDCODE XCKU11P_IDCODE
    #define XCZU11_STRING0 XCKU11P_STRING0
    #define XCZU11_STRING1 XCKU11P_STRING1
    #define XCZU11_STRING2 XCKU11P_STRING2
    #define XCZU11_STRING3 XCKU11P_STRING3
    #define XCZU11_STRING4 XCKU11P_STRING4
    #define XCZU11_STRING5 XCKU11P_STRING5
    #define XCZU11_STRING6 XCKU11P_STRING6
    #define XCZU11_STRING7 XCKU11P_STRING7
    #define XCZU11() {                                                                            \
        XUSP_SETUP_DEVICE(XCZU11_);                                                               \
        XUSP_STRING_CAT_8(XCZU11_);                                                               \
    }

    //XCZU15 is XCKU13P but with PS enabled
    #define XCZU15_NAME "xczu15"
    #define XCZU15_SLRNUM XCKU13P_SLRNUM
    #define XCZU15_ROWNUM XCKU13P_ROWNUM
    #define XCZU15_IDCODE XCKU13P_IDCODE
    #define XCZU15_STRING0 XCKU13P_STRING0
    #define XCZU15_STRING1 XCKU13P_STRING1
    #define XCZU15_STRING2 XCKU13P_STRING2
    #define XCZU15_STRING3 XCKU13P_STRING3
    #define XCZU15_STRING4 XCKU13P_STRING4
    #define XCZU15_STRING5 XCKU13P_STRING5
    #define XCZU15_STRING6 XCKU13P_STRING6
    #define XCZU15() {                                                                            \
        XUSP_SETUP_DEVICE(XCZU15_);                                                               \
        XUSP_STRING_CAT_7(XCZU15_);                                                               \
    }

    //XCZU17 is software-limited version of XCZU19(XCKU15P without PS)
    #define XCZU17_NAME "xczu17"
    #define XCZU17_SLRNUM XCKU15P_SLRNUM
    #define XCZU17_ROWNUM XCKU15P_ROWNUM
    #define XCZU17_IDCODE 0x4A57093
    #define XCZU17_STRING0 XCKU15P_STRING0
    #define XCZU17_STRING1 XCKU15P_STRING1
    #define XCZU17_STRING2 XCKU15P_STRING2
    #define XCZU17_STRING3 XCKU15P_STRING3
    #define XCZU17_STRING4 XCKU15P_STRING4
    #define XCZU17_STRING5 XCKU15P_STRING5
    #define XCZU17_STRING6 XCKU15P_STRING6
    #define XCZU17_STRING7 XCKU15P_STRING7
    #define XCZU17_STRING8 XCKU15P_STRING8
    #define XCZU17_STRING9 XCKU15P_STRING9
    #define XCZU17_STRING10 XCKU15P_STRING10
    #define XCZU17() {                                                                            \
        XUSP_SETUP_DEVICE(XCZU17_);                                                               \
        XUSP_STRING_CAT_11(XCZU17_);                                                              \
    }

    //XCZU19 is XCKU15P but with PS enabled
    #define XCZU19_NAME "xczu19"
    #define XCZU19_SLRNUM XCKU15P_SLRNUM
    #define XCZU19_ROWNUM XCKU15P_ROWNUM
    #define XCZU19_IDCODE XCKU15P_IDCODE
    #define XCZU19_STRING0 XCKU15P_STRING0
    #define XCZU19_STRING1 XCKU15P_STRING1
    #define XCZU19_STRING2 XCKU15P_STRING2
    #define XCZU19_STRING3 XCKU15P_STRING3
    #define XCZU19_STRING4 XCKU15P_STRING4
    #define XCZU19_STRING5 XCKU15P_STRING5
    #define XCZU19_STRING6 XCKU15P_STRING6
    #define XCZU19_STRING7 XCKU15P_STRING7
    #define XCZU19_STRING8 XCKU15P_STRING8
    #define XCZU19_STRING9 XCKU15P_STRING9
    #define XCZU19_STRING10 XCKU15P_STRING10
    #define XCZU19() {                                                                            \
        XUSP_SETUP_DEVICE(XCZU19_);                                                               \
        XUSP_STRING_CAT_11(XCZU19_);                                                              \
    }
    
//Xilinx UltraScale+ Zynq RFSoC
    #define XCZU21DR_NAME "xczu21dr"
    #define XCZU21DR_SLRNUM 1
    #define XCZU21DR_ROWNUM 8
    #define XCZU21DR_IDCODE 0x4A83093
    #define XCZU21DR_STRING0 "2076676676672676676176670407667617667667376672&JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk+\x01"
    #define XCZU21DR_STRING1 "2076676676672676676176670407667617667667376672&JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfmjKQOKIOKQOKIOKQOKQCKQOKk+\x01"
    #define XCZU21DR_STRING2 "2076676676672676676176670407667617667667376672&JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfnjKQOKIOKQOKIOKQOKQCKQOKk+\x01"
    #define XCZU21DR_STRING3 "UyJPLJPSJPLJHLJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk+\x01"
    #define XCZU21DR_STRING4 "UyJPLJPSJPLJHLJPLJPBJPLJfohJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk=\x01"
    #define XCZU21DR_STRING5 "UyJPLJPSJPLJHLJPLJPBJPLJfVhJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk=\x01"
    #define XCZU21DR_STRING6 "UyJPLJPSJPLJHLJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk=\x01"
    #define XCZU21DR_STRING7 XCZU21DR_STRING4
    #define XCZU21DR() {                                                                          \
        XUSP_SETUP_DEVICE(XCZU21DR_);                                                             \
        XUSP_STRING_CAT_8(XCZU21DR_);                                                             \
    }

    #define XCZU25DR_NAME "xczu25dr"
    #define XCZU25DR_SLRNUM 1
    #define XCZU25DR_ROWNUM 6
    #define XCZU25DR_IDCODE 0x4A87093
    #define XCZU25DR_STRING0 XCZU21DR_STRING0
    #define XCZU25DR_STRING1 XCZU21DR_STRING1
    #define XCZU25DR_STRING2 XCZU21DR_STRING2
    #define XCZU25DR_STRING3 XCZU21DR_STRING3
    #define XCZU25DR_STRING4 XCZU21DR_STRING4
    #define XCZU25DR_STRING5 XCZU21DR_STRING5
    #define XCZU25DR() {                                                                          \
        XUSP_SETUP_DEVICE(XCZU25DR_);                                                             \
        XUSP_STRING_CAT_6(XCZU25DR_);                                                             \
    }

    //Same as ZU21DR
    #define XCZU27DR_NAME "xczu27dr"
    #define XCZU27DR_IDCODE 0x4A86093
    #define XCZU27DR() {                                                                          \
        XCZU21DR();                                                                               \
        XUSP_PARTNAME(XCZU27DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU27DR_IDCODE);                                                          \
    }
    
    //Same as ZU21DR
    #define XCZU28DR_NAME "xczu28dr"
    #define XCZU28DR_IDCODE 0x4A82093
    #define XCZU28DR() {                                                                          \
        XCZU21DR();                                                                               \
        XUSP_PARTNAME(XCZU28DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU28DR_IDCODE);                                                          \
    }

    //Same as ZU21DR
    #define XCZU29DR_NAME "xczu29dr"
    #define XCZU29DR_IDCODE 0x4A84093
    #define XCZU29DR() {                                                                          \
        XCZU21DR();                                                                               \
        XUSP_PARTNAME(XCZU29DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU29DR_IDCODE);                                                          \
    }

    //Same as ZU21DR
    #define XCZU39DR_NAME "xczu39dr"
    #define XCZU39DR_IDCODE 0x4A88093
    #define XCZU39DR() {                                                                          \
        XCZU21DR();                                                                               \
        XUSP_PARTNAME(XCZU39DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU39DR_IDCODE);                                                          \
    }

    #define XCZU42DR_NAME "xczu42dr"
    #define XCZU42DR_SLRNUM 1
    #define XCZU42DR_ROWNUM 5
    #define XCZU42DR_IDCODE 0x4ADA093
    #define XCZU42DR_STRING0 "20766766766726766761766704076676176672676676672676676672.JPLJDJPLJHLJPAJPLJf(LJPBJPLJHLJPLJDJPLJFLJPAJPLJHLJPAJPLJf),JPMJPBJPLJPSJPSJPLJf[,JPLJHLJPAJPLJFLJPLJHLJPAJPLJHLJPLJf]hJPLJHLJPBJPLJPLJHMJPabc^JPLJHLJPAJPLJHLJPLJf{jKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU42DR_STRING1 "20766766766726766761766704076676176672676676672676676672.JPLJDJPLJHLJPAJPLJf(LJPBJPLJHLJPLJDJPLJFLJPAJPLJHLJPAJPLJf),JPMJPBJPLJPSJPSJPLJf[,JPLJHLJPAJPLJFLJPLJHLJPAJPLJHLJPLJf]hJPLJHLJPBJPLJPLJHMJPabc^JPLJHLJPAJPLJHLJPLJfmjKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU42DR_STRING2 "20766766766726766761766704076676176672676676672676676672.JPLJDJPLJHLJPAJPLJf(LJPBJPLJHLJPLJDJPLJFLJPAJPLJHLJPAJPLJf),JPMJPBJPLJPSJPSJPLJf},JPLJHLJPAJPLJFLJPLJHLJPAJPLJHLJPLJf]hJPLJHLJPBJPLJPLJHMJPabc^JPLJHLJPAJPLJHLJPLJfnjKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU42DR_STRING3 "UyJPLJPSJPLJHLJPLJPBJPLJfqhJPLJPBJPLJHLJPSJPLJHLJPSJPLJFLJPLJDJPLJHLJPAJPLJf(LJPBJPLJHLJPLJDJPLJFLJPAJPLJHLJPAJPLJf),JPMJPBJPLJPSJPSJPLJf[,JPLJHLJPAJPLJFLJPLJHLJPAJPLJHLJPLJf]hJPLJHLJPBJPLJPLJHMJPabc^JPLJHLJPAJPLJHLJPLJf{jKQOKIOKQOKIOKQOKQCKQOKk;\x01"
    #define XCZU42DR_STRING4 "UyJPLJPSJPLJHLJPLJPBJPLJf<hJPLJPBJPLJHLJPSJPLJHLJPSJPLJFLJPLJDJPLJHLJPAJPLJf(LJPBJPLJHLJPLJDJPLJFLJPAJPLJHLJPAJPLJf),JPMJPBJPLJPSJPSJPLJf[,JPLJHLJPAJPLJFLJPLJHLJPAJPLJHLJPLJf]hJPLJHLJPBJPLJPLJHMJPabc^JPLJHLJPAJPLJHLJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk;\x01"
    #define XCZU42DR() {                                                                          \
        XUSP_SETUP_DEVICE(XCZU42DR_);                                                             \
        XUSP_STRING_CAT_5(XCZU42DR_);                                                             \
    }

    #define XCZU43DR_NAME "xczu43dr"
    #define XCZU43DR_SLRNUM 1
    #define XCZU43DR_ROWNUM 8
    #define XCZU43DR_IDCODE 0x4AA7093
    #define XCZU43DR_STRING0 "2076676676672676676176670407667617667667376672&JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU43DR_STRING1 "2076676676672676676176670407667617667667376672&JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfmjKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU43DR_STRING2 "2076676676672676676176670407667617667667376672&JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfnjKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU43DR_STRING3 "UyJPLJPSJPLJHLJPLJPBJPLJfqhJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk:\x01"
    #define XCZU43DR_STRING4 "UyJPLJPSJPLJHLJPLJPBJPLJfihJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk;\x01"
    #define XCZU43DR_STRING5 "UyJPLJPSJPLJHLJPLJPBJPLJfVhJPLJPBJPSJPLJDJPLJFLJPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJF*-JPMJPLJHLJPBJPLJHLJPMJPSJPAJPLJHLJPLJPSJPLJFLJPLJPBJPLJHLJPLJHMJPLJPAJPLJHLJPLJHMJPabc^JPLJHLJPAJPLJHLJPMJHLJPBJPLJHLJPLJFLJPLJPSJPLJHLJPAJPLJfgjKQOKIOKQOKIOKQOKQCKQOKk;\x01"
    #define XCZU43DR_STRING6 XCZU43DR_STRING4
    #define XCZU43DR_STRING7 XCZU43DR_STRING4
    #define XCZU43DR() {                                                                          \
        XUSP_SETUP_DEVICE(XCZU43DR_);                                                             \
        XUSP_STRING_CAT_8(XCZU43DR_);                                                             \
    }

    //Same as ZU43DR
    #define XCZU46DR_NAME "xczu46dr"
    #define XCZU46DR_IDCODE 0x4AA2093
    #define XCZU46DR() {                                                                          \
        XCZU43DR();                                                                               \
        XUSP_PARTNAME(XCZU46DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU46DR_IDCODE);                                                          \
    }

    //Same as ZU43DR
    #define XCZU47DR_NAME "xczu47dr"
    #define XCZU47DR_IDCODE 0x4AA9093
    #define XCZU47DR() {                                                                          \
        XCZU43DR();                                                                               \
        XUSP_PARTNAME(XCZU47DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU47DR_IDCODE);                                                          \
    }

    //Same as ZU43DR
    #define XCZU48DR_NAME "xczu48dr"
    #define XCZU48DR_IDCODE 0x4AA5093
    #define XCZU48DR() {                                                                          \
        XCZU43DR();                                                                               \
        XUSP_PARTNAME(XCZU48DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU48DR_IDCODE);                                                          \
    }

    //Same as ZU43DR
    #define XCZU49DR_NAME "xczu49dr"
    #define XCZU49DR_IDCODE 0x4AA8093
    #define XCZU49DR() {                                                                          \
        XCZU43DR();                                                                               \
        XUSP_PARTNAME(XCZU49DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU49DR_IDCODE);                                                          \
    }
	
	//Same as ZU42DR
    #define XCZU65DR_NAME "xczu65dr"
    #define XCZU65DR_IDCODE TODO
    #define XCZU65DR() {                                                                          \
        throw runtime_error("Device XCZU65DR not yet implemented.");                              \
        XCZU42DR();                                                                               \
        XUSP_PARTNAME(XCZU65DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU65DR_IDCODE);                                                          \
    }

	//Same as ZU42DR
    #define XCZU67DR_NAME "xczu67dr"
    #define XCZU67DR_IDCODE TODO
    #define XCZU67DR() {                                                                          \
        throw runtime_error("Device XCZU67DR not yet implemented.");                              \
        XCZU42DR();                                                                               \
        XUSP_PARTNAME(XCZU67DR_NAME);                                                             \
        XUSP_IDCODE(0, XCZU67DR_IDCODE);                                                          \
    }

//Xilinx UltraScale+ Alveo rebranding
    //XCU200 is rebranded XCVU9P, but IDCODE is different
    #define XCU200_NAME "xcu200"
    #define XCU200_IDCODE 0x4B37093
    #define XCU200() {                                                                            \
        XCVU9P();                                                                                 \
        XUSP_PARTNAME(XCU200_NAME);                                                               \
        XUSP_IDCODE(0, XCU200_IDCODE);                                                            \
    }

    //XCU250 is rebranded XCVU13P, but IDCODE is different
    #define XCU250_NAME "xcu250"
    #define XCU250_IDCODE 0x4B57093
    #define XCU250() {                                                                            \
        XCVU13P();                                                                                \
        XUSP_PARTNAME(XCU250_NAME);                                                               \
        XUSP_IDCODE(0, XCU250_IDCODE);                                                            \
    }

    //XCU26 is rebranded XCVU23P, but IDCODE is different
    #define XCU26_NAME "xcu26"
    #define XCU26_IDCODE 0x4AD5093
    #define XCU26() {                                                                             \
        XCVU23P();                                                                                \
        XUSP_PARTNAME(XCU26_NAME);                                                                \
        XUSP_IDCODE(0, XCU26_IDCODE);                                                             \
    }

    //XCUX35 is same as XC26
    #define XCUX35_NAME "xcux35"
    #define XCUX35_IDCODE XCU26_IDCODE
    #define XCUX35() {                                                                            \
        XCU26();                                                                                  \
        XUSP_PARTNAME(XCUX35_NAME);                                                               \
        XUSP_IDCODE(0, XCUX35_IDCODE);                                                            \
    }

    //XCU50 is rebranded XCVU35P, but IDCODE is different
    #define XCU50_NAME "xcu50"
    #define XCU50_IDCODE 0x4B77093
    #define XCU50() {                                                                             \
        XCVU35P();                                                                                \
        XUSP_PARTNAME(XCU50_NAME);                                                                \
        XUSP_IDCODE(0, XCU50_IDCODE);                                                             \
    }

    //XCU55N is rebranded XCVU45P, but IDCODE is different
    #define XCU55N_NAME "xcu55n"
    #define XCU55N_IDCODE 0x4B77093
    #define XCU55N() {                                                                            \
        XCVU45P();                                                                                \
        XUSP_PARTNAME(XCU55N_NAME);                                                               \
        XUSP_IDCODE(0, XCU55N_IDCODE);                                                            \
    }

    //XCU55C is rebranded XCVU47P, but IDCODE is different
    #define XCU55C_NAME "xcu55c"
    #define XCU55C_IDCODE 0x4B7D093
    #define XCU55C() {                                                                            \
        XCVU47P();                                                                                \
        XUSP_PARTNAME(XCU55C_NAME);                                                               \
        XUSP_IDCODE(0, XCU55C_IDCODE);                                                            \
    }

    //XCU280 is rebranded XCVU37P, but IDCODE is different
    #define XCU280_NAME "xcu280"
    #define XCU280_IDCODE XCU55C_IDCODE
    #define XCU280() {                                                                            \
        XCVU37P();                                                                                \
        XUSP_PARTNAME(XCU280_NAME);                                                               \
        XUSP_IDCODE(0, XCU280_IDCODE);                                                            \
    }

    /*
    offtopic rant: so lets get this straight:
    1. XCVU37P is same FPGA as XCVU47P but in a different package and changed IDCODE
    2. XCU280 is rebranded XCVU37P with a changed IDCODE
    3. XCU55C is rebranded XCVU47P with a changed IDCODE
    4. XCU280 and XCU55C have the same IDCODE
    5. profit
    */

    //XCU30 is rebranded XCZU7, but IDCODE is different
    #define XCU30_NAME "xcu30"
    #define XCU30_IDCODE 0x4A5C093
    #define XCU30() {                                                                             \
        XCZU7();                                                                                  \
        XUSP_PARTNAME(XCU30_NAME);                                                                \
        XUSP_IDCODE(0, XCU30_IDCODE);                                                             \
    }

    //XCU25 is rebranded XCZU19, but IDCODE is different
    #define XCU25_NAME "xcu25"
    #define XCU25_IDCODE 0x4A58093
    #define XCU25() {                                                                             \
        XCZU19();                                                                                 \
        XUSP_PARTNAME(XCU25_NAME);                                                                \
        XUSP_IDCODE(0, XCU25_IDCODE);                                                             \
    }

// Kria rebranding
    //Kria 26 is rebranded XCZU5
    #define XCK26_NAME "xck26"
    #define XCK26_IDCODE 0x4A49093
    #define XCK26() {                                                                             \
        XCZU5();                                                                                  \
        XUSP_PARTNAME(XCK26_NAME);                                                                \
        XUSP_IDCODE(0, XCK26_IDCODE);                                                             \
    }

#endif // XILINXULTRASCALEPLUSDEVICES_H
