byteman: parseInput
archSelected
cmdIs
getAllButLastStringArg
getAllStrings
getLastStringArg
getNthInt
getNthStringArg
has
hOR
main
paramHas
parseAssembly
parseBlank
parseChange
parseCommand
parseDevice
parseInput
parseMerge
parseOutput
parseRegion
parseVerbose
parseWarn
printDeviceList
selectedArch
setArch
parseInput()
void parseInput (string inputCmd)
Definition at line 192 of file byteman.cpp.
{
     string params = getAllButLastStringArg(inputCmd);
     string filename = getLastStringArg(inputCmd);
     #ifdef XUSP
     if(selectedArch == XIL_USP){
         if(paramHas("main") || paramHas("first"))
             mainXUSP.readBitstream(filename);
         if(paramHas("temp") || paramHas("second"))
             tempXUSP.readBitstream(filename);
     }
     #endif
 }
References getAllButLastStringArg(), getLastStringArg(), paramHas, XilinxUltraScalePlus::readBitstream(), selectedArch, and XIL_USP.
Referenced by parseCommand().