byteman: parseOutput
archSelected
cmdIs
getAllButLastStringArg
getAllStrings
getLastStringArg
getNthInt
getNthStringArg
has
hOR
main
paramHas
parseAssembly
parseBlank
parseChange
parseCommand
parseDevice
parseInput
parseMerge
parseOutput
parseRegion
parseVerbose
parseWarn
printDeviceList
selectedArch
setArch
parseOutput()
void parseOutput (string outputCmd)
Definition at line 218 of file byteman.cpp.
{
     string params = getAllButLastStringArg(outputCmd);
     string filename = getLastStringArg(outputCmd);
     int srcRow, srcCol, sizeRow, sizeCol;
     srcRow = getNthInt(outputCmd, 0);
     srcCol = getNthInt(outputCmd, 1);
     sizeRow = getNthInt(outputCmd, 2);
     sizeCol = getNthInt(outputCmd, 3);
     #ifdef XUSP
     if(selectedArch == XIL_USP)
         mainXUSP.writeBitstream(filename, params, srcRow, srcCol, sizeRow, sizeCol);
     #endif
 }
References getAllButLastStringArg(), getLastStringArg(), getNthInt(), selectedArch, XilinxUltraScalePlus::writeBitstream(), and XIL_USP.
Referenced by parseCommand().