byteman: src/byteman.cpp File Reference
byteman.cpp File Reference
#include <iostream>
#include <stdexcept>
#include <algorithm>
#include <stdio.h>
#include <string.h>
#include <istream>
#include <ostream>
#include <string>
#include <sstream>
#include "byteman.h"
#include "Devices/Xilinx/UltraScalePlus/XilinxUltraScalePlus.h"
Macros
#define cmdIs(x, y) (nextCmd.rfind(x, 0) == 0)
#define has(x) (arch.rfind(x) != string::npos)
#define hOR(x, y) (has(x)||has(y))
#define paramHas(x) (params.find(x) != string::npos)
Functions
string getAllButLastStringArg (string s)
string getAllStrings (string s)
string getLastStringArg (string s)
int getNthInt (string s, int n)
string getNthStringArg (string s, int n)
int main (int argc, char *argv[])
void parseAssembly (string assemblyCmd)
void parseBlank (string blankCmd)
void parseChange (string changeCmd)
void parseCommand (string nextCmd)
void parseDevice (string deviceCmd)
void parseInput (string inputCmd)
void parseMerge (string mergeCmd)
void parseOutput (string outputCmd)
void parseRegion (string regionCmd)
void parseVerbose (string verboseCmd)
void parseWarn (string warnCmd)
void printDeviceList ()
void setArch (string arch)
Variables
bool archSelected = false
Arch selectedArch = ARCH_NULL
Macro Definition Documentation
cmdIs
#define cmdIs (x, y) (nextCmd.rfind(x, 0) == 0)
has
#define has (x) (arch.rfind(x) != string::npos)
hOR
#define hOR (x, y) (has(x)||has(y))
paramHas
#define paramHas (x) (params.find(x) != string::npos)
Definition at line 123 of file byteman.cpp.
Function Documentation
getAllButLastStringArg()
string getAllButLastStringArg (string s)
Definition at line 75 of file byteman.cpp.
{
     stringstream ss(s);
     string ret;
     ret.clear();
     string temp;
     string temp2;
     int intFound;
     ss >> temp;
     while (!ss.eof()) {
         ss >> temp;
         if (!(stringstream(temp) >> intFound)){
             ret.append(temp2).append(" ");
             temp2 = temp;
         }
     }
     return ret;
 }
Referenced by parseDevice(), parseInput(), and parseOutput().
getAllStrings()
string getAllStrings (string s)
Definition at line 92 of file byteman.cpp.
                               { // returns a string of all string components that are not ints
     stringstream ss(s);
     string ret;
     ret.clear();
     string temp;
     int intFound;
     ss >> temp;
     while (!ss.eof()) {
         ss >> temp;
         if (!(stringstream(temp) >> intFound))
             ret.append(temp).append(" ");
         temp.clear();
     }
     return ret;
 }
Referenced by parseBlank(), parseMerge(), and parseRegion().
getLastStringArg()
string getLastStringArg (string s)
Definition at line 59 of file byteman.cpp.
{
     stringstream ss(s);
     string ret;
     ret.clear();
     string temp;
     int intFound;
     ss >> temp;
     while (!ss.eof()) {
         ss >> temp;
         if (!(stringstream(temp) >> intFound)){
             ret = temp;
         }
         temp.clear();
     }
     return ret;
 }
Referenced by parseDevice(), parseInput(), and parseOutput().
getNthInt()
int getNthInt (string s, int n)
Definition at line 107 of file byteman.cpp.
{
     stringstream ss(s);
     string temp;
     int intFound;
     int i = 0;
     while (!ss.eof()) {
         ss >> temp;
         if (stringstream(temp) >> intFound){
             if(i == n)
                 return intFound;
             i++;
         }
         temp.clear();
     }
     return -0x7FFFFFFF;
 }
Referenced by parseMerge(), parseOutput(), parseRegion(), parseVerbose(), and parseWarn().
getNthStringArg()
string getNthStringArg (string s, int n)
Definition at line 40 of file byteman.cpp.
{
     stringstream ss(s);
     string ret;
     ret.clear();
     string temp;
     int intFound;
     int i = 0;
     ss >> temp;
     while (!ss.eof()) {
         ss >> temp;
         if (!(stringstream(temp) >> intFound)){
             if(i == n)
                 return temp;
             i++;
         }
         temp.clear();
     }
     return string("");
 }
main()
int main (int argc, char * argv[])
Definition at line 288 of file byteman.cpp.
{
     if(argc <= 1)
         parseHelp("",1,1);//show usage and terminate with an error code
     try {
         string command;
         bool readSTDIN = false;
         for(int argi = 1 ; argi < argc ; argi++) {
             if(argv[argi][0] == '-' && !command.empty()){ //new cmd and old cmd not empty
                 parseCommand(command);
                 command.clear();
             }
             if(command.empty())
                 command.append(argv[argi]);
             else
                 command.append(" ").append(argv[argi]);
             if(command == "-stdin"){
                 readSTDIN = true;
                 command.clear();
             }
         }
         if(!command.empty())
             parseCommand(command);
         while(readSTDIN){
             getline(cin,command);
             if(command.at(command.find_first_not_of(" \t")) != '#')// if #, skip that line as comment
                 parseCommand(command);
         }
     } catch (const exception &e){
         cout << "The program was terminated with message: \n\t'" << e.what() << "'\n";
         return 1;
     }
     return 0;
 }
References parseCommand(), and parseHelp().
parseAssembly()
void parseAssembly (string assemblyCmd)
Definition at line 231 of file byteman.cpp.
{
     //TODO , text assembly -> bitstream and vice versa
     #ifdef XUSP
     ;
     #endif
 }
Referenced by parseCommand().
parseBlank()
void parseBlank (string blankCmd)
Definition at line 163 of file byteman.cpp.
{
     string params = getAllStrings(blankCmd);
     #ifdef XUSP
     if(selectedArch == XIL_USP){
         if(paramHas("main") || paramHas("first"))
             mainXUSP.blank(params);
         if(paramHas("temp") || paramHas("second"))
             tempXUSP.blank(params);
     }
     #endif
 }
References XilinxUltraScalePlus::blank(), getAllStrings(), paramHas, selectedArch, and XIL_USP.
Referenced by parseCommand().
parseChange()
void parseChange (string changeCmd)
Definition at line 174 of file byteman.cpp.
{
     //TODO lut,ff,wires,bram,uram modifications
     #ifdef XUSP
     ;
     #endif
 }
Referenced by parseCommand().
parseCommand()
void parseCommand (string nextCmd)
Definition at line 255 of file byteman.cpp.
{
     replace(nextCmd.begin(), nextCmd.end(), '=', ' ');
     if (nextCmd.at(0) == '-') nextCmd.erase(0, 1);
     #define cmdIs(x,y) (nextCmd.rfind(x, 0) == 0)
     if(cmdIs("h", "help")){
         parseHelp(nextCmd);
         return;
     }
     if(!archSelected)setArch(nextCmd);
     if(cmdIs("v", "verbose"))
         parseVerbose(nextCmd);
     else if(cmdIs("w", "warn"))
         parseWarn(nextCmd);
     else if(cmdIs("r", "region"))
         parseRegion(nextCmd);
     else if(cmdIs("b", "blank"))
         parseBlank(nextCmd);
     else if(cmdIs("c", "change"))
         parseChange(nextCmd);
     else if(cmdIs("d", "device"))
         parseDevice(nextCmd);
     else if(cmdIs("i", "input"))
         parseInput(nextCmd);
     else if(cmdIs("m", "merge"))
         parseMerge(nextCmd);
     else if(cmdIs("o", "output"))
         parseOutput(nextCmd);
     else if(cmdIs("a", "assembly"))
         parseAssembly(nextCmd);
     else if(cmdIs("e", "end"))
         exit(0);
     #undef cmdIs
 }
References archSelected, cmdIs, parseAssembly(), parseBlank(), parseChange(), parseDevice(), parseHelp(), parseInput(), parseMerge(), parseOutput(), parseRegion(), parseVerbose(), parseWarn(), and setArch().
Referenced by main().
parseDevice()
void parseDevice (string deviceCmd)
Definition at line 180 of file byteman.cpp.
{
     string params = getAllButLastStringArg(deviceCmd);
     string deviceName = getLastStringArg(deviceCmd);
     #ifdef XUSP
     if(selectedArch == XIL_USP){
         if(paramHas("main") || paramHas("first"))
             mainXUSP.setDevice(mainXUSP.getDeviceByNameOrThrow(deviceName), deviceName);
         if(paramHas("temp") || paramHas("second"))
             tempXUSP.setDevice(mainXUSP.getDeviceByNameOrThrow(deviceName), deviceName);
     }
     #endif
 }
References getAllButLastStringArg(), XilinxUltraScalePlus::getDeviceByNameOrThrow(), getLastStringArg(), paramHas, selectedArch, XilinxUltraScalePlus::setDevice(), and XIL_USP.
Referenced by parseCommand().
parseInput()
void parseInput (string inputCmd)
Definition at line 192 of file byteman.cpp.
{
     string params = getAllButLastStringArg(inputCmd);
     string filename = getLastStringArg(inputCmd);
     #ifdef XUSP
     if(selectedArch == XIL_USP){
         if(paramHas("main") || paramHas("first"))
             mainXUSP.readBitstream(filename);
         if(paramHas("temp") || paramHas("second"))
             tempXUSP.readBitstream(filename);
     }
     #endif
 }
References getAllButLastStringArg(), getLastStringArg(), paramHas, XilinxUltraScalePlus::readBitstream(), selectedArch, and XIL_USP.
Referenced by parseCommand().
parseMerge()
void parseMerge (string mergeCmd)
Definition at line 204 of file byteman.cpp.
{
     string params = getAllStrings(mergeCmd);
     int srcRow, srcCol, sizeRow, sizeCol, dstRow, dstCol;
     srcRow = getNthInt(mergeCmd, 0);
     srcCol = getNthInt(mergeCmd, 1);
     sizeRow = getNthInt(mergeCmd, 2);
     sizeCol = getNthInt(mergeCmd, 3);
     dstRow = getNthInt(mergeCmd, 4);
     dstCol = getNthInt(mergeCmd, 5);
     #ifdef XUSP
     if(selectedArch == XIL_USP)
         mainXUSP.merge(&tempXUSP, params, srcRow, srcCol, sizeRow, sizeCol, dstRow, dstCol);
     #endif
 }
References getAllStrings(), getNthInt(), XilinxUltraScalePlus::merge(), selectedArch, and XIL_USP.
Referenced by parseCommand().
parseOutput()
void parseOutput (string outputCmd)
Definition at line 218 of file byteman.cpp.
{
     string params = getAllButLastStringArg(outputCmd);
     string filename = getLastStringArg(outputCmd);
     int srcRow, srcCol, sizeRow, sizeCol;
     srcRow = getNthInt(outputCmd, 0);
     srcCol = getNthInt(outputCmd, 1);
     sizeRow = getNthInt(outputCmd, 2);
     sizeCol = getNthInt(outputCmd, 3);
     #ifdef XUSP
     if(selectedArch == XIL_USP)
         mainXUSP.writeBitstream(filename, params, srcRow, srcCol, sizeRow, sizeCol);
     #endif
 }
References getAllButLastStringArg(), getLastStringArg(), getNthInt(), selectedArch, XilinxUltraScalePlus::writeBitstream(), and XIL_USP.
Referenced by parseCommand().
parseRegion()
void parseRegion (string regionCmd)
Definition at line 149 of file byteman.cpp.
{
     string params = getAllStrings(regionCmd);
     int srcRow, srcCol, sizeRow, sizeCol;
     srcRow = getNthInt(regionCmd, 0);
     srcCol = getNthInt(regionCmd, 1);
     sizeRow = getNthInt(regionCmd, 2);
     sizeCol = getNthInt(regionCmd, 3);
     #ifdef XUSP
     if(selectedArch == XIL_USP){
         mainXUSP.region(params, srcRow, srcCol, sizeRow, sizeCol);
         tempXUSP.region(params, srcRow, srcCol, sizeRow, sizeCol);
     }
     #endif
 }
References getAllStrings(), getNthInt(), XilinxUltraScalePlus::region(), selectedArch, and XIL_USP.
Referenced by parseCommand().
parseVerbose()
void parseVerbose (string verboseCmd)
Definition at line 124 of file byteman.cpp.
{
     int verboseValue = getNthInt(verboseCmd, 0);
     if(verboseValue == 0)verboseValue = 0; // if 0 was given, then it's 0
     else verboseValue = 1; // if nothing was given or something else then 1
     cout<< "verboseValue now is "<< verboseValue << endl;
     #ifdef XUSP
     cout<<"verboseValue" << verboseValue << endl;
     if(selectedArch == XIL_USP){
         mainXUSP.verbose = verboseValue;
         tempXUSP.verbose = verboseValue;
     }
     #endif
 }
References getNthInt(), selectedArch, XilinxUltraScalePlus::verbose, and XIL_USP.
Referenced by parseCommand().
parseWarn()
void parseWarn (string warnCmd)
Definition at line 137 of file byteman.cpp.
{
     int warnValue = getNthInt(warnCmd, 0);
     if(warnValue == 0)warnValue = 0; // if 0 was given, then it's 0
     else warnValue = 1; // if nothing was given or something else then 1
     cout<< "warnValue is now "<< warnValue << endl;
     #ifdef XUSP
     if(selectedArch == XIL_USP){
         mainXUSP.warn = warnValue;
         tempXUSP.warn = warnValue;
     }
     #endif
 }
References getNthInt(), selectedArch, XilinxUltraScalePlus::warn, and XIL_USP.
Referenced by parseCommand().
printDeviceList()
void printDeviceList ()
Definition at line 34 of file byteman.cpp.
                       {
     #ifdef XUSP
     if(selectedArch == ARCH_NULL || selectedArch == XIL_USP)
         mainXUSP.printDeviceList();
     #endif
 }
References ARCH_NULL, XilinxUltraScalePlus::printDeviceList(), selectedArch, and XIL_USP.
Referenced by usage_device().
setArch()
void setArch (string arch)
Definition at line 239 of file byteman.cpp.
{
     archSelected = true; // it will either select it or throw an exception, so just mark it anyway who cares
     #define has(x) (arch.rfind(x) != string::npos)
     #define hOR(x,y) (has(x)||has(y))
     transform(arch.begin(), arch.end(),arch.begin(), ::toupper);
     #ifdef XUSP
     if(has("XUSP") || (has("XILINX") && hOR("ULTRASCALE", "US") && hOR("PLUS","+") ) ) {
         selectedArch = XIL_USP;
         return;
     }
     #endif
     #undef has
     #undef hOR
     throw runtime_error(string("Unknown architecture: \"").append(arch).append("\"."));
 }
References archSelected, has, hOR, selectedArch, and XIL_USP.
Referenced by parseCommand().
Variable Documentation
archSelected
bool archSelected = false
Definition at line 238 of file byteman.cpp.
Referenced by parseCommand(), and setArch().
selectedArch
Arch selectedArch = ARCH_NULL
Definition at line 30 of file byteman.cpp.
Referenced by parseBlank(), parseDevice(), parseInput(), parseMerge(), parseOutput(), parseRegion(), parseVerbose(), parseWarn(), printDeviceList(), and setArch().