byteman: parseCommand
archSelected
cmdIs
getAllButLastStringArg
getAllStrings
getLastStringArg
getNthInt
getNthStringArg
has
hOR
main
paramHas
parseAssembly
parseBlank
parseChange
parseCommand
parseDevice
parseInput
parseMerge
parseOutput
parseRegion
parseVerbose
parseWarn
printDeviceList
selectedArch
setArch
parseCommand()
void parseCommand (string nextCmd)
Definition at line 255 of file byteman.cpp.
{
     replace(nextCmd.begin(), nextCmd.end(), '=', ' ');
     if (nextCmd.at(0) == '-') nextCmd.erase(0, 1);
     #define cmdIs(x,y) (nextCmd.rfind(x, 0) == 0)
     if(cmdIs("h", "help")){
         parseHelp(nextCmd);
         return;
     }
     if(!archSelected)setArch(nextCmd);
     if(cmdIs("v", "verbose"))
         parseVerbose(nextCmd);
     else if(cmdIs("w", "warn"))
         parseWarn(nextCmd);
     else if(cmdIs("r", "region"))
         parseRegion(nextCmd);
     else if(cmdIs("b", "blank"))
         parseBlank(nextCmd);
     else if(cmdIs("c", "change"))
         parseChange(nextCmd);
     else if(cmdIs("d", "device"))
         parseDevice(nextCmd);
     else if(cmdIs("i", "input"))
         parseInput(nextCmd);
     else if(cmdIs("m", "merge"))
         parseMerge(nextCmd);
     else if(cmdIs("o", "output"))
         parseOutput(nextCmd);
     else if(cmdIs("a", "assembly"))
         parseAssembly(nextCmd);
     else if(cmdIs("e", "end"))
         exit(0);
     #undef cmdIs
 }
References archSelected, cmdIs, parseAssembly(), parseBlank(), parseChange(), parseDevice(), parseHelp(), parseInput(), parseMerge(), parseOutput(), parseRegion(), parseVerbose(), parseWarn(), and setArch().
Referenced by main().