byteman: XilinxUltraScalePlus Class Reference
XilinxUltraScalePlus Class Reference
#include "XilinxUltraScalePlus.h"
Public Member Functions
void assembler (string, string)
void assemblerAsmTo (ifstream &, ofstream &)
void assemblerAsmToBin (ifstream &, ofstream &)
void assemblerAsmToBit (ifstream &, ofstream &)
void assemblerParseHeader (ifstream &)
void blank (string)
void deviceHelp ()
void disassemblerBinToAsm (string, ifstream &, ofstream &)
void disassemblerBitToAsm (ifstream &, ofstream &)
void disassemblerToAsm (ifstream &, ofstream &)
void disassemblerWriteHeader (ofstream &)
void ensureInitializedBitstreamArrays () override
int getDeviceByIDCODE (int) override
int getDeviceByIDCODEorThrow (int) override
int getDeviceByName (string) override
int getDeviceByNameOrThrow (string) override
string getFrameType (int, int, int) override
void initFabric ()
void initializeResourceStringParameters () override
void merge (XilinxUltraScalePlus *, string, Rect2D, Coord2D)
void outputBitstreamEmptySLRHeaderSequence (ofstream &, int, bool, Endianness) override
void outputBitstreamEmptySLRWrapUpSequence (ofstream &, int, bool, Endianness) override
void outputBitstreamGlobalFooterSequence (ofstream &, bool, Endianness) override
void outputBitstreamGlobalHeaderSequence (ofstream &, bool, Endianness) override
Written by outputBitstreamSLRHeaderAfterBitstreamSequence(), outputBitstreamEmptySLRHeaderSequence() and used by outputBitstreamSLRWrapUpSequence(), outputBitstreamEmptySLRWrapUpSequence()
void outputBitstreamSLRFooterBitstreamSequence (ofstream &, int, bool, Endianness) override
void outputBitstreamSLRHeaderAfterBitstreamSequence (ofstream &, int, bool, Endianness) override
void outputBitstreamSLRHeaderBitstreamSequence (ofstream &, int, bool, Endianness) override
void outputBitstreamSLRWrapUpSequence (ofstream &, int, bool, Endianness) override
void readBitstream (string)
void setDevice (int, string="") override
void setDeviceByIDCODEOrThrow (int) override
void setDeviceByNameOrThrow (string) override
void setDeviceByPartNameOrThrow () override
void test (bool, bool, uint32_t)
void writeBitstream (string, string, Rect2D)
XilinxUltraScalePlus ()
virtual ~XilinxUltraScalePlus ()
Public Member Functions inherited from CommonDevice2D
CommonDevice2D ()
void region (string, Rect2D)
virtual ~CommonDevice2D ()
Public Member Functions inherited from CommonDevice
CommonDevice ()
void log (string message)
void printMessage (string message)
void warn (string message)
virtual ~CommonDevice ()
Public Member Functions inherited from XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >
XilinxConfigurationAccessPort ()
virtual ~XilinxConfigurationAccessPort ()
Public Attributes
streamoff slrMagicInstrLocation [4]
Public Attributes inherited from CommonDevice2D
vector< Rect2D > regionSelection
Public Attributes inherited from CommonDevice
int enableLog
int enableWarn
string instanceName
Public Attributes inherited from XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >
uint32_t * bitstreamBegin
uint32_t * bitstreamBRAM [MAX_ROWS][MAX_BRAM_COLS]
uint32_t * bitstreamCLB [MAX_ROWS][MAX_COLS]
uint32_t * bitstreamEnd
string designName
string fileDate
string fileTime
int fromRow
streamoff headerLocationOfRemainingFileLength
gets set by outputBITheader() and gets used by outputBITheaderLengthField().
uint32_t IDCODE
string initializedBitstreamParamsShortPartName
the partName of currently initialized resource string parameters
string initializedBitstreamShortPartName
The partName of currently initialized bitstream buffers.
string initializedResourceStringShortPartName
the partName of currently initialized resource string parameters
Endianness loadedBitstreamEndianness
The endianess of the currently loaded bitstream.
bool LUT_isFrameUnusedForResourceLetter [256]
int LUT_numberOfFramesForResourceLetter [256]
string LUT_typeOfFrameForResourceLetter [256]
int maxNumberOfBRAMCols
int maxNumberOfCols
int numberOfBRAMCols [MAX_ROWS]
int numberOfBRAMsBeforeCol [MAX_ROWS][MAX_COLS]
int numberOfCols [MAX_ROWS]
int numberOfFramesBeforeCol [MAX_ROWS][MAX_COLS]
int numberOfFramesPerRow [MAX_ROWS]
int numberOfRows
int numberOfSLRs
int numberOfWordsPerRow [MAX_ROWS]
string partName
char resourceString [MAX_ROWS][MAX_COLS]
int rowsInBottomHalf
int rowsInTopHalf
struct XilinxConfigurationAccessPort::SelectedOptions selectedOptions
struct {
int fromRow
uint32_t IDCODE
int rowsInBottomHalf
int rowsInTopHalf
int toRow
} SLRinfo [MAX_SLRS]
int toRow
Additional Inherited Members
Public Types inherited from XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >
enum MergeOP
Detailed Description
Definition at line 31 of file XilinxUltraScalePlus.h.
Constructor & Destructor Documentation
XilinxUltraScalePlus()
XilinxUltraScalePlus::XilinxUltraScalePlus ()
Definition at line 31 of file XilinxUltraScalePlus.cpp.
 {
     initFabric();
 }
~XilinxUltraScalePlus()
XilinxUltraScalePlus::~XilinxUltraScalePlus () virtual
Definition at line 36 of file XilinxUltraScalePlus.cpp.
 {
 }
Member Function Documentation
assembler()
void XilinxUltraScalePlus::assembler (string filenameIn, string filenameOut)
Definition at line 32 of file XUSP_Assembler.cpp.
 {
     enum FILEFORMAT {FILE_NULL = 0, FILE_BIT, FILE_BIN, FILE_BIT_ASM};
     FILEFORMAT fileformatIn = FILE_NULL, fileformatOut = FILE_NULL;
     if(str::iff::stringEndsWith(filenameIn, ".bit"))
         fileformatIn = FILE_BIT;
     if(str::iff::stringEndsWith(filenameIn, ".bin"))
         fileformatIn = FILE_BIN;
     if(str::iff::stringEndsWith(filenameIn, ".bitasm"))
         fileformatIn = FILE_BIT_ASM;
     if(str::iff::stringEndsWith(filenameOut, ".bit"))
         fileformatOut = FILE_BIT;
     if(str::iff::stringEndsWith(filenameOut, ".bin"))
         fileformatOut = FILE_BIN;
     if(str::iff::stringEndsWith(filenameOut, ".bitasm"))
         fileformatOut = FILE_BIT_ASM;
     ifstream fin (filenameIn, ifstream::binary);
     if(!fin.good())
         throw runtime_error(string("Could not open file: \"").append(filenameIn).append("\" .\n"));
     ofstream fout (filenameOut, ofstream::binary | ofstream::trunc);
     if(!fout.good())
         throw runtime_error(string("Could not open file: \"").append(filenameOut).append("\"!\n"));
     if(fileformatIn == FILE_BIT && fileformatOut == FILE_BIT_ASM)
         disassemblerBitToAsm(fin, fout);
     else if(fileformatIn == FILE_BIN && fileformatOut == FILE_BIT_ASM)
         disassemblerBinToAsm(filenameIn, fin, fout);
     else if(fileformatIn == FILE_BIT_ASM && fileformatOut == FILE_BIT)
         assemblerAsmToBit(fin, fout);
     else if(fileformatIn == FILE_BIT_ASM && fileformatOut == FILE_BIN)
         assemblerAsmToBin(fin, fout);
     else
         throw runtime_error(string("Unknown Xilinx US+ assembler operation between file formats. See \"byteman -h assembly\".\n"));
     fin.close();
     fout.close();
 }
References str::iff::stringEndsWith().
assemblerAsmTo()
void XilinxUltraScalePlus::assemblerAsmTo (ifstream & fin, ofstream & fout)
Definition at line 125 of file XUSP_Assembler.cpp.
 {
     outputCAPheaderConstant(fout, loadedBitstreamEndianness);
     XCAP::Register regAddr = XCAP::Register::UNDEFINED;
     int frameCount = 0;
     int slr = 0, b = 7, r = 0, c = 0, m = 0;
     for (string line; getline(fin, line); ) {
         if(line.at(line.find_first_not_of(" \t")) == '#')// if #, skip that line as comment
             continue;
         transform(line.begin(), line.end(),line.begin(), ::toupper);
         replace(line.begin(), line.end(), '=', ' ');
         replace(line.begin(), line.end(), '#', ' ');
         replace(line.begin(), line.end(), ',', ' ');
         if(str::iff::stringContains(line, "SYNC") && (!str::iff::stringContains(line, "DESYNC"))){
             XCAP_writeSYNQ(fout, loadedBitstreamEndianness);
         }
         else if(str::iff::stringContains(line, ".WORD")){
             uint32_t wordValue;
             if(!str::parse::multipleUints(line, wordValue))wordValue = 0;
             FileIO::write32(fout, wordValue, loadedBitstreamEndianness);
         }
         else if(str::iff::stringContains(line, "NOP")){
             int nopHiddenValue;
             if(!str::parse::multipleInts(line, nopHiddenValue))nopHiddenValue = 0;
             XCAP_writeNOP(fout, 1, nopHiddenValue, loadedBitstreamEndianness);
         }
         else if(str::iff::stringContains(line, "RESERVED")){
             int reservedHiddenValue;
             if(!str::parse::multipleInts(line, reservedHiddenValue))reservedHiddenValue = 0;
             XCAP_writeRESERVED(fout, 1, reservedHiddenValue, loadedBitstreamEndianness);
         }
         else if(str::iff::stringContains(line, "SELECT NEXT SLR")){
             slr++;
             int magic1size;
             if(!str::parse::multipleInts(line, magic1size))magic1size = 0;
             XCAP_writeSelectRegister(fout, XCAP::Register::MAGIC1, loadedBitstreamEndianness);
             XCAP_writeType2(fout, magic1size, loadedBitstreamEndianness);
         }
         else if(str::iff::stringContains(line, "@")){
             XCAP::Register newRegAddr = getXCAPregister(line);
             if(str::iff::stringContains(line, "READ REG @")){
                 int readLength;
                 if(!str::parse::multipleInts(line, readLength)) readLength = 1; // default read length is 1 if unspecified
                 XCAP_writeReadRegister(fout, newRegAddr, readLength, loadedBitstreamEndianness);
             } else {// must be a write then \_()_/
                 if(newRegAddr == XCAP::Register::UNDEFINED){
                     throw runtime_error(string("Couldn't parse assembly command: \"").append(line).append("\"!"));
                 } else if(str::iff::stringContains(line, "SELECT REGISTER")){
                     XCAP_writeSelectRegister(fout, newRegAddr, loadedBitstreamEndianness);
                 } else if(newRegAddr == XCAP::Register::FDRI){
                     if(!str::parse::multipleInts(line, frameCount))
                         throw runtime_error(string("FDRI command needs size: \"").append(line).append("\"!"));
                     int wordCount = frameCount * XUSP_WORDS_PER_FRAME;
                     if(regAddr == XCAP::Register::FDRI) {
                         XCAP_writeType2(fout, wordCount, loadedBitstreamEndianness);
                     } else {
                         XCAP_writeFDRI1(fout, wordCount, loadedBitstreamEndianness);
                     }
                     if(frameCount > 0){
                         string frameLine;
                         for (string frameLine; getline(fin, frameLine); ) {
                             if(frameLine.at(frameLine.find_first_not_of(" \t")) == '#')// if #, skip that line as comment
                                 continue;
                             uint32_t frameData[XUSP_WORDS_PER_FRAME];
                             if(!str::parse::arrayOfUints(frameLine, XUSP_WORDS_PER_FRAME, &frameData[0]))
                                 throw runtime_error(string("Was expecting the data for a full frame on this line: \"").append(frameLine).append("\", because I think there are ").append(to_string(frameCount)).append(" frames left."));
                             //first 3 words are clk, next 90 are the 0-45 and 48-93 data words
                             for (int w = XUSP_WORDS_AT_CLK; w < (XUSP_WORDS_AT_CLK + XUSP_WORDS_BEFORE_CLK) ; w++){
                                 FileIO::write32(fout, frameData[w], loadedBitstreamEndianness);
                             }
                             for (int w = 0; w < XUSP_WORDS_AT_CLK ; w++){
                                 FileIO::write32(fout, frameData[w], loadedBitstreamEndianness);
                             }
                             for (int w = (XUSP_WORDS_AT_CLK + XUSP_WORDS_BEFORE_CLK); w < XUSP_WORDS_PER_FRAME ; w++){
                                 FileIO::write32(fout, frameData[w], loadedBitstreamEndianness);
                             }
                             frameCount--;
                             if(frameCount == 0)
                                 break;
                         }
                         if(frameCount != 0)
                             throw runtime_error(string("End of file reached while performing FDRI frame writes.!"));
                     }
                 } else if(newRegAddr == XCAP::Register::FAR){
                     if(!str::parse::multipleInts(line, b, r, c, m))
                         throw runtime_error(string("Could not parse the new FAR value: \"").append(line).append("\"!"));
                     r += SLRinfo[slr].fromRow;
                     uint32_t farValue = XCAP_getFAR(slr, b, r, c, m);
                     XCAP_writeRegister(fout, XCAP::Register::FAR, farValue, loadedBitstreamEndianness);
                 } else {
                     uint32_t newValue;
                     if(!str::parse::multipleUints(line, newValue))
                         throw runtime_error(string("Could not parse the new register value: \"").append(line).append("\"!"));
                     XCAP_writeRegister(fout, newRegAddr, newValue, loadedBitstreamEndianness);
                 }
             }
             regAddr = newRegAddr;
         } else {// ! str::iff::stringContains(line, "@")
             //must have been a command then
             XCAP::Command cmdID = getXCAPcommand(line);
             if(cmdID == XCAP::Command::UNDEFINED)
                 throw runtime_error(string("Couldn't parse assembly command: \"").append(line).append("\"!"));
             XCAP_writeCommand(fout, cmdID, loadedBitstreamEndianness);
         }
     }
     outputBITheaderLengthField(fout, loadedBitstreamEndianness);
 }
References str::parse::arrayOfUints(), XCAP::FAR, XCAP::FDRI, getXCAPcommand(), getXCAPregister(), XCAP::MAGIC1, str::parse::multipleInts(), str::parse::multipleUints(), outputBITheaderLengthField(), outputCAPheaderConstant(), str::replace(), str::iff::stringContains(), Endian::to_string(), XCAP::UNDEFINED, FileIO::write32(), XCAP_getFAR(), XCAP_writeCommand(), XCAP_writeFDRI1(), XCAP_writeNOP(), XCAP_writeReadRegister(), XCAP_writeRegister(), XCAP_writeRESERVED(), XCAP_writeSelectRegister(), XCAP_writeSYNQ(), XCAP_writeType2(), XUSP_WORDS_AT_CLK, XUSP_WORDS_BEFORE_CLK, and XUSP_WORDS_PER_FRAME.
assemblerAsmToBin()
void XilinxUltraScalePlus::assemblerAsmToBin (ifstream & fin, ofstream & fout)
Definition at line 98 of file XUSP_Assembler.cpp.
{
     assemblerParseHeader(fin);
     setDeviceByPartNameOrThrow();
     initializeResourceStringParameters();
     assemblerAsmTo(fin, fout);
 }
assemblerAsmToBit()
void XilinxUltraScalePlus::assemblerAsmToBit (ifstream & fin, ofstream & fout)
Definition at line 89 of file XUSP_Assembler.cpp.
{
     assemblerParseHeader(fin);
     setDeviceByPartNameOrThrow();
     initializeResourceStringParameters();
     outputBITheader(fout, loadedBitstreamEndianness);
     assemblerAsmTo(fin, fout);
 }
References outputBITheader().
assemblerParseHeader()
void XilinxUltraScalePlus::assemblerParseHeader (ifstream & fin)
Definition at line 107 of file XUSP_Assembler.cpp.
 {
     for (string line; getline(fin, line); ) {
         auto firstEqPos = line.find_first_of('=');
         if(firstEqPos != string::npos)
             line.replace(firstEqPos, 1, '=', ' ');
         if(str::iff::stringContains(line, "Name"))designName = str::parse::lastStringWord(line);
         if(str::iff::stringContains(line, "FPGA"))partName = str::parse::lastStringWord(line);
         if(str::iff::stringContains(line, "Date"))fileDate = str::parse::lastStringWord(line);
         if(str::iff::stringContains(line, "Time"))fileTime = str::parse::lastStringWord(line);
         if(str::iff::stringContains(line, "HEADER END"))break;
     }
     log("Design name: " + designName);
     log("FPGA: " + partName);
     log("Date: " + fileDate);
     log("Time: " + fileTime);
 }
References str::parse::lastStringWord(), and str::iff::stringContains().
blank()
void XilinxUltraScalePlus::blank (string params)
Definition at line 20 of file XUSP_Blank.cpp.
{
     ensureInitializedBitstreamArrays();
     parseParams(params);
     blankBuffers();
 }
References blankBuffers(), ensureInitializedBitstreamArrays(), and parseParams().
deviceHelp()
void XilinxUltraScalePlus::deviceHelp ()
Definition at line 1109 of file XUSP_Devices.cpp.
 {
     if(initializedResourceStringShortPartName == "") {//if no device is initialized
         cout << "A list of currently recognized US+ devices: " << endl;
         #ifdef XUSPARTIX
         cout << "  UltraScale+ Artix: " << endl;
         cout << "    XCAU10P, XCAU15P, XCAU20P, XCAU25P" << endl;
         #endif
         #ifdef XUSPKINTEX
         cout << "  UltraScale+ Kintex: " << endl;
         cout << "    XCKU3P, XQKU3P, XCKU5P, XQKU5P, XCKU9P, XQKU9P, XCKU11P, XQKU11P, XCKU13P, XQKU13P, XCKU15P, XQKU15P, XCKU19P, XQKU19P" << endl;
         #endif
         #ifdef XUSPVIRTEX
         cout << "  UltraScale+ Virtex: " << endl;
         cout << "    XCVU3P, XQVU3P, XCVU5P, XQVU5P, XCVU7P, XQVU7P, XCVU9P, XQVU9P, XCVU11P, XQVU11P, XCVU13P, XQVU13P," << endl;
         cout << "    XCVU19P, XQVU19P, XCVU23P, XQVU23P, XCVU27P, XQVU27P, XCVU29P, XQVU29P, XCVU31P, XQVU31P, XCVU33P," << endl;
         cout << "    XQVU33P, XCVU35P, XQVU35P, XCVU37P, XQVU37P, XCVU45P, XQVU45P, XCVU47P, XQVU47P, XCVU57P, XQVU57P" << endl;
         #endif
         #ifdef XUSPZYNQRF
         cout << "  UltraScale+ Zynq RFSoC: " << endl;
         cout << "    XCZU21DR, XQZU21DR, XCZU25DR, XCZU27DR, XCZU28DR, XQZU28DR, XCZU29DR, XQZU29DR, XCZU39DR, XCZU42DR," << endl;
         cout << "    XCZU43DR, XCZU46DR, XQZU48DR, XQZU49DR, XCZU47DR, XCZU48DR, XCZU49DR" << endl;
         #endif
         #ifdef XUSPZYNQMP
         cout << "  UltraScale+ Zynq MPSoC: " << endl;
         cout << "    XCZU1, XAZU1, XQZU1, XCZU2, XAZU2, XQZU2, XCZU3, XAZU3, XQZU3, XCZU4, XAZU4, XQZU4," << endl;
         cout << "    XCZU5, XAZU5, XQZU5, XCZU6, XAZU6, XQZU6, XCZU7, XAZU7, XQZU7, XCZU9, XAZU9, XQZU9," << endl;
         cout << "    XCZU11, XAZU11, XQZU11, XCZU15, XAZU15, XQZU15, XCZU17, XAZU17, XQZU17, XCZU19, XAZU19, XQZU19" << endl;
         #endif
         #ifdef XUSPALVEO
         cout << "  UltraScale+ Alveo: " << endl;
         cout << "    XCU200, Alveo U200, XCU250, Alveo U250, XCU26, Alveo U26, XCUX35, Alveo U35, XCU50, Alveo U50," << endl;
         cout << "    XCU55N, Alveo U55N, XCU55C, Alveo U55C, XCU280, Alveo U280, XCU30, Alveo U30, XCU25, Alveo U25" << endl;
         #endif
         #ifdef XUSPBOARDS
         cout << "  Misc UltraScale+ Boards: " << endl;
         cout << "    ZCU 102, ZU-GMSL2, ZCU104, ZCU106, AXU15EG, AXU2CG, AXU3EG, AXU4EV, AXU5EV, AXU9EG, ULTRAZED-EV, CHAMP-XD1S, ZU-3EG," << endl;
         cout << "    ZU-5EV, HTG-Z999-06, HTG-Z999-09, HTG-Z999-15, HTG-930-9-3, HTG-930-9, HTG-930-13-3, HTG-930-13, HTG-937-37P, HTG-937-47P," << endl;
         cout << "    HTG-Z922-11, HTG-Z922-19-DG, HTG-Z922-19, CZU3EG, CZU4EV, TE0802, TE0803-04-3BE11, TE0807-03-7DE21, TE0808-05-9BE21," << endl;
         cout << "    TE0808-05-9GI21, TE0808-05-BBE21, TE0812, TEB0911, TEB0912, TYSOM-3-ZU7EV, XPEDITE2600, AMC574, ZCU208, ZCU216, ZCU670," << endl;
         cout << "    Ultra96, K26C, K26I, KV260, AMC584, HTG-960, VCU1525, VCU118, VCU128, VCU129, HTG-940-9-3, HTG-940-9, HTG-940-13-3," << endl;
         cout << "    HTG-940-13, HTG-9200-5P, HTG-9200-9P, HTG-9200-13P, HTG-VUP-PCIE-HH-9P, HTG-910-9, HTG-VUP-PCIE-HH-13P, HTG-910-13," << endl;
         cout << "    HTG-ZRF-FMC-28, HTG-ZRF-FMC-48, HTG-ZRF16-29, HTG-ZRF16-49, HTG-ZRF-HH-28, HTG-ZRF-HH-48, HTG-ZUSP-PCIE-11-3," << endl;
         cout << "    HTG-ZUSP-PCIE-19-2, HTG-ZRF8-R2-28, HTG-ZRF8-28, HTG-ZRF8-R2-48-I, HTG-ZRF8-48-I, HTG-ZRF8-R2-48, HTG-ZRF8-48" << endl;
         cout << "    ZUBoard 1CG, KCU 116, Vermeo T1 MPSoC, Vermeo T1 RFSoC, ZCU 1275, ZCU 1285, ZCU 111" << endl;
         #endif
     } else {
         printResourceStringInfo();
     }
 }
References printResourceStringInfo().
disassemblerBinToAsm()
void XilinxUltraScalePlus::disassemblerBinToAsm (string filenameIn, ifstream & fin, ofstream & fout)
Definition at line 72 of file XUSP_Assembler.cpp.
{
     loadedBitstreamEndianness = parseBitstreamEndianness(fin);
     uint32_t idcode = parseBitstreamIDCODE(fin, loadedBitstreamEndianness);
     setDeviceByIDCODEOrThrow(idcode);
     designName = filenameIn;
     updateDateAndTime();
     disassemblerToAsm(fin, fout);
 }
References parseBitstreamEndianness(), parseBitstreamIDCODE(), and updateDateAndTime().
disassemblerBitToAsm()
void XilinxUltraScalePlus::disassemblerBitToAsm (ifstream & fin, ofstream & fout)
Definition at line 82 of file XUSP_Assembler.cpp.
{
     loadedBitstreamEndianness = parseBitstreamEndianness(fin);
     parseBITheader(fin, loadedBitstreamEndianness);
     setDeviceByPartNameOrThrow();
     disassemblerToAsm(fin, fout);
 }
References parseBITheader(), and parseBitstreamEndianness().
disassemblerToAsm()
void XilinxUltraScalePlus::disassemblerToAsm (ifstream & fin, ofstream & fout)
Definition at line 246 of file XUSP_Assembler.cpp.
 {
     initializeResourceStringParameters();
     disassemblerWriteHeader(fout);
     XCAP::Register regAddr = XCAP::Register::UNDEFINED;
     bool synched = false;
     int wordCount = 0;
     int shadowFrameValid = 0;
     int slr = 0, b = 7, r = 0, c = 0, m = 0;
     //Parse bitstream
     for( ; ; ){
         uint32_t instruction = FileIO::read32(fin, loadedBitstreamEndianness);
         if(!fin.good()){
             break; // done with the bitstream
         } else {
             if(! synched){
                 if(0xAA995566 == instruction){
                     synched = true;
                     fout << "SYNC" << endl;
                 } else {
                     fout << ".word " <<"0x" << uppercase << hex << setw(8) << setfill('0') << instruction << endl;
                 }
             } else {
                 int instructionType = XCAP_getInstructionType(instruction);
                 XCAP::Operation instructionOPCODE = XCAP_getInstructionOperation(instruction);
                 int instructionPayload = XCAP_getInstructionPayload(instruction);
                 if(instructionType == 1) {
                     wordCount = XCAP_getInstructionWordCount(instruction);
                     regAddr = XCAP_getInstructionRegister(instruction);
                 } else if(instructionType == 2) {
                     wordCount = instructionPayload;
                 } else {
                     fout << "0x" << uppercase << hex << setw(8) << setfill('0') << instruction << " (Invalid instruction [invalid type])" << endl;
                     continue;
                 }
                 if(instructionOPCODE == XCAP::Operation::NOP) {
                     if(instructionPayload != 0)
                         fout << "NOP #" << instructionPayload << endl;
                     else
                         fout << "NOP" << endl;
                 } else if(instructionOPCODE == XCAP::Operation::RESERVED) {
                     if(instructionPayload != 0)
                         fout << "RESERVED #" << instructionPayload << endl;
                     else
                         fout << "RESERVED" << endl;
                 } else if(instructionOPCODE == XCAP::Operation::READ) {
                     fout << "Read Reg @";
                     writeXCAPregisterName(fout, regAddr);
                     fout << " for length #" << wordCount << endl;
                 } else { // XCAP::Operation::WRITE
                     if((regAddr == XCAP::Register::FDRI) && (wordCount > 0) && (wordCount % XUSP_WORDS_PER_FRAME == 0)) {
                         if(shadowFrameValid) {
                             fout << dec << "# Shadow register contents are written to frame (BlockType="<<b<<", GlobalRowAddress="<<r<<", MajorAddress="<<c<<", MinorAddress="<<m<<") (Frame type: " << getFrameType(b,r,c) << ")."<<endl;
                             XCAP_IncrementFAR(slr, b, r, c, m);
                         }
                         shadowFrameValid = 1;
                         int frameCount = (wordCount/XUSP_WORDS_PER_FRAME);
                         fout << dec << "@FDRI for #" << frameCount << " frames:" << endl;
                         for(int i = 0 ; i < frameCount ; i++){
                             fout << "# ";
                             if(i == (frameCount-1)) fout << "(This frame data is written to shadow register!)";
                             fout << dec << "Writing frame #" << i << " (BlockType="<<b<<", GlobalRowAddress="<<r<<", MajorAddress="<<c<<", MinorAddress="<<m<<") (Frame type: " << getFrameType(b,r,c) << ") hex data:"<<endl;
                             uint32_t frameData[XUSP_WORDS_PER_FRAME];
                             for(int w = 0 ; w < XUSP_WORDS_PER_FRAME ; w++){
                                 frameData[w] = FileIO::read32(fin, loadedBitstreamEndianness);
                             }
                             fout<<"CLOCK: ";
                             for(int w = XUSP_WORDS_BEFORE_CLK ; w < (XUSP_WORDS_BEFORE_CLK + XUSP_WORDS_AT_CLK) ; w++){
                                 fout<< "0x"  << uppercase << hex << setw(8) << setfill('0') << frameData[w] << " ";
                             }
                             fout<<" ;DATA: ";
                             for(int w = 0 ; w < XUSP_WORDS_BEFORE_CLK ; w++){
                                 fout<< "0x"  << uppercase << hex << setw(8) << setfill('0') << frameData[w] << " ";
                             }
                             for(int w = (XUSP_WORDS_BEFORE_CLK + XUSP_WORDS_AT_CLK) ; w < XUSP_WORDS_PER_FRAME ; w++){
                                 fout<< "0x"  << uppercase << hex << setw(8) << setfill('0') << frameData[w] << " ";
                             }
                             fout << endl;
                             XCAP_IncrementFAR(slr, b, r, c, m);
                         }
                     } else if(regAddr == XCAP::Register::CMD && wordCount == 1){
                         uint32_t writeData = FileIO::read32(fin, loadedBitstreamEndianness);
                         writeXCAPcommandName(fout, static_cast<XCAP::Command>(writeData));
                         fout << ";";
                         if(XCAP::Command::DESYNC == static_cast<XCAP::Command>(writeData)){
                             shadowFrameValid = 0;
                             synched = false;
                         }
                         if(XCAP::Command::WCFG == static_cast<XCAP::Command>(writeData)){
                             shadowFrameValid = 0;
                             fout << " (also clears shadow register)";
                         }
                         fout << endl;
                     } else if(regAddr == XCAP::Register::MAGIC1){
                         uint32_t nextInstr = FileIO::read32(fin, loadedBitstreamEndianness);
                         int nextInstrType = XCAP_getInstructionType(nextInstr);
                         XCAP::Operation nextInstrOP = XCAP_getInstructionOperation(nextInstr);
                         int nextInstrPayload = XCAP_getInstructionPayload(nextInstr);
                         if(2 == nextInstrType && XCAP::Operation::WRITE == nextInstrOP && 0 < nextInstrPayload){
                             slr++;
                             synched = false;
                             fout << "Select next SLR for the next #"<<dec<<nextInstrPayload<<" words." << endl;
                         } else {
                             fout << "Bad MAGIC1 instruction" << endl;
                             fin.seekg(-4,ios::cur);//rewind next instruction if not
                         }
                     } else if((instructionType == 1) && (wordCount == 0)){
                         fout << "Select register @";
                         writeXCAPregisterName(fout, regAddr);
                         fout << endl;
                     } else if(wordCount == 1){
                         uint32_t writeData = FileIO::read32(fin, loadedBitstreamEndianness);
                         fout << "@";
                         writeXCAPregisterName(fout, regAddr);
                         if(regAddr == XCAP::Register::FAR) {
                             XCAP_parseFAR(writeData, slr, b, r, c, m);
                             fout << " = BlockType=" << dec <<b<<" RowAddress="<<(r-SLRinfo[slr].fromRow)<<" MajorAddress="<<c<<" MinorAddress="<<m<< endl;
                         } else {
                             fout << " = 0x" << uppercase << hex << setw(8) << setfill('0') << writeData << endl;
                         }
                     } else {
                         fout << "0x"<< uppercase << hex << setw(8) << setfill('0') << instruction << "(Bad instruction)" << endl;
                     }
                 } // OP_WRITE
             }// if synched
         } // if fin is still good
     } // for(;;)
 }
References XCAP::CMD, XCAP::DESYNC, XCAP::FAR, XCAP::FDRI, XCAP::MAGIC1, XCAP::NOP, XCAP::READ, FileIO::read32(), XCAP::RESERVED, XCAP::UNDEFINED, XCAP::WCFG, XCAP::WRITE, writeXCAPcommandName(), writeXCAPregisterName(), XCAP_getInstructionOperation(), XCAP_getInstructionPayload(), XCAP_getInstructionRegister(), XCAP_getInstructionType(), XCAP_getInstructionWordCount(), XCAP_IncrementFAR(), XCAP_parseFAR(), XUSP_WORDS_AT_CLK, XUSP_WORDS_BEFORE_CLK, and XUSP_WORDS_PER_FRAME.
disassemblerWriteHeader()
void XilinxUltraScalePlus::disassemblerWriteHeader (ofstream & fout)
Definition at line 236 of file XUSP_Assembler.cpp.
 {
     fout<<"--- HEADER BEGIN ---"<<endl;
     fout<<"Name = \""<<designName<<"\""<<endl;
     fout<<"FPGA = \""<<partName<<"\""<<endl;
     fout<<"Date = \""<<fileDate<<"\""<<endl;
     fout<<"Time = \""<<fileTime<<"\""<<endl;
     fout<<"--- HEADER END ---"<<endl;
 }
ensureInitializedBitstreamArrays()
void XilinxUltraScalePlus::ensureInitializedBitstreamArrays () override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 78 of file XilinxUltraScalePlus.cpp.
{
     if(initializedResourceStringShortPartName == "")
         throw runtime_error("The target device needs to be known, before you can manipulate any bitstream!");
     if(initializedBitstreamShortPartName != initializedResourceStringShortPartName){//The device is changed
         initializedBitstreamShortPartName = initializedResourceStringShortPartName;
         if(bitstreamBegin != nullptr)
             delete bitstreamBegin;
         initializeResourceStringParameters();
         //Allocate
         int clbPlaneSize = numberOfRows * numberOfWordsPerRow[0];
         int bramPlaneSize = numberOfRows * XUSP_WORDS_PER_FRAME * (XUSP_EXTRA_FRAMES_PER_ROW + maxNumberOfBRAMCols * XUSP_FRAMES_PER_BRAM_CONTENT_COLUMN);
         bitstreamBegin = new uint32_t[clbPlaneSize + bramPlaneSize + 100];
         //Calc pointers
         int offset = 0;
         for(int slr = 0 ; slr < numberOfSLRs ; slr++){
             for(int r = SLRinfo[slr].fromRow ; r <= SLRinfo[slr].toRow ; r++){
                 for(int c = 0 ; c < numberOfCols[r] ; c++){
                     bitstreamCLB[r][c] = &bitstreamBegin[offset];
                     offset += LUT_numberOfFramesForResourceLetter[(uint8_t)resourceString[r][c]] * XUSP_WORDS_PER_FRAME;
                 }
             }
             for(int r = SLRinfo[slr].fromRow ; r <= SLRinfo[slr].toRow ; r++){
                 for(int c = 0 ; c < numberOfBRAMCols[r] ; c++){
                     bitstreamBRAM[r][c] = &bitstreamBegin[offset];
                     offset += XUSP_FRAMES_PER_BRAM_CONTENT_COLUMN * XUSP_WORDS_PER_FRAME;
                 }
                 bitstreamBRAM[r][numberOfBRAMCols[r]] = &bitstreamBegin[offset];
                 offset += XUSP_EXTRA_FRAMES_PER_ROW * XUSP_WORDS_PER_FRAME;
             }
         }
         bitstreamEnd = &bitstreamBegin[offset];
         log("Reserved "+to_string(clbPlaneSize + bramPlaneSize)+" words for the bitstream buffers of device \""+partName+"\"");
     }
 }
References Endian::to_string(), XUSP_EXTRA_FRAMES_PER_ROW, XUSP_FRAMES_PER_BRAM_CONTENT_COLUMN, and XUSP_WORDS_PER_FRAME.
Referenced by blank(), and test().
getDeviceByIDCODE()
int XilinxUltraScalePlus::getDeviceByIDCODE (int IDCODE) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 58 of file XUSP_Devices.cpp.
 {
     //US+ Artix
     #ifdef XUSPARTIX
     if(IDCODE == XCAU10P_IDCODE)
         return XUSP_DEVICE_XCAU10P;
     if(IDCODE == XCAU15P_IDCODE)
         return XUSP_DEVICE_XCAU15P;
     if(IDCODE == XCAU20P_IDCODE)
         return XUSP_DEVICE_XCAU20P;
     if(IDCODE == XCAU25P_IDCODE)
         return XUSP_DEVICE_XCAU25P;
     #endif
     //US+ Kintex
     #ifdef XUSPKINTEX
     if(IDCODE == XCKU3P_IDCODE)
         return XUSP_DEVICE_XCKU3P;
     if(IDCODE == XCKU5P_IDCODE)
         return XUSP_DEVICE_XCKU5P;
     if(IDCODE == XCKU9P_IDCODE)
         return XUSP_DEVICE_XCKU9P;
     if(IDCODE == XCKU11P_IDCODE)
         return XUSP_DEVICE_XCKU11P;
     if(IDCODE == XCKU13P_IDCODE)
         return XUSP_DEVICE_XCKU13P;
     if(IDCODE == XCKU15P_IDCODE)
         return XUSP_DEVICE_XCKU15P;
     if(IDCODE == XCKU19P_IDCODE)
         return XUSP_DEVICE_XCKU19P;
     #endif
     //US+ Virtex
     #ifdef XUSPVIRTEX
     if(IDCODE == XCVU3P_IDCODE)
         return XUSP_DEVICE_XCVU3P;
     if(IDCODE == XCVU5P_IDCODE)
         return XUSP_DEVICE_XCVU5P;
     if(IDCODE == XCVU7P_IDCODE)
         return XUSP_DEVICE_XCVU7P;
     if(IDCODE == XCVU9P_IDCODE)
         return XUSP_DEVICE_XCVU9P;
     if(IDCODE == XCVU11P_IDCODE)
         return XUSP_DEVICE_XCVU11P;
     if(IDCODE == XCVU13P_IDCODE)
         return XUSP_DEVICE_XCVU13P;
     if(IDCODE == XCVU19P_IDCODE)
         return XUSP_DEVICE_XCVU19P;
     if(IDCODE == XCVU23P_IDCODE)
         return XUSP_DEVICE_XCVU23P;
     if(IDCODE == XCVU27P_IDCODE)
         return XUSP_DEVICE_XCVU27P;
     if(IDCODE == XCVU29P_IDCODE)
         return XUSP_DEVICE_XCVU29P;
     if(IDCODE == XCVU31P_IDCODE)
         return XUSP_DEVICE_XCVU31P;
     if(IDCODE == XCVU33P_IDCODE)
         return XUSP_DEVICE_XCVU33P;
     if(IDCODE == XCVU35P_IDCODE)
         return XUSP_DEVICE_XCVU35P;
     if(IDCODE == XCVU37P_IDCODE)
         return XUSP_DEVICE_XCVU37P;
     if(IDCODE == XCVU45P_IDCODE)
         return XUSP_DEVICE_XCVU45P;
     if(IDCODE == XCVU47P_IDCODE)
         return XUSP_DEVICE_XCVU47P;
     if(IDCODE == XCVU57P_IDCODE)
         return XUSP_DEVICE_XCVU57P;
     #endif
     //US+ RFSoC (RFSOC BEFORE MPSOC, since names collide!)
     #ifdef XUSPZYNQ
     if(IDCODE == XCZU21DR_IDCODE)
         return XUSP_DEVICE_XCZU21DR;
     if(IDCODE == XCZU25DR_IDCODE)
         return XUSP_DEVICE_XCZU25DR;
     if(IDCODE == XCZU27DR_IDCODE)
         return XUSP_DEVICE_XCZU27DR;
     if(IDCODE == XCZU28DR_IDCODE)
         return XUSP_DEVICE_XCZU28DR;
     if(IDCODE == XCZU29DR_IDCODE)
         return XUSP_DEVICE_XCZU29DR;
     if(IDCODE == XCZU39DR_IDCODE)
         return XUSP_DEVICE_XCZU39DR;
     if(IDCODE == XCZU42DR_IDCODE)
         return XUSP_DEVICE_XCZU42DR;
     if(IDCODE == XCZU43DR_IDCODE)
         return XUSP_DEVICE_XCZU43DR;
     if(IDCODE == XCZU46DR_IDCODE)
         return XUSP_DEVICE_XCZU46DR;
     if(IDCODE == XCZU47DR_IDCODE)
         return XUSP_DEVICE_XCZU47DR;
     if(IDCODE == XCZU48DR_IDCODE)
         return XUSP_DEVICE_XCZU48DR;
     if(IDCODE == XCZU49DR_IDCODE)
         return XUSP_DEVICE_XCZU49DR;
     if(IDCODE == XCZU65DR_IDCODE)
         return XUSP_DEVICE_XCZU65DR;
     if(IDCODE == XCZU67DR_IDCODE)
         return XUSP_DEVICE_XCZU67DR;
     #endif
     //US+ Zynq
     #ifdef XUSPZYNQ
     if(IDCODE == XCZU1_IDCODE)
         return XUSP_DEVICE_XCZU1;
     if(IDCODE == XCZU2_IDCODE)
         return XUSP_DEVICE_XCZU2;
     if(IDCODE == XCZU3_IDCODE)
         return XUSP_DEVICE_XCZU3;
     if(IDCODE == XCZU4_IDCODE)
         return XUSP_DEVICE_XCZU4;
     if(IDCODE == XCZU5_IDCODE)
         return XUSP_DEVICE_XCZU5;
     if(IDCODE == XCZU6_IDCODE)
         return XUSP_DEVICE_XCZU6;
     if(IDCODE == XCZU7_IDCODE)
         return XUSP_DEVICE_XCZU7;
     if(IDCODE == XCZU9_IDCODE)
         return XUSP_DEVICE_XCZU9;
     if(IDCODE == XCZU11_IDCODE)
         return XUSP_DEVICE_XCZU11;
     if(IDCODE == XCZU15_IDCODE)
         return XUSP_DEVICE_XCZU15;
     if(IDCODE == XCZU17_IDCODE)
         return XUSP_DEVICE_XCZU17;
     if(IDCODE == XCZU19_IDCODE)
         return XUSP_DEVICE_XCZU19;
     #endif
     //Alveo rebranding
     #ifdef XUSPALVEO
     if(IDCODE == XCU200_IDCODE)
         return XUSP_DEVICE_XCU200;
     if(IDCODE == XCU250_IDCODE)
         return XUSP_DEVICE_XCU250;
     if(IDCODE == XCU26_IDCODE)
         return XUSP_DEVICE_XCU26;
     if(IDCODE == XCUX35_IDCODE)
         return XUSP_DEVICE_XCUX35;
     if(IDCODE == XCU50_IDCODE)
         return XUSP_DEVICE_XCU50;
     if(IDCODE == XCU55N_IDCODE)
         return XUSP_DEVICE_XCU55N;
     if(IDCODE == XCU55C_IDCODE)
         return XUSP_DEVICE_XCU55C;
     if(IDCODE == XCU280_IDCODE)
         return XUSP_DEVICE_XCU280;
     if(IDCODE == XCU30_IDCODE)
         return XUSP_DEVICE_XCU30;
     if(IDCODE == XCU25_IDCODE)
         return XUSP_DEVICE_XCU25;
     //Kria
     if(IDCODE == XCK26_IDCODE)
         return XUSP_DEVICE_XCK26;
     #endif
     return XUSP_DEVICE_NULL;
 }
References XCAU10P_IDCODE, XCAU15P_IDCODE, XCAU20P_IDCODE, XCAU25P_IDCODE, XCK26_IDCODE, XCKU11P_IDCODE, XCKU13P_IDCODE, XCKU15P_IDCODE, XCKU19P_IDCODE, XCKU3P_IDCODE, XCKU5P_IDCODE, XCKU9P_IDCODE, XCU200_IDCODE, XCU250_IDCODE, XCU25_IDCODE, XCU26_IDCODE, XCU280_IDCODE, XCU30_IDCODE, XCU50_IDCODE, XCU55C_IDCODE, XCU55N_IDCODE, XCUX35_IDCODE, XCVU11P_IDCODE, XCVU13P_IDCODE, XCVU19P_IDCODE, XCVU23P_IDCODE, XCVU27P_IDCODE, XCVU29P_IDCODE, XCVU31P_IDCODE, XCVU33P_IDCODE, XCVU35P_IDCODE, XCVU37P_IDCODE, XCVU3P_IDCODE, XCVU45P_IDCODE, XCVU47P_IDCODE, XCVU57P_IDCODE, XCVU5P_IDCODE, XCVU7P_IDCODE, XCVU9P_IDCODE, XCZU11_IDCODE, XCZU15_IDCODE, XCZU17_IDCODE, XCZU19_IDCODE, XCZU1_IDCODE, XCZU21DR_IDCODE, XCZU25DR_IDCODE, XCZU27DR_IDCODE, XCZU28DR_IDCODE, XCZU29DR_IDCODE, XCZU2_IDCODE, XCZU39DR_IDCODE, XCZU3_IDCODE, XCZU42DR_IDCODE, XCZU43DR_IDCODE, XCZU46DR_IDCODE, XCZU47DR_IDCODE, XCZU48DR_IDCODE, XCZU49DR_IDCODE, XCZU4_IDCODE, XCZU5_IDCODE, XCZU65DR_IDCODE, XCZU67DR_IDCODE, XCZU6_IDCODE, XCZU7_IDCODE, XCZU9_IDCODE, XUSP_DEVICE_NULL, XUSP_DEVICE_XCAU10P, XUSP_DEVICE_XCAU15P, XUSP_DEVICE_XCAU20P, XUSP_DEVICE_XCAU25P, XUSP_DEVICE_XCK26, XUSP_DEVICE_XCKU11P, XUSP_DEVICE_XCKU13P, XUSP_DEVICE_XCKU15P, XUSP_DEVICE_XCKU19P, XUSP_DEVICE_XCKU3P, XUSP_DEVICE_XCKU5P, XUSP_DEVICE_XCKU9P, XUSP_DEVICE_XCU200, XUSP_DEVICE_XCU25, XUSP_DEVICE_XCU250, XUSP_DEVICE_XCU26, XUSP_DEVICE_XCU280, XUSP_DEVICE_XCU30, XUSP_DEVICE_XCU50, XUSP_DEVICE_XCU55C, XUSP_DEVICE_XCU55N, XUSP_DEVICE_XCUX35, XUSP_DEVICE_XCVU11P, XUSP_DEVICE_XCVU13P, XUSP_DEVICE_XCVU19P, XUSP_DEVICE_XCVU23P, XUSP_DEVICE_XCVU27P, XUSP_DEVICE_XCVU29P, XUSP_DEVICE_XCVU31P, XUSP_DEVICE_XCVU33P, XUSP_DEVICE_XCVU35P, XUSP_DEVICE_XCVU37P, XUSP_DEVICE_XCVU3P, XUSP_DEVICE_XCVU45P, XUSP_DEVICE_XCVU47P, XUSP_DEVICE_XCVU57P, XUSP_DEVICE_XCVU5P, XUSP_DEVICE_XCVU7P, XUSP_DEVICE_XCVU9P, XUSP_DEVICE_XCZU1, XUSP_DEVICE_XCZU11, XUSP_DEVICE_XCZU15, XUSP_DEVICE_XCZU17, XUSP_DEVICE_XCZU19, XUSP_DEVICE_XCZU2, XUSP_DEVICE_XCZU21DR, XUSP_DEVICE_XCZU25DR, XUSP_DEVICE_XCZU27DR, XUSP_DEVICE_XCZU28DR, XUSP_DEVICE_XCZU29DR, XUSP_DEVICE_XCZU3, XUSP_DEVICE_XCZU39DR, XUSP_DEVICE_XCZU4, XUSP_DEVICE_XCZU42DR, XUSP_DEVICE_XCZU43DR, XUSP_DEVICE_XCZU46DR, XUSP_DEVICE_XCZU47DR, XUSP_DEVICE_XCZU48DR, XUSP_DEVICE_XCZU49DR, XUSP_DEVICE_XCZU5, XUSP_DEVICE_XCZU6, XUSP_DEVICE_XCZU65DR, XUSP_DEVICE_XCZU67DR, XUSP_DEVICE_XCZU7, and XUSP_DEVICE_XCZU9.
getDeviceByIDCODEorThrow()
int XilinxUltraScalePlus::getDeviceByIDCODEorThrow (int IDCODE) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 28 of file XUSP_Devices.cpp.
 {
     int deviceID = getDeviceByIDCODE(IDCODE);
     if(deviceID == XUSP_DEVICE_NULL)
         throw runtime_error(string("Unknown device with IDCODE = ").append(to_string(IDCODE)).append(" . Maybe the device is not Xilinx US+ device?"));
     return deviceID;
 }
References Endian::to_string(), and XUSP_DEVICE_NULL.
getDeviceByName()
int XilinxUltraScalePlus::getDeviceByName (string name) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 213 of file XUSP_Devices.cpp.
 {
     name = str::removeSpaces(name);
     name = str::stringToLower(name);
     //US+ Artix
     #ifdef XUSPARTIX
         if(str::iff::stringContains(name, XCAU10P_NAME))
             return XUSP_DEVICE_XCAU10P;
         if(str::iff::stringContains(name, XCAU15P_NAME))
             return XUSP_DEVICE_XCAU15P;
         if(str::iff::stringContains(name, XCAU20P_NAME))
             return XUSP_DEVICE_XCAU20P;
         if(str::iff::stringContains(name, XCAU25P_NAME))
             return XUSP_DEVICE_XCAU25P;
     #endif
     //US+ Kintex
     #ifdef XUSPKINTEX
         if(str::iff::stringContains(name, XCKU3P_NAME,  "xqku3p"))
             return XUSP_DEVICE_XCKU3P;
         if(str::iff::stringContains(name, XCKU5P_NAME,  "xqku5p"))
             return XUSP_DEVICE_XCKU5P;
         if(str::iff::stringContains(name, XCKU9P_NAME,  "xqku9p"))
             return XUSP_DEVICE_XCKU9P;
         if(str::iff::stringContains(name, XCKU11P_NAME, "xqku11p"))
             return XUSP_DEVICE_XCKU11P;
         if(str::iff::stringContains(name, XCKU13P_NAME, "xqku13p"))
             return XUSP_DEVICE_XCKU13P;
         if(str::iff::stringContains(name, XCKU15P_NAME, "xqku15p"))
             return XUSP_DEVICE_XCKU15P;
         if(str::iff::stringContains(name, XCKU19P_NAME, "xqku19p"))
             return XUSP_DEVICE_XCKU19P;
     #endif
     //US+ Virtex
     #ifdef XUSPVIRTEX
         if(str::iff::stringContains(name, XCVU3P_NAME,  "xqvu3p"))
             return XUSP_DEVICE_XCVU3P;
         if(str::iff::stringContains(name, XCVU5P_NAME,  "xqvu5p"))
             return XUSP_DEVICE_XCVU5P;
         if(str::iff::stringContains(name, XCVU7P_NAME,  "xqvu7p"))
             return XUSP_DEVICE_XCVU7P;
         if(str::iff::stringContains(name, XCVU9P_NAME,  "xqvu9p"))
             return XUSP_DEVICE_XCVU9P;
         if(str::iff::stringContains(name, XCVU11P_NAME, "xqvu11p"))
             return XUSP_DEVICE_XCVU11P;
         if(str::iff::stringContains(name, XCVU13P_NAME, "xqvu13p"))
             return XUSP_DEVICE_XCVU13P;
         if(str::iff::stringContains(name, XCVU19P_NAME, "xqvu19p"))
             return XUSP_DEVICE_XCVU19P;
         if(str::iff::stringContains(name, XCVU23P_NAME, "xqvu23p"))
             return XUSP_DEVICE_XCVU23P;
         if(str::iff::stringContains(name, XCVU27P_NAME, "xqvu27p"))
             return XUSP_DEVICE_XCVU27P;
         if(str::iff::stringContains(name, XCVU29P_NAME, "xqvu29p"))
             return XUSP_DEVICE_XCVU29P;
         if(str::iff::stringContains(name, XCVU31P_NAME, "xqvu31p"))
             return XUSP_DEVICE_XCVU31P;
         if(str::iff::stringContains(name, XCVU33P_NAME, "xqvu33p"))
             return XUSP_DEVICE_XCVU33P;
         if(str::iff::stringContains(name, XCVU35P_NAME, "xqvu35p"))
             return XUSP_DEVICE_XCVU35P;
         if(str::iff::stringContains(name, XCVU37P_NAME, "xqvu37p"))
             return XUSP_DEVICE_XCVU37P;
         if(str::iff::stringContains(name, XCVU45P_NAME, "xqvu45p"))
             return XUSP_DEVICE_XCVU45P;
         if(str::iff::stringContains(name, XCVU47P_NAME, "xqvu47p"))
             return XUSP_DEVICE_XCVU47P;
         if(str::iff::stringContains(name, XCVU57P_NAME, "xqvu57p"))
             return XUSP_DEVICE_XCVU57P;
     #endif
     //US+ RFSoC (RFSOC BEFORE MPSOC, since names collide!)
     #ifdef XUSPZYNQRF
         if(str::iff::stringContains(name, XCZU21DR_NAME, "xqzu21dr"))
             return XUSP_DEVICE_XCZU21DR;
         if(str::iff::stringContains(name, XCZU25DR_NAME))
             return XUSP_DEVICE_XCZU25DR;
         if(str::iff::stringContains(name, XCZU27DR_NAME))
             return XUSP_DEVICE_XCZU27DR;
         if(str::iff::stringContains(name, XCZU28DR_NAME, "xqzu28dr"))
             return XUSP_DEVICE_XCZU28DR;
         if(str::iff::stringContains(name, XCZU29DR_NAME, "xqzu29dr"))
             return XUSP_DEVICE_XCZU29DR;
         if(str::iff::stringContains(name, XCZU39DR_NAME))
             return XUSP_DEVICE_XCZU39DR;
         if(str::iff::stringContains(name, XCZU42DR_NAME))
             return XUSP_DEVICE_XCZU42DR;
         if(str::iff::stringContains(name, XCZU43DR_NAME))
             return XUSP_DEVICE_XCZU43DR;
         if(str::iff::stringContains(name, XCZU46DR_NAME, "xqzu48dr", "xqzu49dr"))
             return XUSP_DEVICE_XCZU46DR; // Yes, this row is correct.
         if(str::iff::stringContains(name, XCZU47DR_NAME))
             return XUSP_DEVICE_XCZU47DR;
         if(str::iff::stringContains(name, XCZU48DR_NAME))
             return XUSP_DEVICE_XCZU48DR;
         if(str::iff::stringContains(name, XCZU49DR_NAME))
             return XUSP_DEVICE_XCZU49DR;
         if(str::iff::stringContains(name, XCZU65DR_NAME))
             return XUSP_DEVICE_XCZU65DR;
         if(str::iff::stringContains(name, XCZU67DR_NAME))
             return XUSP_DEVICE_XCZU67DR;
     #endif
     //US+ Zynq
     #ifdef XUSPZYNQMP
         if(str::iff::stringContains(name, XCZU2_NAME,  "xazu2",  "xqzu2"))
             return XUSP_DEVICE_XCZU2;
         if(str::iff::stringContains(name, XCZU3_NAME,  "xazu3",  "xqzu3"))
             return XUSP_DEVICE_XCZU3;
         if(str::iff::stringContains(name, XCZU4_NAME,  "xazu4",  "xqzu4"))
             return XUSP_DEVICE_XCZU4;
         if(str::iff::stringContains(name, XCZU5_NAME,  "xazu5",  "xqzu5"))
             return XUSP_DEVICE_XCZU5;
         if(str::iff::stringContains(name, XCZU6_NAME,  "xazu6",  "xqzu6"))
             return XUSP_DEVICE_XCZU6;
         if(str::iff::stringContains(name, XCZU7_NAME,  "xazu7",  "xqzu7"))
             return XUSP_DEVICE_XCZU7;
         if(str::iff::stringContains(name, XCZU9_NAME,  "xazu9",  "xqzu9"))
             return XUSP_DEVICE_XCZU9;
         if(str::iff::stringContains(name, XCZU11_NAME, "xazu11", "xqzu11"))
             return XUSP_DEVICE_XCZU11;
         if(str::iff::stringContains(name, XCZU15_NAME, "xazu15", "xqzu15"))
             return XUSP_DEVICE_XCZU15;
         if(str::iff::stringContains(name, XCZU17_NAME, "xazu17", "xqzu17"))
             return XUSP_DEVICE_XCZU17;
         if(str::iff::stringContains(name, XCZU19_NAME, "xazu19", "xqzu19"))
             return XUSP_DEVICE_XCZU19;
         if(str::iff::stringContains(name, XCZU1_NAME,  "xazu1",  "xqzu1"))
             return XUSP_DEVICE_XCZU1;
     #endif
     //Alveo rebranding
     #ifdef XUSPALVEO
         if(str::iff::stringContains(name, XCU200_NAME, "alveou200"))
             return XUSP_DEVICE_XCU200;
         if(str::iff::stringContains(name, XCU250_NAME, "alveou250"))
             return XUSP_DEVICE_XCU250;
         if(str::iff::stringContains(name, XCU26_NAME, "alveou26"))
             return XUSP_DEVICE_XCU26;
         if(str::iff::stringContains(name, XCUX35_NAME, "alveou35"))
             return XUSP_DEVICE_XCUX35;
         if(str::iff::stringContains(name, XCU50_NAME, "alveou50"))
             return XUSP_DEVICE_XCU50;
         if(str::iff::stringContains(name, XCU55N_NAME, "alveou55n"))
             return XUSP_DEVICE_XCU55N;
         if(str::iff::stringContains(name, XCU55C_NAME, "alveou55c"))
             return XUSP_DEVICE_XCU55C;
         if(str::iff::stringContains(name, XCU280_NAME, "alveou280"))
             return XUSP_DEVICE_XCU280;
         if(str::iff::stringContains(name, XCU30_NAME, "alveou30"))
             return XUSP_DEVICE_XCU30;
         if(str::iff::stringContains(name, XCU25_NAME, "alveou25"))
             return XUSP_DEVICE_XCU25;
         //Kria
         if(str::iff::stringContains(name, XCK26_NAME))
             return XUSP_DEVICE_XCK26;
         if(str::iff::stringContains(name, "k26c", "kria26c"))
             return XUSP_DEVICE_K26C;
         if(str::iff::stringContains(name, "k26i", "kria26i"))
             return XUSP_DEVICE_K26I;
         if(str::iff::stringContains(name, "kv260"))
             return XUSP_DEVICE_KV260;
     #endif
     //Some boards for easier use
     #ifdef XUSPBOARDS
         if(str::iff::stringContains(name, "zcu102", "zu-gmsl2"))
             return XUSP_DEVICE_ZCU102;
         if(str::iff::stringContains(name, "zcu104"))
             return XUSP_DEVICE_ZCU104;
         if(str::iff::stringContains(name, "zcu106"))
             return XUSP_DEVICE_ZCU106;
         if(str::iff::stringContains(name, "axu15eg"))
             return XUSP_DEVICE_AXU15EG;
         if(str::iff::stringContains(name, "axu2cg"))
             return XUSP_DEVICE_AXU2CG;
         if(str::iff::stringContains(name, "axu3eg"))
             return XUSP_DEVICE_AXU3EG;
         if(str::iff::stringContains(name, "axu4ev"))
             return XUSP_DEVICE_AXU4EV;
         if(str::iff::stringContains(name, "axu5ev"))
             return XUSP_DEVICE_AXU5EV;
         if(str::iff::stringContains(name, "axu9eg"))
             return XUSP_DEVICE_AXU9EG;
         if(str::iff::stringContains(name, "ultrazed-ev"))
             return XUSP_DEVICE_ULTRAZED_EV;
         if(str::iff::stringContains(name, "champ-xd1s"))
             return XUSP_DEVICE_CHAMP_XD1S;
         if(str::iff::stringContains(name, "zu-3eg"))
             return XUSP_DEVICE_ZU_3EG;
         if(str::iff::stringContains(name, "zu-5ev"))
             return XUSP_DEVICE_ZU_5EV;
         if(str::iff::stringContains(name, "htg-z999-06"))
             return XUSP_DEVICE_HTG_Z999_06;
         if(str::iff::stringContains(name, "htg-z999-09"))
             return XUSP_DEVICE_HTG_Z999_09;
         if(str::iff::stringContains(name, "htg-z999-15"))
             return XUSP_DEVICE_HTG_Z999_15;
         if(str::iff::stringContains(name, "htg-930-9-3"))
             return XUSP_DEVICE_HTG_930_9_3;
         if(str::iff::stringContains(name, "htg-930-9"))
             return XUSP_DEVICE_HTG_930_9;
         if(str::iff::stringContains(name, "htg-930-13-3"))
             return XUSP_DEVICE_HTG_930_13_3;
         if(str::iff::stringContains(name, "htg-930-13"))
             return XUSP_DEVICE_HTG_930_13;
         if(str::iff::stringContains(name, "htg-937-37p"))
             return XUSP_DEVICE_HTG_937_37P;
         if(str::iff::stringContains(name, "htg-937-47p"))
             return XUSP_DEVICE_HTG_937_47P;
         if(str::iff::stringContains(name, "htg-z922-11"))
             return XUSP_DEVICE_HTG_Z922_11;
         if(str::iff::stringContains(name, "htg-z922-19-dg"))
             return XUSP_DEVICE_HTG_Z922_19_DG;
         if(str::iff::stringContains(name, "htg-z922-19"))
             return XUSP_DEVICE_HTG_Z922_19;
         if(str::iff::stringContains(name, "czu3eg"))
             return XUSP_DEVICE_CZU3EG;
         if(str::iff::stringContains(name, "czu4ev"))
             return XUSP_DEVICE_CZU4EV;
         if(str::iff::stringContains(name, "te0802"))
             return XUSP_DEVICE_TE0802;
         if(str::iff::stringContains(name, "te0803-04-3be11"))
             return XUSP_DEVICE_TE0803_04_3BE11;
         if(str::iff::stringContains(name, "te0807-03-7de21"))
             return XUSP_DEVICE_TE0807_03_7DE21;
         if(str::iff::stringContains(name, "te0808-05-9be21"))
             return XUSP_DEVICE_TE0808_05_9BE21;
         if(str::iff::stringContains(name, "te0808-05-9gi21"))
             return XUSP_DEVICE_TE0808_05_9GI21;
         if(str::iff::stringContains(name, "te0808-05-bbe21"))
             return XUSP_DEVICE_TE0808_05_BBE21;
         if(str::iff::stringContains(name, "te0812"))
             return XUSP_DEVICE_TE0812;
         if(str::iff::stringContains(name, "teb0911"))
             return XUSP_DEVICE_TEB0911;
         if(str::iff::stringContains(name, "teb0912"))
             return XUSP_DEVICE_TEB0912;
         if(str::iff::stringContains(name, "tysom-3-zu7ev"))
             return XUSP_DEVICE_TYSOM_3_ZU7EV;
         if(str::iff::stringContains(name, "xpedite2600"))
             return XUSP_DEVICE_XPEDITE2600;
         if(str::iff::stringContains(name, "amc574"))
             return XUSP_DEVICE_AMC574;
         if(str::iff::stringContains(name, "zcu208"))
             return XUSP_DEVICE_ZCU208;
         if(str::iff::stringContains(name, "zcu216"))
             return XUSP_DEVICE_ZCU216;
         if(str::iff::stringContains(name, "zcu670"))
             return XUSP_DEVICE_ZCU670;
         if(str::iff::stringContains(name, "ultra96"))
             return XUSP_DEVICE_ULTRA96;
         if(str::iff::stringContains(name, "amc584"))
             return XUSP_DEVICE_AMC584;
         if(str::iff::stringContains(name, "htg-960"))
             return XUSP_DEVICE_HTG_960;
         if(str::iff::stringContains(name, "vcu1525"))
             return XUSP_DEVICE_VCU1525;
         if(str::iff::stringContains(name, "vcu118"))
             return XUSP_DEVICE_VCU118;
         if(str::iff::stringContains(name, "vcu128"))
             return XUSP_DEVICE_VCU128;
         if(str::iff::stringContains(name, "vcu129"))
             return XUSP_DEVICE_VCU129;
         if(str::iff::stringContains(name, "htg-940-9-3"))
             return XUSP_DEVICE_HTG_940_9_3;
         if(str::iff::stringContains(name, "htg-940-9"))
             return XUSP_DEVICE_HTG_940_9;
         if(str::iff::stringContains(name, "htg-940-13-3"))
             return XUSP_DEVICE_HTG_940_13_3;
         if(str::iff::stringContains(name, "htg-940-13"))
             return XUSP_DEVICE_HTG_940_13;
         if(str::iff::stringContains(name, "htg-9200-5p"))
             return XUSP_DEVICE_HTG_9200_5P;
         if(str::iff::stringContains(name, "htg-9200-9p"))
             return XUSP_DEVICE_HTG_9200_9P;
         if(str::iff::stringContains(name, "htg-9200-13p"))
             return XUSP_DEVICE_HTG_9200_13P;
         if(str::iff::stringContains(name, "htg-vup-pcie-hh-9p", "htg-910-9"))
             return XUSP_DEVICE_HTG_VUP_PCIE_HH_9P;
         if(str::iff::stringContains(name, "htg-vup-pcie-hh-13p", "htg-910-13"))
             return XUSP_DEVICE_HTG_VUP_PCIE_HH_13P;
         if(str::iff::stringContains(name, "htg-zrf-fmc-28"))
             return XUSP_DEVICE_HTG_ZRF_FMC_28;
         if(str::iff::stringContains(name, "htg-zrf-fmc-48"))
             return XUSP_DEVICE_HTG_ZRF_FMC_48;
         if(str::iff::stringContains(name, "htg-zrf16-29"))
             return XUSP_DEVICE_HTG_ZRF16_29;
         if(str::iff::stringContains(name, "htg-zrf16-49"))
             return XUSP_DEVICE_HTG_ZRF16_49;
         if(str::iff::stringContains(name, "htg-zrf-hh-28"))
             return XUSP_DEVICE_HTG_ZRF_HH_28;
         if(str::iff::stringContains(name, "htg-zrf-hh-48"))
             return XUSP_DEVICE_HTG_ZRF_HH_48;
         if(str::iff::stringContains(name, "htg-zusp-pcie-11-3"))
             return XUSP_DEVICE_HTG_ZUSP_PCIE_11_3;
         if(str::iff::stringContains(name, "htg-zusp-pcie-19-2"))
             return XUSP_DEVICE_HTG_ZUSP_PCIE_19_2;
         if(str::iff::stringContains(name, "htg-zrf8-r2-28", "htg-zrf8-28"))
             return XUSP_DEVICE_HTG_ZRF8_R2_28;
         if(str::iff::stringContains(name, "htg-zrf8-r2-48-I", "htg-zrf8-48-i"))
             return XUSP_DEVICE_HTG_ZRF8_R2_48_I;
         if(str::iff::stringContains(name, "htg-zrf8-r2-48", "htg-zrf8-48"))
             return XUSP_DEVICE_HTG_ZRF8_R2_48;
         if(str::iff::stringContains(name, "zuboard1cg"))
             return XUSP_DEVICE_ZUBOARD_1CG;
         if(str::iff::stringContains(name, "kcu116"))
             return XUSP_DEVICE_KCU116;
         if(str::iff::stringContains(name, "vermeot1mp"))
             return XUSP_DEVICE_VERMEO_T1_MP;
         if(str::iff::stringContains(name, "vermeot1rf"))
             return XUSP_DEVICE_VERMEO_T1_RF;
         if(str::iff::stringContains(name, "zcu1275"))
             return XUSP_DEVICE_ZCU1275;
         if(str::iff::stringContains(name, "zcu1285"))
             return XUSP_DEVICE_ZCU1285;
         if(str::iff::stringContains(name, "zcu111"))
             return XUSP_DEVICE_ZCU111;
         if(str::iff::stringContains(name, "genesyszu-5ev", "genesyszu5ev", "genesys-5ev", "genesys5ev"))
             return XUSP_DEVICE_GENESYS_5EV;
         if(str::iff::stringContains(name, "genesyszu-3eg", "genesyszu3eg", "genesys-3eg", "genesys3eg"))
             return XUSP_DEVICE_GENESYS_3EG;
     #endif
     return XUSP_DEVICE_NULL;
 }
References str::removeSpaces(), str::iff::stringContains(), str::stringToLower(), XCAU10P_NAME, XCAU15P_NAME, XCAU20P_NAME, XCAU25P_NAME, XCK26_NAME, XCKU11P_NAME, XCKU13P_NAME, XCKU15P_NAME, XCKU19P_NAME, XCKU3P_NAME, XCKU5P_NAME, XCKU9P_NAME, XCU200_NAME, XCU250_NAME, XCU25_NAME, XCU26_NAME, XCU280_NAME, XCU30_NAME, XCU50_NAME, XCU55C_NAME, XCU55N_NAME, XCUX35_NAME, XCVU11P_NAME, XCVU13P_NAME, XCVU19P_NAME, XCVU23P_NAME, XCVU27P_NAME, XCVU29P_NAME, XCVU31P_NAME, XCVU33P_NAME, XCVU35P_NAME, XCVU37P_NAME, XCVU3P_NAME, XCVU45P_NAME, XCVU47P_NAME, XCVU57P_NAME, XCVU5P_NAME, XCVU7P_NAME, XCVU9P_NAME, XCZU11_NAME, XCZU15_NAME, XCZU17_NAME, XCZU19_NAME, XCZU1_NAME, XCZU21DR_NAME, XCZU25DR_NAME, XCZU27DR_NAME, XCZU28DR_NAME, XCZU29DR_NAME, XCZU2_NAME, XCZU39DR_NAME, XCZU3_NAME, XCZU42DR_NAME, XCZU43DR_NAME, XCZU46DR_NAME, XCZU47DR_NAME, XCZU48DR_NAME, XCZU49DR_NAME, XCZU4_NAME, XCZU5_NAME, XCZU65DR_NAME, XCZU67DR_NAME, XCZU6_NAME, XCZU7_NAME, XCZU9_NAME, XUSP_DEVICE_AMC574, XUSP_DEVICE_AMC584, XUSP_DEVICE_AXU15EG, XUSP_DEVICE_AXU2CG, XUSP_DEVICE_AXU3EG, XUSP_DEVICE_AXU4EV, XUSP_DEVICE_AXU5EV, XUSP_DEVICE_AXU9EG, XUSP_DEVICE_CHAMP_XD1S, XUSP_DEVICE_CZU3EG, XUSP_DEVICE_CZU4EV, XUSP_DEVICE_GENESYS_3EG, XUSP_DEVICE_GENESYS_5EV, XUSP_DEVICE_HTG_9200_13P, XUSP_DEVICE_HTG_9200_5P, XUSP_DEVICE_HTG_9200_9P, XUSP_DEVICE_HTG_930_13, XUSP_DEVICE_HTG_930_13_3, XUSP_DEVICE_HTG_930_9, XUSP_DEVICE_HTG_930_9_3, XUSP_DEVICE_HTG_937_37P, XUSP_DEVICE_HTG_937_47P, XUSP_DEVICE_HTG_940_13, XUSP_DEVICE_HTG_940_13_3, XUSP_DEVICE_HTG_940_9, XUSP_DEVICE_HTG_940_9_3, XUSP_DEVICE_HTG_960, XUSP_DEVICE_HTG_VUP_PCIE_HH_13P, XUSP_DEVICE_HTG_VUP_PCIE_HH_9P, XUSP_DEVICE_HTG_Z922_11, XUSP_DEVICE_HTG_Z922_19, XUSP_DEVICE_HTG_Z922_19_DG, XUSP_DEVICE_HTG_Z999_06, XUSP_DEVICE_HTG_Z999_09, XUSP_DEVICE_HTG_Z999_15, XUSP_DEVICE_HTG_ZRF16_29, XUSP_DEVICE_HTG_ZRF16_49, XUSP_DEVICE_HTG_ZRF8_R2_28, XUSP_DEVICE_HTG_ZRF8_R2_48, XUSP_DEVICE_HTG_ZRF8_R2_48_I, XUSP_DEVICE_HTG_ZRF_FMC_28, XUSP_DEVICE_HTG_ZRF_FMC_48, XUSP_DEVICE_HTG_ZRF_HH_28, XUSP_DEVICE_HTG_ZRF_HH_48, XUSP_DEVICE_HTG_ZUSP_PCIE_11_3, XUSP_DEVICE_HTG_ZUSP_PCIE_19_2, XUSP_DEVICE_K26C, XUSP_DEVICE_K26I, XUSP_DEVICE_KCU116, XUSP_DEVICE_KV260, XUSP_DEVICE_NULL, XUSP_DEVICE_TE0802, XUSP_DEVICE_TE0803_04_3BE11, XUSP_DEVICE_TE0807_03_7DE21, XUSP_DEVICE_TE0808_05_9BE21, XUSP_DEVICE_TE0808_05_9GI21, XUSP_DEVICE_TE0808_05_BBE21, XUSP_DEVICE_TE0812, XUSP_DEVICE_TEB0911, XUSP_DEVICE_TEB0912, XUSP_DEVICE_TYSOM_3_ZU7EV, XUSP_DEVICE_ULTRA96, XUSP_DEVICE_ULTRAZED_EV, XUSP_DEVICE_VCU118, XUSP_DEVICE_VCU128, XUSP_DEVICE_VCU129, XUSP_DEVICE_VCU1525, XUSP_DEVICE_VERMEO_T1_MP, XUSP_DEVICE_VERMEO_T1_RF, XUSP_DEVICE_XCAU10P, XUSP_DEVICE_XCAU15P, XUSP_DEVICE_XCAU20P, XUSP_DEVICE_XCAU25P, XUSP_DEVICE_XCK26, XUSP_DEVICE_XCKU11P, XUSP_DEVICE_XCKU13P, XUSP_DEVICE_XCKU15P, XUSP_DEVICE_XCKU19P, XUSP_DEVICE_XCKU3P, XUSP_DEVICE_XCKU5P, XUSP_DEVICE_XCKU9P, XUSP_DEVICE_XCU200, XUSP_DEVICE_XCU25, XUSP_DEVICE_XCU250, XUSP_DEVICE_XCU26, XUSP_DEVICE_XCU280, XUSP_DEVICE_XCU30, XUSP_DEVICE_XCU50, XUSP_DEVICE_XCU55C, XUSP_DEVICE_XCU55N, XUSP_DEVICE_XCUX35, XUSP_DEVICE_XCVU11P, XUSP_DEVICE_XCVU13P, XUSP_DEVICE_XCVU19P, XUSP_DEVICE_XCVU23P, XUSP_DEVICE_XCVU27P, XUSP_DEVICE_XCVU29P, XUSP_DEVICE_XCVU31P, XUSP_DEVICE_XCVU33P, XUSP_DEVICE_XCVU35P, XUSP_DEVICE_XCVU37P, XUSP_DEVICE_XCVU3P, XUSP_DEVICE_XCVU45P, XUSP_DEVICE_XCVU47P, XUSP_DEVICE_XCVU57P, XUSP_DEVICE_XCVU5P, XUSP_DEVICE_XCVU7P, XUSP_DEVICE_XCVU9P, XUSP_DEVICE_XCZU1, XUSP_DEVICE_XCZU11, XUSP_DEVICE_XCZU15, XUSP_DEVICE_XCZU17, XUSP_DEVICE_XCZU19, XUSP_DEVICE_XCZU2, XUSP_DEVICE_XCZU21DR, XUSP_DEVICE_XCZU25DR, XUSP_DEVICE_XCZU27DR, XUSP_DEVICE_XCZU28DR, XUSP_DEVICE_XCZU29DR, XUSP_DEVICE_XCZU3, XUSP_DEVICE_XCZU39DR, XUSP_DEVICE_XCZU4, XUSP_DEVICE_XCZU42DR, XUSP_DEVICE_XCZU43DR, XUSP_DEVICE_XCZU46DR, XUSP_DEVICE_XCZU47DR, XUSP_DEVICE_XCZU48DR, XUSP_DEVICE_XCZU49DR, XUSP_DEVICE_XCZU5, XUSP_DEVICE_XCZU6, XUSP_DEVICE_XCZU65DR, XUSP_DEVICE_XCZU67DR, XUSP_DEVICE_XCZU7, XUSP_DEVICE_XCZU9, XUSP_DEVICE_XPEDITE2600, XUSP_DEVICE_ZCU102, XUSP_DEVICE_ZCU104, XUSP_DEVICE_ZCU106, XUSP_DEVICE_ZCU111, XUSP_DEVICE_ZCU1275, XUSP_DEVICE_ZCU1285, XUSP_DEVICE_ZCU208, XUSP_DEVICE_ZCU216, XUSP_DEVICE_ZCU670, XUSP_DEVICE_ZU_3EG, XUSP_DEVICE_ZU_5EV, and XUSP_DEVICE_ZUBOARD_1CG.
getDeviceByNameOrThrow()
int XilinxUltraScalePlus::getDeviceByNameOrThrow (string name) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 36 of file XUSP_Devices.cpp.
 {
     int deviceID = getDeviceByName(name);
     if(deviceID == XUSP_DEVICE_NULL)
         throw runtime_error(string("Unknown device: ").append(name).append(". Maybe the device is not Xilinx US+ device?"));
     return deviceID;
 }
References XUSP_DEVICE_NULL.
getFrameType()
string XilinxUltraScalePlus::getFrameType (int blockType, int rowAddress, int columnAddress) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 117 of file XilinxUltraScalePlus.cpp.
{
     if(XUSP_BLOCKTYPE_BLOCKRAM == blockType)
         return "BlockRAM Contents";
     else if(XUSP_BLOCKTYPE_LOGIC == blockType)
         return LUT_typeOfFrameForResourceLetter[(uint8_t)resourceString[rowAddress][columnAddress]];
     else
         return "Unknown";
 }
References XUSP_BLOCKTYPE_BLOCKRAM, and XUSP_BLOCKTYPE_LOGIC.
initFabric()
void XilinxUltraScalePlus::initFabric ()
Definition at line 22 of file XUSP_Fabric.cpp.
{
     setFabricChar(char(0), 0, "EndedLine", true);
     setFabricChar(char(1), XUSP_EXTRA_FRAMES_PER_ROW, "EndOfLine", true);
     //The Xilinx US+ fabric in byteman is encoded in the following letters:
     //A-C are brams
     setFabricChar('A',  6, "BRAM/RCLK_BRAM_INTF_L");               //"BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL/RCLK_BRAM_INTF_L"
     setFabricChar('B',  6, "BRAM/RCLK_BRAM_INTF_TD_L");            //"BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL/RCLK_BRAM_INTF_TD_L"
     setFabricChar('C',  6, "BRAM/RCLK_BRAM_INTF_TD_R");            //"BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL+BRAM+NULL+NULL+NULL+NULL/RCLK_BRAM_INTF_TD_R"
     //D is URAM
     setFabricChar('D',  9, "URAM");                                //"URAM_URAM_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+URAM_URAM_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+URAM_URAM_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+URAM_URAM_DELAY_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_RCLK_URAM_INTF_L_FT"
     //E-I are DSPs with diff clock resources
     setFabricChar('E',  8, "DSP/RCLK_DSP_INTF_L");                 //"DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL/RCLK_DSP_INTF_L"
     setFabricChar('F',  8, "DSP/RCLK_DSP_INTF_CLKBUF_L");          //"DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL/RCLK_DSP_INTF_CLKBUF_L"
     setFabricChar('G',  8, "DSP/RCLK_DSP_INTF_R");                 //"DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL/RCLK_DSP_INTF_R"
     setFabricChar('H',  8, "DSP/RCLK_RCLK_DSP_INTF_DC12_L_FT");    //"DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL/RCLK_RCLK_DSP_INTF_DC12_L_FT"
     setFabricChar('I',  8, "DSP/RCLK_RCLK_DSP_INTF_DC12_R_FT");    //"DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL/RCLK_RCLK_DSP_INTF_DC12_R_FT"
     //J-K are switchmatrixes with diff clock resources
     setFabricChar('J', 76, "INT/RCLK_INT_L");                      //"INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT/RCLK_INT_L"
     setFabricChar('K', 76, "INT/RCLK_INT_R");                      //"INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT+INT/RCLK_INT_R"
     //L-N are CLEM with diff clock resources
     setFabricChar('L', 16, "CLEM/RCLK_CLEM_L");                    //"CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM/RCLK_CLEM_L";
     setFabricChar('M', 16, "CLEM/RCLK_CLEM_CLKBUF_L");             //"CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM/RCLK_CLEM_CLKBUF_L";
     setFabricChar('N', 16, "CLEM/RCLK_CLEM_DMC_L");                //"CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM+CLEM/RCLK_CLEM_DMC_L";
     //O is CLEM_R
     setFabricChar('O', 16, "CLEM_R");                              //"CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R+CLEM_R/RCLK_CLEM_R"
     //P-R are CLEL_R with diff clock resources
     setFabricChar('P', 16, "CLEL_R/RCLK_CLEL_R_L");                //"CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R/RCLK_CLEL_R_L";
     setFabricChar('Q', 16, "CLEL_R/RCLK_CLEL_R_R");                //"CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R/RCLK_CLEL_R_R";
     setFabricChar('R', 16, "CLEL_R/RCLK_CLEL_R_DCG10_R");          //"CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R+CLEL_R/RCLK_CLEL_R_DCG10_R"
     //S-T are CLEL_L with diff clock resources
     setFabricChar('S', 16, "CLEL_L/RCLK_CLEL_L_L");                //"CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L/RCLK_CLEL_L_L"
     setFabricChar('T', 16, "CLEL_L/RCLK_CLEL_L_R");                //"CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L+CLEL_L/RCLK_CLEL_L_R"
     //X-Z are lagunas with diff clock resources
     setFabricChar('X', 16, "LAG_LAG/RCLK_LAG_L");                  //"LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG/RCLK_LAG_L"
     setFabricChar('Y', 16, "LAG_LAG/RCLK_LAG_R");                  //"LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG/RCLK_LAG_R"
     setFabricChar('Z', 16, "LAG_LAG/RCLK_LAG_DMC_L");              //"LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG+LAG_LAG/RCLK_LAG_DMC_L"
     //a-d, f-z, U-W, "_!@#$%^&*-+=:;()[]{}<" are I/O and misc
     setFabricChar('a',  8, "HPIO_L");                                                       //"HPIO_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+HPIO_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_HPIO_L"
     setFabricChar('b',  4, "XIPHY_BYTE_L");                                                 //"XIPHY_BYTE_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+XIPHY_BYTE_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+XIPHY_BYTE_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+XIPHY_BYTE_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_RCLK_XIPHY_INNER_FT"
     setFabricChar('c', 12, "CMT_L");                                                        //"CMT_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('d',  4, "INT_INTF_LEFT_TERM_IO_FT");                                     //"INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT+INT_INTF_LEFT_TERM_IO_FT/RCLK_RCLK_INTF_LEFT_TERM_IO_FT"
     setFabricChar('f',  4, "INT_INTF_R_PCIE4");                                             //"INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4+INT_INTF_R_PCIE4/RCLK_INTF_R_IBRK_L"
     setFabricChar('g', 10, "HDIO_BOT_RIGHT");                                               //"HDIO_BOT_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+HDIO_TOP_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_HDIO"
     setFabricChar('h',  4, "INT_INTF_L_PCIE4/RCLK_INTF_L_IBRK_PCIE4_L");                    //"INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4/RCLK_INTF_L_IBRK_PCIE4_L"
     setFabricChar('i', 10, "PCIE4C_PCIE4C_FT");                                             //"PCIE4C_PCIE4C_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('j',  4, "INT_INTF_L_PCIE4/RCLK_INTF_L_IBRK_PCIE4_R");                    //"INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4/RCLK_INTF_L_IBRK_PCIE4_R"
     setFabricChar('k',  4, "INT_INTF_R_TERM_GT/RCLK_INTF_R_TERM_GT");                       //"INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT/RCLK_INTF_R_TERM_GT"
     setFabricChar('l',  8, "GTH_QUAD_RIGHT");                                               //"GTH_QUAD_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('m', 10, "CFG_CONFIG");                                                   //"CFG_CONFIG+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('n', 10, "CFGIO_IOB20");                                                  //"CFGIO_IOB20+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+AMS+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_AMS_CFGIO"
     setFabricChar('o', 10, "PCIE4_PCIE4_FT");                                               //"PCIE4_PCIE4_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('p',  8, "GTY_R");                                                        //"GTY_R+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('q', 10, "CMAC");                                                         //"CMAC+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('r', 16, "INT_INTF_LEFT_TERM_PSS/RCLK_INTF_LEFT_TERM_DA7");               //"INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS/RCLK_INTF_LEFT_TERM_DA7"
     setFabricChar('t',  4, "INT_INTF_RIGHT_TERM_IO");                                       //"INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO+INT_INTF_RIGHT_TERM_IO/RCLK_INTF_RIGHT_TERM_IO"
     setFabricChar('u', 12, "CMT_RIGHT");                                                    //"CMT_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('v',  4, "XIPHY_BYTE_RIGHT");                                             //"XIPHY_BYTE_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+XIPHY_BYTE_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+XIPHY_BYTE_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+XIPHY_BYTE_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_XIPHY_OUTER_RIGHT"
     setFabricChar('w',  8, "HPIO_RIGHT");                                                   //"HPIO_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+HPIO_RIGHT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/RCLK_HPIO_R"
     setFabricChar('x',  8, "GTH_QUAD_LEFT");                                                //"GTH_QUAD_LEFT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('y',  4, "INT_INTF_L_TERM_GT");                                           //"INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT+INT_INTF_L_TERM_GT/RCLK_INTF_L_TERM_GT"
     setFabricChar('z',  4, "INT_INTF_R_TERM_GT/RCLK_INTF_RIGHT_TERM_GT_IO");                //"INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT+INT_INTF_R_TERM_GT/RCLK_INTF_RIGHT_TERM_GT_IO"
     setFabricChar('U',  8, "GTY_L");                                                        //"GTY_L+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('V', 10, "ILKN_ILKN_FT");                                                 //"ILKN_ILKN_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('W',  8, "GTM_DUAL_RIGHT_FT");                                            //"GTM_DUAL_RIGHT_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('_',  8, "GTM_DUAL_LEFT_FT");                                             //"GTM_DUAL_LEFT_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('!',  8, "BLI_BLI_FT");                                                   //"BLI_BLI_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL+DSP+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('@', 12, "CMT_LEFT_H");                                                   //"CMT_LEFT_H+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('#', 16, "INT_INTF_LEFT_TERM_PSS/RCLK_INTF_LEFT_TERM_ALTO");              //"INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS/RCLK_INTF_LEFT_TERM_ALTO"
     setFabricChar('$', 16, "INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_DA6_FT");       //"INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_DA6_FT"
     setFabricChar('%', 16, "INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_DA8_FT");       //"INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_DA8_FT"
     setFabricChar('^',  4, "INT_INTF_L_CMT");                                               //"INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_CMT+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_IO+INT_INTF_L_CMT+INT_INTF_L_CMT/RCLK_INTF_L_IBRK_IO_L"
     setFabricChar('&', 16, "INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_DC12_FT");      //"INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_DC12_FT"
     setFabricChar('*',  2, "FE_FE_FT");                                                     //"FE_FE_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('-',  4, "INT_INTF_L_PCIE4/RCLK_RCLK_INTF_LEFT_IBRK_FE_L_FT");            //"INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4/RCLK_RCLK_INTF_LEFT_IBRK_FE_L_FT"
     setFabricChar('+',  8, "HSADC_HSADC_RIGHT_FT");                                         //"HSADC_HSADC_RIGHT_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('=',  8, "HSDAC_HSDAC_RIGHT_FT");                                         //"HSDAC_HSDAC_RIGHT_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar(':',  8, "RFADC_RFADC_RIGHT_FT");                                         //"RFADC_RFADC_RIGHT_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar(';',  8, "RFDAC_RFDAC_RIGHT_FT");                                         //"RFDAC_RFDAC_RIGHT_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('.', 16, "INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_MX8_FT");       //"INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS+INT_INTF_LEFT_TERM_PSS/RCLK_RCLK_INTF_LEFT_TERM_MX8_FT"
     setFabricChar(',',  4, "INT_INTF_L_PCIE4/RCLK_RCLK_INTF_LEFT_IBRK_MX8_L_FT");           //"INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4+INT_INTF_L_PCIE4/RCLK_RCLK_INTF_LEFT_IBRK_MX8_L_FT"
     setFabricChar('(', 10, "DFE_DFE_TILEB_FT");            //"DFE_DFE_TILEB_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar(')',  2, "DFE_DFE_TILEC_FT");            //"DFE_DFE_TILEC_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('[',  2, "DFE_DFE_TILED_FT");            //"DFE_DFE_TILED_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar(']', 10, "DFE_DFE_TILEE_FT");            //"DFE_DFE_TILEE_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('{', 10, "DFE_DFE_TILEG_FT");            //"DFE_DFE_TILEG_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('}',  2, "DFE_DFE_TILEF_FT");            //"DFE_DFE_TILEF_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     setFabricChar('<', 10, "DFE_DFE_TILEA_FT");            //"DFE_DFE_TILEA_FT+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL+NULL/NULL"
     //Also in the fabric exist frames that are mapped in bitstreams, but do not physically exist on the device. We encode these as follows:
     setFabricChar('0', 4,  "EMPTY4",  true);
     setFabricChar('1', 6,  "EMPTY6",  true); //and 256 empty frames in block type 1
     setFabricChar('2', 8,  "EMPTY8",  true);
     setFabricChar('3', 9,  "EMPTY9",  true);
     setFabricChar('4', 10, "EMPTY10", true);
     setFabricChar('5', 12, "EMPTY12", true);
     setFabricChar('6', 16, "EMPTY16", true);
     setFabricChar('7', 76, "EMPTY76", true);
     setFabricChar('8', 2,  "EMPTY2",  true);
 }
References setFabricChar(), and XUSP_EXTRA_FRAMES_PER_ROW.
initializeResourceStringParameters()
void XilinxUltraScalePlus::initializeResourceStringParameters () override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 40 of file XilinxUltraScalePlus.cpp.
{
     if(initializedResourceStringShortPartName == "")
         throw runtime_error("The target device needs to be known, before you can manipulate any bitstream!");
     if(initializedBitstreamParamsShortPartName != initializedResourceStringShortPartName){//The device is changed
         initializedBitstreamParamsShortPartName = initializedResourceStringShortPartName;
         for((numberOfCols[0] = 0, numberOfFramesBeforeCol[0][0] = 0, numberOfBRAMCols[0] = 0) ; resourceString[0][numberOfCols[0]] != '\0' ; numberOfCols[0]++){
             numberOfFramesBeforeCol[0][numberOfCols[0]+1] = numberOfFramesBeforeCol[0][numberOfCols[0]] + LUT_numberOfFramesForResourceLetter[(uint8_t)resourceString[0][numberOfCols[0]]];
             numberOfBRAMsBeforeCol[0][numberOfCols[0]] = numberOfBRAMCols[0];
             if(str::iff::charIs(resourceString[0][numberOfCols[0]], 'A', 'B', 'C', '1')) //A-C are BlockRAM columns, '1' is empty blockram column
                 numberOfBRAMCols[0]++;
         }
         for(int c = numberOfCols[0] + 1 ; c < XUSP_MAX_COLS ; c++){
             numberOfFramesBeforeCol[0][c] = numberOfFramesBeforeCol[0][c - 1];
         }
         for(int c = numberOfCols[0] ; c < XUSP_MAX_COLS ; c++){
             numberOfBRAMsBeforeCol[0][c] = numberOfBRAMsBeforeCol[0][c - 1];
         }
         numberOfFramesPerRow[0] = numberOfFramesBeforeCol[0][numberOfCols[0]+1];
         numberOfWordsPerRow[0] = numberOfFramesPerRow[0] * XUSP_WORDS_PER_FRAME;
         maxNumberOfCols = numberOfCols[0];
         maxNumberOfBRAMCols = numberOfBRAMCols[0];
         for(int r = 1 ; r < numberOfRows ; r++){
             numberOfBRAMCols[r] = numberOfBRAMCols[0];
             numberOfCols[r] = numberOfCols[0];
             numberOfFramesPerRow[r] = numberOfFramesPerRow[0];
             numberOfWordsPerRow[r] = numberOfWordsPerRow[0];
             for(int c = 0 ; c < XUSP_MAX_COLS ; c++){
                 numberOfFramesBeforeCol[r][c] = numberOfFramesBeforeCol[0][c];
             }
             for(int c = 0 ; c < XUSP_MAX_COLS ; c++){
                 numberOfBRAMsBeforeCol[r][c]  = numberOfBRAMsBeforeCol[0][c];
             }
         }
     }
 }
References str::iff::charIs(), XUSP_MAX_COLS, and XUSP_WORDS_PER_FRAME.
merge()
void XilinxUltraScalePlus::merge (XilinxUltraScalePlus * srcBitstream, string params, Rect2D src, Coord2D dst)
Definition at line 24 of file XUSP_Merge.cpp.
{
     log("Merging bitstreams.");
     //This function uses a pointer to the second XUSP instance, but this pointer should get optimized as it is statically provided in the main function
     parseParams(params);
     if(!selectedOptions.partialNotFull){
         log("Merging the whole FPGA");
         src.position = {0, 0};
         dst = {0, 0};
         src.size.row = numberOfRows * XUSP_CLB_PER_CLOCK_REGION;
         src.size.col = maxNumberOfCols;
     }
     ensureRegionCompatibility(src, dst);
     if(src.position.row%XUSP_CLB_PER_CLOCK_REGION != 0)
         throw runtime_error(string("Currently only full clock region height relocations are supported (use row numbers multiple of ").append(to_string(XUSP_CLB_PER_CLOCK_REGION)).append(")."));
     if(src.size.row%XUSP_CLB_PER_CLOCK_REGION != 0)
         throw runtime_error(string("Currently only full clock region height relocations are supported (use row numbers multiple of ").append(to_string(XUSP_CLB_PER_CLOCK_REGION)).append(")."));
     if(dst.row%XUSP_CLB_PER_CLOCK_REGION != 0)
         throw runtime_error(string("Currently only full clock region height relocations are supported (use row numbers multiple of ").append(to_string(XUSP_CLB_PER_CLOCK_REGION)).append(")."));
     Endianness endianDifference = Endian::diff(loadedBitstreamEndianness, srcBitstream->loadedBitstreamEndianness);
     if((Endianness::NATIVE == endianDifference) && MergeOP::SET == selectedOptions.op)
         fastMerge(srcBitstream, src, dst);
     else
         flexiMerge(srcBitstream, endianDifference, src, dst);
     log("Merging bitstreams complete.");
 }
References Coord2D::col, Endian::diff(), ensureRegionCompatibility(), fastMerge(), flexiMerge(), XilinxConfigurationAccessPort< MAX_SLRS, MAX_ROWS, MAX_COLS, MAX_BRAM_COLS, BLOCKTYPE_MAX, BLOCKTYPE_LOGIC, BLOCKTYPE_BLOCKRAM, WORDS_BEFORE_CLK, WORDS_AT_CLK, WORDS_AFTER_CLK, WORDS_PER_FRAME, FRAMES_PER_BRAM_CONTENT_COLUMN, CLB_PER_CLOCK_REGION, BRAM_PER_CLOCK_REGION, EXTRA_FRAMES_PER_ROW, FAR_ENABLE_TOP_BOTTOM_BIT, FAR_TOP_BOTTOM_BIT_SHIFT, FAR_BLOCKTYPE_SHIFT, FAR_BLOCKTYPE_MASK, FAR_ROWADDRESS_SHIFT, FAR_ROWADDRESS_MASK, FAR_COLUMNADDRESS_SHIFT, FAR_COLUMNADDRESS_MASK, FAR_MINORADDRESS_SHIFT, FAR_MINORADDRESS_MASK >::loadedBitstreamEndianness, NATIVE, parseParams(), Rect2D::position, Coord2D::row, Rect2D::size, Endian::to_string(), and XUSP_CLB_PER_CLOCK_REGION.
outputBitstreamEmptySLRHeaderSequence()
void XilinxUltraScalePlus::outputBitstreamEmptySLRHeaderSequence (ofstream & fout, int slr, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 101 of file XUSP_Output.cpp.
 {
     XCAP_writeNOP(fout, 132, 0, e);
     //Optional Shutdown + 1 NOP ?
     XCAP_writeCommand(fout, XCAP::Command::RCRC, e);
     XCAP_writeNOP(fout, 2, 0, e);
     XCAP_writeRegister(fout, XCAP::Register::IDCODE, SLRinfo[slr].IDCODE, e);
     XCAP_writeCommand(fout, XCAP::Command::NULLCMD, e);
     if((slr + 1) < numberOfSLRs) { // If there are more SLRs, output the magic
         XCAP_writeSelectRegister(fout, XCAP::Register::MAGIC1, e);
         slrMagicInstrLocation[slr] = fout.tellp();
         XCAP_writeType2(fout, 0, e);
     }
 }
References XCAP::IDCODE, XCAP::MAGIC1, XCAP::NULLCMD, XCAP::RCRC, XCAP_writeCommand(), XCAP_writeNOP(), XCAP_writeRegister(), XCAP_writeSelectRegister(), and XCAP_writeType2().
outputBitstreamEmptySLRWrapUpSequence()
void XilinxUltraScalePlus::outputBitstreamEmptySLRWrapUpSequence (ofstream & fout, int slr, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 116 of file XUSP_Output.cpp.
 {
     streamoff currentStreamHead = fout.tellp();
     streamoff bypassSize = (currentStreamHead - slrMagicInstrLocation[slr])/4 - 1;
     fout.seekp(slrMagicInstrLocation[slr]);
     FileIO::write32(fout, static_cast<uint32_t>(bypassSize), e);
     fout.seekp(currentStreamHead);
     XCAP_writeNOP(fout, 16, 0, loadedBitstreamEndianness);
     XCAP_writeCommand(fout, XCAP::Command::START, loadedBitstreamEndianness);
     XCAP_writeNOP(fout, 1, 0, loadedBitstreamEndianness);
     XCAP_writeCommand(fout, XCAP::Command::DESYNC, loadedBitstreamEndianness);
     XCAP_writeNOP(fout, 16, 0, loadedBitstreamEndianness);
 }
References XCAP::DESYNC, XCAP::START, FileIO::write32(), XCAP_writeCommand(), and XCAP_writeNOP().
outputBitstreamGlobalFooterSequence()
void XilinxUltraScalePlus::outputBitstreamGlobalFooterSequence (ofstream & fout, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 33 of file XUSP_Output.cpp.
 {
     XCAP_writeNOP(fout, 400, 0, loadedBitstreamEndianness);
 }
References XCAP_writeNOP().
outputBitstreamGlobalHeaderSequence()
void XilinxUltraScalePlus::outputBitstreamGlobalHeaderSequence (ofstream & fout, bool fullBitstream, Endianness e) override virtual
Written by outputBitstreamSLRHeaderAfterBitstreamSequence(), outputBitstreamEmptySLRHeaderSequence() and used by outputBitstreamSLRWrapUpSequence(), outputBitstreamEmptySLRWrapUpSequence()
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 29 of file XUSP_Output.cpp.
 {
 }
outputBitstreamSLRFooterBitstreamSequence()
void XilinxUltraScalePlus::outputBitstreamSLRFooterBitstreamSequence (ofstream & fout, int slr, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 49 of file XUSP_Output.cpp.
 {
     if(fullBitstream) // Add GRESTORE since it is full device bitstream.
     {
         XCAP_writeCommand(fout, XCAP::Command::GRESTORE, e);
         XCAP_writeNOP(fout, 1, 0, e);
     }
     XCAP_writeNOP(fout, 1, 0, e);
     uint32_t ctrl0 = XCAP_getCTRL0value(0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
     XCAP_writeMaskAndRegister(fout, XCAP::Register::CTRL0, ctrl0, ctrl0, e);
     XCAP_writeCommand(fout, XCAP::Command::DGHIGH, e);
     XCAP_writeNOP(fout, 20, 0, e);
     XCAP_writeCommand(fout, XCAP::Command::START, e);
     XCAP_writeNOP(fout, 1, 0, e);
     XCAP_writeRegister(fout, XCAP::Register::FAR, XCAP_getFarFarInstruction(), e);
     XCAP_writeNOP(fout, 1, 0, e);
     XCAP_writeCommand(fout, XCAP::Command::RCRC, e);
     XCAP_writeNOP(fout, 1, 0, e);
     XCAP_writeCommand(fout, XCAP::Command::DESYNC, e);
     XCAP_writeNOP(fout, 16, 0, e);
 }
References XCAP::CTRL0, XCAP::DESYNC, XCAP::DGHIGH, XCAP::FAR, XCAP::GRESTORE, XCAP::RCRC, XCAP::START, XCAP_getCTRL0value(), XCAP_getFarFarInstruction(), XCAP_writeCommand(), XCAP_writeMaskAndRegister(), XCAP_writeNOP(), and XCAP_writeRegister().
outputBitstreamSLRHeaderAfterBitstreamSequence()
void XilinxUltraScalePlus::outputBitstreamSLRHeaderAfterBitstreamSequence (ofstream & fout, int slr, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 74 of file XUSP_Output.cpp.
 {
     if((slr + 1) < numberOfSLRs) { // If there are more SLRs, output the magic
         XCAP_writeNOP(fout, 400, 0, e);
         XCAP_writeSYNQ(fout, e);
         XCAP_writeNOP(fout, 1, 0, e);
         XCAP_writeCommand(fout, XCAP::Command::RCRC, e);
         XCAP_writeNOP(fout, 2, 0, e);
         XCAP_writeSelectRegister(fout, XCAP::Register::MAGIC1, e);
         slrMagicInstrLocation[slr] = fout.tellp();
         XCAP_writeType2(fout, 0, e);
     }
 }
References XCAP::MAGIC1, XCAP::RCRC, XCAP_writeCommand(), XCAP_writeNOP(), XCAP_writeSelectRegister(), XCAP_writeSYNQ(), and XCAP_writeType2().
outputBitstreamSLRHeaderBitstreamSequence()
void XilinxUltraScalePlus::outputBitstreamSLRHeaderBitstreamSequence (ofstream & fout, int slr, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 37 of file XUSP_Output.cpp.
 {
     XCAP_writeNOP(fout, 132, 0, e);
     //Optional Shutdown + 1 NOP ?
     XCAP_writeCommand(fout, XCAP::Command::RCRC, e);
     XCAP_writeNOP(fout, 2, 0, e);
     XCAP_writeRegister(fout, XCAP::Register::IDCODE, SLRinfo[slr].IDCODE, e);
     XCAP_writeCommand(fout, XCAP::Command::NULLCMD, e);
     uint32_t ctrl0 = XCAP_getCTRL0value(0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0); //disable fallback bitstream, enable overwriting of LUTs
     XCAP_writeMaskAndRegister(fout, XCAP::Register::CTRL0, ctrl0, ctrl0, e);
     XCAP_writeMaskAndRegister(fout, XCAP::Register::CTRL1, 0x20000, 0, e);
 }
References XCAP::CTRL0, XCAP::CTRL1, XCAP::IDCODE, XCAP::NULLCMD, XCAP::RCRC, XCAP_getCTRL0value(), XCAP_writeCommand(), XCAP_writeMaskAndRegister(), XCAP_writeNOP(), and XCAP_writeRegister().
outputBitstreamSLRWrapUpSequence()
void XilinxUltraScalePlus::outputBitstreamSLRWrapUpSequence (ofstream & fout, int slr, bool fullBitstream, Endianness e) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 88 of file XUSP_Output.cpp.
 {
     streamoff currentStreamHead = fout.tellp();
     streamoff bypassSize = (currentStreamHead - slrMagicInstrLocation[slr])/4 - 1;
     fout.seekp(slrMagicInstrLocation[slr]);
     FileIO::write32(fout, static_cast<uint32_t>(bypassSize), e);
     fout.seekp(currentStreamHead);
     XCAP_writeNOP(fout, 16, 0, loadedBitstreamEndianness);
     XCAP_writeCommand(fout, XCAP::Command::START, loadedBitstreamEndianness);
     XCAP_writeNOP(fout, 1, 0, loadedBitstreamEndianness);
     XCAP_writeCommand(fout, XCAP::Command::DESYNC, loadedBitstreamEndianness);
     XCAP_writeNOP(fout, 16, 0, loadedBitstreamEndianness);
 }
References XCAP::DESYNC, XCAP::START, FileIO::write32(), XCAP_writeCommand(), and XCAP_writeNOP().
readBitstream()
void XilinxUltraScalePlus::readBitstream (string filename)
Definition at line 30 of file XUSP_Input.cpp.
 {
     ifstream fin (filename, ifstream::binary);
     if(!fin.good())
         throw runtime_error(string("Could not open file: \"").append(filename).append("\" .\n"));
     log("Reading Xilinx UltraScale+ bitstream from file \"" + filename + "\"");
     loadedBitstreamEndianness = parseBitstreamEndianness(fin);
     if(str::iff::stringEndsWith(filename, ".bit"))
         readBitstreamBIT(fin);
     else if(str::iff::stringEndsWith(filename, ".bin"))
         readBitstreamBIN(fin);
     else
         throw runtime_error(string("Unknown Xilinx UltraScale+ file format tried to be read.\n"));
     fin.close();
     log("Xilinx UltraScale+ bitstream file \"" + filename + "\" read successfully.");
 }
References parseBitstreamEndianness(), readBitstreamBIN(), readBitstreamBIT(), and str::iff::stringEndsWith().
setDevice()
void XilinxUltraScalePlus::setDevice (int deviceID, string customPartName = "") override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 543 of file XUSP_Devices.cpp.
 {
     clearResourceStringArrays();
     bool customNameSet = false;
     #define setCustomPartName(x) {customNameSet = true; partName = x;}
     switch(deviceID){
         //XUSP Artix
         #ifdef XUSPARTIX
         case XUSP_DEVICE_XCAU10P:
             XCAU10P();
             break;
         case XUSP_DEVICE_XCAU15P:
             XCAU15P();
             break;
         case XUSP_DEVICE_XCAU20P:
             XCAU20P();
             break;
         case XUSP_DEVICE_XCAU25P:
             XCAU25P();
             break;
         #endif
         //XUSP Kintex
         #ifdef XUSPKINTEX
         case XUSP_DEVICE_XCKU3P:
             XCKU3P();
             break;
         case XUSP_DEVICE_XCKU5P:
             XCKU5P();
             break;
         case XUSP_DEVICE_XCKU9P:
             XCKU9P();
             break;
         case XUSP_DEVICE_XCKU11P:
             XCKU11P();
             break;
         case XUSP_DEVICE_XCKU13P:
             XCKU13P();
             break;
         case XUSP_DEVICE_XCKU15P:
             XCKU15P();
             break;
         case XUSP_DEVICE_XCKU19P:
             XCKU19P();
             break;
         #endif
         //XUSP Virtex
         #ifdef XUSPVIRTEX
         case XUSP_DEVICE_XCVU3P:
             XCVU3P();
             break;
         case XUSP_DEVICE_XCVU5P:
             XCVU5P();
             break;
         case XUSP_DEVICE_XCVU7P:
             XCVU7P();
             break;
         case XUSP_DEVICE_XCVU9P:
             XCVU9P();
             break;
         case XUSP_DEVICE_XCVU11P:
             XCVU11P();
             break;
         case XUSP_DEVICE_XCVU13P:
             XCVU13P();
             break;
         case XUSP_DEVICE_XCVU19P:
             XCVU19P();
             break;
         case XUSP_DEVICE_XCVU23P:
             XCVU23P();
             break;
         case XUSP_DEVICE_XCVU27P:
             XCVU27P();
             break;
         case XUSP_DEVICE_XCVU29P:
             XCVU29P();
             break;
         case XUSP_DEVICE_XCVU31P:
             XCVU31P();
             break;
         case XUSP_DEVICE_XCVU33P:
             XCVU33P();
             break;
         case XUSP_DEVICE_XCVU35P:
             XCVU35P();
             break;
         case XUSP_DEVICE_XCVU37P:
             XCVU37P();
             break;
         case XUSP_DEVICE_XCVU45P:
             XCVU45P();
             break;
         case XUSP_DEVICE_XCVU47P:
             XCVU47P();
             break;
         case XUSP_DEVICE_XCVU57P:
             XCVU57P();
             break;
         #endif
         //XUSP RFSoC
         #ifdef XUSPZYNQRF
         case XUSP_DEVICE_XCZU21DR:
             XCZU21DR();
             break;
         case XUSP_DEVICE_XCZU25DR:
             XCZU25DR();
             break;
         case XUSP_DEVICE_XCZU27DR:
             XCZU27DR();
             break;
         case XUSP_DEVICE_XCZU28DR:
             XCZU28DR();
             break;
         case XUSP_DEVICE_XCZU29DR:
             XCZU29DR();
             break;
         case XUSP_DEVICE_XCZU39DR:
             XCZU39DR();
             break;
         case XUSP_DEVICE_XCZU42DR:
             XCZU42DR();
             break;
         case XUSP_DEVICE_XCZU43DR:
             XCZU43DR();
             break;
         case XUSP_DEVICE_XCZU46DR:
             XCZU46DR();
             break;
         case XUSP_DEVICE_XCZU47DR:
             XCZU47DR();
             break;
         case XUSP_DEVICE_XCZU48DR:
             XCZU48DR();
             break;
         case XUSP_DEVICE_XCZU49DR:
             XCZU49DR();
             break;
         case XUSP_DEVICE_XCZU65DR:
             XCZU65DR();
             break;
         case XUSP_DEVICE_XCZU67DR:
             XCZU67DR();
             break;
         #endif
         //XUSP MPSoC
         #ifdef XUSPZYNQMP
         case XUSP_DEVICE_XCZU1:
             XCZU1();
             break;
         case XUSP_DEVICE_XCZU2:
             XCZU2();
             break;
         case XUSP_DEVICE_XCZU3:
             XCZU3();
             break;
         case XUSP_DEVICE_XCZU4:
             XCZU4();
             break;
         case XUSP_DEVICE_XCZU5:
             XCZU5();
             break;
         case XUSP_DEVICE_XCZU6:
             XCZU6();
             break;
         case XUSP_DEVICE_XCZU7:
             XCZU7();
             break;
         case XUSP_DEVICE_XCZU9:
             XCZU9();
             break;
         case XUSP_DEVICE_XCZU11:
             XCZU11();
             break;
         case XUSP_DEVICE_XCZU15:
             XCZU15();
             break;
         case XUSP_DEVICE_XCZU17:
             XCZU17();
             break;
         case XUSP_DEVICE_XCZU19:
             XCZU19();
             break;
         #endif
         //XUSP Alveo
         #ifdef XUSPALVEO
         case XUSP_DEVICE_XCU200:
             XCU200();
             setCustomPartName("xcu200-fsgd2104-2-e");
             break;
         case XUSP_DEVICE_XCU250:
             XCU250();
             setCustomPartName("xcu250-figd2104-2l-e");
             break;
         case XUSP_DEVICE_XCU26:
             XCU26();
             setCustomPartName("xcu26-l2vsva1365e");
             break;
         case XUSP_DEVICE_XCUX35:
             XCUX35();
             break;
         case XUSP_DEVICE_XCU50:
             XCU50();
             setCustomPartName("xcu50-fsvh2104-2lv-e");
             break;
         case XUSP_DEVICE_XCU55N:
             XCU55N();
             break;
         case XUSP_DEVICE_XCU55C:
             XCU55C();
             setCustomPartName("xcu55c-l2fsvh2892e");
             break;
         case XUSP_DEVICE_XCU280:
             XCU280();
             break;
         case XUSP_DEVICE_XCU30:
             XCU30();
             break;
         case XUSP_DEVICE_XCU25:
             XCU25();
             break;
         //Kria
         case XUSP_DEVICE_XCK26:
             XCK26();
             break;
         case XUSP_DEVICE_K26C:
             XCK26();
             setCustomPartName("xck26-sfvc784-2lv-c");
             break;
         case XUSP_DEVICE_K26I:
             XCK26();
             setCustomPartName("xck26-sfvc784-2lv-i");
             break;
         case XUSP_DEVICE_KV260:
             XCK26();
             setCustomPartName("xck26-sfvc784-2lv-c");
             break;
         #endif
         //XUSP Boards
         #ifdef XUSPBOARDS
         case XUSP_DEVICE_ZCU102:
             XCZU9();
             setCustomPartName("xczu9eg-2ffvb1156");
             break;
         case XUSP_DEVICE_ZCU104:
             XCZU7();
             setCustomPartName("xczu7ev-2ffvc1156");
             break;
         case XUSP_DEVICE_ZCU106:
             XCZU7();
             setCustomPartName("xczu7ev-2ffvc1156");
             break;
         case XUSP_DEVICE_AXU15EG:
             XCZU15();
             setCustomPartName("xczu15eg-2sffvb1156i");
             break;
         case XUSP_DEVICE_AXU2CG:
             XCZU2();
             setCustomPartName("xczu2cg-1sfvc784e");
             break;
         case XUSP_DEVICE_AXU3EG:
             XCZU3();
             setCustomPartName("xczu3eg-1sfvc784i");
             break;
         case XUSP_DEVICE_AXU4EV:
             XCZU4();
             setCustomPartName("xczu4ev-1sfvc784i");
             break;
         case XUSP_DEVICE_AXU5EV:
             XCZU5();
             setCustomPartName("xczu5ev-2sfvc784i");
             break;
         case XUSP_DEVICE_AXU9EG:
             XCZU9();
             setCustomPartName("xczu9eg-2ffvb1156i");
             break;
         case XUSP_DEVICE_ULTRAZED_EV:
             XCZU7();
             setCustomPartName("xczu7ev-fbvb900");
             break;
         case XUSP_DEVICE_CHAMP_XD1S:
             XCZU4();
             break;
         case XUSP_DEVICE_ZU_3EG:
             XCZU3();
             setCustomPartName("xczu3eg-sfvc784-1-e");
             break;
         case XUSP_DEVICE_ZU_5EV:
             XCZU5();
             setCustomPartName("xczu5ev-sfvc784-1-e");
             break;
         case XUSP_DEVICE_HTG_Z999_06:
             XCZU6();
             setCustomPartName("xczu6eg-2ffvb1156e");
             break;
         case XUSP_DEVICE_HTG_Z999_09:
             XCZU9();
             setCustomPartName("xczu9eg-2ffvb1156e");
             break;
         case XUSP_DEVICE_HTG_Z999_15:
             XCZU15();
             setCustomPartName("xczu15eg-2ffvb1156e");
             break;
         case XUSP_DEVICE_HTG_930_9_3:
             XCVU9P();
             setCustomPartName("xcvu9p-3flgb2104e");
             break;
         case XUSP_DEVICE_HTG_930_9:
             XCVU9P();
             setCustomPartName("xcvu9p-2flgb2104e");
             break;
         case XUSP_DEVICE_HTG_930_13_3:
             XCVU13P();
             setCustomPartName("xcvu13p-3fhgb2104e");
             break;
         case XUSP_DEVICE_HTG_930_13:
             XCVU13P();
             setCustomPartName("xcvu13p-2fhgb2104e");
             break;
         case XUSP_DEVICE_HTG_937_37P:
             XCVU37P();
             setCustomPartName("xcvu37p-2fsvh2892e4539");
             break;
         case XUSP_DEVICE_HTG_937_47P:
             XCVU47P();
             setCustomPartName("xcvu47p-2fsvh2892e4539");
             break;
         case XUSP_DEVICE_HTG_Z922_11:
             XCZU11();
             setCustomPartName("xczu11eg-3ffvc1760e");
             break;
         case XUSP_DEVICE_HTG_Z922_19_DG:
             XCZU19();
             setCustomPartName("xqzu19eg-2ffvc1760e");
             break;
         case XUSP_DEVICE_HTG_Z922_19:
             XCZU19();
             setCustomPartName("xczu19eg-2ffvc1760e");
             break;
         case XUSP_DEVICE_CZU3EG:
             XCZU3();
             setCustomPartName("xczu3eg-1sfvc784e");
             break;
         case XUSP_DEVICE_CZU4EV:
             XCZU4();
             setCustomPartName("xczu3eg-1sfvc784e");
             break;
         case XUSP_DEVICE_TE0802:
             XCZU2();
             setCustomPartName("xczu2cg-1sbva484e");
             break;
         case XUSP_DEVICE_TE0803_04_3BE11:
             XCZU3();
             setCustomPartName("xczu3eg-1sfvc784e");
             break;
         case XUSP_DEVICE_TE0807_03_7DE21:
             XCZU7();
             setCustomPartName("xczu7ev-1fbvb900e");
             break;
         case XUSP_DEVICE_TE0808_05_9BE21:
             XCZU9();
             setCustomPartName("xczu9eg-1ffvc900e");
             break;
         case XUSP_DEVICE_TE0808_05_9GI21:
             XCZU9();
             setCustomPartName("xczu9eg-2ffvc900i");
             break;
         case XUSP_DEVICE_TE0808_05_BBE21:
             XCZU15();
             setCustomPartName("xczu15eg-1ffvc900e");
             break;
         case XUSP_DEVICE_TE0812:
             XCZU6();
             setCustomPartName("xczu6eg-1ffvc900i");
             break;
         case XUSP_DEVICE_TEB0911:
             XCZU9();
             setCustomPartName("xczu9eg-1ffvb1156e");
             break;
         case XUSP_DEVICE_TEB0912:
             XCZU11();
             setCustomPartName("xczu11eg-1ffvc1760i");
             break;
         case XUSP_DEVICE_TYSOM_3_ZU7EV:
             XCZU7();
             setCustomPartName("zu7ev-ffvc1156");
             break;
         case XUSP_DEVICE_XPEDITE2600:
             XCZU11();
             setCustomPartName("xczu11eg");
             break;
         case XUSP_DEVICE_AMC574:
             XCZU29DR();
             setCustomPartName("xczu29dr");
             break;
         case XUSP_DEVICE_ZCU208:
             XCZU48DR();
             setCustomPartName("xczu48dr-2fsvg1517e5184");
             break;
         case XUSP_DEVICE_ZCU216:
             XCZU49DR();
             setCustomPartName("xczu49dr-2ffvf1760");
             break;
         case XUSP_DEVICE_ZCU670:
             XCZU67DR();
             setCustomPartName("xczu67dr-2fsve1156i");
             break;
         case XUSP_DEVICE_ULTRA96:
             XCZU3();
             setCustomPartName("xczu3eg-sbva484-1-i");
             break;
         case XUSP_DEVICE_AMC584:
             XCVU13P();
             break;
         case XUSP_DEVICE_HTG_960:
             XCVU19P();
             setCustomPartName("xcvu19p-2fsvb3824e");
             break;
         case XUSP_DEVICE_VCU1525:
             XCVU9P();
             setCustomPartName("xcvu9p-l2fsgd2104e");
             break;
         case XUSP_DEVICE_VCU118:
             XCVU9P();
             setCustomPartName("xcvu9p-lga2104e");
             break;
         case XUSP_DEVICE_VCU128:
             XCVU37P();
             setCustomPartName("xcvu37p-l2fsvh2892e");
             break;
         case XUSP_DEVICE_VCU129:
             XCVU29P();
             setCustomPartName("xcvu29p-l2fsga2577e");
             break;
         case XUSP_DEVICE_HTG_940_9_3:
             XCVU9P();
             setCustomPartName("xcvu9p-3flgb2104e");
             break;
         case XUSP_DEVICE_HTG_940_9:
             XCVU9P();
             setCustomPartName("xcvu9p-2flgb2104e");
             break;
         case XUSP_DEVICE_HTG_940_13_3:
             XCVU13P();
             setCustomPartName("xcvu13p-3fhgb2104e");
             break;
         case XUSP_DEVICE_HTG_940_13:
             XCVU13P();
             setCustomPartName("xcvu13p-2fhgb2104e");
             break;
         case XUSP_DEVICE_HTG_9200_5P:
             XCVU5P();
             setCustomPartName("xcvu5p-2flgb2104e");
             break;
         case XUSP_DEVICE_HTG_9200_9P:
             XCVU9P();
             setCustomPartName("xcvu9p-2flgb2104e");
             break;
         case XUSP_DEVICE_HTG_9200_13P:
             XCVU13P();
             setCustomPartName("xcvu13p-2fhgb2104e");
             break;
         case XUSP_DEVICE_HTG_VUP_PCIE_HH_9P:
             XCVU9P();
             setCustomPartName("xcvu9p-2flgb2104e");
             break;
         case XUSP_DEVICE_HTG_VUP_PCIE_HH_13P:
             XCVU13P();
             setCustomPartName("xcvu13p-2fhgb2104e");
             break;
         case XUSP_DEVICE_HTG_ZRF_FMC_28:
             XCZU28DR();
             setCustomPartName("xczu28dr-2ffvg1517");
             break;
         case XUSP_DEVICE_HTG_ZRF_FMC_48:
             XCZU48DR();
             setCustomPartName("xczu48dr-2ffvg1517");
             break;
         case XUSP_DEVICE_HTG_ZRF16_29:
             XCZU29DR();
             setCustomPartName("xczu29dr-2ffvf1760e");
             break;
         case XUSP_DEVICE_HTG_ZRF16_49:
             XCZU49DR();
             setCustomPartName("xczu49dr-2ffvf1760e");
             break;
         case XUSP_DEVICE_HTG_ZRF_HH_28:
             XCZU28DR();
             setCustomPartName("xczu28dr-2ffvg1517");
             break;
         case XUSP_DEVICE_HTG_ZRF_HH_48:
             XCZU48DR();
             setCustomPartName("xczu48dr-2ffvg1517");
             break;
         case XUSP_DEVICE_HTG_ZUSP_PCIE_11_3:
             XCZU11();
             setCustomPartName("xczu11eg-3ffvc1760e");
             break;
         case XUSP_DEVICE_HTG_ZUSP_PCIE_19_2:
             XCZU19();
             setCustomPartName("xczu19eg-2ffvc1760e");
             break;
         case XUSP_DEVICE_HTG_ZRF8_R2_28:
             XCZU28DR();
             setCustomPartName("xczu28dr-2ffvg1517");
             break;
         case XUSP_DEVICE_HTG_ZRF8_R2_48_I:
             XCZU48DR();
             setCustomPartName("xczu48dr-ffvg1517-2-i");
             break;
         case XUSP_DEVICE_HTG_ZRF8_R2_48:
             XCZU48DR();
             setCustomPartName("xczu48dr-2ffvg1517");
             break;
         case XUSP_DEVICE_ZUBOARD_1CG:
             XCZU1();
             break;
         case XUSP_DEVICE_KCU116:
             XCKU5P();
             setCustomPartName("xcku5p-ffvb676-2-e");
             break;
         case XUSP_DEVICE_VERMEO_T1_MP:
             XCZU19();
             setCustomPartName("xczu19eg-ffvd1760-2L-e");
             break;
         case XUSP_DEVICE_VERMEO_T1_RF:
             XCZU21DR();
             setCustomPartName("xczu21dr-ffvd1156-2L-e");
             break;
         case XUSP_DEVICE_ZCU1275:
             XCZU29DR();
             setCustomPartName("xczu29dr-ffvf1760-2-e");
             break;
         case XUSP_DEVICE_ZCU1285:
             XCZU39DR();
             setCustomPartName("xczu39dr-ffvf1760-2-i");
             break;
         case XUSP_DEVICE_ZCU111:
             XCZU28DR();
             setCustomPartName("xczu28dr-ffvg1517-2-e");
             break;
         case XUSP_DEVICE_GENESYS_5EV:
             XCZU5();
             setCustomPartName("xczu5ev-sfvc784-1-e");
             break;
         case XUSP_DEVICE_GENESYS_3EG:
             XCZU3();
             setCustomPartName("xczu3eg-sfvc784-1-e");
             break;
         #endif
         default:throw runtime_error("Unknown device ID.");
     }
     #undef setCustomPartName
     if(!customNameSet) // if we didn't set already a good full name
         if(customPartName != "")// if not empty string
             partName = customPartName;
     log("Initialized device resource string for \"" + initializedResourceStringShortPartName + "\"");
 }
References clearResourceStringArrays(), XCAU10P, XCAU15P, XCAU20P, XCAU25P, XCK26, XCKU11P, XCKU13P, XCKU15P, XCKU19P, XCKU3P, XCKU5P, XCKU9P, XCU200, XCU25, XCU250, XCU26, XCU280, XCU30, XCU50, XCU55C, XCU55N, XCUX35, XCVU11P, XCVU13P, XCVU19P, XCVU23P, XCVU27P, XCVU29P, XCVU31P, XCVU33P, XCVU35P, XCVU37P, XCVU3P, XCVU45P, XCVU47P, XCVU57P, XCVU5P, XCVU7P, XCVU9P, XCZU1, XCZU11, XCZU15, XCZU17, XCZU19, XCZU2, XCZU21DR, XCZU25DR, XCZU27DR, XCZU28DR, XCZU29DR, XCZU3, XCZU39DR, XCZU4, XCZU42DR, XCZU43DR, XCZU46DR, XCZU47DR, XCZU48DR, XCZU49DR, XCZU5, XCZU6, XCZU65DR, XCZU67DR, XCZU7, XCZU9, XUSP_DEVICE_AMC574, XUSP_DEVICE_AMC584, XUSP_DEVICE_AXU15EG, XUSP_DEVICE_AXU2CG, XUSP_DEVICE_AXU3EG, XUSP_DEVICE_AXU4EV, XUSP_DEVICE_AXU5EV, XUSP_DEVICE_AXU9EG, XUSP_DEVICE_CHAMP_XD1S, XUSP_DEVICE_CZU3EG, XUSP_DEVICE_CZU4EV, XUSP_DEVICE_GENESYS_3EG, XUSP_DEVICE_GENESYS_5EV, XUSP_DEVICE_HTG_9200_13P, XUSP_DEVICE_HTG_9200_5P, XUSP_DEVICE_HTG_9200_9P, XUSP_DEVICE_HTG_930_13, XUSP_DEVICE_HTG_930_13_3, XUSP_DEVICE_HTG_930_9, XUSP_DEVICE_HTG_930_9_3, XUSP_DEVICE_HTG_937_37P, XUSP_DEVICE_HTG_937_47P, XUSP_DEVICE_HTG_940_13, XUSP_DEVICE_HTG_940_13_3, XUSP_DEVICE_HTG_940_9, XUSP_DEVICE_HTG_940_9_3, XUSP_DEVICE_HTG_960, XUSP_DEVICE_HTG_VUP_PCIE_HH_13P, XUSP_DEVICE_HTG_VUP_PCIE_HH_9P, XUSP_DEVICE_HTG_Z922_11, XUSP_DEVICE_HTG_Z922_19, XUSP_DEVICE_HTG_Z922_19_DG, XUSP_DEVICE_HTG_Z999_06, XUSP_DEVICE_HTG_Z999_09, XUSP_DEVICE_HTG_Z999_15, XUSP_DEVICE_HTG_ZRF16_29, XUSP_DEVICE_HTG_ZRF16_49, XUSP_DEVICE_HTG_ZRF8_R2_28, XUSP_DEVICE_HTG_ZRF8_R2_48, XUSP_DEVICE_HTG_ZRF8_R2_48_I, XUSP_DEVICE_HTG_ZRF_FMC_28, XUSP_DEVICE_HTG_ZRF_FMC_48, XUSP_DEVICE_HTG_ZRF_HH_28, XUSP_DEVICE_HTG_ZRF_HH_48, XUSP_DEVICE_HTG_ZUSP_PCIE_11_3, XUSP_DEVICE_HTG_ZUSP_PCIE_19_2, XUSP_DEVICE_K26C, XUSP_DEVICE_K26I, XUSP_DEVICE_KCU116, XUSP_DEVICE_KV260, XUSP_DEVICE_TE0802, XUSP_DEVICE_TE0803_04_3BE11, XUSP_DEVICE_TE0807_03_7DE21, XUSP_DEVICE_TE0808_05_9BE21, XUSP_DEVICE_TE0808_05_9GI21, XUSP_DEVICE_TE0808_05_BBE21, XUSP_DEVICE_TE0812, XUSP_DEVICE_TEB0911, XUSP_DEVICE_TEB0912, XUSP_DEVICE_TYSOM_3_ZU7EV, XUSP_DEVICE_ULTRA96, XUSP_DEVICE_ULTRAZED_EV, XUSP_DEVICE_VCU118, XUSP_DEVICE_VCU128, XUSP_DEVICE_VCU129, XUSP_DEVICE_VCU1525, XUSP_DEVICE_VERMEO_T1_MP, XUSP_DEVICE_VERMEO_T1_RF, XUSP_DEVICE_XCAU10P, XUSP_DEVICE_XCAU15P, XUSP_DEVICE_XCAU20P, XUSP_DEVICE_XCAU25P, XUSP_DEVICE_XCK26, XUSP_DEVICE_XCKU11P, XUSP_DEVICE_XCKU13P, XUSP_DEVICE_XCKU15P, XUSP_DEVICE_XCKU19P, XUSP_DEVICE_XCKU3P, XUSP_DEVICE_XCKU5P, XUSP_DEVICE_XCKU9P, XUSP_DEVICE_XCU200, XUSP_DEVICE_XCU25, XUSP_DEVICE_XCU250, XUSP_DEVICE_XCU26, XUSP_DEVICE_XCU280, XUSP_DEVICE_XCU30, XUSP_DEVICE_XCU50, XUSP_DEVICE_XCU55C, XUSP_DEVICE_XCU55N, XUSP_DEVICE_XCUX35, XUSP_DEVICE_XCVU11P, XUSP_DEVICE_XCVU13P, XUSP_DEVICE_XCVU19P, XUSP_DEVICE_XCVU23P, XUSP_DEVICE_XCVU27P, XUSP_DEVICE_XCVU29P, XUSP_DEVICE_XCVU31P, XUSP_DEVICE_XCVU33P, XUSP_DEVICE_XCVU35P, XUSP_DEVICE_XCVU37P, XUSP_DEVICE_XCVU3P, XUSP_DEVICE_XCVU45P, XUSP_DEVICE_XCVU47P, XUSP_DEVICE_XCVU57P, XUSP_DEVICE_XCVU5P, XUSP_DEVICE_XCVU7P, XUSP_DEVICE_XCVU9P, XUSP_DEVICE_XCZU1, XUSP_DEVICE_XCZU11, XUSP_DEVICE_XCZU15, XUSP_DEVICE_XCZU17, XUSP_DEVICE_XCZU19, XUSP_DEVICE_XCZU2, XUSP_DEVICE_XCZU21DR, XUSP_DEVICE_XCZU25DR, XUSP_DEVICE_XCZU27DR, XUSP_DEVICE_XCZU28DR, XUSP_DEVICE_XCZU29DR, XUSP_DEVICE_XCZU3, XUSP_DEVICE_XCZU39DR, XUSP_DEVICE_XCZU4, XUSP_DEVICE_XCZU42DR, XUSP_DEVICE_XCZU43DR, XUSP_DEVICE_XCZU46DR, XUSP_DEVICE_XCZU47DR, XUSP_DEVICE_XCZU48DR, XUSP_DEVICE_XCZU49DR, XUSP_DEVICE_XCZU5, XUSP_DEVICE_XCZU6, XUSP_DEVICE_XCZU65DR, XUSP_DEVICE_XCZU67DR, XUSP_DEVICE_XCZU7, XUSP_DEVICE_XCZU9, XUSP_DEVICE_XPEDITE2600, XUSP_DEVICE_ZCU102, XUSP_DEVICE_ZCU104, XUSP_DEVICE_ZCU106, XUSP_DEVICE_ZCU111, XUSP_DEVICE_ZCU1275, XUSP_DEVICE_ZCU1285, XUSP_DEVICE_ZCU208, XUSP_DEVICE_ZCU216, XUSP_DEVICE_ZCU670, XUSP_DEVICE_ZU_3EG, XUSP_DEVICE_ZU_5EV, and XUSP_DEVICE_ZUBOARD_1CG.
setDeviceByIDCODEOrThrow()
void XilinxUltraScalePlus::setDeviceByIDCODEOrThrow (int idcode) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 53 of file XUSP_Devices.cpp.
{
     int deviceID = getDeviceByIDCODEorThrow(idcode);
     setDevice(deviceID);
 }
setDeviceByNameOrThrow()
void XilinxUltraScalePlus::setDeviceByNameOrThrow (string name) override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 48 of file XUSP_Devices.cpp.
{
     int deviceID = getDeviceByNameOrThrow(name);
     setDevice(deviceID, name);
 }
setDeviceByPartNameOrThrow()
void XilinxUltraScalePlus::setDeviceByPartNameOrThrow () override virtual
Implements XilinxConfigurationAccessPort< 4, 20, 1024, 16, 2, 0, 1, 45, 3, XUSP_WORDS_AFTER_CLK,(XUSP_WORDS_BEFORE_CLK+XUSP_WORDS_AT_CLK+XUSP_WORDS_AFTER_CLK), 256, 60, 12, XUSP_EXTRA_FRAMES_PER_ROW, XUSP_USESTOPBOTTOM, XUSP_TOPBOTTOM_SHIFT, 24, 0x7, 18, 0x3F, 8, 0x3FF, XUSP_MINORADDRESS_SHIFT, 0xFF >.
Definition at line 44 of file XUSP_Devices.cpp.
{
     setDeviceByNameOrThrow(partName);
 }
test()
void XilinxUltraScalePlus::test (bool usableFramesOnly, bool testValueEqual, uint32_t testValue)
Definition at line 20 of file XUSP_Test.cpp.
{
     log("Testing bitstream against value" + to_string(testValue) + ".");
     ensureInitializedBitstreamArrays();
     ensureFramesAre(usableFramesOnly, testValueEqual, testValue);
     log("Testing finished successfully.");
 }
References ensureFramesAre(), ensureInitializedBitstreamArrays(), CommonDevice::log(), and Endian::to_string().
writeBitstream()
void XilinxUltraScalePlus::writeBitstream (string filename, string params, Rect2D cmdRect)
Creates a new bitstream file and writes the selected regions in it.
filename Name of the output file.
Exceptions
runtime_error if args don't define a correct region.
Definition at line 137 of file XUSP_Output.cpp.
 {
     size_t dotpos = filename.rfind(".");
     if(dotpos == string::npos)
         throw runtime_error(string("Invalid file name: \"").append(filename).append("\"!\n"));
     designName = filename.substr(0, dotpos);
     log("Writing Xilinx UltraScale+ bitstream to file \"" + filename + "\":");
     parseParams(params);
     if(selectedOptions.partialNotFull) {
         if((cmdRect.position.row % XUSP_CLB_PER_CLOCK_REGION != 0) || (cmdRect.size.row % XUSP_CLB_PER_CLOCK_REGION != 0))
             throw runtime_error("Currently only full clock region height relocations are supported (use row numbers multiple of 60).");
         if(cmdRect.size.row <= 0 || cmdRect.size.col <= 0)
             throw runtime_error("Invalid output size dimentions.");
     }
     ofstream fout (filename, ofstream::binary | ofstream::trunc);
     if(!fout.good())
         throw runtime_error(string("Could not open file: \"").append(filename).append("\"!\n"));
     if(str::iff::stringEndsWith(filename, ".bit"))
         writeBitstreamBIT(fout, cmdRect);
     else if(str::iff::stringEndsWith(filename, ".bin"))
         writeBitstreamBIN(fout, cmdRect);
     else
         throw runtime_error(string("Unknown Xilinx UltraScale+ file format tried to be written.\n"));
     fout.close();
     log("Xilinx UltraScale+ bitstream file \"" + filename + "\" written successfully.");
 }
References Coord2D::col, parseParams(), Rect2D::position, Coord2D::row, Rect2D::size, str::iff::stringEndsWith(), writeBitstreamBIN(), writeBitstreamBIT(), and XUSP_CLB_PER_CLOCK_REGION.
Member Data Documentation
slrMagicInstrLocation
streamoff XilinxUltraScalePlus::slrMagicInstrLocation[4]
Definition at line 51 of file XilinxUltraScalePlus.h.
The documentation for this class was generated from the following files:
src/Devices/Xilinx/UltraScalePlus/XilinxUltraScalePlus.h
src/Devices/Xilinx/UltraScalePlus/XilinxUltraScalePlus.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Assembler.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Blank.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Devices.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Fabric.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Input.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Merge.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Output.cpp
src/Devices/Xilinx/UltraScalePlus/XUSP_Test.cpp