byteman: XilinxConfigurationAccessPort Class Reference
XilinxConfigurationAccessPort Class Reference abstract
#include "XilinxConfigurationAccessPort.h"
Public Member Functions
void findBitstreamSync (ifstream &, Endianess)
streamoff outputBITheader (ofstream &, Endianess=Endianess::NATIVE)
void outputBITheaderLengthField (ofstream &, streamoff, Endianess=Endianess::NATIVE)
void outputCAPheaderConstant (ofstream &, Endianess=Endianess::NATIVE)
void parseBITheader (ifstream &, Endianess)
Endianess parseBitstreamEndianess (ifstream &)
uint32_t parseBitstreamIDCODE (ifstream &, Endianess)
void updateDateAndTime ()
virtual uint32_t XCAP_IDCODEInstruction ()=0
virtual uint32_t XCAP_SyncInstruction ()=0
XilinxConfigurationAccessPort ()
virtual ~XilinxConfigurationAccessPort ()
Public Member Functions inherited from CommonDevice
CommonDevice ()
void log (string message)
void printMessage (string message)
void warn (string message)
virtual ~CommonDevice ()
Public Attributes
string designName
string fileDate
string fileTime
string partName
Public Attributes inherited from CommonDevice
int enableLog
int enableWarn
string instanceName
Detailed Description
Definition at line 30 of file XilinxConfigurationAccessPort.h.
Constructor & Destructor Documentation
XilinxConfigurationAccessPort()
XilinxConfigurationAccessPort::XilinxConfigurationAccessPort ()
Definition at line 21 of file XilinxConfigurationAccessPort.cpp.
 {
     designName = "";
     partName = "";
 }
References designName, and partName.
~XilinxConfigurationAccessPort()
XilinxConfigurationAccessPort::~XilinxConfigurationAccessPort () virtual
Definition at line 26 of file XilinxConfigurationAccessPort.cpp.
 {
 }
Member Function Documentation
findBitstreamSync()
void XilinxConfigurationAccessPort::findBitstreamSync (ifstream & fin, Endianess e)
Reads a bitstream header until and including the sync command.
fin input file stream. Moves the stream pointer to after the SYNC command and in a word-aligned position with the following instructions.
Definition at line 165 of file XilinxConfigurationAccessPortFileInput.cpp.
 {
     for( ; ; ){
         if(!fin.good())
             throw runtime_error("Was unable to find input bitstream's SYNC command.");
         int word = FileIO::read32(fin, e);
         if(XCAP_SyncInstruction() == word){
             return;
         } else
             fin.seekg(-3,ios::cur);
     }
 }
References FileIO::read32(), and XCAP_SyncInstruction().
Referenced by XilinxUltraScalePlus::readBitstreamBIN().
outputBITheader()
streamoff XilinxConfigurationAccessPort::outputBITheader (ofstream & fout, Endianess e = Endianess::NATIVE)
Definition at line 20 of file XilinxConfigurationAccessPortFileOutput.cpp.
 {
     cout << "Output endianess is " << Endian::to_string(e) << endl;
     FileIO::write16(fout, 9, e);//16-bit BE value = 9
     FileIO::writeString(fout, string("\x0F\xF0\x0F\xF0\x0F\xF0\x0F\xF0"), e);
     FileIO::write16(fout, 1, e);//16-bit BE value = 1
     FileIO::write8(fout, 'a', e);
     FileIO::write16(fout, static_cast<uint16_t>(designName.size()+1), e);
     FileIO::writeString(fout, designName, e);
     FileIO::write8(fout, 'b', e);//8-bit BE value = 'b'
     FileIO::write16(fout, static_cast<uint16_t>(partName.size()+1), e);
     FileIO::writeString(fout, partName, e);
     FileIO::write8(fout, 'c', e);//8-bit BE value = 'c'
     FileIO::write16(fout, static_cast<uint16_t>(fileDate.size()+1), e);
     FileIO::writeString(fout, fileDate, e);
     FileIO::write8(fout, 'd', e);//8-bit BE value = 'd'
     FileIO::write16(fout, static_cast<uint16_t>(fileTime.size()+1), e);
     FileIO::writeString(fout, fileTime, e);
     FileIO::write8(fout, 'e', e);//8-bit BE value = 'e'
     streamoff headerLocationOfRemainingFileLength = fout.tellp();
     FileIO::write32(fout, 0, e);//32-bit BE value = 0 representing remaining file size. needs to be fixed later
     return headerLocationOfRemainingFileLength;
 }
References designName, fileDate, fileTime, partName, Endian::to_string(), FileIO::write16(), FileIO::write32(), FileIO::write8(), and FileIO::writeString().
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), and XilinxUltraScalePlus::writeBitstreamBIT().
outputBITheaderLengthField()
void XilinxConfigurationAccessPort::outputBITheaderLengthField (ofstream & fout, streamoff headerLocationOfRemainingFileLength, Endianess e = Endianess::NATIVE)
Definition at line 44 of file XilinxConfigurationAccessPortFileOutput.cpp.
 {
     streamoff finalFileSize = fout.tellp();
     streamoff reportDiff = finalFileSize - (headerLocationOfRemainingFileLength + 4);
     fout.seekp(headerLocationOfRemainingFileLength);
     FileIO::write32(fout, static_cast<uint32_t>(reportDiff), e);
 }
References FileIO::write32().
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), and XilinxUltraScalePlus::writeBitstreamBIT().
outputCAPheaderConstant()
void XilinxConfigurationAccessPort::outputCAPheaderConstant (ofstream & fout, Endianess e = Endianess::NATIVE)
Definition at line 52 of file XilinxConfigurationAccessPortFileOutput.cpp.
 {
     for(int i = 0 ; i < 16 ; i++) // 64 bytes of 0xFF
         FileIO::write32(fout, 0xFFFFFFFF, e);//32-bit BE value = 0xFFFFFFFF
     FileIO::write32(fout, 0x000000BB, e);
     FileIO::write32(fout, 0x11220044, e);
     FileIO::write32(fout, 0xFFFFFFFF, e);
     FileIO::write32(fout, 0xFFFFFFFF, e);
     FileIO::write32(fout, XCAP_SyncInstruction(), e);
 }
References FileIO::write32(), and XCAP_SyncInstruction().
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScalePlus::writeBitstreamMainEmptySLR(), and XilinxUltraScalePlus::writeBitstreamMainSingleSLR().
parseBITheader()
void XilinxConfigurationAccessPort::parseBITheader (ifstream & fin, Endianess e)
Reads and parses .BIT header until and including the sync command. Updates "designName", "partName", "fileDate", "fileTime".
fin input file stream, which is left at the position following the located sync command.
Definition at line 27 of file XilinxConfigurationAccessPortFileInput.cpp.
 {
     //.bit header c0nstant:
     int headerConstTextLength = FileIO::read16(fin, e);
     string headerConstText = FileIO::readString(fin, headerConstTextLength, e);
     int headerConstText2Length = FileIO::read16(fin, e);
     string headerConstText2 = FileIO::readString(fin, headerConstText2Length, e);
     if((!((9 == headerConstTextLength) && ("\x0F\xF0\x0F\xF0\x0F\xF0\x0F\xF0" == headerConstText) && (1 == headerConstText2Length) && ("a" == headerConstText2))))
         warn(".bit c0nstant header differs from expected.");
     //.bit header vars:
     int headerDesignNameLength = FileIO::read16(fin, e);
     designName = FileIO::readString(fin, headerDesignNameLength, e);
     log("Name of design: " + designName);
     for(int headerDone = 0 ; !headerDone ; ){
         int key = FileIO::readNative8(fin);
         switch(key){
             case 'b': {
                 int headerAttrLength = FileIO::read16(fin, e);
                 partName = FileIO::readString(fin, headerAttrLength, e);
                 log("FPGA part: " + partName);
                 break;
             }
             case 'c': {
                 int headerAttrLength = FileIO::read16(fin, e);
                 fileDate = FileIO::readString(fin, headerAttrLength, e);
                 log("Date: " + fileDate);
                 break;
             }
             case 'd': {
                 int headerAttrLength = FileIO::read16(fin, e);
                 fileTime = FileIO::readString(fin, headerAttrLength, e);
                 log("Time: " + fileTime);
                 break;
             }
             case 'e': {
                 headerDone = 1;//last attribute in a .bit header
                 int reportedRemainingFileLength = FileIO::read32(fin, e);
                 int tmpPos = (int)fin.tellg();
                 fin.seekg (0, fin.end);
                 int fileSize = (int)fin.tellg();
                 fin.seekg (tmpPos, fin.beg);
                 if(fileSize != (tmpPos + reportedRemainingFileLength))
                     warn(".bit header contained inaccurate file length field.");
                 break;
             }
             default: {
                 warn(".bit header contained unknown file field type.");
             }
         }
     }
     //Follow some 0xFF's and the bus width detection c0nstant "\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x44\x00\x22\x11\xBB\x00\x00\x00\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF"
     //However we don't care about reading those
     //Find sync
     for(int syncDetectionDone = 0 ; !syncDetectionDone ; ){
         int word = FileIO::read32(fin, e);
         if(XCAP_SyncInstruction() == word)
             syncDetectionDone++;
         else
             fin.seekg(-3,ios::cur);
     }
 }
References designName, fileDate, fileTime, CommonDevice::log(), partName, FileIO::read16(), FileIO::read32(), FileIO::readNative8(), FileIO::readString(), CommonDevice::warn(), and XCAP_SyncInstruction().
Referenced by XilinxUltraScalePlus::disassemblerBitToAsm(), and XilinxUltraScalePlus::readBitstreamBIT().
parseBitstreamEndianess()
Endianess XilinxConfigurationAccessPort::parseBitstreamEndianess (ifstream & fin)
Reads a bitstream header until and including the sync command and returns the file's endianess.
fin input file stream. Gets fixed back to the original value before leaving this function!
Definition at line 96 of file XilinxConfigurationAccessPortFileInput.cpp.
 {
     streamoff fileOffset = fin.tellg();
     //Optional bitstream header
     //Follow some 0xFF's and the bus width detection c0nstant "\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x44\x00\x22\x11\xBB\x00\x00\x00\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF"
     //However we don't care about reading those
     Endianess returnVal;
     //Find sync
     for(int syncDetectionDone = 0 ; !syncDetectionDone ; ){
         if(!fin.good())
             throw runtime_error("Was unable to find input bitstream's SYNC command.");
         int word = FileIO::read32(fin, Endianess::NATIVE);
         if(XCAP_SyncInstruction() == word){
             returnVal = Endianess::NATIVE;
             syncDetectionDone++;
         } else if(XCAP_SyncInstruction() == (Endian::NativeToBigEndian32(word))){
             returnVal = Endianess::BE;
             syncDetectionDone++;
         } else if(XCAP_SyncInstruction() == (Endian::NativeToLittleEndian32(word))){
             returnVal = Endianess::LE;
             syncDetectionDone++;
         } else if(XCAP_SyncInstruction() == Endian::BitSwap32(Endian::NativeToBigEndian32(word))){
             returnVal = Endianess::BE_BS;
             syncDetectionDone++;
         } else if(XCAP_SyncInstruction() == Endian::BitSwap32(Endian::NativeToLittleEndian32(word))){
             returnVal = Endianess::LE_BS;
             syncDetectionDone++;
         } else
             fin.seekg(-3,ios::cur);
     }
     log("Detected file endianess: " + Endian::to_string(returnVal));
     fin.seekg(fileOffset, fin.beg);
     return returnVal;
 }
References BE, BE_BS, Endian::BitSwap32(), LE, LE_BS, CommonDevice::log(), NATIVE, Endian::NativeToBigEndian32(), Endian::NativeToLittleEndian32(), FileIO::read32(), Endian::to_string(), and XCAP_SyncInstruction().
Referenced by XilinxUltraScalePlus::disassemblerBitToAsm(), and XilinxUltraScalePlus::readBitstream().
parseBitstreamIDCODE()
uint32_t XilinxConfigurationAccessPort::parseBitstreamIDCODE (ifstream & fin, Endianess e)
Reads a bitstream until and including the first IDCODE command and returns the first SLRs IDCODE.
fin input file stream. Gets fixed back to the original value before leaving this function!
Definition at line 139 of file XilinxConfigurationAccessPortFileInput.cpp.
 {
     streamoff fileOffset = fin.tellg();
     //Optional bitstream header
     uint32_t returnVal;
     //Find sync
     for(int syncDetectionDone = 0 ; !syncDetectionDone ; ){
         if(!fin.good())
             throw runtime_error("Was unable to find input bitstream's IDCODE command.");
         int word = FileIO::read32(fin, e);
         if(XCAP_IDCODEInstruction() == word){
             returnVal = FileIO::read32(fin, e);
             syncDetectionDone++;
         } else
             fin.seekg(-3,ios::cur);
     }
     fin.seekg(fileOffset, fin.beg);
     return returnVal;
 }
References FileIO::read32(), and XCAP_IDCODEInstruction().
Referenced by XilinxUltraScalePlus::readBitstreamBIN().
updateDateAndTime()
void XilinxConfigurationAccessPort::updateDateAndTime ()
Definition at line 30 of file XilinxConfigurationAccessPort.cpp.
 {
     time_t timestamp = time(0);
     struct tm  tstruct;
     char       buf[80];
     tstruct = *localtime(&timestamp);
     strftime(buf, sizeof(buf), "%Y/%m/%d", &tstruct);
     fileDate = string(buf);
     strftime(buf, sizeof(buf), "%H:%M:%S", &tstruct);
     fileTime = string(buf);
 }
References fileDate, and fileTime.
Referenced by XilinxUltraScalePlus::writeBitstreamBIT().
XCAP_IDCODEInstruction()
virtual uint32_t XilinxConfigurationAccessPort::XCAP_IDCODEInstruction () pure virtual
Implemented in XilinxUltraScalePlus.
Referenced by parseBitstreamIDCODE().
XCAP_SyncInstruction()
virtual uint32_t XilinxConfigurationAccessPort::XCAP_SyncInstruction () pure virtual
Implemented in XilinxUltraScalePlus.
Referenced by findBitstreamSync(), outputCAPheaderConstant(), parseBITheader(), and parseBitstreamEndianess().
Member Data Documentation
designName
string XilinxConfigurationAccessPort::designName
Definition at line 51 of file XilinxConfigurationAccessPort.h.
Referenced by outputBITheader(), parseBITheader(), and XilinxConfigurationAccessPort().
fileDate
string XilinxConfigurationAccessPort::fileDate
Definition at line 53 of file XilinxConfigurationAccessPort.h.
Referenced by outputBITheader(), parseBITheader(), and updateDateAndTime().
fileTime
string XilinxConfigurationAccessPort::fileTime
Definition at line 54 of file XilinxConfigurationAccessPort.h.
Referenced by outputBITheader(), parseBITheader(), and updateDateAndTime().
partName
string XilinxConfigurationAccessPort::partName
Definition at line 52 of file XilinxConfigurationAccessPort.h.
Referenced by outputBITheader(), parseBITheader(), and XilinxConfigurationAccessPort().
The documentation for this class was generated from the following files:
src/Devices/Xilinx/XilinxConfigurationAccessPort.h
src/Devices/Xilinx/XilinxConfigurationAccessPort.cpp
src/Devices/Xilinx/XilinxConfigurationAccessPortFileInput.cpp
src/Devices/Xilinx/XilinxConfigurationAccessPortFileOutput.cpp