byteman: CommonDevice Class Reference
CommonDevice Class Reference
#include "CommonDevice.h"
Public Member Functions
CommonDevice ()
void log (string message)
void printMessage (string message)
void warn (string message)
virtual ~CommonDevice ()
Public Attributes
int enableLog
int enableWarn
string instanceName
Detailed Description
Definition at line 26 of file CommonDevice.h.
Constructor & Destructor Documentation
CommonDevice()
CommonDevice::CommonDevice () inline
Definition at line 29 of file CommonDevice.h.
                       {
             enableWarn = 1;
             enableLog = 0;
         };
~CommonDevice()
virtual CommonDevice::~CommonDevice () inline virtual
Definition at line 33 of file CommonDevice.h.
{
         };
Member Function Documentation
log()
void CommonDevice::log (string message) inline
Definition at line 53 of file CommonDevice.h.
{
             #ifdef ENABLELOGS
                 if(enableLog)
                     CommonDevice::printMessage(string("  info  : ").append(message));
             #endif
         }
References printMessage().
printMessage()
void CommonDevice::printMessage (string message) inline
Definition at line 39 of file CommonDevice.h.
{
             time_t timestamp = time(0);
             struct tm  tstruct;
             char       timeChars[80];
             tstruct = *localtime(&timestamp);
             strftime(timeChars, sizeof(timeChars), "%d %b %Y %H:%M:%S @ ", &tstruct);
             cout << timeChars << instanceName << message << endl;
         }
Referenced by log(), and warn().
warn()
void CommonDevice::warn (string message) inline
Definition at line 47 of file CommonDevice.h.
{
             #ifdef ENABLEWARN
                 if(enableWarn)
                     CommonDevice::printMessage(string(" warning: ").append(message));
             #endif
         }
References printMessage().
Member Data Documentation
enableLog
int CommonDevice::enableLog
Definition at line 38 of file CommonDevice.h.
enableWarn
int CommonDevice::enableWarn
Definition at line 37 of file CommonDevice.h.
instanceName
string CommonDevice::instanceName
Definition at line 35 of file CommonDevice.h.
The documentation for this class was generated from the following file:
src/Devices/CommonDevice.h