byteman: src/Common/Endianess.h File Reference
Endianess.h File Reference
#include <cstdint>
#include <string>
Namespaces
Endian
Enumerations
enum Endianess {
Endianess::NATIVE, Endianess::BIG_ENDIAN, Endianess::LITTLE_ENDIAN, Endianess::BIG_ENDIAN_BITSWAPPED,
Endianess::LITTLE_ENDIAN_BITSWAPPED
}
Functions
uint16_t Endian::BigEndianToNative16 (uint16_t x)
uint32_t Endian::BigEndianToNative32 (uint32_t x)
uint64_t Endian::BigEndianToNative64 (uint64_t x)
uint8_t Endian::BigEndianToNative8 (uint8_t x)
uint16_t Endian::BitSwap16 (uint16_t x)
uint32_t Endian::BitSwap32 (uint32_t x)
uint64_t Endian::BitSwap64 (uint64_t x)
uint8_t Endian::BitSwap8 (uint8_t x)
Endianess Endian::diff (Endianess e1, Endianess e2)
Endianess Endian::fixEndianIfNative (Endianess e)
static int IS_LITTLE_ENDIAN (void)
uint16_t Endian::LittleEndianToNative16 (uint16_t x)
uint32_t Endian::LittleEndianToNative32 (uint32_t x)
uint64_t Endian::LittleEndianToNative64 (uint64_t x)
uint8_t Endian::LittleEndianToNative8 (uint8_t x)
uint16_t Endian::NativeToAnyEndianess16 (uint16_t x, Endianess e)
uint32_t Endian::NativeToAnyEndianess32 (uint32_t x, Endianess e)
uint64_t Endian::NativeToAnyEndianess64 (uint64_t x, Endianess e)
uint8_t Endian::NativeToAnyEndianess8 (uint8_t x, Endianess e)
uint16_t Endian::NativeToBigEndian16 (uint16_t x)
uint32_t Endian::NativeToBigEndian32 (uint32_t x)
uint64_t Endian::NativeToBigEndian64 (uint64_t x)
uint8_t Endian::NativeToBigEndian8 (uint8_t x)
uint16_t Endian::NativeToLittleEndian16 (uint16_t x)
uint32_t Endian::NativeToLittleEndian32 (uint32_t x)
uint64_t Endian::NativeToLittleEndian64 (uint64_t x)
uint8_t Endian::NativeToLittleEndian8 (uint8_t x)
uint16_t Endian::swapbytes16 (uint16_t x)
uint32_t Endian::swapbytes32 (uint32_t x)
uint64_t Endian::swapbytes64 (uint64_t x)
Endianess Endian::swapEndian (Endianess e)
Endianess Endian::swapEndianBits (Endianess e)
string Endian::to_string (Endianess e)
Enumeration Type Documentation
Endianess
enum Endianess strong
Enumerator
NATIVE
Whatever native is, it will always be the fastest endianess to process.
BIG_ENDIAN
Enforce Big endianess.
LITTLE_ENDIAN
Enforce Little endianess.
BIG_ENDIAN_BITSWAPPED
Enforce Big endianess with bit swaps inside each byte.
LITTLE_ENDIAN_BITSWAPPED
Enforce Little endianess with bit swaps inside each byte.
Definition at line 43 of file Endianess.h.
                      {
     NATIVE,
     BIG_ENDIAN,
     LITTLE_ENDIAN,
     BIG_ENDIAN_BITSWAPPED,
     LITTLE_ENDIAN_BITSWAPPED
 };
Function Documentation
IS_LITTLE_ENDIAN()
static int IS_LITTLE_ENDIAN (void) static
Definition at line 32 of file Endianess.h.
 {
     union {
         unsigned int v;
         unsigned char b;
     } u;
     u.v = 1;
     return u.b;
 }
Referenced by Endian::diff(), Endian::fixEndianIfNative(), Endian::NativeToBigEndian16(), Endian::NativeToBigEndian32(), Endian::NativeToBigEndian64(), Endian::NativeToLittleEndian16(), Endian::NativeToLittleEndian32(), Endian::NativeToLittleEndian64(), Endian::swapEndian(), and Endian::swapEndianBits().