byteman: src/help.cpp File Reference
help.cpp File Reference
#include <iostream>
#include "byteman.h"
#include <sstream>
#include <stdexcept>
Macros
#define argIs(x, y) (word == x || word == y)
Functions
void parseHelp (string args, int shouldExit, int exitCode)
void usage ()
void usage_assembly ()
void usage_blank ()
void usage_change ()
void usage_device ()
void usage_end ()
void usage_help ()
void usage_input ()
void usage_merge ()
void usage_output ()
void usage_region ()
void usage_stdin ()
void usage_verbose ()
void usage_warn ()
void usageArg (string args)
Macro Definition Documentation
argIs
#define argIs (x, y) (word == x || word == y)
Function Documentation
parseHelp()
void parseHelp (string args, int shouldExit, int exitCode)
Definition at line 25 of file help.cpp.
 {
     stringstream ss(args);
     string word;
     ss >> word;
     if(ss.eof())
         usage();
     else
         usageArg(args);
     if(shouldExit)
         exit(exitCode);
 }
References usage(), and usageArg().
Referenced by main(), and parseCommand().
usage()
void usage ()
Definition at line 37 of file help.cpp.
 {
     cout << "byteman " << VERSION << " (Build " << VERSION_BUILD << ") usage:" << endl;
     cout << "byteman ARCH [-command...]* [-stdin]" << endl;
     cout << "\tCommands:    [Default] : [Description]                                    " << endl;
     cout << "\t-a (assembly)          : (de)compile bitstream assembly files. See \"byteman -h assembly\"" << endl;
     cout << "\t-b (blank)             : Erases bitstream buffers. See \"byteman -h blank\"" << endl;
     cout << "\t-c (change)            : Modify primitives (i.e., LUT contents). See \"byteman -h change\"" << endl;
     cout << "\t-d (device)    NULL    : Manually select target device. See \"byteman -h device\"" << endl;
     cout << "\t-e (end)               : Exit byteman. Useful during stdin. See \"byteman -h end\"" << endl;
     cout << "\t-i (input)             : Input bitstream. See \"byteman -h input\"" << endl;
     cout << "\t-m (merge)             : Merge bitstreams. See \"byteman -h merge\"" << endl;
     cout << "\t-r (region)            : Modify region selection. See \"byteman -h region\"" << endl;
     cout << "\t-o (output)            : Output bitstream. See \"byteman -h output\"" << endl;
     cout << "\t-h (help)              : Get help. See \"byteman -h help\"" << endl;
     cout << "\t-v (verbose)   0       : Enable/disable spam. See \"byteman -h verbose\"" << endl;
     cout << "\t-w (warn)      1       : Enable/disable warnings. See \"byteman -h warn\"" << endl;
     cout << "\t-stdin                 : Continue using standard input. See \"byteman -h stdin\"" << endl;
     cout << "Examples: " << endl;
     cout << "\tbyteman.exe Xilinx US+ -w -i main static.bit -i temp filter.bit -merge logic 180:67 120:30 240:37 -o logic 240:37 120:30 relocatedFilter.bit" << endl;
     cout << "\tbyteman.exe Xilinx US+ -w -d zcu102 -blank main logic blockram -i temp filter.bit -merge logic 180:67 120:30 180:67 -o logic 180:67 120:30 mergedFilter.bit" << endl;
 }
References VERSION, and VERSION_BUILD.
Referenced by parseHelp().
usage_assembly()
void usage_assembly ()
Definition at line 147 of file help.cpp.
 {
     cout<<"TODO usage_assembly" << endl;
     ArchAssemblyHelp();
 }
References ArchAssemblyHelp().
Referenced by usageArg().
usage_blank()
void usage_blank ()
Definition at line 112 of file help.cpp.
 {
     cout<<"TODO usage_blank" << endl;
 }
Referenced by usageArg().
usage_change()
void usage_change ()
Definition at line 116 of file help.cpp.
 {
     cout<<"TODO usage_change" << endl;
 }
Referenced by usageArg().
usage_device()
void usage_device ()
Definition at line 120 of file help.cpp.
 {
     cout<<"TODO usage_device" << endl;
     cout << "Available devices:" <<endl;
     ArchDeviceHelp();
 }
References ArchDeviceHelp().
Referenced by usageArg().
usage_end()
void usage_end ()
Definition at line 152 of file help.cpp.
 {
     cout<<"TODO usage_end" << endl;
 }
Referenced by usageArg().
usage_help()
void usage_help ()
Definition at line 127 of file help.cpp.
 {
     cout<<"TODO usage_help" << endl;
     cout<<"headache" << endl;
 }
Referenced by usageArg().
usage_input()
void usage_input ()
Definition at line 132 of file help.cpp.
 {
     cout<<"TODO usage_input" << endl;
     cout <<"Input params: main/first, second/temp" << endl;
 }
Referenced by usageArg().
usage_merge()
void usage_merge ()
Definition at line 137 of file help.cpp.
 {
     cout<<"TODO usage_merge" << endl;
     cout <<"Merge params: clk/clock, clb/logic, bram, uram, set, xor, or, and" << endl;
 }
Referenced by usageArg().
usage_output()
void usage_output ()
Definition at line 142 of file help.cpp.
 {
     cout<<"TODO usage_output" << endl;
     cout <<"Output params: main/first, second/temp, clb, bram, blank, full, partial" << endl;
 }
Referenced by usageArg().
usage_region()
void usage_region ()
Definition at line 107 of file help.cpp.
 {
     cout<<"TODO usage_region" << endl;
     cout <<"Region params: main/first, second/temp, add,clear" << endl;
 }
Referenced by usageArg().
usage_stdin()
void usage_stdin ()
Definition at line 156 of file help.cpp.
 {
     cout << "\t-stdin                    : Continue using the same commands on standard input." << endl;
     cout << "\t                            Standard input ends with a command \"end\"." << endl;
     cout << "\t                            Stdin commands dont need \"-\" in front and can be on multiple lines." << endl;
     cout << "\t                            \"#\" starts a comment until a newline is seen." << endl;
 }
Referenced by usageArg().
usage_verbose()
void usage_verbose ()
Definition at line 99 of file help.cpp.
 {
     cout<<"TODO usage_verbose" << endl;
 }
Referenced by usageArg().
usage_warn()
void usage_warn ()
Definition at line 103 of file help.cpp.
 {
     cout<<"TODO usage_warn" << endl;
 }
Referenced by usageArg().
usageArg()
void usageArg (string args)
Definition at line 62 of file help.cpp.
 {
     stringstream ss(args);
     string word;
     ss >> word;
     while (!ss.eof()) {
         ss >> word;
     #define argIs(x,y) (word == x || word == y)
     if(argIs("v", "verbose"))
         usage_verbose();
     else if(argIs("w", "warn"))
         usage_warn();
     else if(argIs("r", "region"))
         usage_region();
     else if(argIs("b", "blank"))
         usage_blank();
     else if(argIs("c", "change"))
         usage_change();
     else if(argIs("d", "device"))
         usage_device();
     else if(argIs("h", "help"))
         usage_help();
     else if(argIs("i", "input"))
         usage_input();
     else if(argIs("m", "merge"))
         usage_merge();
     else if(argIs("o", "output"))
         usage_output();
     else if(argIs("a", "assembly"))
         usage_assembly();
     else if(argIs("e", "end"))
         usage_end();
     else if(argIs("s", "stdin"))
         usage_stdin();
     #undef argIs
     }
 }
References argIs, usage_assembly(), usage_blank(), usage_change(), usage_device(), usage_end(), usage_help(), usage_input(), usage_merge(), usage_output(), usage_region(), usage_stdin(), usage_verbose(), and usage_warn().
Referenced by parseHelp().