byteman: usageArg
argIs
parseHelp
usage
usage_assembly
usage_blank
usage_change
usage_device
usage_end
usage_help
usage_input
usage_merge
usage_output
usage_region
usage_stdin
usage_verbose
usage_warn
usageArg
usageArg()
void usageArg (string args)
Definition at line 57 of file help.cpp.
{
     stringstream ss(args);
     string word;
     ss >> word;
     while (!ss.eof()) {
         ss >> word;
     #define argIs(x,y) (word == x || word == y)
     if(argIs("v", "verbose"))
         usage_verbose();
     else if(argIs("w", "warn"))
         usage_warn();
     else if(argIs("r", "region"))
         usage_region();
     else if(argIs("b", "blank"))
         usage_blank();
     else if(argIs("c", "change"))
         usage_change();
     else if(argIs("d", "device"))
         usage_device();
     else if(argIs("h", "help"))
         usage_help();
     else if(argIs("i", "input"))
         usage_input();
     else if(argIs("m", "merge"))
         usage_merge();
     else if(argIs("o", "output"))
         usage_output();
     else if(argIs("a", "assembly"))
         usage_assembly();
     else if(argIs("e", "end"))
         usage_end();
     else if(argIs("s", "stdin"))
         usage_stdin();
     #undef argIs
     }
 }
References argIs, usage_assembly(), usage_blank(), usage_change(), usage_device(), usage_end(), usage_help(), usage_input(), usage_merge(), usage_output(), usage_region(), usage_stdin(), usage_verbose(), and usage_warn().
Referenced by parseHelp().