byteman: src/Devices/Xilinx/XCAP/inlineBlank.h File Reference
inlineBlank.h File Reference
Functions
void blankBuffers ()
void clearResourceStringArrays ()
Function Documentation
blankBuffers()
void blankBuffers () inline
Definition at line 23 of file inlineBlank.h.
 {
     uint8_t blankByte = selectedOptions.intParam % 256;
     if(regionSelection.empty()) {
         if(selectedOptions.clb && selectedOptions.clk) {
             memset(&bitstreamBegin[0], blankByte, ((uint64_t)&bitstreamBRAM[0][0][0]-(uint64_t)&bitstreamBegin[0]));
         }
         else if(selectedOptions.clb || selectedOptions.clk){
             for(int r = 0 ; r < numberOfRows ; r++){
                 for(int c = 0 ; c < numberOfCols[r] ; c++){
                     for(int m = 0 ; m < LUT_numberOfFramesForResourceLetter[(uint8_t)resourceString[r][c]] ; m++){
                         if(selectedOptions.clb){
                             memset(&bitstreamCLB[r][c][m*WORDS_PER_FRAME], blankByte, (WORDS_BEFORE_CLK * 4));
                             memset(&bitstreamCLB[r][c][m*WORDS_PER_FRAME+(WORDS_BEFORE_CLK+WORDS_AT_CLK)], blankByte, (WORDS_AFTER_CLK * 4));
                         }
                         if(selectedOptions.clk){
                             for(int w = 0 ; w < WORDS_AT_CLK ; w++){
                                 bitstreamCLB[r][c][m*WORDS_PER_FRAME + WORDS_BEFORE_CLK + w] = ((blankByte << 24) | (blankByte << 16) | (blankByte << 8) | (blankByte));
                             }
                         }
                     }
                 }
             }
         }
         if(selectedOptions.bram)
             memset(&bitstreamBRAM[0][0][0], blankByte, ((uint64_t)&bitstreamEnd[0]-(uint64_t)&bitstreamBRAM[0][0][0]));
     } else {
         for (Rect2D &selRect : regionSelection) {
             int fromRow = selRect.position.row / CLB_PER_CLOCK_REGION;
             int toRow = (selRect.position.row + selRect.size.row) / CLB_PER_CLOCK_REGION;
             int fromCol = selRect.position.col;
             int toCol = selRect.position.col + selRect.size.col;
             for(int r = fromRow ; r < toRow ; r++){
                 if(selectedOptions.clb && selectedOptions.clk){
                     int blankSize = numberOfFramesBeforeCol[r][toCol] - numberOfFramesBeforeCol[r][fromCol];
                     blankSize *= WORDS_PER_FRAME * 4;
                     memset(&bitstreamCLB[r][fromCol][0], blankByte, blankSize);
                 }
                 else if(selectedOptions.clb || selectedOptions.clk){
                     for(int c = fromCol ; c < toCol ; c++){
                         for(int m = 0 ; m < LUT_numberOfFramesForResourceLetter[(uint8_t)resourceString[r][c]] ; m++){
                             if(selectedOptions.clb){
                                 memset(&bitstreamCLB[r][c][m*WORDS_PER_FRAME], blankByte, (WORDS_BEFORE_CLK * 4));
                                 memset(&bitstreamCLB[r][c][m*WORDS_PER_FRAME+(WORDS_BEFORE_CLK+WORDS_AT_CLK)], blankByte, (WORDS_AFTER_CLK * 4));
                             }
                             if(selectedOptions.clk){
                                 for(int w = 0 ; w < WORDS_AT_CLK ; w++){
                                     bitstreamCLB[r][c][m*WORDS_PER_FRAME + WORDS_BEFORE_CLK + w] = ((blankByte << 24) | (blankByte << 16) | (blankByte << 8) | (blankByte));
                                 }
                             }
                         }
                     }
                 }
                 if(selectedOptions.bram){
                     int blankSize = numberOfBRAMsBeforeCol[r][toCol] - numberOfBRAMsBeforeCol[r][fromCol];
                     blankSize *= FRAMES_PER_BRAM_CONTENT_COLUMN * WORDS_PER_FRAME * 4;
                     memset(&bitstreamCLB[r][numberOfBRAMsBeforeCol[r][fromCol]][0], blankByte, blankSize); //memset with size 0 is safe, no need to check anything
                 }
             }
         }
     }
     bitstreamHasValidData = true;
 }
Referenced by XilinxSeries7::blank(), XilinxUltraScalePlus::blank(), and XilinxUltraScale::blank().
clearResourceStringArrays()
void clearResourceStringArrays () inline
Definition at line 17 of file inlineBlank.h.
 {
     initializedResourceStringShortPartName = "";
     memset(&resourceString, 0, MAX_ROWS * MAX_COLS * sizeof(char));
 }
Referenced by XilinxSeries7::setDevice(), XilinxUltraScalePlus::setDevice(), and XilinxUltraScale::setDevice().