byteman: src/Devices/Xilinx/XCAP/inlineAssembly.h File Reference
inlineAssembly.h File Reference
Functions
void assemblyOutputData (std::ifstream &fin, std::ofstream &fout, std::streamoff sizeInBytes)
Function Documentation
assemblyOutputData()
void assemblyOutputData (std::ifstream & fin, std::ofstream & fout, std::streamoff sizeInBytes) inline
Definition at line 17 of file inlineAssembly.h.
 {
     std::streamoff numOfWords = sizeInBytes/(std::streamoff)4;
     for(std::streamoff i = 0 ; i < numOfWords ; i++){
         uint32_t aWord = FileIO::read32(fin, loadedBitstreamEndianness);
         fout << ".word " << "0x" << std::uppercase << std::hex << std::setw(8) << std::setfill('0') << aWord << std::endl;
     }
     std::streamoff numOfBytes = sizeInBytes % (std::streamoff)4;
     for(std::streamoff i = 0 ; i < numOfBytes ; i++){
         uint8_t aByte = FileIO::read32(fin, loadedBitstreamEndianness);
         fout << ".byte " << "0x" << std::uppercase << std::hex << std::setw(2) << std::setfill('0') << aByte << std::endl;
     }
 }
References FileIO::read32().
Referenced by XilinxSeries7::disassemblerToAsm(), XilinxUltraScalePlus::disassemblerToAsm(), and XilinxUltraScale::disassemblerToAsm().