byteman: src/Devices/Xilinx/XCAP/inlinePrintResourceStringInfo.h File Reference
inlinePrintResourceStringInfo.h File Reference
Functions
void printResourceStringInfo ()
Function Documentation
printResourceStringInfo()
void printResourceStringInfo () inline
Definition at line 17 of file inlinePrintResourceStringInfo.h.
{
     cout << "Brakdown of X coordinates in device " + partName + ":" << endl;
     for(int r = 0 ; r < numberOfRows ; r++){
         cout << "\tRow " << r << " (counting from bottom up) is represented by Y coordinate range " << r * CLB_PER_CLOCK_REGION << "-" << ((r + 1) * CLB_PER_CLOCK_REGION - 1) << "." << endl;
         cout << "\tRow " << r << " has the following X coordinates with respective column resources:" << endl;
         for(int c = 0 ; ; c++){
             uint8_t resourceLetter = (uint8_t)resourceString[r][c];
             if(resourceLetter <= 1)
                 break;
             if(LUT_isFrameUnusedForResourceLetter[resourceLetter])
                 cout << "\t\t" << c << ": Unused/hidden resource" << endl;
             else
                 cout << "\t\t" << c << ": " << LUT_typeOfFrameForResourceLetter[resourceLetter] << endl;
         }
         cout << endl;
     }
 }
Referenced by XilinxSeries7::deviceHelp(), XilinxUltraScalePlus::deviceHelp(), and XilinxUltraScale::deviceHelp().