byteman: src/Devices/Xilinx/XCAP/inlineChange.h File Reference
inlineChange.h File Reference
Functions
void ensureSelectedEndianness (Endianness newEndianness)
void setBitstreamWord (std::string params)
Function Documentation
ensureSelectedEndianness()
void ensureSelectedEndianness (Endianness newEndianness) inline
Definition at line 17 of file inlineChange.h.
{
     ensureInitializedBitstreamArrays();//initialize bitstream arrays before modifications
     Endianness endiannessConvertion = Endian::diff(loadedBitstreamEndianness, newEndianness);
     if(endiannessConvertion == Endianness::NATIVE)// if there is no actual convertion needed
         return;
     int bitstreamSize = bitstreamEnd - bitstreamBegin;
     if(endiannessConvertion == Endianness::BE)
         for( int i = 0 ; i < bitstreamSize ; i++)
             bitstreamBegin[i] = Endian::NativeToBigEndian32(bitstreamBegin[i]);
     if(endiannessConvertion == Endianness::LE)
         for( int i = 0 ; i < bitstreamSize ; i++)
             bitstreamBegin[i] = Endian::NativeToLittleEndian32(bitstreamBegin[i]);
     if(endiannessConvertion == Endianness::BE_BS)
         for( int i = 0 ; i < bitstreamSize ; i++)
             bitstreamBegin[i] = Endian::BitSwap32(Endian::NativeToBigEndian32(bitstreamBegin[i]));
     if(endiannessConvertion == Endianness::LE_BS)
         for( int i = 0 ; i < bitstreamSize ; i++)
             bitstreamBegin[i] = Endian::BitSwap32(Endian::NativeToLittleEndian32(bitstreamBegin[i]));
     loadedBitstreamEndianness = newEndianness;
 }
References BE, BE_BS, Endian::BitSwap32(), Endian::diff(), LE, LE_BS, NATIVE, Endian::NativeToBigEndian32(), and Endian::NativeToLittleEndian32().
Referenced by XilinxSeries7::change(), XilinxUltraScale::change(), XilinxUltraScalePlus::change(), readBitstreamMain(), and readBitstreamRBDMain().
setBitstreamWord()
void setBitstreamWord (std::string params) inline
Definition at line 43 of file inlineChange.h.
{
     ensureInitializedBitstreamArrays();//initialize bitstream arrays before modifications
     uint32_t r, y, c, b, m, w, mask, newVal;
     str::parse::multipleUints(params, y, c, b, m, w, mask, newVal);
     mask = Endian::NativeToAnyEndianness32(mask, loadedBitstreamEndianness);
     newVal = Endian::NativeToAnyEndianness32(newVal, loadedBitstreamEndianness);
     r = y / CLB_PER_CLOCK_REGION;
     if(b == BLOCKTYPE_LOGIC){
         bitstreamCLB[r][c][m*WORDS_PER_FRAME + w] = (mask & newVal) | ((mask^0xFFFFFFFF) & bitstreamCLB[r][c][m*WORDS_PER_FRAME + w]);
     } else if(b == BLOCKTYPE_BLOCKRAM){
         bitstreamBRAM[r][numberOfBRAMsBeforeCol[r][c]][m*WORDS_PER_FRAME + w] = (mask & newVal) | ((mask^0xFFFFFFFF) & bitstreamBRAM[r][numberOfBRAMsBeforeCol[r][c]][m*WORDS_PER_FRAME + w]);
     }
     bitstreamHasValidData = true;
 }
References str::parse::multipleUints(), and Endian::NativeToAnyEndianness32().
Referenced by XilinxSeries7::change(), XilinxUltraScale::change(), and XilinxUltraScalePlus::change().