byteman: src/Devices/Xilinx/XCAP/inlineParseParams.h File Reference
inlineParseParams.h File Reference
Functions
void parseParams (std::string params)
Function Documentation
parseParams()
void parseParams (std::string params) inline
Parses argument options for multiple operations.
params A list of parameters to control behavior:
"clock" or "clk" : Selects the clocks for operation.
"logic" or "clb" : Selects the blocktype 0 for operation.
"blockram" or "bram" : Selects the blockram contents for operation.
If neither clock, logic, or blockram are chosen, chooses all.
"blank" : Selects bitstream blanking (zeroing) operation.
"full" : Disabling partial selection.
"partial" : Writes only selected regions. Selected by default.
"set" : Selects SET operation.
"xor" : Selects bitwise XOR operation.
"or" : Selects bitwise OR operation.
"and" : Selects bitwise AND operation.
Definition at line 32 of file inlineParseParams.h.
{
     selectedOptions = SelectedOptions();
     selectedOptions.clk = false;
     selectedOptions.clb = false;
     selectedOptions.bram = false;
     selectedOptions.blank = false;
     selectedOptions.partialNotFull = true;
     selectedOptions.op = MergeOP::SET;
     selectedOptions.skipUnused = true;
     selectedOptions.forceEndianness = false;
     selectedOptions.intParam = 0;
     replace(params.begin(), params.end(), ',', ' ');
     std::stringstream ss(params);
     std::string param;
     while (!ss.eof()) {
         ss >> param;
         if(param == "clock" || param == "clk")selectedOptions.clk = true;
         if(param == "logic" || param == "clb")selectedOptions.clb = true;
         if(param == "blockram" || param == "bram")selectedOptions.bram = true;
         if(param == "blank")selectedOptions.blank = true;
         if(param == "full")selectedOptions.partialNotFull = false;
         if(param == "partial")selectedOptions.partialNotFull = true;
         if(param == "set")selectedOptions.op = MergeOP::SET;
         if(param == "xor")selectedOptions.op = MergeOP::XOR;
         if(param == "or")selectedOptions.op = MergeOP::OR;
         if(param == "and")selectedOptions.op = MergeOP::AND;
         if(param == "bigendian"){
             selectedOptions.forceEndianness = true;
             selectedOptions.forcedEndianness = Endianness::BE;
         }
         if(param == "littleendian"){
             selectedOptions.forceEndianness = true;
             selectedOptions.forcedEndianness = Endianness::LE;
         }
         if(param == "bigendianwithbitswap"){
             selectedOptions.forceEndianness = true;
             selectedOptions.forcedEndianness = Endianness::BE_BS;
         }
         if(param == "littleendianwithbitswap"){
             selectedOptions.forceEndianness = true;
             selectedOptions.forcedEndianness = Endianness::LE_BS;
         }
         if(param == "nativeendian"){
             selectedOptions.forceEndianness = true;
             selectedOptions.forcedEndianness = Endianness::NATIVE;
         }
         param.clear();
     }
     if(!str::parse::multipleInts(params, selectedOptions.intParam))
         selectedOptions.intParam = 0; //default 0 if there is nothing
     if(!selectedOptions.clk && !selectedOptions.clb && !selectedOptions.bram){ // by default, choose all
         selectedOptions.clk = selectedOptions.bram = selectedOptions.clb = true;
     }
 }
References BE, BE_BS, LE, LE_BS, str::parse::multipleInts(), NATIVE, and str::replace().
Referenced by XilinxSeries7::blank(), XilinxUltraScale::blank(), XilinxUltraScalePlus::blank(), XilinxSeries7::change(), XilinxUltraScalePlus::change(), XilinxUltraScale::change(), XilinxUltraScale::merge(), XilinxUltraScalePlus::merge(), XilinxSeries7::merge(), XilinxUltraScalePlus::writeBitstream(), XilinxSeries7::writeBitstream(), and XilinxUltraScale::writeBitstream().