byteman: src/Devices/Xilinx/XCAP/inlineSetFabric.h File Reference
inlineSetFabric.h File Reference
Functions
void setFabricChar (char character, int frameNumber, std::string tileName, bool isUnused=false)
Function Documentation
setFabricChar()
void setFabricChar (char character, int frameNumber, std::string tileName, bool isUnused = false) inline
Definition at line 17 of file inlineSetFabric.h.
{
     LUT_numberOfFramesForResourceLetter[(uint8_t)character] = frameNumber;
     LUT_isFrameUnusedForResourceLetter[(uint8_t)character]  = isUnused;
     LUT_typeOfFrameForResourceLetter[(uint8_t)character]    = tileName;
 }
Referenced by XilinxSeries7::initFabric(), XilinxUltraScalePlus::initFabric(), and XilinxUltraScale::initFabric().