byteman: StringFuncs Namespace Reference
StringFuncs Namespace Reference
Namespaces
checkIf
parse
Functions
string findStringAndGetAllAfter (string checkedString, string searchString)
string removeExternalQuotes (string str)
string removeSpaces (string str)
string replace (string str, char oldChar, char newChar)
string stringToLower (string str)
string stringToUpper (string str)
Function Documentation
findStringAndGetAllAfter()
string StringFuncs::findStringAndGetAllAfter (string checkedString, string searchString) inline
Parameters
searchString Finds string searchString inside checkedString and returns all to the right inside checkedString. If can't be found, returns empty string.
Definition at line 258 of file StringFuncs.h.
     {
         size_t loc = checkedString.find(searchString);
         if(string::npos == loc)
             return string("");
         return checkedString.substr(loc + searchString.size());
     }
Referenced by byteman::parseCommand().
removeExternalQuotes()
string StringFuncs::removeExternalQuotes (string str) inline
Parameters
str Removes double quotes from start and end of string str and returns the resulting string.
Definition at line 285 of file StringFuncs.h.
     {
         if(str.empty())
             return str;
         if(str.front() == '"')
             str.erase(str.begin());
         if(str.empty())
             return str;
         if(str.back() == '"')
             str.erase(str.end()-1);
         return str;
     }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit().
removeSpaces()
string StringFuncs::removeSpaces (string str) inline
Parameters
str Removes all space chars of str returns the resulting string.
Definition at line 270 of file StringFuncs.h.
     {
         str.erase(remove_if(str.begin(), str.end(), ::isspace), str.end());
         return str;
     }
Referenced by XilinxUltraScalePlus::getDeviceByName().
replace()
string StringFuncs::replace (string str, char oldChar, char newChar) inline
Parameters
newChar Replaces all instances of oldChar in string str with newChar and returns the resulting string.
Definition at line 265 of file StringFuncs.h.
     {
         replace(str.begin(), str.end(), '=', ' ');
         return str;
     }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), byteman::parseCommand(), XilinxUltraScalePlus::parseParams(), and byteman::parseParams().
stringToLower()
string StringFuncs::stringToLower (string str) inline
Parameters
str Replaces all uppercase characters in str with lowercase and returns the resulting string.
Definition at line 280 of file StringFuncs.h.
     {
         transform(str.begin(), str.end(),str.begin(), ::tolower);
         return str;
     }
Referenced by XilinxUltraScalePlus::getDeviceByName(), and byteman::setArchitecture().
stringToUpper()
string StringFuncs::stringToUpper (string str) inline
Parameters
str Replaces all lowercase characters in str with uppercase and returns the resulting string.
Definition at line 275 of file StringFuncs.h.
     {
         transform(str.begin(), str.end(),str.begin(), ::toupper);
         return str;
     }