byteman: StringFuncs::parse Namespace Reference
StringFuncs::parse Namespace Reference
Functions
string allStringWords (string s)
string allStringWordsWithoutLastStringWord (string s)
bool arrayOfUints (string s, int arrsize, uint32_t *arr)
string lastStringWord (string s)
template<typename ... Args>
bool multipleInts (string s, Args &... args)
template<typename ... Rest>
bool multipleInts (stringstream &ss)
template<typename ... Rest>
bool multipleInts (stringstream &ss, int &x, Rest &... args)
bool nthInteger (string s, int n, int &x)
string nthStringWord (string s, int n)
Function Documentation
allStringWords()
string StringFuncs::parse::allStringWords (string s) inline
Parameters
s Parses a string s, removes all integers and returns the rest
Definition at line 53 of file StringFuncs.h.
         {
             stringstream ss(s);
             string ret;
             ret.clear();
             string temp;
             int intFound;
             ss >> temp;
             while (!ss.eof()) {
                 ss >> temp;
                 if (!(stringstream(temp) >> intFound))
                     ret.append(temp).append(" ");
                 temp.clear();
             }
             return ret;
         }
Referenced by byteman::parseBlank(), byteman::parseMerge(), and byteman::parseRegion().
allStringWordsWithoutLastStringWord()
string StringFuncs::parse::allStringWordsWithoutLastStringWord (string s) inline
Parameters
s Parses a string s, removes all integers and the last string word. Returns the rest
Definition at line 89 of file StringFuncs.h.
         {
             stringstream ss(s);
             string ret;
             ret.clear();
             string temp;
             string temp2;
             int intFound;
             ss >> temp;
             while (!ss.eof()) {
                 ss >> temp;
                 try{
                     intFound = stoi(temp, nullptr, 0);
                 } catch (const exception &e) {
                     if(!ret.empty())
                         ret.append(" ");
                     ret.append(temp2);
                     temp2 = temp;
                     e;
                 }
                 temp.clear();
             }
             return ret;
         }
Referenced by byteman::parseDevice(), byteman::parseInput(), and byteman::parseOutput().
arrayOfUints()
bool StringFuncs::parse::arrayOfUints (string s, int arrsize, uint32_t * arr) inline
Parameters
arr Removes all string words from a given string s and returns the parsed arrsize number of integers into arr
Definition at line 135 of file StringFuncs.h.
         {
             if (arrsize == 0)
                 return true;
             stringstream ss(s);
             string temp;
             uint32_t intFound;
             bool intWasFound = false;
             for (int i = 0 ; i < arrsize ; i++)
             {
                 intWasFound = false;
                 while ((!ss.eof()) && (!intWasFound)) {
                     ss >> temp;
                     try{
                         intFound = (uint32_t)(stoll(temp, nullptr, 0));
                         arr[i] = intFound;
                         intWasFound = true;
                     } catch (const exception &e) {
                         e;
                     }
                     temp.clear();
                 }
                 if(ss.eof() && (!intWasFound))
                     return false;
             }
             return true;   //success
         }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit().
lastStringWord()
string StringFuncs::parse::lastStringWord (string s) inline
Parameters
s Parses a string s, removes all integers and returns the last of all string words
Definition at line 69 of file StringFuncs.h.
         {
             stringstream ss(s);
             string ret;
             ret.clear();
             string temp;
             int intFound;
             ss >> temp;
             while (!ss.eof()) {
                 ss >> temp;
                 try{
                     intFound = stoi(temp, nullptr, 0);
                 } catch (const exception &e) {
                     ret = temp;
                     e;
                 }
                 temp.clear();
             }
             return ret;
         }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), byteman::parseDevice(), byteman::parseInput(), and byteman::parseOutput().
multipleInts() [1/3]
template<typename ... Args> bool StringFuncs::parse::multipleInts (string s, Args &... args) inline
Parameters
args Parses string s for integer values, that are returned into args
Definition at line 192 of file StringFuncs.h.
         {
             stringstream ss(s);
             return multipleInts(ss, args...);
         }
Referenced by multipleInts().
multipleInts() [2/3]
template<typename ... Rest> bool StringFuncs::parse::multipleInts (stringstream & ss) inline
Definition at line 164 of file StringFuncs.h.
         {
             return true;
         }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), byteman::parseMerge(), byteman::parseOutput(), byteman::parseRegion(), byteman::parseVerbose(), and byteman::parseWarn().
multipleInts() [3/3]
template<typename ... Rest> bool StringFuncs::parse::multipleInts (stringstream & ss, int & x, Rest &... args) inline
Parameters
args Parses stringstream ss for integer values, that are returned into x, args
Definition at line 168 of file StringFuncs.h.
         {
             int numArgs = sizeof...(args);
             string temp;
             int intFound;
             bool intWasFound = false;
             while ((!ss.eof()) && (!intWasFound)) {
                 ss >> temp;
                 try{
                     intFound = stoi(temp, nullptr, 0);
                     x = intFound;
                     intWasFound = true;
                 } catch (const exception &e) {
                     e;
                 }
                 temp.clear();
             }
             if(ss.eof() && (!intWasFound))
                 return false;
             if (numArgs == 0)
                 return true;
             else
                 return multipleInts(ss, args...);
         }
References multipleInts().
nthInteger()
bool StringFuncs::parse::nthInteger (string s, int n, int & x) inline
Parameters
x Parses a string s, returns the n-th integer
Definition at line 113 of file StringFuncs.h.
         {
             stringstream ss(s);
             string temp;
             int intFound;
             int i = 0;
             while (!ss.eof()) {
                 ss >> temp;
                 try{
                     intFound = stoi(temp, nullptr, 0);
                     if(i == n) {
                         x = intFound;
                         return true;
                     }
                     i++;
                 } catch (const exception &e) {
                     e;
                 }
                 temp.clear();
             }
             return false;
         }
nthStringWord()
string StringFuncs::parse::nthStringWord (string s, int n) inline
Parameters
n Parses a string s, returns the n-th string word that is not an integer
Definition at line 30 of file StringFuncs.h.
         {
             stringstream ss(s);
             string ret;
             ret.clear();
             string temp;
             int intFound;
             int i = 0;
             ss >> temp;
             while (!ss.eof()) {
                 ss >> temp;
                 try{
                     intFound = stoi(temp, nullptr, 0);
                 } catch (const exception &e) {
                     if(i == n)
                         return temp;
                     i++;
                     e;
                 }
                 temp.clear();
             }
             return string("");
         }
Referenced by byteman::parseAssembly().