byteman: parseString Namespace Reference
parseString Namespace Reference
Functions
string getAllButLastWord (string s)
string getAllWords (string s)
bool getArrayOfUints (string s, int arrsize, uint32_t *arr)
string getLastWord (string s)
template<typename ... Args>
bool getMultipleInts (string s, Args &... args)
template<typename First , typename ... Rest>
bool getMultipleIntsRecursive (stringstream &ss)
template<typename First , typename ... Rest>
bool getMultipleIntsRecursive (stringstream &ss, int &x, Rest &... args)
bool getNthInt (string s, int n, int &x)
string getNthWord (string s, int n)
string removeQuotes (string s)
Function Documentation
getAllButLastWord()
string parseString::getAllButLastWord (string s)
Definition at line 68 of file parseString.cpp.
                                 { // returns a string of all string components that are not ints
         stringstream ss(s);
         string ret;
         ret.clear();
         string temp;
         int intFound;
         ss >> temp;
         while (!ss.eof()) {
             ss >> temp;
             if (!(stringstream(temp) >> intFound))
                 ret.append(temp).append(" ");
             temp.clear();
         }
         return ret;
Referenced by parseDevice(), parseInput(), and parseOutput().
getAllWords()
string parseString::getAllWords (string s)
Definition at line 85 of file parseString.cpp.
{
         stringstream ss(s);
         string temp;
         int intFound;
         int i = 0;
         while (!ss.eof()) {
             ss >> temp;
             try{
                 intFound = stoi(temp, nullptr, 0);
                 if(i == n) {
                     x = intFound;
                     return true;
                 }
                 i++;
Referenced by parseBlank(), parseMerge(), and parseRegion().
getArrayOfUints()
bool parseString::getArrayOfUints (string s, int arrsize, uint32_t * arr)
Definition at line 122 of file parseString.cpp.
{
                     e;
                 }
                 temp.clear();
             }
             if(ss.eof() && (!intWasFound))
                 return false;
         }
         return true;   //success
     }
     string removeQuotes(string s){
         if(s.empty())
             return s;
         if(s.front() == '"')
             s.erase(s.begin());
         if(s.empty())
             return s;
         if(s.back() == '"')
             s.erase(s.end()-1);
         return s;
     }
 }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit().
getLastWord()
string parseString::getLastWord (string s)
Definition at line 52 of file parseString.cpp.
{
         stringstream ss(s);
         string ret;
         ret.clear();
         string temp;
         string temp2;
         int intFound;
         ss >> temp;
         while (!ss.eof()) {
             ss >> temp;
             if (!(stringstream(temp) >> intFound)){
                 ret.append(temp2).append(" ");
                 temp2 = temp;
             }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), parseDevice(), parseInput(), and parseOutput().
getMultipleInts()
template<typename ... Args> bool parseString::getMultipleInts (string s, Args &... args)
Definition at line 47 of file parseString.h.
     {
         stringstream ss(s);
         return getMultipleIntsRecursive<int>(ss, args...);
     }
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), parseMerge(), parseOutput(), parseRegion(), parseVerbose(), and parseWarn().
getMultipleIntsRecursive() [1/2]
template<typename First , typename ... Rest> bool parseString::getMultipleIntsRecursive (stringstream & ss)
Definition at line 19 of file parseString.h.
     {
         return true;
     }
getMultipleIntsRecursive() [2/2]
template<typename First , typename ... Rest> bool parseString::getMultipleIntsRecursive (stringstream & ss, int & x, Rest &... args)
Definition at line 23 of file parseString.h.
     {
         int numArgs = sizeof...(args);
         string temp;
         int intFound;
         bool intWasFound = false;
         while ((!ss.eof()) && (!intWasFound)) {
             ss >> temp;
             try{
                 intFound = stoi(temp, nullptr, 0);
                 x = intFound;
                 intWasFound = true;
             } catch (const exception &e) {
                 e;
             }
             temp.clear();
         }
         if(ss.eof() && (!intWasFound))
             return false;
         if (numArgs == 0)
             return true;
         else
             return getMultipleIntsRecursive<int>(ss, args...);
     }
getNthInt()
bool parseString::getNthInt (string s, int n, int & x)
Definition at line 100 of file parseString.cpp.
{
                 e;
             }
             temp.clear();
         }
         return false;
     }
     bool getArrayOfUints(string s, int arrsize, uint32_t* arr)
     {
         if (arrsize == 0)
             return true;
         stringstream ss(s);
         string temp;
         uint32_t intFound;
         bool intWasFound = false;
         for (int i = 0 ; i < arrsize ; i++)
         {
             intWasFound = false;
             while ((!ss.eof()) && (!intWasFound)) {
                 ss >> temp;
getNthWord()
string parseString::getNthWord (string s, int n)
Definition at line 33 of file parseString.cpp.
{
         stringstream ss(s);
         string ret;
         ret.clear();
         string temp;
         int intFound;
         ss >> temp;
         while (!ss.eof()) {
             ss >> temp;
             if (!(stringstream(temp) >> intFound)){
                 ret = temp;
             }
             temp.clear();
         }
Referenced by parseAssembly().
removeQuotes()
string parseString::removeQuotes (string s)
Definition at line 149 of file parseString.cpp.
Referenced by XilinxUltraScalePlus::assemblerAsmToBit().