byteman: StringFuncs::checkIf Namespace Reference
StringFuncs::checkIf Namespace Reference
Functions
template<typename ... Rest>
bool firstStringWordIs (string checkedString, string nextString, Rest ... restStrings)
template<typename ... Rest>
bool stringBeginsWith (string checkedString)
template<typename ... Rest>
bool stringBeginsWith (string checkedString, string nextString, Rest ... restStrings)
template<typename ... Rest>
bool stringContains (string checkedString)
template<typename ... Rest>
bool stringContains (string checkedString, string nextString, Rest ... restStrings)
template<typename ... Rest>
bool stringEndsWith (string checkedString)
template<typename ... Rest>
bool stringEndsWith (string checkedString, string nextString, Rest ... restStrings)
template<typename ... Rest>
bool stringIs (string checkedString)
template<typename ... Rest>
bool stringIs (string checkedString, string nextString, Rest ... restStrings)
template<typename ... Rest>
bool stringWordIs (string checkedString)
template<typename ... Rest>
bool stringWordIs (string checkedString, string nextString, Rest ... restStrings)
Function Documentation
firstStringWordIs()
template<typename ... Rest> bool StringFuncs::checkIf::firstStringWordIs (string checkedString, string nextString, Rest ... restStrings) inline
Parameters
restStrings Returns true if string checkedString's first word matches fully any of strings nextString or restStrings
Definition at line 250 of file StringFuncs.h.
         {
             stringstream ss(checkedString);
             string firstWord;
             ss >> firstWord;
             return stringWordIs(firstWord, nextString, restStrings...);
         }
References stringWordIs().
Referenced by byteman::parseCommand().
stringBeginsWith() [1/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringBeginsWith (string checkedString) inline
Parameters
checkedString Returns false. End of recursion for template
Definition at line 230 of file StringFuncs.h.
         {
             return false;
         }
stringBeginsWith() [2/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringBeginsWith (string checkedString, string nextString, Rest ... restStrings) inline
Parameters
restStrings Returns true if string checkedString's first characters match fully any of strings nextString or restStrings
Definition at line 234 of file StringFuncs.h.
         {
             if(0 == checkedString.rfind(nextString, 0))
                 return true;
             return stringBeginsWith(checkedString, restStrings...);
         }
Referenced by stringWordIs().
stringContains() [1/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringContains (string checkedString) inline
Parameters
checkedString Returns false. End of recursion for template
Definition at line 220 of file StringFuncs.h.
         {
             return false;
         }
Referenced by XilinxUltraScalePlus::getDeviceByName(), and byteman::setArchitecture().
stringContains() [2/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringContains (string checkedString, string nextString, Rest ... restStrings) inline
Parameters
restStrings Returns true if string checkedString contains any of strings nextString or restStrings
Definition at line 224 of file StringFuncs.h.
         {
             if(string::npos != checkedString.rfind(nextString))
                 return true;
             return stringContains(checkedString, restStrings...);
         }
stringEndsWith() [1/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringEndsWith (string checkedString) inline
Parameters
checkedString Returns false. End of recursion for template
Definition at line 199 of file StringFuncs.h.
         {
             return false;
         }
Referenced by XilinxUltraScalePlus::assembler(), XilinxUltraScalePlus::readBitstream(), and XilinxUltraScalePlus::writeBitstream().
stringEndsWith() [2/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringEndsWith (string checkedString, string nextString, Rest ... restStrings) inline
Parameters
restStrings Returns true if string checkedString's final characters match fully any of strings nextString or restStrings
Definition at line 203 of file StringFuncs.h.
         {
             if(checkedString.length() >= nextString.length())
                 if(0 == checkedString.compare (checkedString.length() - nextString.length(), nextString.length(), nextString))
                     return true;
             return stringEndsWith(checkedString, restStrings...);
         }
Referenced by stringIs().
stringIs() [1/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringIs (string checkedString) inline
Parameters
checkedString Returns false. End of recursion for template
Definition at line 210 of file StringFuncs.h.
         {
             return false;
         }
Referenced by byteman::help().
stringIs() [2/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringIs (string checkedString, string nextString, Rest ... restStrings) inline
Parameters
restStrings Returns true if string checkedString matches fully any of strings nextString or restStrings
Definition at line 214 of file StringFuncs.h.
         {
             if(checkedString == nextString)
                 return true;
             return stringEndsWith(checkedString, restStrings...);
         }
References stringEndsWith().
stringWordIs() [1/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringWordIs (string checkedString) inline
Parameters
checkedString Returns false. End of recursion for template
Definition at line 240 of file StringFuncs.h.
         {
             return false;
         }
stringWordIs() [2/2]
template<typename ... Rest> bool StringFuncs::checkIf::stringWordIs (string checkedString, string nextString, Rest ... restStrings) inline
Parameters
restStrings Returns true if string checkedString matches fully any of strings nextString or restStrings
Definition at line 244 of file StringFuncs.h.
         {
             if(checkedString == nextString)
                 return true;
             return stringBeginsWith(checkedString, restStrings...);
         }
References stringBeginsWith().
Referenced by firstStringWordIs().