byteman: str Namespace Reference
str Namespace Reference
Namespaces
iff
parse
Functions
void findAndReplace (std::string &str, std::string toFind, std::string toReplaceWith)
std::string findStringAndGetAllAfter (std::string checkedString, std::string searchString)
Finds string searchString inside checkedString and returns all to the right inside checkedString. If can't be found, returns empty string.
std::string removeExternalQuotes (std::string str)
Removes double quotes from start and end of string str and returns the resulting string.
std::string removeSpaces (std::string str)
Removes all space chars of str returns the resulting string.
std::string replace (std::string str, char oldChar, char newChar)
Replaces all instances of oldChar in string str with newChar and returns the resulting string.
std::string stringToLower (std::string str)
Replaces all uppercase characters in str with lowercase and returns the resulting string.
std::string stringToUpper (std::string str)
Replaces all lowercase characters in str with uppercase and returns the resulting string.
Detailed Description
The str::iff:: namespace holds some custom and/or shorter functions for string conditionals (searching/matching).
The str::parse:: namespace holds some custom and/or shorter functions for string parsing.
The str:: namespace holds some custom and/or shorter functions including string string parsing and string manipulation.
Function Documentation
findAndReplace()
void str::findAndReplace (std::string & str, std::string toFind, std::string toReplaceWith) inline
Definition at line 77 of file str.h.
     {
         size_t pos = str.find(toFind);
         while( pos != std::string::npos) {
             str.replace(pos, toFind.size(), toReplaceWith);
             pos = str.find(toFind, pos + toReplaceWith.size());
         }
     }
findStringAndGetAllAfter()
std::string str::findStringAndGetAllAfter (std::string checkedString, std::string searchString) inline
Finds string searchString inside checkedString and returns all to the right inside checkedString. If can't be found, returns empty string.
Definition at line 33 of file str.h.
     {
         size_t loc = checkedString.find(searchString);
         if(std::string::npos == loc)
             return std::string("");
         return checkedString.substr(loc + searchString.size());
     }
Referenced by byteman::parse().
removeExternalQuotes()
std::string str::removeExternalQuotes (std::string str) inline
Removes double quotes from start and end of string str and returns the resulting string.
Definition at line 65 of file str.h.
     {
         if(str.empty())
             return str;
         if(str.front() == '"')
             str.erase(str.begin());
         if(str.empty())
             return str;
         if(str.back() == '"')
             str.erase(str.end()-1);
         return str;
     }
removeSpaces()
std::string str::removeSpaces (std::string str) inline
Removes all space chars of str returns the resulting string.
Definition at line 47 of file str.h.
     {
         str.erase(remove_if(str.begin(), str.end(), ::isspace), str.end());
         return str;
     }
Referenced by XilinxSeries7::getDeviceByName(), XilinxUltraScale::getDeviceByName(), and XilinxUltraScalePlus::getDeviceByName().
replace()
std::string str::replace (std::string str, char oldChar, char newChar) inline
Replaces all instances of oldChar in string str with newChar and returns the resulting string.
Definition at line 41 of file str.h.
     {
         replace(str.begin(), str.end(), oldChar, newChar);
         return str;
     }
Referenced by XilinxSeries7::assemblerAsmTo(), XilinxUltraScale::assemblerAsmTo(), XilinxUltraScalePlus::assemblerAsmTo(), byteman::parse(), parseParams(), and byteman::parseParamsAndRemoveThemFromString().
stringToLower()
std::string str::stringToLower (std::string str) inline
Replaces all uppercase characters in str with lowercase and returns the resulting string.
Definition at line 59 of file str.h.
     {
         transform(str.begin(), str.end(), str.begin(), ::tolower);
         return str;
     }
Referenced by XilinxSeries7::getDeviceByName(), XilinxUltraScale::getDeviceByName(), XilinxUltraScalePlus::getDeviceByName(), byteman::parse(), byteman::parseTest(), and byteman::setArchitecture().
stringToUpper()
std::string str::stringToUpper (std::string str) inline
Replaces all lowercase characters in str with uppercase and returns the resulting string.
Definition at line 53 of file str.h.
     {
         transform(str.begin(), str.end(), str.begin(), ::toupper);
         return str;
     }