byteman: str::iff Namespace Reference
str::iff Namespace Reference
Functions
template<typename ... Rest>
bool charIs (char checkedChar)
Returns false. End of recursion for template.
template<typename ... Rest>
bool charIs (char checkedChar, char nextChar, Rest ... restChars)
Returns true if char checkedChar matches any of chars nextChar or restChars.
template<typename ... Rest>
bool firstStringWordIs (std::string checkedString, std::string nextString, Rest ... restStrings)
Returns true if string checkedString's first word matches fully any of strings nextString or restStrings.
template<typename ... Rest>
bool stringBeginsWith (std::string checkedString)
Returns false. End of recursion for template.
template<typename ... Rest>
bool stringBeginsWith (std::string checkedString, std::string nextString, Rest ... restStrings)
Returns true if string checkedString's first characters match fully any of strings nextString or restStrings.
template<typename ... Rest>
bool stringContains (std::string checkedString)
Returns false. End of recursion for template.
template<typename ... Rest>
bool stringContains (std::string checkedString, std::string nextString, Rest ... restStrings)
Returns true if string checkedString contains any of strings nextString or restStrings.
template<typename ... Rest>
bool stringEndsWith (std::string checkedString)
Returns false. End of recursion for template.
template<typename ... Rest>
bool stringEndsWith (std::string checkedString, std::string nextString, Rest ... restStrings)
Returns true if string checkedString's final characters match fully any of strings nextString or restStrings.
template<typename ... Rest>
bool stringIs (std::string checkedString)
Returns false. End of recursion for template.
template<typename ... Rest>
bool stringIs (std::string checkedString, std::string nextString, Rest ... restStrings)
Returns true if string checkedString matches fully any of strings nextString or restStrings.
template<typename ... Rest>
bool stringWordIs (std::string checkedString)
Returns false. End of recursion for template.
template<typename ... Rest>
bool stringWordIs (std::string checkedString, std::string nextString, Rest ... restStrings)
Returns true if string checkedString matches fully any of strings nextString or restStrings.
Function Documentation
charIs() [1/2]
template<typename ... Rest> bool str::iff::charIs (char checkedChar) inline
Returns false. End of recursion for template.
Definition at line 101 of file iff.h.
         {
             return false;
         }
Referenced by charIs(), XilinxSeries7::initializeResourceStringParameters(), XilinxUltraScale::initializeResourceStringParameters(), and XilinxUltraScalePlus::initializeResourceStringParameters().
charIs() [2/2]
template<typename ... Rest> bool str::iff::charIs (char checkedChar, char nextChar, Rest ... restChars) inline
Returns true if char checkedChar matches any of chars nextChar or restChars.
Definition at line 106 of file iff.h.
         {
             if(checkedChar == nextChar)
                 return true;
             return charIs(checkedChar, restChars...);
         }
References charIs().
firstStringWordIs()
template<typename ... Rest> bool str::iff::firstStringWordIs (std::string checkedString, std::string nextString, Rest ... restStrings) inline
Returns true if string checkedString's first word matches fully any of strings nextString or restStrings.
Definition at line 93 of file iff.h.
         {
             std::stringstream ss(checkedString);
             std::string firstWord;
             ss >> firstWord;
             return stringWordIs(firstWord, nextString, restStrings...);
         }
References stringWordIs().
Referenced by byteman::parse().
stringBeginsWith() [1/2]
template<typename ... Rest> bool str::iff::stringBeginsWith (std::string checkedString) inline
Returns false. End of recursion for template.
Definition at line 69 of file iff.h.
         {
             return false;
         }
Referenced by stringBeginsWith(), and stringWordIs().
stringBeginsWith() [2/2]
template<typename ... Rest> bool str::iff::stringBeginsWith (std::string checkedString, std::string nextString, Rest ... restStrings) inline
Returns true if string checkedString's first characters match fully any of strings nextString or restStrings.
Definition at line 74 of file iff.h.
         {
             if(0 == checkedString.rfind(nextString, 0))
                 return true;
             return stringBeginsWith(checkedString, restStrings...);
         }
References stringBeginsWith().
stringContains() [1/2]
template<typename ... Rest> bool str::iff::stringContains (std::string checkedString) inline
Returns false. End of recursion for template.
Definition at line 57 of file iff.h.
         {
             return false;
         }
Referenced by XilinxSeries7::assemblerAsmTo(), XilinxUltraScale::assemblerAsmTo(), XilinxUltraScalePlus::assemblerAsmTo(), XilinxSeries7::assemblerParseHeader(), XilinxUltraScale::assemblerParseHeader(), XilinxUltraScalePlus::assemblerParseHeader(), XilinxSeries7::getDeviceByName(), XilinxUltraScale::getDeviceByName(), XilinxUltraScalePlus::getDeviceByName(), getXCAPcommand(), getXCAPregister(), byteman::parseTest(), byteman::setArchitecture(), and stringContains().
stringContains() [2/2]
template<typename ... Rest> bool str::iff::stringContains (std::string checkedString, std::string nextString, Rest ... restStrings) inline
Returns true if string checkedString contains any of strings nextString or restStrings.
Definition at line 62 of file iff.h.
         {
             if(std::string::npos != checkedString.rfind(nextString))
                 return true;
             return stringContains(checkedString, restStrings...);
         }
References stringContains().
stringEndsWith() [1/2]
template<typename ... Rest> bool str::iff::stringEndsWith (std::string checkedString) inline
Returns false. End of recursion for template.
Definition at line 32 of file iff.h.
         {
             return false;
         }
Referenced by XilinxSeries7::assembler(), XilinxUltraScale::assembler(), XilinxUltraScalePlus::assembler(), XilinxSeries7::readBitstream(), XilinxUltraScale::readBitstream(), XilinxUltraScalePlus::readBitstream(), stringEndsWith(), XilinxSeries7::writeBitstream(), XilinxUltraScale::writeBitstream(), and XilinxUltraScalePlus::writeBitstream().
stringEndsWith() [2/2]
template<typename ... Rest> bool str::iff::stringEndsWith (std::string checkedString, std::string nextString, Rest ... restStrings) inline
Returns true if string checkedString's final characters match fully any of strings nextString or restStrings.
Definition at line 37 of file iff.h.
         {
             if(checkedString.length() >= nextString.length())
                 if(0 == checkedString.compare (checkedString.length() - nextString.length(), nextString.length(), nextString))
                     return true;
             return stringEndsWith(checkedString, restStrings...);
         }
References stringEndsWith().
stringIs() [1/2]
template<typename ... Rest> bool str::iff::stringIs (std::string checkedString) inline
Returns false. End of recursion for template.
Definition at line 45 of file iff.h.
         {
             return false;
         }
Referenced by byteman::help(), and stringIs().
stringIs() [2/2]
template<typename ... Rest> bool str::iff::stringIs (std::string checkedString, std::string nextString, Rest ... restStrings) inline
Returns true if string checkedString matches fully any of strings nextString or restStrings.
Definition at line 50 of file iff.h.
         {
             if(checkedString == nextString)
                 return true;
             return stringIs(checkedString, restStrings...);
         }
References stringIs().
stringWordIs() [1/2]
template<typename ... Rest> bool str::iff::stringWordIs (std::string checkedString) inline
Returns false. End of recursion for template.
Definition at line 81 of file iff.h.
         {
             return false;
         }
Referenced by firstStringWordIs().
stringWordIs() [2/2]
template<typename ... Rest> bool str::iff::stringWordIs (std::string checkedString, std::string nextString, Rest ... restStrings) inline
Returns true if string checkedString matches fully any of strings nextString or restStrings.
Definition at line 86 of file iff.h.
         {
             if(checkedString == nextString)
                 return true;
             return stringBeginsWith(checkedString, restStrings...);
         }
References stringBeginsWith().