byteman: rect Namespace Reference
rect Namespace Reference
Functions
bool empty (Rect2D r)
Rect2D getOverlap (Rect2D r1, Rect2D r2)
Function Documentation
empty()
bool rect::empty (Rect2D r) inline
Definition at line 50 of file Coords.h.
{
         return (0 >= r.size.row || 0 >= r.size.col);
     }
References Coord2D::col, Coord2D::row, and Rect2D::size.
Referenced by XilinxUltraScalePlus::writeBitstreamMain(), and XilinxUltraScalePlus::writeBitstreamMainSingleRegion().
getOverlap()
Rect2D rect::getOverlap (Rect2D r1, Rect2D r2) inline
Definition at line 36 of file Coords.h.
{
         Rect2D retRect;
         retRect.position.col = max(r1.position.col, r2.position.col);
         retRect.size.col = min((r1.position.col+r1.size.col), (r2.position.col+r2.size.col)) - retRect.position.col;
         if(0 > retRect.size.col)
             retRect.size.col = 0;
         retRect.position.row = max(r1.position.row, r2.position.row);
         retRect.size.row = min((r1.position.row+r1.size.row), (r2.position.row+r2.size.row)) - retRect.position.row;
         if(0 > retRect.size.row)
             retRect.size.row = 0;
         return retRect;
     }
References Coord2D::col, Rect2D::position, Coord2D::row, and Rect2D::size.
Referenced by XilinxUltraScalePlus::writeBitstreamMain(), and XilinxUltraScalePlus::writeBitstreamMainSingleSLR().