byteman: str::parse Namespace Reference
str::parse Namespace Reference
Functions
std::string allStringWords (std::string s)
Parses a string s, removes all integers and returns the rest.
std::string allStringWordsWithoutLastStringWord (std::string s)
Parses a string s, removes all integers and the last string word. Returns the rest.
bool arrayOfUints (std::string s, int arrsize, uint32_t *arr)
Removes all string words from a given string s and returns the parsed arrsize number of integers into arr.
std::string lastStringWord (std::string s)
Parses a string s, removes all integers and returns the last of all string words.
template<typename ... Args>
bool multipleInts (std::string s, Args &... args)
Parses string s for integer values, that are returned into args.
template<typename ... Rest>
bool multipleInts (std::stringstream &ss)
template<typename ... Rest>
bool multipleInts (std::stringstream &ss, int &x, Rest &... args)
Parses stringstream ss for integer values, that are returned into x, args.
template<typename ... Args>
bool multipleUints (std::string s, Args &... args)
Parses string s for uint32_t values, that are returned into args.
template<typename ... Rest>
bool multipleUints (std::stringstream &ss)
template<typename ... Rest>
bool multipleUints (std::stringstream &ss, uint32_t &x, Rest &... args)
Parses stringstream ss for uint32_t values, that are returned into x, args.
bool nthInteger (std::string s, int n, int &x)
Parses a string s, returns the n-th integer.
std::string nthStringWord (std::string s, int n)
Parses a string s, returns the n-th string word that is not an integer.
Function Documentation
allStringWords()
std::string str::parse::allStringWords (std::string s) inline
Parses a string s, removes all integers and returns the rest.
Definition at line 57 of file parse.h.
         {
             std::stringstream ss(s);
             std::string temp, ret = "";
             int intFound;
             while (!ss.eof()) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     intFound = stoi(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                 } catch (const std::exception &e) {
                     if(!ret.empty())
                         ret.append(" ");
                     ret.append(temp);
                     e;
                 }
                 temp.clear();
             }
             return ret;
         }
Referenced by byteman::parseMerge(), and byteman::parseRegion().
allStringWordsWithoutLastStringWord()
std::string str::parse::allStringWordsWithoutLastStringWord (std::string s) inline
Parses a string s, removes all integers and the last string word. Returns the rest.
Definition at line 105 of file parse.h.
         {
             std::stringstream ss(s);
             std::string ret;
             ret.clear();
             std::string temp;
             std::string temp2;
             int intFound;
             while (!ss.eof()) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     intFound = stoi(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                 } catch (const std::exception &e) {
                     if(!ret.empty())
                         ret.append(" ");
                     ret.append(temp2);
                     temp2 = temp;
                     e;
                 }
                 temp.clear();
             }
             return ret;
         }
Referenced by byteman::parseOutput().
arrayOfUints()
bool str::parse::arrayOfUints (std::string s, int arrsize, uint32_t * arr) inline
Removes all string words from a given string s and returns the parsed arrsize number of integers into arr.
Definition at line 160 of file parse.h.
         {
             if (arrsize == 0)
                 return true;
             std::stringstream ss(s);
             std::string temp;
             uint32_t intFound;
             bool intWasFound = false;
             for (int i = 0 ; i < arrsize ; i++)
             {
                 intWasFound = false;
                 while ((!ss.eof()) && (!intWasFound)) {
                     ss >> quoted(temp);
                     if(temp.empty()) break;
                     try{
                         size_t sz;
                         intFound = (uint32_t)(stoll(temp, &sz, 0));
                         if(temp.size() != sz)
                             throw std::exception();
                         arr[i] = intFound;
                         intWasFound = true;
                     } catch (const std::exception &e) {
                         e;
                     }
                     temp.clear();
                 }
                 if(ss.eof() && (!intWasFound))
                     return false;
             }
             return true;   //success
         }
Referenced by XilinxSeries7::assemblerAsmTo(), XilinxUltraScale::assemblerAsmTo(), and XilinxUltraScalePlus::assemblerAsmTo().
lastStringWord()
std::string str::parse::lastStringWord (std::string s) inline
Parses a string s, removes all integers and returns the last of all string words.
Definition at line 81 of file parse.h.
         {
             std::stringstream ss(s);
             std::string ret;
             ret.clear();
             std::string temp;
             int intFound;
             while (!ss.eof()) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     intFound = stoi(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                 } catch (const std::exception &e) {
                     ret = temp;
                     e;
                 }
                 temp.clear();
             }
             return ret;
         }
Referenced by XilinxSeries7::assemblerParseHeader(), XilinxUltraScale::assemblerParseHeader(), XilinxUltraScalePlus::assemblerParseHeader(), byteman::parseInput(), and byteman::parseOutput().
multipleInts() [1/3]
template<typename ... Args> bool str::parse::multipleInts (std::string s, Args &... args) inline
Parses string s for integer values, that are returned into args.
Definition at line 223 of file parse.h.
         {
             std::stringstream ss(s);
             return multipleInts(ss, args...);
         }
References multipleInts().
multipleInts() [2/3]
template<typename ... Rest> bool str::parse::multipleInts (std::stringstream & ss) inline
Definition at line 192 of file parse.h.
         {
             return true;
         }
Referenced by XilinxSeries7::assemblerAsmTo(), XilinxUltraScale::assemblerAsmTo(), XilinxUltraScalePlus::assemblerAsmTo(), multipleInts(), byteman::parseMerge(), byteman::parseOutput(), parseParams(), byteman::parseRegion(), byteman::parseVerbose(), and byteman::parseWarn().
multipleInts() [3/3]
template<typename ... Rest> bool str::parse::multipleInts (std::stringstream & ss, int & x, Rest &... args) inline
Parses stringstream ss for integer values, that are returned into x, args.
Definition at line 197 of file parse.h.
         {
             int numArgs = sizeof...(args);
             std::string temp;
             int intFound;
             bool intWasFound = false;
             while ((!ss.eof()) && (!intWasFound)) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     intFound = stoi(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                     x = intFound;
                     intWasFound = true;
                 } catch (const std::exception &e) {
                     e;
                 }
                 temp.clear();
             }
             if(ss.eof() && (!intWasFound))
                 return false;
             return multipleInts(ss, args...);
         }
References multipleInts().
multipleUints() [1/3]
template<typename ... Args> bool str::parse::multipleUints (std::string s, Args &... args) inline
Parses string s for uint32_t values, that are returned into args.
Definition at line 260 of file parse.h.
         {
             std::stringstream ss(s);
             return multipleUints(ss, args...);
         }
References multipleUints().
multipleUints() [2/3]
template<typename ... Rest> bool str::parse::multipleUints (std::stringstream & ss) inline
Definition at line 229 of file parse.h.
         {
             return true;
         }
Referenced by XilinxSeries7::assemblerAsmTo(), XilinxUltraScale::assemblerAsmTo(), XilinxUltraScalePlus::assemblerAsmTo(), multipleUints(), byteman::parseTest(), and setBitstreamWord().
multipleUints() [3/3]
template<typename ... Rest> bool str::parse::multipleUints (std::stringstream & ss, uint32_t & x, Rest &... args) inline
Parses stringstream ss for uint32_t values, that are returned into x, args.
Definition at line 234 of file parse.h.
         {
             int numArgs = sizeof...(args);
             std::string temp;
             unsigned long uintFound;
             bool intWasFound = false;
             while ((!ss.eof()) && (!intWasFound)) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     uintFound = stoul(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                     x = (uint32_t)uintFound;
                     intWasFound = true;
                 } catch (const std::exception &e) {
                     e;
                 }
                 temp.clear();
             }
             if(ss.eof() && (!intWasFound))
                 return false;
             return multipleUints(ss, args...);
         }
References multipleUints().
nthInteger()
bool str::parse::nthInteger (std::string s, int n, int & x) inline
Parses a string s, returns the n-th integer.
Definition at line 133 of file parse.h.
         {
             std::stringstream ss(s);
             std::string temp;
             int intFound;
             int i = 0;
             while (!ss.eof()) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     intFound = stoi(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                     if(i == n) {
                         x = intFound;
                         return true;
                     }
                     i++;
                 } catch (const std::exception &e) {
                     e;
                 }
                 temp.clear();
             }
             return false;
         }
nthStringWord()
std::string str::parse::nthStringWord (std::string s, int n) inline
Parses a string s, returns the n-th string word that is not an integer.
Definition at line 33 of file parse.h.
         {
             std::stringstream ss(s);
             std::string temp;
             int intFound, i = 0;
             while (!ss.eof()) {
                 ss >> quoted(temp);
                 if(temp.empty()) break;
                 try{
                     size_t sz;
                     intFound = stoi(temp, &sz, 0);
                     if(temp.size() != sz)
                         throw std::exception();
                 } catch (const std::exception &e) {
                     if(i == n)
                         return temp;
                     i++;
                     e;
                 }
                 temp.clear();
             }
             return std::string("");
         }
Referenced by byteman::parseAssembly().