byteman: Endian Namespace Reference
Endian Namespace Reference
Functions
uint16_t BigEndianToNative16 (uint16_t x)
uint32_t BigEndianToNative32 (uint32_t x)
uint64_t BigEndianToNative64 (uint64_t x)
uint8_t BigEndianToNative8 (uint8_t x)
uint16_t BitSwap16 (uint16_t x)
uint32_t BitSwap32 (uint32_t x)
uint64_t BitSwap64 (uint64_t x)
uint8_t BitSwap8 (uint8_t x)
Endianess diff (Endianess e1, Endianess e2)
Endianess fixEndianIfNative (Endianess e)
uint16_t LittleEndianToNative16 (uint16_t x)
uint32_t LittleEndianToNative32 (uint32_t x)
uint64_t LittleEndianToNative64 (uint64_t x)
uint8_t LittleEndianToNative8 (uint8_t x)
uint16_t NativeToAnyEndianess16 (uint16_t x, Endianess e)
uint32_t NativeToAnyEndianess32 (uint32_t x, Endianess e)
uint64_t NativeToAnyEndianess64 (uint64_t x, Endianess e)
uint8_t NativeToAnyEndianess8 (uint8_t x, Endianess e)
uint16_t NativeToBigEndian16 (uint16_t x)
uint32_t NativeToBigEndian32 (uint32_t x)
uint64_t NativeToBigEndian64 (uint64_t x)
uint8_t NativeToBigEndian8 (uint8_t x)
uint16_t NativeToLittleEndian16 (uint16_t x)
uint32_t NativeToLittleEndian32 (uint32_t x)
uint64_t NativeToLittleEndian64 (uint64_t x)
uint8_t NativeToLittleEndian8 (uint8_t x)
uint16_t swapbytes16 (uint16_t x)
uint32_t swapbytes32 (uint32_t x)
uint64_t swapbytes64 (uint64_t x)
Endianess swapEndian (Endianess e)
Endianess swapEndianBits (Endianess e)
string to_string (Endianess e)
Function Documentation
BigEndianToNative16()
uint16_t Endian::BigEndianToNative16 (uint16_t x) inline
Definition at line 168 of file Endianess.h.
{
         return NativeToBigEndian16(x);
     }
References NativeToBigEndian16().
Referenced by FileIO::writeBigEndian16(), and FileIO::writeBitSwappedBigEndian16().
BigEndianToNative32()
uint32_t Endian::BigEndianToNative32 (uint32_t x) inline
Definition at line 171 of file Endianess.h.
{
         return NativeToBigEndian32(x);
     }
References NativeToBigEndian32().
Referenced by FileIO::writeBigEndian32(), and FileIO::writeBitSwappedBigEndian32().
BigEndianToNative64()
uint64_t Endian::BigEndianToNative64 (uint64_t x) inline
Definition at line 174 of file Endianess.h.
{
         return NativeToBigEndian64(x);
     }
References NativeToBigEndian64().
Referenced by FileIO::writeBigEndian64(), and FileIO::writeBitSwappedBigEndian64().
BigEndianToNative8()
uint8_t Endian::BigEndianToNative8 (uint8_t x) inline
Definition at line 165 of file Endianess.h.
{
         return ((uint8_t)(x));
     }
Referenced by FileIO::writeBigEndian8(), and FileIO::writeBitSwappedBigEndian8().
BitSwap16()
uint16_t Endian::BitSwap16 (uint16_t x) inline
Definition at line 194 of file Endianess.h.
{
         return (((x & 0x8080)>>7) | ((x & 0x4040)>>5) | ((x & 0x2020)>>3) | ((x & 0x1010)>>1) | ((x & 0x0808)<<1) | ((x & 0x0404)<<3) | ((x & 0x0202)<<5) | ((x & 0x0101)<<7));
     }
Referenced by NativeToAnyEndianess16(), FileIO::readBitSwappedBigEndian16(), FileIO::readBitSwappedLittleEndian16(), FileIO::writeBitSwappedBigEndian16(), and FileIO::writeBitSwappedLittleEndian16().
BitSwap32()
uint32_t Endian::BitSwap32 (uint32_t x) inline
Definition at line 197 of file Endianess.h.
{
         return (((x & 0x80808080)>>7) | ((x & 0x40404040)>>5) | ((x & 0x20202020)>>3) | ((x & 0x10101010)>>1) | ((x & 0x08080808)<<1) | ((x & 0x04040404)<<3) | ((x & 0x02020202)<<5) | ((x & 0x01010101)<<7));
     }
Referenced by NativeToAnyEndianess32(), FileIO::readBitSwappedBigEndian32(), FileIO::readBitSwappedLittleEndian32(), FileIO::writeBitSwappedBigEndian32(), and FileIO::writeBitSwappedLittleEndian32().
BitSwap64()
uint64_t Endian::BitSwap64 (uint64_t x) inline
Definition at line 200 of file Endianess.h.
{
         return (((x & 0x8080808080808080)>>7) | ((x & 0x4040404040404040)>>5) | ((x & 0x2020202020202020)>>3) | ((x & 0x1010101010101010)>>1) | ((x & 0x0808080808080808)<<1) | ((x & 0x0404040404040404)<<3) | ((x & 0x0202020202020202)<<5) | ((x & 0x0101010101010101)<<7));
     }
Referenced by NativeToAnyEndianess64(), FileIO::readBitSwappedBigEndian64(), FileIO::readBitSwappedLittleEndian64(), FileIO::writeBitSwappedBigEndian64(), and FileIO::writeBitSwappedLittleEndian64().
BitSwap8()
uint8_t Endian::BitSwap8 (uint8_t x) inline
Definition at line 191 of file Endianess.h.
{
         return (((x & 0x80)>>7) | ((x & 0x40)>>5) | ((x & 0x20)>>3) | ((x & 0x10)>>1) | ((x & 0x08)<<1) | ((x & 0x04)<<3) | ((x & 0x02)<<5) | ((x & 0x01)<<7));
     }
Referenced by FileIO::readBitSwappedBigEndian8(), FileIO::readBitSwappedLittleEndian8(), FileIO::readBitSwappedStringIntoCharArray(), FileIO::writeBitSwappedBigEndian8(), FileIO::writeBitSwappedCharArray(), FileIO::writeBitSwappedLittleEndian8(), and FileIO::writeBitSwappedString().
diff()
Endianess Endian::diff (Endianess e1, Endianess e2) inline
Returns what endianess operation is needed to convert between two endianesses. The returned endianess represents the operation needed to be done between host system's endianess and returned one, to achieve the same conversion as between the two given endianesses. For example, will return Endianess::NATIVE if no conversion is needed.
Definition at line 105 of file Endianess.h.
{
         Endianess accumulatedEndianessDiff = Endianess::NATIVE;
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e1 || Endianess::LITTLE_ENDIAN_BITSWAPPED == e1)
             accumulatedEndianessDiff = swapEndianBits(accumulatedEndianessDiff);
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e2 || Endianess::LITTLE_ENDIAN_BITSWAPPED == e2)
             accumulatedEndianessDiff = swapEndianBits(accumulatedEndianessDiff);
         if(IS_LITTLE_ENDIAN()){ // If native system is little endian
             if(Endianess::BIG_ENDIAN == e1 || Endianess::BIG_ENDIAN_BITSWAPPED == e1)
                 accumulatedEndianessDiff = swapEndian(accumulatedEndianessDiff);
             if(Endianess::BIG_ENDIAN == e2 || Endianess::BIG_ENDIAN_BITSWAPPED == e2)
                 accumulatedEndianessDiff = swapEndian(accumulatedEndianessDiff);
         } else { // If native system is big endian
             if(Endianess::LITTLE_ENDIAN == e1 || Endianess::LITTLE_ENDIAN_BITSWAPPED == e1)
                 accumulatedEndianessDiff = swapEndian(accumulatedEndianessDiff);
             if(Endianess::LITTLE_ENDIAN == e2 || Endianess::LITTLE_ENDIAN_BITSWAPPED == e2)
                 accumulatedEndianessDiff = swapEndian(accumulatedEndianessDiff);
         }
         return fixEndianIfNative(accumulatedEndianessDiff);
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, fixEndianIfNative(), IS_LITTLE_ENDIAN(), LITTLE_ENDIAN, LITTLE_ENDIAN_BITSWAPPED, NATIVE, swapEndian(), and swapEndianBits().
Referenced by XilinxUltraScalePlus::merge().
fixEndianIfNative()
Endianess Endian::fixEndianIfNative (Endianess e) inline
Definition at line 91 of file Endianess.h.
{
         if(IS_LITTLE_ENDIAN() && Endianess::LITTLE_ENDIAN == e)
             return Endianess::NATIVE;
         if((!(IS_LITTLE_ENDIAN())) && Endianess::BIG_ENDIAN == e)
             return Endianess::NATIVE;
         return e;
     }
References BIG_ENDIAN, IS_LITTLE_ENDIAN(), LITTLE_ENDIAN, and NATIVE.
Referenced by diff().
LittleEndianToNative16()
uint16_t Endian::LittleEndianToNative16 (uint16_t x) inline
Definition at line 180 of file Endianess.h.
{
         return NativeToLittleEndian16(x);
     }
References NativeToLittleEndian16().
Referenced by FileIO::writeBitSwappedLittleEndian16(), and FileIO::writeLittleEndian16().
LittleEndianToNative32()
uint32_t Endian::LittleEndianToNative32 (uint32_t x) inline
Definition at line 183 of file Endianess.h.
{
         return NativeToLittleEndian32(x);
     }
References NativeToLittleEndian32().
Referenced by FileIO::writeBitSwappedLittleEndian32(), and FileIO::writeLittleEndian32().
LittleEndianToNative64()
uint64_t Endian::LittleEndianToNative64 (uint64_t x) inline
Definition at line 186 of file Endianess.h.
{
         return NativeToLittleEndian64(x);
     }
References NativeToLittleEndian64().
Referenced by FileIO::writeBitSwappedLittleEndian64(), and FileIO::writeLittleEndian64().
LittleEndianToNative8()
uint8_t Endian::LittleEndianToNative8 (uint8_t x) inline
Definition at line 177 of file Endianess.h.
{
         return ((uint8_t)(x));
     }
Referenced by FileIO::writeBitSwappedLittleEndian8(), and FileIO::writeLittleEndian8().
NativeToAnyEndianess16()
uint16_t Endian::NativeToAnyEndianess16 (uint16_t x, Endianess e) inline
Definition at line 207 of file Endianess.h.
{
         if(Endianess::BIG_ENDIAN == e)
             return NativeToBigEndian16(x);
         if(Endianess::LITTLE_ENDIAN == e)
             return NativeToLittleEndian16(x);
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e)
             return BitSwap16(NativeToBigEndian16(x));
         if(Endianess::LITTLE_ENDIAN_BITSWAPPED == e)
             return BitSwap16(NativeToLittleEndian16(x));
         //Native then
         return ((uint16_t)(x));
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, BitSwap16(), LITTLE_ENDIAN, LITTLE_ENDIAN_BITSWAPPED, NativeToBigEndian16(), and NativeToLittleEndian16().
NativeToAnyEndianess32()
uint32_t Endian::NativeToAnyEndianess32 (uint32_t x, Endianess e) inline
Definition at line 219 of file Endianess.h.
{
         if(Endianess::BIG_ENDIAN == e)
             return NativeToBigEndian32(x);
         if(Endianess::LITTLE_ENDIAN == e)
             return NativeToLittleEndian32(x);
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e)
             return BitSwap32(NativeToBigEndian32(x));
         if(Endianess::LITTLE_ENDIAN_BITSWAPPED == e)
             return BitSwap32(NativeToLittleEndian32(x));
         //Native then
         return ((uint32_t)(x));
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, BitSwap32(), LITTLE_ENDIAN, LITTLE_ENDIAN_BITSWAPPED, NativeToBigEndian32(), and NativeToLittleEndian32().
Referenced by XilinxUltraScalePlus::flexiMerge().
NativeToAnyEndianess64()
uint64_t Endian::NativeToAnyEndianess64 (uint64_t x, Endianess e) inline
Definition at line 231 of file Endianess.h.
{
         if(Endianess::BIG_ENDIAN == e)
             return NativeToBigEndian64(x);
         if(Endianess::LITTLE_ENDIAN == e)
             return NativeToLittleEndian64(x);
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e)
             return BitSwap64(NativeToBigEndian64(x));
         if(Endianess::LITTLE_ENDIAN_BITSWAPPED == e)
             return BitSwap64(NativeToLittleEndian64(x));
         //Native then
         return ((uint64_t)(x));
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, BitSwap64(), LITTLE_ENDIAN, LITTLE_ENDIAN_BITSWAPPED, NativeToBigEndian64(), and NativeToLittleEndian64().
NativeToAnyEndianess8()
uint8_t Endian::NativeToAnyEndianess8 (uint8_t x, Endianess e) inline
Definition at line 204 of file Endianess.h.
{
         return ((uint8_t)(x));
     }
NativeToBigEndian16()
uint16_t Endian::NativeToBigEndian16 (uint16_t x) inline
Definition at line 142 of file Endianess.h.
{
         return (IS_LITTLE_ENDIAN())?swapbytes16(x):((uint16_t)(x));
     }
References IS_LITTLE_ENDIAN(), and swapbytes16().
Referenced by BigEndianToNative16(), NativeToAnyEndianess16(), and FileIO::readBigEndian16().
NativeToBigEndian32()
uint32_t Endian::NativeToBigEndian32 (uint32_t x) inline
Definition at line 145 of file Endianess.h.
{
         return (IS_LITTLE_ENDIAN())?swapbytes32(x):((uint32_t)(x));
     }
References IS_LITTLE_ENDIAN(), and swapbytes32().
Referenced by BigEndianToNative32(), NativeToAnyEndianess32(), and FileIO::readBigEndian32().
NativeToBigEndian64()
uint64_t Endian::NativeToBigEndian64 (uint64_t x) inline
Definition at line 148 of file Endianess.h.
{
         return (IS_LITTLE_ENDIAN())?swapbytes64(x):((uint64_t)(x));
     }
References IS_LITTLE_ENDIAN(), and swapbytes64().
Referenced by BigEndianToNative64(), NativeToAnyEndianess64(), and FileIO::readBigEndian64().
NativeToBigEndian8()
uint8_t Endian::NativeToBigEndian8 (uint8_t x) inline
Definition at line 139 of file Endianess.h.
{
         return ((uint8_t)(x));
     }
NativeToLittleEndian16()
uint16_t Endian::NativeToLittleEndian16 (uint16_t x) inline
Definition at line 155 of file Endianess.h.
{
         return (IS_LITTLE_ENDIAN())?((uint16_t)(x)):swapbytes16(x);
     }
References IS_LITTLE_ENDIAN(), and swapbytes16().
Referenced by LittleEndianToNative16(), NativeToAnyEndianess16(), and FileIO::readLittleEndian16().
NativeToLittleEndian32()
uint32_t Endian::NativeToLittleEndian32 (uint32_t x) inline
Definition at line 158 of file Endianess.h.
{
         return (IS_LITTLE_ENDIAN())?((uint32_t)(x)):swapbytes32(x);
     }
References IS_LITTLE_ENDIAN(), and swapbytes32().
Referenced by LittleEndianToNative32(), NativeToAnyEndianess32(), and FileIO::readLittleEndian32().
NativeToLittleEndian64()
uint64_t Endian::NativeToLittleEndian64 (uint64_t x) inline
Definition at line 161 of file Endianess.h.
{
         return (IS_LITTLE_ENDIAN())?((uint64_t)(x)):swapbytes64(x);
     }
References IS_LITTLE_ENDIAN(), and swapbytes64().
Referenced by LittleEndianToNative64(), NativeToAnyEndianess64(), and FileIO::readLittleEndian64().
NativeToLittleEndian8()
uint8_t Endian::NativeToLittleEndian8 (uint8_t x) inline
Definition at line 152 of file Endianess.h.
{
         return ((uint8_t)(x));
     }
swapbytes16()
uint16_t Endian::swapbytes16 (uint16_t x) inline
Definition at line 128 of file Endianess.h.
{
         return (uint16_t)(((uint16_t)(x) & 0xffU) << 8 | ((uint16_t)(x) & 0xff00U) >> 8);
     }
Referenced by NativeToBigEndian16(), and NativeToLittleEndian16().
swapbytes32()
uint32_t Endian::swapbytes32 (uint32_t x) inline
Definition at line 131 of file Endianess.h.
{
         return (uint32_t)(((uint32_t)(x) & 0xff) << 24 | ((uint32_t)(x) & 0xff00) << 8 | ((uint32_t)(x) & 0xff0000) >> 8 | ((uint32_t)(x) & 0xff000000) >> 24);
     }
Referenced by NativeToBigEndian32(), and NativeToLittleEndian32().
swapbytes64()
uint64_t Endian::swapbytes64 (uint64_t x) inline
Definition at line 134 of file Endianess.h.
{
         return (uint64_t)((((uint64_t)(x) & 0xff) << 56) | ((uint64_t)(x) & 0xff00ULL) << 40 |((uint64_t)(x) & 0xff0000ULL) << 24 |((uint64_t)(x) & 0xff000000ULL) << 8 |((uint64_t)(x) & 0xff00000000ULL) >> 8 |((uint64_t)(x) & 0xff0000000000ULL) >> 24 | ((uint64_t)(x) & 0xff000000000000ULL) >> 40 | ((uint64_t)(x) & 0xff00000000000000ULL) >> 56);
     }
Referenced by NativeToBigEndian64(), and NativeToLittleEndian64().
swapEndian()
Endianess Endian::swapEndian (Endianess e) inline
Definition at line 63 of file Endianess.h.
{
         if(Endianess::BIG_ENDIAN == e)
             return Endianess::LITTLE_ENDIAN;
         if(Endianess::LITTLE_ENDIAN == e)
             return Endianess::BIG_ENDIAN;
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e)
             return Endianess::LITTLE_ENDIAN_BITSWAPPED;
         if(Endianess::LITTLE_ENDIAN_BITSWAPPED == e)
             return Endianess::BIG_ENDIAN_BITSWAPPED;
         //Native then
         if(IS_LITTLE_ENDIAN())
             return Endianess::BIG_ENDIAN;
         return Endianess::LITTLE_ENDIAN;
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, IS_LITTLE_ENDIAN(), LITTLE_ENDIAN, and LITTLE_ENDIAN_BITSWAPPED.
Referenced by diff().
swapEndianBits()
Endianess Endian::swapEndianBits (Endianess e) inline
Definition at line 77 of file Endianess.h.
{
         if(Endianess::BIG_ENDIAN == e)
             return Endianess::BIG_ENDIAN_BITSWAPPED;
         if(Endianess::LITTLE_ENDIAN == e)
             return Endianess::LITTLE_ENDIAN_BITSWAPPED;
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e)
             return Endianess::BIG_ENDIAN;
         if(Endianess::LITTLE_ENDIAN_BITSWAPPED == e)
             return Endianess::LITTLE_ENDIAN;
         //Native then
         if(IS_LITTLE_ENDIAN())
             return Endianess::LITTLE_ENDIAN_BITSWAPPED;
         return Endianess::BIG_ENDIAN_BITSWAPPED;
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, IS_LITTLE_ENDIAN(), LITTLE_ENDIAN, and LITTLE_ENDIAN_BITSWAPPED.
Referenced by diff().
to_string()
string Endian::to_string (Endianess e) inline
Definition at line 52 of file Endianess.h.
{
         if(Endianess::BIG_ENDIAN == e)
             return "Big Endian";
         if(Endianess::LITTLE_ENDIAN == e)
             return "Little Endian";
         if(Endianess::BIG_ENDIAN_BITSWAPPED == e)
             return "Big Endian with BitSwap";
         if(Endianess::LITTLE_ENDIAN_BITSWAPPED == e)
             return "Little Endian with BitSwap";
         return "Native";
     }
References BIG_ENDIAN, BIG_ENDIAN_BITSWAPPED, LITTLE_ENDIAN, and LITTLE_ENDIAN_BITSWAPPED.
Referenced by XilinxUltraScalePlus::assemblerAsmToBit(), and XilinxUltraScalePlus::getDeviceByIDCODEorThrow().