byteman: src/Devices/Xilinx/XCAP_inline_CAP.h File Reference
XCAP_inline_CAP.h File Reference
Macros
#define FABRIC_SYNC_WORD 0xAA995566
Functions
XCAP::Command getXCAPcommand (string s)
XCAP::Register getXCAPregister (string s)
void writeXCAPcommandName (ofstream &fout, XCAP::Command commandID)
void writeXCAPregisterName (ofstream &fout, XCAP::Register registerID)
XCAP::Operation XCAP_getInstructionOperation (uint32_t instruction)
Parses and returns instruction operation. Most Xil instructions will NOP or write.
uint32_t XCAP_getInstructionPayload (uint32_t instruction)
Parses and returns instruction payload. This is the immediate value after instruction type and operation encodings.
XCAP::Register XCAP_getInstructionRegister (uint32_t instruction)
Parses and returns instruction register. This is the register being addressed if the instruction is of type 1.
uint32_t XCAP_getInstructionType (uint32_t instruction)
Parses and returns instruction type. Valid Xil instructions will be of types 1 and 2.
uint32_t XCAP_getInstructionWordCount (uint32_t instruction)
Parses and returns instruction word count. This is the number of words to be read/written if the instruction is of type 1.
uint32_t XCAP_IDCODEInstruction ()
Generate and return the encoding for a IDCODE writing instruction.
void XCAP_IncrementFAR (int slrID, int &blockType, int &rowAddress, int &columnAddress, int &minorAddress)
void XCAP_IncrementFAR_BlockType0 (int slrID, int &blockType, int &rowAddress, int &columnAddress, int &minorAddress)
void XCAP_IncrementFAR_BlockType1 (int slrID, int &blockType, int &rowAddress, int &columnAddress, int &minorAddress)
uint32_t XCAP_makeFAR (int slr, int blockType, int rowAddress, int columnAddress, int minorAddress)
uint32_t XCAP_makeFarFarInstruction ()
Generate and return the encoding for a Far FAR instruction.
uint32_t XCAP_makeInstruction (int type, XCAP::Operation operation, XCAP::Register reg, int payload)
Generate and return the encoding for an instruction.
uint32_t XCAP_makeSyncInstruction ()
Generate and return the encoding for a SYNC instruction.
uint32_t XCAP_makeType1Instruction (XCAP::Operation operation, XCAP::Register reg, int payload)
Generate and return the encoding for a type 1 instruction.
uint32_t XCAP_makeType1NopInstruction (int payload)
Generate and return the encoding for a type 1 NOP instruction.
uint32_t XCAP_makeType1ReadInstruction (XCAP::Register reg, int payload)
Generate and return the encoding for a type 1 Read instruction.
uint32_t XCAP_makeType1ReservedInstruction (int payload)
Generate and return the encoding for a type 1 Reserved instruction.
uint32_t XCAP_makeType1WriteInstruction (XCAP::Register reg, int payload)
Generate and return the encoding for a type 1 Write instruction.
uint32_t XCAP_makeType2Instruction (XCAP::Operation operation, int payload)
Generate and return the encoding for a type 2 instruction.
uint32_t XCAP_makeType2NopInstruction (int payload)
Generate and return the encoding for a type 2 NOP instruction.
uint32_t XCAP_makeType2ReadInstruction (int payload)
Generate and return the encoding for a type 2 Read instruction.
uint32_t XCAP_makeType2ReservedInstruction (int payload)
Generate and return the encoding for a type 2 Reserved instruction.
uint32_t XCAP_makeType2WriteInstruction (int payload)
Generate and return the encoding for a type 2 Write instruction.
void XCAP_parseFAR (int farValue, int slr, int &blockType, int &rowAddress, int &columnAddress, int &minorAddress)
void XCAP_writeCommand (ofstream &fout, XCAP::Command cmd, Endianness e)
Generate the encoding for writing a CAP command and write it to file ofstream.
void XCAP_writeFDRI (ofstream &fout, int wordCount, Endianness e)
Generate and write an FDRI command. Always uses type 2 command for simplicity.
void XCAP_writeFDRI1 (ofstream &fout, int wordCount, Endianness e)
Generate and write only a type 1 FDRI command.
void XCAP_writeMaskAndRegister (ofstream &fout, XCAP::Register reg, int writeMask, int writeValue, Endianness e)
Generate the encoding for writing a CAP register with a mask and write it to file ofstream.
void XCAP_writeNOP (ofstream &fout, int cnt, int payload, Endianness e)
Generate the encoding for NOP instructions and write them to file ofstream.
void XCAP_writeReadRegister (ofstream &fout, XCAP::Register reg, int readLength, Endianness e)
Generate the encoding for reading a CAP register and write it to file ofstream.
void XCAP_writeRegister (ofstream &fout, XCAP::Register reg, int writeValue, Endianness e)
Generate the encoding for writing a CAP register and write it to file ofstream.
void XCAP_writeRESERVED (ofstream &fout, int cnt, int payload, Endianness e)
Generate the encoding for Reserved instructions and write them to file ofstream.
void XCAP_writeSelectRegister (ofstream &fout, XCAP::Register reg, Endianness e)
Generate the encoding for "selecting" a CAP register and write it to file ofstream.
void XCAP_writeSYNQ (ofstream &fout, Endianness e)
Generate and write an SYNQ command.
void XCAP_writeType2 (ofstream &fout, int wordCount, Endianness e)
Generate and write only a type 2 FDRI command.
Macro Definition Documentation
FABRIC_SYNC_WORD
#define FABRIC_SYNC_WORD 0xAA995566
Definition at line 17 of file XCAP_inline_CAP.h.
Function Documentation
getXCAPcommand()
XCAP::Command getXCAPcommand (string s) inline
Definition at line 67 of file XCAP_inline_CAP.h.
 {
     if(str::iff::stringContains(s, "NULL"))
         return XCAP::Command::NULLCMD;
     else if(str::iff::stringContains(s, "WCFG", "WRITE CONFIG"))
         return XCAP::Command::WCFG;
     else if(str::iff::stringContains(s, "MFW", "MULTIPLE FRAME WRITE"))
         return XCAP::Command::MFW;
     else if(str::iff::stringContains(s, "DGHIGH", "DEASSERT GHIGH"))
         return XCAP::Command::DGHIGH;
     else if(str::iff::stringContains(s, "RCFG", "READ CONFIG"))
         return XCAP::Command::RCFG;
     else if(str::iff::stringContains(s, "START"))
         return XCAP::Command::START;
     else if(str::iff::stringContains(s, "URAM", "CLEAR URAM"))
         return XCAP::Command::URAM;
     else if(str::iff::stringContains(s, "RCRC", "RESET CRC"))
         return XCAP::Command::RCRC;
     else if(str::iff::stringContains(s, "AGHIGH", "ASSERT GHIGH"))
         return XCAP::Command::AGHIGH;
     else if(str::iff::stringContains(s, "SWITCH"))
         return XCAP::Command::SWITCH;
     else if(str::iff::stringContains(s, "GRESTORE"))
         return XCAP::Command::GRESTORE;
     else if(str::iff::stringContains(s, "SHUTDOWN"))
         return XCAP::Command::SHUTDOWN;
     else if(str::iff::stringContains(s, "DESYNC"))
         return XCAP::Command::DESYNC;
     else if(str::iff::stringContains(s, "IPROG"))
         return XCAP::Command::IPROG;
     else if(str::iff::stringContains(s, "CRCC"))
         return XCAP::Command::CRCC;
     else if(str::iff::stringContains(s, "LTIMER"))
         return XCAP::Command::LTIMER;
     else if(str::iff::stringContains(s, "BSPI_READ"))
         return XCAP::Command::BSPI_READ;
     else if(str::iff::stringContains(s, "FALL_EDGE"))
         return XCAP::Command::FALL_EDGE;
     else if(str::iff::stringContains(s, "MAGIC2"))
         return XCAP::Command::MAGIC2;
     return XCAP::Command::UNDEFINED;
 }
References XCAP::AGHIGH, XCAP::BSPI_READ, XCAP::CRCC, XCAP::DESYNC, XCAP::DGHIGH, XCAP::FALL_EDGE, XCAP::GRESTORE, XCAP::IPROG, XCAP::LTIMER, XCAP::MAGIC2, XCAP::MFW, XCAP::NULLCMD, XCAP::RCFG, XCAP::RCRC, XCAP::SHUTDOWN, XCAP::START, str::iff::stringContains(), XCAP::SWITCH, XCAP::UNDEFINED, XCAP::URAM, and XCAP::WCFG.
Referenced by XilinxUltraScale::assemblerAsmToBit(), and XilinxUltraScalePlus::assemblerAsmToBit().
getXCAPregister()
XCAP::Register getXCAPregister (string s) inline
Definition at line 19 of file XCAP_inline_CAP.h.
 {
     if(str::iff::stringContains(s, "CRC"))
         return XCAP::Register::CRC;
     else if(str::iff::stringContains(s, "FAR"))
         return XCAP::Register::FAR;
     else if(str::iff::stringContains(s, "FDRI"))
         return XCAP::Register::FDRI;
     else if(str::iff::stringContains(s, "FDRO"))
         return XCAP::Register::FDRO;
     else if(str::iff::stringContains(s, "CTRL0"))
         return XCAP::Register::CTRL0;
     else if(str::iff::stringContains(s, "MASK"))
         return XCAP::Register::MASK;
     else if(str::iff::stringContains(s, "STAT"))
         return XCAP::Register::STAT;
     else if(str::iff::stringContains(s, "LOUT"))
         return XCAP::Register::LOUT;
     else if(str::iff::stringContains(s, "COR0"))
         return XCAP::Register::COR0;
     else if(str::iff::stringContains(s, "MFWR"))
         return XCAP::Register::MFWR;
     else if(str::iff::stringContains(s, "CBC"))
         return XCAP::Register::CBC;
     else if(str::iff::stringContains(s, "IDCODE"))
         return XCAP::Register::IDCODE;
     else if(str::iff::stringContains(s, "AXSS"))
         return XCAP::Register::AXSS;
     else if(str::iff::stringContains(s, "COR1"))
         return XCAP::Register::COR1;
     else if(str::iff::stringContains(s, "WBSTAR"))
         return XCAP::Register::WBSTAR;
     else if(str::iff::stringContains(s, "TIMER"))
         return XCAP::Register::TIMER;
     else if(str::iff::stringContains(s, "MAGIC0"))
         return XCAP::Register::MAGIC0;
     else if(str::iff::stringContains(s, "BOOTSTS"))
         return XCAP::Register::BOOTSTS;
     else if(str::iff::stringContains(s, "CTRL1"))
         return XCAP::Register::CTRL1;
     else if(str::iff::stringContains(s, "MAGIC1"))
         return XCAP::Register::MAGIC1;
     else if(str::iff::stringContains(s, "BSPI"))
         return XCAP::Register::BSPI;
     return XCAP::Register::UNDEFINED;
 }
References XCAP::AXSS, XCAP::BOOTSTS, XCAP::BSPI, XCAP::CBC, XCAP::COR0, XCAP::COR1, XCAP::CRC, XCAP::CTRL0, XCAP::CTRL1, XCAP::FAR, XCAP::FDRI, XCAP::FDRO, XCAP::IDCODE, XCAP::LOUT, XCAP::MAGIC0, XCAP::MAGIC1, XCAP::MASK, XCAP::MFWR, XCAP::STAT, str::iff::stringContains(), XCAP::TIMER, XCAP::UNDEFINED, and XCAP::WBSTAR.
Referenced by XilinxUltraScale::assemblerAsmToBit(), and XilinxUltraScalePlus::assemblerAsmToBit().
writeXCAPcommandName()
void writeXCAPcommandName (ofstream & fout, XCAP::Command commandID) inline
Definition at line 111 of file XCAP_inline_CAP.h.
 {
     switch(commandID){
         case XCAP::Command::NULLCMD:
             fout << "Null Command";
             break;
         case XCAP::Command::WCFG:
             fout << "Write Config";
             break;
         case XCAP::Command::MFW:
             fout << "Multiple Frame Write";
             break;
         case XCAP::Command::DGHIGH:
             fout << "Deassert GHIGH";
             break;
         case XCAP::Command::RCFG:
             fout << "Read Config";
             break;
         case XCAP::Command::START:
             fout << "Start";
             break;
         case XCAP::Command::URAM:
             fout << "Clear URAM";
             break;
         case XCAP::Command::RCRC:
             fout << "Reset CRC";
             break;
         case XCAP::Command::AGHIGH:
             fout << "Assert GHIGH";
             break;
         case XCAP::Command::SWITCH:
             fout << "Switch";
             break;
         case XCAP::Command::GRESTORE:
             fout << "GRestore";
             break;
         case XCAP::Command::SHUTDOWN:
             fout << "Shutdown";
             break;
         case XCAP::Command::DESYNC:
             fout << "Desync";
             break;
         case XCAP::Command::IPROG:
             fout << "IProg";
             break;
         case XCAP::Command::CRCC:
             fout << "CRCC";
             break;
         case XCAP::Command::LTIMER:
             fout << "LTimer";
             break;
         case XCAP::Command::BSPI_READ:
             fout << "BSPI_Read";
             break;
         case XCAP::Command::FALL_EDGE:
             fout << "Fall_Edge";
             break;
         case XCAP::Command::MAGIC2:
             fout << "MAGIC2";
             break;
         default:
             fout << string("UNKNOWN(").append(to_string(static_cast<int>(commandID))).append(")");
             break;
     }
 }
References XCAP::AGHIGH, XCAP::BSPI_READ, XCAP::CRCC, XCAP::DESYNC, XCAP::DGHIGH, XCAP::FALL_EDGE, XCAP::GRESTORE, XCAP::IPROG, XCAP::LTIMER, XCAP::MAGIC2, XCAP::MFW, XCAP::NULLCMD, XCAP::RCFG, XCAP::RCRC, XCAP::SHUTDOWN, XCAP::START, XCAP::SWITCH, Endian::to_string(), XCAP::URAM, and XCAP::WCFG.
Referenced by XilinxUltraScale::disassemblerBitToAsm(), and XilinxUltraScalePlus::disassemblerBitToAsm().
writeXCAPregisterName()
void writeXCAPregisterName (ofstream & fout, XCAP::Register registerID) inline
Definition at line 177 of file XCAP_inline_CAP.h.
 {
     switch(registerID){
         case XCAP::Register::CRC:
             fout << "CRC";
             break;
         case XCAP::Register::FAR:
             fout << "FAR";
             break;
         case XCAP::Register::FDRI:
             fout << "FDRI";
             break;
         case XCAP::Register::FDRO:
             fout << "FDRO";
             break;
         case XCAP::Register::CMD:
             fout << "CMD";
             break;
         case XCAP::Register::CTRL0:
             fout << "CTRL0";
             break;
         case XCAP::Register::MASK:
             fout << "MASK";
             break;
         case XCAP::Register::STAT:
             fout << "STAT";
             break;
         case XCAP::Register::LOUT:
             fout << "LOUT";
             break;
         case XCAP::Register::COR0:
             fout << "COR0";
             break;
         case XCAP::Register::MFWR:
             fout << "MFWR";
             break;
         case XCAP::Register::CBC:
             fout << "CBC";
             break;
         case XCAP::Register::IDCODE:
             fout << "IDCODE";
             break;
         case XCAP::Register::AXSS:
             fout << "AXSS";
             break;
         case XCAP::Register::COR1:
             fout << "COR1";
             break;
         case XCAP::Register::WBSTAR:
             fout << "WBSTAR";
             break;
         case XCAP::Register::TIMER:
             fout << "TIMER";
             break;
         case XCAP::Register::MAGIC0:
             fout << "MAGIC0";
             break;
         case XCAP::Register::BOOTSTS:
             fout << "BOOTSTS";
             break;
         case XCAP::Register::CTRL1:
             fout << "CTRL1";
             break;
         case XCAP::Register::MAGIC1:
             fout << "MAGIC1";
             break;
         case XCAP::Register::BSPI:
             fout << "BSPI";
             break;
         default:
             fout << string("UNKNOWN(").append(to_string(static_cast<int>(registerID))).append(")");
             break;
     }
 }
References XCAP::AXSS, XCAP::BOOTSTS, XCAP::BSPI, XCAP::CBC, XCAP::CMD, XCAP::COR0, XCAP::COR1, XCAP::CRC, XCAP::CTRL0, XCAP::CTRL1, XCAP::FAR, XCAP::FDRI, XCAP::FDRO, XCAP::IDCODE, XCAP::LOUT, XCAP::MAGIC0, XCAP::MAGIC1, XCAP::MASK, XCAP::MFWR, XCAP::STAT, XCAP::TIMER, Endian::to_string(), and XCAP::WBSTAR.
Referenced by XilinxUltraScale::disassemblerBitToAsm(), and XilinxUltraScalePlus::disassemblerBitToAsm().
XCAP_getInstructionOperation()
XCAP::Operation XCAP_getInstructionOperation (uint32_t instruction) inline
Parses and returns instruction operation. Most Xil instructions will NOP or write.
Definition at line 320 of file XCAP_inline_CAP.h.
 {
     return static_cast<XCAP::Operation>((instruction>>27) & 0x3); //Operation is @ bits [28:27]
 }
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_getInstructionPayload()
uint32_t XCAP_getInstructionPayload (uint32_t instruction) inline
Parses and returns instruction payload. This is the immediate value after instruction type and operation encodings.
Definition at line 326 of file XCAP_inline_CAP.h.
 {
     return (instruction & 0x07FFFFFF);  //Payload in type 2 instructions is @ bits [26:0]
 }
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_getInstructionRegister()
XCAP::Register XCAP_getInstructionRegister (uint32_t instruction) inline
Parses and returns instruction register. This is the register being addressed if the instruction is of type 1.
Definition at line 332 of file XCAP_inline_CAP.h.
 {
     return static_cast<XCAP::Register>((instruction>>13) & 0x1F);   //Register in type 1 instructions is @ bits [17:13]
 }
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_getInstructionType()
uint32_t XCAP_getInstructionType (uint32_t instruction) inline
Parses and returns instruction type. Valid Xil instructions will be of types 1 and 2.
Definition at line 314 of file XCAP_inline_CAP.h.
 {
     return ((instruction>>29) & 0x7); // type is @ bits [31:29]
 }
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_getInstructionWordCount()
uint32_t XCAP_getInstructionWordCount (uint32_t instruction) inline
Parses and returns instruction word count. This is the number of words to be read/written if the instruction is of type 1.
Definition at line 338 of file XCAP_inline_CAP.h.
 {
     return (instruction & 0x7FF);   //WordCount in type 1 instructions is @ bits [10:0]
 }
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_IDCODEInstruction()
uint32_t XCAP_IDCODEInstruction () inline
Generate and return the encoding for a IDCODE writing instruction.
Definition at line 485 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType1WriteInstruction(XCAP::Register::IDCODE, 1);
 }
References XCAP::IDCODE, and XCAP_makeType1WriteInstruction().
Referenced by parseBitstreamIDCODE().
XCAP_IncrementFAR()
void XCAP_IncrementFAR (int slrID, int & blockType, int & rowAddress, int & columnAddress, int & minorAddress) inline
Definition at line 288 of file XCAP_inline_CAP.h.
 {
     if(BLOCKTYPE_LOGIC == blockType){
         XCAP_IncrementFAR_BlockType0(slrID, blockType, rowAddress, columnAddress, minorAddress);
     } else if(BLOCKTYPE_BLOCKRAM == blockType){
         XCAP_IncrementFAR_BlockType1(slrID, blockType, rowAddress, columnAddress, minorAddress);
     }
 }
References XCAP_IncrementFAR_BlockType0(), and XCAP_IncrementFAR_BlockType1().
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_IncrementFAR_BlockType0()
void XCAP_IncrementFAR_BlockType0 (int slrID, int & blockType, int & rowAddress, int & columnAddress, int & minorAddress) inline
Definition at line 252 of file XCAP_inline_CAP.h.
 {
     minorAddress++;
     if((columnAddress == numberOfCols)?(minorAddress == EXTRA_FRAMES_PER_ROW):(minorAddress == LUT_numberOfFramesForResourceLetter[(uint8_t)resourceString[rowAddress][columnAddress]])){
         minorAddress = 0;
         columnAddress++;
         if(columnAddress == (numberOfCols+1)){
             columnAddress = 0;
             if(rowAddress == SLRinfo[slrID].toRow){
                 rowAddress = SLRinfo[slrID].fromRow;
                 blockType++;
             } else {
                 rowAddress++;
             }
         }
     }
 }
Referenced by XCAP_IncrementFAR().
XCAP_IncrementFAR_BlockType1()
void XCAP_IncrementFAR_BlockType1 (int slrID, int & blockType, int & rowAddress, int & columnAddress, int & minorAddress) inline
Definition at line 270 of file XCAP_inline_CAP.h.
 {
     minorAddress++;
     if((columnAddress == numberOfBRAMCols)?(minorAddress == EXTRA_FRAMES_PER_ROW):(minorAddress == FRAMES_PER_BRAM_CONTENT_COLUMN)){
         minorAddress = 0;
         columnAddress++;
         if(columnAddress == (numberOfBRAMCols+1)){
             columnAddress = 0;
             if(rowAddress == SLRinfo[slrID].toRow){
                 rowAddress = SLRinfo[slrID].fromRow;
                 blockType++;
             } else {
                 rowAddress++;
             }
         }
     }
 }
Referenced by XCAP_IncrementFAR().
XCAP_makeFAR()
uint32_t XCAP_makeFAR (int slr, int blockType, int rowAddress, int columnAddress, int minorAddress) inline
Definition at line 306 of file XCAP_inline_CAP.h.
 {
     return (((blockType & FAR_BLOCKTYPE_MASK) << FAR_BLOCKTYPE_SHIFT) | (((rowAddress - SLRinfo[slr].fromRow) & FAR_ROWADDRESS_MASK) << FAR_ROWADDRESS_SHIFT) | ((columnAddress & FAR_COLUMNADDRESS_MASK) << FAR_COLUMNADDRESS_SHIFT) | ((minorAddress & FAR_MINORADDRESS_MASK) << FAR_MINORADDRESS_SHIFT));
 }
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), writeBitstreamMainSingleRegion(), and XCAP_makeFarFarInstruction().
XCAP_makeFarFarInstruction()
uint32_t XCAP_makeFarFarInstruction () inline
Generate and return the encoding for a Far FAR instruction.
Definition at line 497 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeFAR(0,7,63,0,0);
 }
References XCAP_makeFAR().
Referenced by XilinxUltraScale::outputBitstreamSLRFooterBitstreamSequence(), and XilinxUltraScalePlus::outputBitstreamSLRFooterBitstreamSequence().
XCAP_makeInstruction()
uint32_t XCAP_makeInstruction (int type, XCAP::Operation operation, XCAP::Register reg, int payload) inline
Generate and return the encoding for an instruction.
Definition at line 344 of file XCAP_inline_CAP.h.
 {
     //type 1 instr: type@[31:29] ; operation@[28:27] ; reg@[17:13] ; payload@[10:0]
     //type 2 instr: type@[31:29] ; operation@[28:27] ; payload@[26:0]
     //This function works for both types, but is not safe for bad instructions
     return (((type & 0x7) << 29) | ((static_cast<int>(operation) & 0x3) << 27) | ((static_cast<int>(reg) & 0x1F) << 13) | (payload & 0x07FFFFFF));
 }
Referenced by XCAP_makeType1Instruction(), and XCAP_makeType2Instruction().
XCAP_makeSyncInstruction()
uint32_t XCAP_makeSyncInstruction () inline
Generate and return the encoding for a SYNC instruction.
Definition at line 491 of file XCAP_inline_CAP.h.
 {
     return FABRIC_SYNC_WORD;
 }
References FABRIC_SYNC_WORD.
Referenced by findBitstreamSync(), outputCAPheaderConstant(), parseBITheader(), parseBitstreamEndianness(), and XCAP_writeSYNQ().
XCAP_makeType1Instruction()
uint32_t XCAP_makeType1Instruction (XCAP::Operation operation, XCAP::Register reg, int payload) inline
Generate and return the encoding for a type 1 instruction.
Definition at line 353 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeInstruction(1, operation, reg, (payload & 0x7FF));
 }
References XCAP_makeInstruction().
Referenced by XCAP_makeType1NopInstruction(), XCAP_makeType1ReadInstruction(), XCAP_makeType1ReservedInstruction(), and XCAP_makeType1WriteInstruction().
XCAP_makeType1NopInstruction()
uint32_t XCAP_makeType1NopInstruction (int payload) inline
Generate and return the encoding for a type 1 NOP instruction.
Definition at line 359 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType1Instruction(XCAP::Operation::NOP, static_cast<XCAP::Register>(0), payload);
 }
References XCAP::NOP, and XCAP_makeType1Instruction().
Referenced by XCAP_writeNOP().
XCAP_makeType1ReadInstruction()
uint32_t XCAP_makeType1ReadInstruction (XCAP::Register reg, int payload) inline
Generate and return the encoding for a type 1 Read instruction.
Definition at line 365 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType1Instruction(XCAP::Operation::READ, reg, (payload & 0x7FF));
 }
References XCAP::READ, and XCAP_makeType1Instruction().
Referenced by XCAP_writeReadRegister().
XCAP_makeType1ReservedInstruction()
uint32_t XCAP_makeType1ReservedInstruction (int payload) inline
Generate and return the encoding for a type 1 Reserved instruction.
Definition at line 377 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType1Instruction(XCAP::Operation::RESERVED, static_cast<XCAP::Register>(0), payload);
 }
References XCAP::RESERVED, and XCAP_makeType1Instruction().
Referenced by XCAP_writeRESERVED().
XCAP_makeType1WriteInstruction()
uint32_t XCAP_makeType1WriteInstruction (XCAP::Register reg, int payload) inline
Generate and return the encoding for a type 1 Write instruction.
Definition at line 371 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType1Instruction(XCAP::Operation::WRITE, reg, (payload & 0x7FF));
 }
References XCAP::WRITE, and XCAP_makeType1Instruction().
Referenced by XCAP_IDCODEInstruction(), XCAP_writeFDRI1(), XCAP_writeRegister(), and XCAP_writeSelectRegister().
XCAP_makeType2Instruction()
uint32_t XCAP_makeType2Instruction (XCAP::Operation operation, int payload) inline
Generate and return the encoding for a type 2 instruction.
Definition at line 383 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeInstruction(2, operation, static_cast<XCAP::Register>(0), payload);
 }
References XCAP_makeInstruction().
Referenced by XCAP_makeType2NopInstruction(), XCAP_makeType2ReadInstruction(), XCAP_makeType2ReservedInstruction(), and XCAP_makeType2WriteInstruction().
XCAP_makeType2NopInstruction()
uint32_t XCAP_makeType2NopInstruction (int payload) inline
Generate and return the encoding for a type 2 NOP instruction.
Definition at line 389 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType2Instruction(XCAP::Operation::NOP, payload);
 }
References XCAP::NOP, and XCAP_makeType2Instruction().
XCAP_makeType2ReadInstruction()
uint32_t XCAP_makeType2ReadInstruction (int payload) inline
Generate and return the encoding for a type 2 Read instruction.
Definition at line 395 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType2Instruction(XCAP::Operation::READ, (payload & 0x07FFFFFF));
 }
References XCAP::READ, and XCAP_makeType2Instruction().
XCAP_makeType2ReservedInstruction()
uint32_t XCAP_makeType2ReservedInstruction (int payload) inline
Generate and return the encoding for a type 2 Reserved instruction.
Definition at line 407 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType2Instruction(XCAP::Operation::RESERVED, payload);
 }
References XCAP::RESERVED, and XCAP_makeType2Instruction().
XCAP_makeType2WriteInstruction()
uint32_t XCAP_makeType2WriteInstruction (int payload) inline
Generate and return the encoding for a type 2 Write instruction.
Definition at line 401 of file XCAP_inline_CAP.h.
 {
     return XCAP_makeType2Instruction(XCAP::Operation::WRITE, (payload & 0x07FFFFFF));
 }
References XCAP::WRITE, and XCAP_makeType2Instruction().
Referenced by XCAP_writeType2().
XCAP_parseFAR()
void XCAP_parseFAR (int farValue, int slr, int & blockType, int & rowAddress, int & columnAddress, int & minorAddress) inline
Definition at line 297 of file XCAP_inline_CAP.h.
 {
     blockType = (farValue >> FAR_BLOCKTYPE_SHIFT) & FAR_BLOCKTYPE_MASK;
     rowAddress = (farValue >> FAR_ROWADDRESS_SHIFT) & FAR_ROWADDRESS_MASK;
     rowAddress += SLRinfo[slr].fromRow;
     columnAddress = (farValue >> FAR_COLUMNADDRESS_SHIFT) & FAR_COLUMNADDRESS_MASK;
     minorAddress = (farValue >> FAR_MINORADDRESS_SHIFT) & FAR_MINORADDRESS_MASK;
 }
Referenced by XilinxUltraScale::disassemblerBitToAsm(), XilinxUltraScalePlus::disassemblerBitToAsm(), and readBitstreamMain().
XCAP_writeCommand()
void XCAP_writeCommand (ofstream & fout, XCAP::Command cmd, Endianness e) inline
Generate the encoding for writing a CAP command and write it to file ofstream.
Definition at line 451 of file XCAP_inline_CAP.h.
 {
     XCAP_writeRegister(fout, XCAP::Register::CMD, static_cast<int>(cmd), e);
 }
References XCAP::CMD, and XCAP_writeRegister().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScalePlus::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScale::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScale::outputBitstreamEmptySLRWrapUpSequence(), XilinxUltraScalePlus::outputBitstreamEmptySLRWrapUpSequence(), XilinxUltraScalePlus::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRHeaderAfterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderAfterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRHeaderBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRWrapUpSequence(), XilinxUltraScale::outputBitstreamSLRWrapUpSequence(), and writeBitstreamMainSingleRegion().
XCAP_writeFDRI()
void XCAP_writeFDRI (ofstream & fout, int wordCount, Endianness e) inline
Generate and write an FDRI command. Always uses type 2 command for simplicity.
Definition at line 478 of file XCAP_inline_CAP.h.
 {
     XCAP_writeFDRI1(fout, 0, e);
     XCAP_writeType2(fout, wordCount, e);
 }
References XCAP_writeFDRI1(), and XCAP_writeType2().
Referenced by writeBitstreamMainSingleRegion().
XCAP_writeFDRI1()
void XCAP_writeFDRI1 (ofstream & fout, int wordCount, Endianness e) inline
Generate and write only a type 1 FDRI command.
Definition at line 464 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType1WriteInstruction(XCAP::Register::FDRI, wordCount);
     FileIO::write32(fout, instruction, e);
 }
References XCAP::FDRI, FileIO::write32(), and XCAP_makeType1WriteInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), and XCAP_writeFDRI().
XCAP_writeMaskAndRegister()
void XCAP_writeMaskAndRegister (ofstream & fout, XCAP::Register reg, int writeMask, int writeValue, Endianness e) inline
Generate the encoding for writing a CAP register with a mask and write it to file ofstream.
Definition at line 457 of file XCAP_inline_CAP.h.
 {
     XCAP_writeRegister(fout, XCAP::Register::MASK, writeMask, e);
     XCAP_writeRegister(fout, reg, writeValue, e);
 }
References XCAP::MASK, and XCAP_writeRegister().
Referenced by XilinxUltraScale::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderBitstreamSequence(), and XilinxUltraScale::outputBitstreamSLRHeaderBitstreamSequence().
XCAP_writeNOP()
void XCAP_writeNOP (ofstream & fout, int cnt, int payload, Endianness e) inline
Generate the encoding for NOP instructions and write them to file ofstream.
Definition at line 413 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType1NopInstruction(payload);
     for(int i = 0 ; i < cnt ; i++)
         FileIO::write32(fout, instruction, e);
 }
References FileIO::write32(), and XCAP_makeType1NopInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScalePlus::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScale::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScalePlus::outputBitstreamEmptySLRWrapUpSequence(), XilinxUltraScale::outputBitstreamEmptySLRWrapUpSequence(), XilinxUltraScale::outputBitstreamGlobalFooterSequence(), XilinxUltraScalePlus::outputBitstreamGlobalFooterSequence(), XilinxUltraScale::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderAfterBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRHeaderAfterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRHeaderBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRWrapUpSequence(), XilinxUltraScalePlus::outputBitstreamSLRWrapUpSequence(), and writeBitstreamMainSingleRegion().
XCAP_writeReadRegister()
void XCAP_writeReadRegister (ofstream & fout, XCAP::Register reg, int readLength, Endianness e) inline
Generate the encoding for reading a CAP register and write it to file ofstream.
Definition at line 436 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType1ReadInstruction(reg, readLength);
     FileIO::write32(fout, instruction, e);
 }
References FileIO::write32(), and XCAP_makeType1ReadInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), and XilinxUltraScalePlus::assemblerAsmToBit().
XCAP_writeRegister()
void XCAP_writeRegister (ofstream & fout, XCAP::Register reg, int writeValue, Endianness e) inline
Generate the encoding for writing a CAP register and write it to file ofstream.
Definition at line 443 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType1WriteInstruction(reg, 1);
     FileIO::write32(fout, instruction, e);
     FileIO::write32(fout, writeValue, e);
 }
References FileIO::write32(), and XCAP_makeType1WriteInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScale::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScalePlus::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScale::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRFooterBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRHeaderBitstreamSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderBitstreamSequence(), writeBitstreamMainSingleRegion(), XCAP_writeCommand(), and XCAP_writeMaskAndRegister().
XCAP_writeRESERVED()
void XCAP_writeRESERVED (ofstream & fout, int cnt, int payload, Endianness e) inline
Generate the encoding for Reserved instructions and write them to file ofstream.
Definition at line 421 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType1ReservedInstruction(payload);
     for(int i = 0 ; i < cnt ; i++)
         FileIO::write32(fout, instruction, e);
 }
References FileIO::write32(), and XCAP_makeType1ReservedInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), and XilinxUltraScalePlus::assemblerAsmToBit().
XCAP_writeSelectRegister()
void XCAP_writeSelectRegister (ofstream & fout, XCAP::Register reg, Endianness e) inline
Generate the encoding for "selecting" a CAP register and write it to file ofstream.
Definition at line 429 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType1WriteInstruction(reg, 0);
     FileIO::write32(fout, instruction, e);
 }
References FileIO::write32(), and XCAP_makeType1WriteInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScalePlus::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScale::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderAfterBitstreamSequence(), and XilinxUltraScale::outputBitstreamSLRHeaderAfterBitstreamSequence().
XCAP_writeSYNQ()
void XCAP_writeSYNQ (ofstream & fout, Endianness e) inline
Generate and write an SYNQ command.
Definition at line 503 of file XCAP_inline_CAP.h.
 {
     FileIO::write32(fout, XCAP_makeSyncInstruction(), e);
 }
References FileIO::write32(), and XCAP_makeSyncInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScale::outputBitstreamSLRHeaderAfterBitstreamSequence(), and XilinxUltraScalePlus::outputBitstreamSLRHeaderAfterBitstreamSequence().
XCAP_writeType2()
void XCAP_writeType2 (ofstream & fout, int wordCount, Endianness e) inline
Generate and write only a type 2 FDRI command.
Definition at line 471 of file XCAP_inline_CAP.h.
 {
     uint32_t instruction = XCAP_makeType2WriteInstruction(wordCount);
     FileIO::write32(fout, instruction, e);
 }
References FileIO::write32(), and XCAP_makeType2WriteInstruction().
Referenced by XilinxUltraScale::assemblerAsmToBit(), XilinxUltraScalePlus::assemblerAsmToBit(), XilinxUltraScalePlus::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScale::outputBitstreamEmptySLRHeaderSequence(), XilinxUltraScalePlus::outputBitstreamSLRHeaderAfterBitstreamSequence(), XilinxUltraScale::outputBitstreamSLRHeaderAfterBitstreamSequence(), and XCAP_writeFDRI().