byteman: src/Devices/Xilinx/XCAP_inline_ParseParams.h File Reference
XCAP_inline_ParseParams.h File Reference
Functions
void parseParams (string params)
Function Documentation
parseParams()
void parseParams (string params) inline
Parses argument options for multiple operations.
params A list of parameters to control behavior:
"clock" or "clk" : Selects the clocks for operation.
"logic" or "clb" : Selects the blocktype 0 for operation.
"blockram" or "bram" : Selects the blockram contents for operation.
If neither clock, logic, or blockram are chosen, chooses all.
"blank" : Selects bitstream blanking (zeroing) operation.
"full" : Disabling partial selection.
"partial" : Writes only selected regions. Selected by default.
"set" : Selects SET operation.
"xor" : Selects bitwise XOR operation.
"or" : Selects bitwise OR operation.
"and" : Selects bitwise AND operation.
Definition at line 32 of file XCAP_inline_ParseParams.h.
{
     selectedOptions = SelectedOptions();
     replace(params.begin(), params.end(), ',', ' ');
     stringstream ss(params);
     string param;
     while (!ss.eof()) {
         ss >> param;
         if(param == "clock" || param == "clk")selectedOptions.clk++;
         if(param == "logic" || param == "clb")selectedOptions.clb++;
         if(param == "blockram" || param == "bram")selectedOptions.bram++;
         if(param == "blank")selectedOptions.blank++;
         if(param == "full")selectedOptions.partial = 0;
         if(param == "partial")selectedOptions.partial = 1;
         if(param == "set")selectedOptions.op = MergeOP::SET;
         if(param == "xor")selectedOptions.op = MergeOP::XOR;
         if(param == "or")selectedOptions.op = MergeOP::OR;
         if(param == "and")selectedOptions.op = MergeOP::AND;
         param.clear();
     }
     if(selectedOptions.clk == 0 && selectedOptions.clb == 0 && selectedOptions.bram == 0){ // by default, choose all
         selectedOptions.clk = selectedOptions.bram = selectedOptions.clb = 1;
     }
 }
References str::replace().
Referenced by XilinxUltraScale::blank(), XilinxUltraScalePlus::blank(), XilinxUltraScale::merge(), XilinxUltraScalePlus::merge(), byteman::parse(), XilinxUltraScalePlus::writeBitstream(), and XilinxUltraScale::writeBitstream().