byteman: src/Devices/Xilinx/UltraScalePlus/XilinxUltraScalePlusAssembler.cpp File Reference
XilinxUltraScalePlusAssembler.cpp File Reference
#include "XilinxUltraScalePlus.h"
#include "XilinxUltraScalePlusCAP.h"
#include "../../../Common/fileIO.h"
#include "../../../Common/parseString.h"
#include <iostream>
#include <algorithm>
#include <string>
#include <stdexcept>
#include <fstream>
#include <cstring>
#include <iomanip>
Macros
#define has(x) (line.find(x) != string::npos)
#define has(x) (line.find(x) != string::npos)
#define has(x) (line.find(x) != string::npos)
#define has(x) (line.find(x) != string::npos)
#define hOR(x, y) (has(x)||has(y))
#define hOR(x, y) (has(x)||has(y))
Functions
int assemblerGetCommandID (string line)
int assemblerGetRegID (string line)
void writeCommandName (ofstream &fout, int cmdNum)
void writeRegisterName (ofstream &fout, int regNum)
Macro Definition Documentation
has [1/4]
#define has (x) (line.find(x) != string::npos)
has [2/4]
#define has (x) (line.find(x) != string::npos)
has [3/4]
#define has (x) (line.find(x) != string::npos)
has [4/4]
#define has (x) (line.find(x) != string::npos)
hOR [1/2]
#define hOR (x, y) (has(x)||has(y))
hOR [2/2]
#define hOR (x, y) (has(x)||has(y))
Function Documentation
assemblerGetCommandID()
int assemblerGetCommandID (string line)
Definition at line 95 of file XilinxUltraScalePlusAssembler.cpp.
{
     #define has(x) (line.find(x) != string::npos)
     #define hOR(x,y) (has(x)||has(y))
     if(has("NULL"))return XUSP_CAP_CMD_NULL;
     else if(hOR("WCFG", "WRITE CONFIG"))return XUSP_CAP_CMD_WCFG;
     else if(hOR("MFW", "MULTIPLE FRAME WRITE"))return XUSP_CAP_CMD_MFW;
     else if(hOR("DGHIGH", "DEASSERT GHIGH"))return XUSP_CAP_CMD_DGHIGH;
     else if(hOR("RCFG", "READ CONFIG"))return XUSP_CAP_CMD_RCFG;
     else if(has("START"))return XUSP_CAP_CMD_START;
     else if(hOR("URAM", "CLEAR URAM"))return XUSP_CAP_CMD_URAM;
     else if(hOR("RCRC", "RESET CRC"))return XUSP_CAP_CMD_RCRC;
     else if(hOR("AGHIGH", "ASSERT GHIGH"))return XUSP_CAP_CMD_AGHIGH;
     else if(has("SWITCH"))return XUSP_CAP_CMD_SWITCH;
     else if(has("GRESTORE"))return XUSP_CAP_CMD_GRESTORE;
     else if(has("SHUTDOWN"))return XUSP_CAP_CMD_SHUTDOWN;
     else if(has("DESYNC"))return XUSP_CAP_CMD_DESYNC;
     else if(has("IPROG"))return XUSP_CAP_CMD_IPROG;
     else if(has("CRCC"))return XUSP_CAP_CMD_CRCC;
     else if(has("LTIMER"))return XUSP_CAP_CMD_LTIMER;
     else if(has("BSPI_READ"))return XUSP_CAP_CMD_BSPI_READ;
     else if(has("FALL_EDGE"))return XUSP_CAP_CMD_FALL_EDGE;
     return XUSP_CAP_CMD_UNKNOWN;
     #undef has
     #undef hOR
 }
References has, hOR, XUSP_CAP_CMD_AGHIGH, XUSP_CAP_CMD_BSPI_READ, XUSP_CAP_CMD_CRCC, XUSP_CAP_CMD_DESYNC, XUSP_CAP_CMD_DGHIGH, XUSP_CAP_CMD_FALL_EDGE, XUSP_CAP_CMD_GRESTORE, XUSP_CAP_CMD_IPROG, XUSP_CAP_CMD_LTIMER, XUSP_CAP_CMD_MFW, XUSP_CAP_CMD_NULL, XUSP_CAP_CMD_RCFG, XUSP_CAP_CMD_RCRC, XUSP_CAP_CMD_SHUTDOWN, XUSP_CAP_CMD_START, XUSP_CAP_CMD_SWITCH, XUSP_CAP_CMD_UNKNOWN, XUSP_CAP_CMD_URAM, and XUSP_CAP_CMD_WCFG.
Referenced by XilinxUltraScalePlus::assemblerAsmToBit().
assemblerGetRegID()
int assemblerGetRegID (string line)
Definition at line 69 of file XilinxUltraScalePlusAssembler.cpp.
{
     #define has(x) (line.find(x) != string::npos)
     if(has("CRC"))return XUSP_CAP_REG_CRC;
     else if(has("FAR"))return XUSP_CAP_REG_FAR;
     else if(has("FDRI"))return XUSP_CAP_REG_FDRI;
     else if(has("FDRO"))return XUSP_CAP_REG_FDRO;
     else if(has("CTRL0"))return XUSP_CAP_REG_CTRL0;
     else if(has("MASK"))return XUSP_CAP_REG_MASK;
     else if(has("STAT"))return XUSP_CAP_REG_STAT;
     else if(has("LOUT"))return XUSP_CAP_REG_LOUT;
     else if(has("COR0"))return XUSP_CAP_REG_COR0;
     else if(has("MFWR"))return XUSP_CAP_REG_MFWR;
     else if(has("CBC"))return XUSP_CAP_REG_CBC;
     else if(has("IDCODE"))return XUSP_CAP_REG_IDCODE;
     else if(has("AXSS"))return XUSP_CAP_REG_AXSS;
     else if(has("COR1"))return XUSP_CAP_REG_COR1;
     else if(has("WBSTAR"))return XUSP_CAP_REG_WBSTAR;
     else if(has("TIMER"))return XUSP_CAP_REG_TIMER;
     else if(has("MAGIC0"))return XUSP_CAP_REG_MAGIC0;
     else if(has("BOOTSTS"))return XUSP_CAP_REG_BOOTSTS;
     else if(has("CTRL1"))return XUSP_CAP_REG_CTRL1;
     else if(has("MAGIC1"))return XUSP_CAP_REG_MAGIC1;
     else if(has("BSPI"))return XUSP_CAP_REG_BSPI;
     return XUSP_CAP_REG_UNKNOWN;
     #undef has
 }
References has, XUSP_CAP_REG_AXSS, XUSP_CAP_REG_BOOTSTS, XUSP_CAP_REG_BSPI, XUSP_CAP_REG_CBC, XUSP_CAP_REG_COR0, XUSP_CAP_REG_COR1, XUSP_CAP_REG_CRC, XUSP_CAP_REG_CTRL0, XUSP_CAP_REG_CTRL1, XUSP_CAP_REG_FAR, XUSP_CAP_REG_FDRI, XUSP_CAP_REG_FDRO, XUSP_CAP_REG_IDCODE, XUSP_CAP_REG_LOUT, XUSP_CAP_REG_MAGIC0, XUSP_CAP_REG_MAGIC1, XUSP_CAP_REG_MASK, XUSP_CAP_REG_MFWR, XUSP_CAP_REG_STAT, XUSP_CAP_REG_TIMER, XUSP_CAP_REG_UNKNOWN, and XUSP_CAP_REG_WBSTAR.
Referenced by XilinxUltraScalePlus::assemblerAsmToBit().
writeCommandName()
void writeCommandName (ofstream & fout, int cmdNum)
Definition at line 229 of file XilinxUltraScalePlusAssembler.cpp.
{
     switch(cmdNum){
         case XUSP_CAP_CMD_NULL: fout << "Null Command"; break;
         case XUSP_CAP_CMD_WCFG: fout << "Write Config"; break;
         case XUSP_CAP_CMD_MFW: fout << "Multiple Frame Write"; break;
         case XUSP_CAP_CMD_DGHIGH: fout << "Deassert GHIGH"; break; // TODO: XUSP_CAP_CMD_DGHIGH and XUSP_CAP_CMD_LFRM are the same
         case XUSP_CAP_CMD_RCFG: fout << "Read Config"; break;
         case XUSP_CAP_CMD_START: fout << "Start"; break;
         case XUSP_CAP_CMD_URAM: fout << "Clear URAM"; break;
         case XUSP_CAP_CMD_RCRC: fout << "Reset CRC"; break;
         case XUSP_CAP_CMD_AGHIGH: fout << "Assert GHIGH"; break;
         case XUSP_CAP_CMD_SWITCH: fout << "Switch"; break;
         case XUSP_CAP_CMD_GRESTORE: fout << "GRestore"; break;
         case XUSP_CAP_CMD_SHUTDOWN: fout << "Shutdown"; break;
         case XUSP_CAP_CMD_DESYNC: fout << "Desync"; break;
         case XUSP_CAP_CMD_IPROG: fout << "IProg"; break;
         case XUSP_CAP_CMD_CRCC: fout << "CRCC"; break;
         case XUSP_CAP_CMD_LTIMER: fout << "LTimer"; break;
         case XUSP_CAP_CMD_BSPI_READ: fout << "BSPI_Read"; break;
         case XUSP_CAP_CMD_FALL_EDGE: fout << "Fall_Edge"; break;
         default: fout << "UNKNOWN"; break;
     }
 }
References XUSP_CAP_CMD_AGHIGH, XUSP_CAP_CMD_BSPI_READ, XUSP_CAP_CMD_CRCC, XUSP_CAP_CMD_DESYNC, XUSP_CAP_CMD_DGHIGH, XUSP_CAP_CMD_FALL_EDGE, XUSP_CAP_CMD_GRESTORE, XUSP_CAP_CMD_IPROG, XUSP_CAP_CMD_LTIMER, XUSP_CAP_CMD_MFW, XUSP_CAP_CMD_NULL, XUSP_CAP_CMD_RCFG, XUSP_CAP_CMD_RCRC, XUSP_CAP_CMD_SHUTDOWN, XUSP_CAP_CMD_START, XUSP_CAP_CMD_SWITCH, XUSP_CAP_CMD_URAM, and XUSP_CAP_CMD_WCFG.
Referenced by XilinxUltraScalePlus::disassemblerBitToAsm().
writeRegisterName()
void writeRegisterName (ofstream & fout, int regNum)
Definition at line 252 of file XilinxUltraScalePlusAssembler.cpp.
{
     switch(regNum){
         case XUSP_CAP_REG_CRC: fout << "CRC"; break;
         case XUSP_CAP_REG_FAR: fout << "FAR"; break;
         case XUSP_CAP_REG_FDRI: fout << "FDRI"; break;
         case XUSP_CAP_REG_FDRO: fout << "FDRO"; break;
         case XUSP_CAP_REG_CMD: fout << "CMD"; break;
         case XUSP_CAP_REG_CTRL0: fout << "CTRL0"; break;
         case XUSP_CAP_REG_MASK: fout << "MASK"; break;
         case XUSP_CAP_REG_STAT: fout << "STAT"; break;
         case XUSP_CAP_REG_LOUT: fout << "LOUT"; break;
         case XUSP_CAP_REG_COR0: fout << "COR0"; break;
         case XUSP_CAP_REG_MFWR: fout << "MFWR"; break;
         case XUSP_CAP_REG_CBC: fout << "CBC"; break;
         case XUSP_CAP_REG_IDCODE: fout << "IDCODE"; break;
         case XUSP_CAP_REG_AXSS: fout << "AXSS"; break;
         case XUSP_CAP_REG_COR1: fout << "COR1"; break;
         case XUSP_CAP_REG_WBSTAR: fout << "WBSTAR"; break;
         case XUSP_CAP_REG_TIMER: fout << "TIMER"; break;
         case XUSP_CAP_REG_MAGIC0: fout << "MAGIC0"; break;
         case XUSP_CAP_REG_BOOTSTS: fout << "BOOTSTS"; break;
         case XUSP_CAP_REG_CTRL1: fout << "CTRL1"; break;
         case XUSP_CAP_REG_MAGIC1: fout << "MAGIC1"; break;
         case XUSP_CAP_REG_BSPI: fout << "BSPI"; break;
         default: fout << "UNKNOWN"; break;
     }
 }
References XUSP_CAP_REG_AXSS, XUSP_CAP_REG_BOOTSTS, XUSP_CAP_REG_BSPI, XUSP_CAP_REG_CBC, XUSP_CAP_REG_CMD, XUSP_CAP_REG_COR0, XUSP_CAP_REG_COR1, XUSP_CAP_REG_CRC, XUSP_CAP_REG_CTRL0, XUSP_CAP_REG_CTRL1, XUSP_CAP_REG_FAR, XUSP_CAP_REG_FDRI, XUSP_CAP_REG_FDRO, XUSP_CAP_REG_IDCODE, XUSP_CAP_REG_LOUT, XUSP_CAP_REG_MAGIC0, XUSP_CAP_REG_MAGIC1, XUSP_CAP_REG_MASK, XUSP_CAP_REG_MFWR, XUSP_CAP_REG_STAT, XUSP_CAP_REG_TIMER, and XUSP_CAP_REG_WBSTAR.
Referenced by XilinxUltraScalePlus::disassemblerBitToAsm().