message("Auto-incrementing version")
file(READ "src/version.h" VERSION_HEADER)
string(REGEX MATCH "#define VER_MINOR ([0-9]+)" FIRST_LINE "${VERSION_HEADER}")
math(EXPR NEW_VER_MINOR "${CMAKE_MATCH_1}+1")
message(STATUS " Minor: ${NEW_VER_MINOR}")
string(REGEX REPLACE "#define VER_MINOR ([0-9]+)" "#define VER_MINOR ${NEW_VER_MINOR}" VERSION_HEADER "${VERSION_HEADER}")
file(WRITE "src/version.h" "${VERSION_HEADER}")
