file(READ "CMakeLists.txt" CMakeLists)
string(REGEX MATCH "byteman VERSION ([0-9]+).([0-9]+).([0-9]+)" FIRST_LINE "${CMakeLists}")
set(NEW_VER_MAJOR ${CMAKE_MATCH_1})
set(NEW_VER_MINOR ${CMAKE_MATCH_2})
math(EXPR NEW_VER_BUILD "${CMAKE_MATCH_3}+1")
string(REGEX REPLACE "byteman VERSION ([0-9]+).([0-9]+).([0-9]+)" "byteman VERSION ${NEW_VER_MAJOR}.${NEW_VER_MINOR}.${NEW_VER_BUILD}" CMakeLists "${CMakeLists}")
file(WRITE "CMakeLists.txt" "${CMakeLists}")
file(READ "src/byteman.h" BytemanHeader)
string(REGEX REPLACE "#define VERSION \"([0-9]+).([0-9]+)\"" "#define VERSION \"${NEW_VER_MAJOR}.${NEW_VER_MINOR}\"" BytemanHeader "${BytemanHeader}")
string(REGEX REPLACE "#define VERSION_BUILD \"([0-9]+)\"" "#define VERSION_BUILD \"${NEW_VER_BUILD}\"" BytemanHeader "${BytemanHeader}")
file(WRITE "src/byteman.h" "${BytemanHeader}")
file(READ "Doxyfile.in" DoxyFile)
string(REGEX REPLACE "PROJECT_NUMBER = ([0-9]+).([0-9]+)" "PROJECT_NUMBER = ${NEW_VER_MAJOR}.${NEW_VER_MINOR}" DoxyFile "${DoxyFile}")
file(WRITE "Doxyfile.in" "${DoxyFile}")