###############################################################################
# Copyright 2022 Kristiyan Manev, University of Manchester
#
# Licensed under the Apache License, Version 2.0(the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
name: "Docs "

on:
  workflow_run:
    workflows: ["Versioner "]
    types:
      - completed

jobs:
  deploy-doxygen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Install doxygen
      run: sudo apt-get update; sudo apt-get install -y doxygen graphviz mscgen

    - name: Generate Doxygen Documentation
      run: doxygen Resources/Doxyfile.in
      shell: bash

    - name: Create .nojekyll (ensures pages with underscores work on gh pages)
      run: touch docs/.nojekyll
      shell: bash

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
