on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release


jobs:
  build:
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: Increment minor version
      run: cmake -P ${{github.workspace}}/IncrMinorVersion.cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Binaries/Windows-x86/

    - name: Build
      run: cmake --build ${{github.workspace}}/Binaries/Windows-x86 --config ${{env.BUILD_TYPE}}


    - name: Commit binary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/Binaries/Windows-x86/byteman.exe
        git add ${{github.workspace}}/CMakeLists.txt
        git diff-index --quiet HEAD || git commit -am "Binaries" -a
        git push


  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: Increment minor version
      run: cmake -P ${{github.workspace}}/IncrMinorVersion.cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Binaries/Linux-x86

    - name: Build
      run: cmake --build ${{github.workspace}}/Binaries/Linux-x86 --config ${{env.BUILD_TYPE}}


    - name: Commit binary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/Binaries/Linux-x86/byteman
        git diff-index --quiet HEAD || git commit -am "Binaries" -a
        git push

