on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release


jobs:
  auto-version:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: Increment and propagate build number
      run: cmake -P ${{github.workspace}}/.github/workflows/CMakeVersioner.cmake

    - name: Commit version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/src/byteman.h
        git add ${{github.workspace}}/CMakeLists.txt
        git diff-index --quiet HEAD || git commit -am "Autoversion" -a
        git push
    
  build-windows:
    needs: [auto-version]
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\Binaries\Windows-x86\

    - name: Build
      run: cmake --build ${{github.workspace}}\Binaries\Windows-x86 --target ALL_BUILD --config ${{env.BUILD_TYPE}}

    - name: Delete old binary
      continue-on-error: true
      run: del "${{github.workspace}}\Binaries\Windows-x86\byteman.exe"

    - name: Put new binary
      run: move "${{github.workspace}}\Binaries\Windows-x86\Release\byteman.exe" "${{github.workspace}}\Binaries\Windows-x86\"

    - name: Commit binary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}\Binaries\Windows-x86\byteman.exe
        git diff-index --quiet HEAD || git commit -am "Binaries" -a
        git push

  build-linux:
    needs: [build-windows]
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Binaries/Linux-x86

    - name: Build
      run: cmake --build ${{github.workspace}}/Binaries/Linux-x86 --config ${{env.BUILD_TYPE}}

    - name: Commit binary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/Binaries/Linux-x86/byteman
        git diff-index --quiet HEAD || git commit -am "Binaries" -a
        git push

  deploy-doxygen:
    runs-on: ubuntu-latest
    needs: [build-linux]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Install doxygen
      run: sudo apt-get update; sudo apt-get install -y doxygen graphviz

        
    - name: Generate Doxygen Documentation
      run: doxygen Resources/Doxyfile.in
      shell: bash
      
    - name: Create .nojekyll (ensures pages with underscores work on gh pages)
      run: touch docs/.nojekyll
      shell: bash

    - name: Commit docs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/docs/*
        git diff-index --quiet HEAD || git commit -am "Docs" -a
        git push