name: "Elf/x86 "

env:
  BUILD_TYPE: Release

on:
  workflow_run:
    workflows: ["Win/x86 "]
    types:
      - completed

jobs:
  build-linux:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Binaries/Linux-x86

    - name: Build
      run: cmake --build ${{github.workspace}}/Binaries/Linux-x86 --config ${{env.BUILD_TYPE}}

    - name: Commit binary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/Binaries/Linux-x86/byteman
        git diff-index --quiet HEAD || git commit -am "Binaries" -a
        git push