name: "Elf/ARM "

env:
  BUILD_TYPE: Release

on:
  workflow_run:
    workflows: ["Versioner "]
    types:
      - completed

jobs:
  build-linux-arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Install cross-compilation toolchain
      run: sudo apt-get update -y; sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Binaries/Linux-ARM -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++ -DCMAKE_AR=arm-linux-gnueabi-ar -DCMAKE_LINKER=arm-linux-gnueabi-ld -DCMAKE_OBJCOPY=arm-linux-gnueabi-objcopy -DCMAKE_RANLIB=arm-linux-gnueabi-ranlib

    - name: Build
      run: cmake --build ${{github.workspace}}/Binaries/Linux-ARM --config ${{env.BUILD_TYPE}}

    - name: Commit binary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/Binaries/Linux-ARM/byteman
        git commit -m "Binaries"
        until git push &> /dev/null
        do
          until git pull &> /dev/null
          do
            sleep 1
            git status
          done
        done
