name: "Build 0" #build number is always 1 ahead.

on:
  push:
    branches: [ main ]

jobs:
  auto-version:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: Increment and propagate build number
      run: cmake -P ${{github.workspace}}/.github/workflows/CMakeVersioner.cmake

    - name: Commit version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{github.workspace}}/src/byteman.h
        git add ${{github.workspace}}/CMakeLists.txt
        git diff-index --quiet HEAD || git commit -am "Autoversion" -a
        git push